wireapp/kalium

src/main/java/com/wire/kalium/api/notification/NotificationApi.kt
src/main/java/com/wire/kalium/api/notification/NotificationApiImpl.kt

----
----
the notificationsByBatch request was not able to call for all notifications
add getAllNotifications and 
----
----
----

fix: add call to get getAllNotifications

---

Makefile

----
----
Running: `$ make` fails with:
```
make: *** No rule to make target `cryptobox-compile', needed by `cryptobox4j'.  Stop.
```
Fix typo in Makefile.
Running: `$ make` should  complete successfully.
----
----
----

fix: running make fails to due to missing target

---

src/main/java/com/wire/kalium/api/conversation/ConversationEvent.kt
src/main/java/com/wire/kalium/api/conversation/CreateConversationRequest.kt
src/test/java/com/wire/kalium/api/user/client/ClientApiTest.kt

----
----
#96 
forgot to use the AccessRole enum in conversation response
Using the already written enum
----

fix: fix ClientApiTest and use the AccessRole enum for conv access response

---

src/main/java/com/wire/kalium/models/inbound/AudioPreviewMessage.kt
src/main/java/com/wire/kalium/models/inbound/CallingMessage.kt
src/main/java/com/wire/kalium/models/inbound/ConfirmationMessage.kt
src/main/java/com/wire/kalium/models/inbound/DeletedTextMessage.kt
src/main/java/com/wire/kalium/models/inbound/EditedTextMessage.kt
src/main/java/com/wire/kalium/models/inbound/EphemeralTextMessage.kt
src/main/java/com/wire/kalium/models/inbound/FilePreviewMessage.kt
src/main/java/com/wire/kalium/models/inbound/PhotoPreviewMessage.kt
src/main/java/com/wire/kalium/models/inbound/PingMessage.kt
src/main/java/com/wire/kalium/models/inbound/ReactionMessage.kt
src/main/java/com/wire/kalium/models/inbound/RemoteMessage.kt
src/main/java/com/wire/kalium/models/inbound/TextMessage.kt
src/main/java/com/wire/kalium/models/inbound/VideoPreviewMessage.kt

----
----
The models in `models.inbound` had useless serialization annotations, probably caused during the Java → Kotlin convertion.
Delete them!
These classes are probably getting replaced soon too, but it's easier to read and understand when re-implementing without garbage in the way.
N/A
----
----

chore: cleanup useless serialization annotations for inbound models.

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/LoginApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/logout/Cookie.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/logout/LogoutApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/logout/LogoutImp.kt

----
----
It adds the logout functionality by injecting the `zuid` cookie on the http request header.
It closes issue #113 
----

feat: add the logout api implementation details

---

.editorconfig

----
----
We still have differences in IDE configs regarding wildcard imports, which can lead to unnecessary line-diffs and code conflicts.
IntelliJ's default settings for wildcard imports under specific packages were not fully covered by `.editorconfig`:
Add `ij_kotlin_packages_to_use_import_on_demand = ^` to .editorconfig.
N/A
----
----

style: prevent wildcard import for specific packages using editorconfig

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/websocket/EventApi.kt

----
----
we were using ```Json.decodeFromStream()``` to desrialize incoming frames from websocket but it's a jvm only fumction
casting the incoming byteArray to string and using decodeFromString
----

fix: replace decodeFromStream

---

buildSrc/src/main/java/Dependencies.kt
cli/src/main/kotlin/com/wire/kalium/cli/ConversationsApplication.kt
cli/src/main/kotlin/com/wire/kalium/cli/InMemoryCredentialsLedger.kt
cli/src/main/kotlin/com/wire/kalium/cli/LoginApplication.kt
network/build.gradle.kts
network/src/androidMain/kotlin/com/wire/kalium/network/HttpEngine.kt
network/src/commonMain/kotlin/com/wire/kalium/network/HttpEngine.kt
network/src/commonMain/kotlin/com/wire/kalium/network/NetworkModule.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/CredentialsProvider.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/KtorHttpClient.kt
network/src/commonMain/kotlin/com/wire/kalium/network/tools/KtxSerializer.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/jvmMain/kotlin/com/wire/kalium/network/HttpEngine.kt

Small sample of utilization in `LoginApplication`
----
----
Closes #154 
A simple dependency container with lazy initialization of API implementations.
Reduced some code cuplication for multiple HttpClientEngine instances.
Check CLI's `ConversationsApplication` for sample on utilization.
N/A
We can include some E2E tests or integration later.
----
----

feat: Add dependency container for network module

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/model/Asset.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/model/Service.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/self/SelfApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/self/SelfUserInfoResponse.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/self/UserSsoId.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/self/SelfApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/self/SelfUserInfoResponseJson.kt

----
----
#128 
givenAValidRegisterLogoutRequest_whenCallingTheRegisterLogoutEndpoint_theRequestShouldBeConfiguredCorrectly
givenTheServerReturnsAnError_whenCallingTheGetSelfEndpoint_theCorrectExceptionIsThrown
----
----

feat: add self user info request

---

network/src/commonMain/kotlin/com/wire/kalium/network/tools/KtxSerializer.kt

----
----
right now the serializer will throw an Exitprion if a value is missing from the json String.
to avoid that i added ```explicitNulls = null``` to the  serializer configration
for more info see [kotlinx.serialization 1.3](https://blog.jetbrains.com/kotlin/2021/09/kotlinx-serialization-1-3-released/)
----
----

chore: configure the serializer to ignore null values

---

network/src/commonMain/kotlin/com/wire/kalium/network/NetworkModule.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/IDs.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/CreateConversationRequest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/message/MessageApiImp.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/teams/TeamsApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/teams/TeamsApiImp.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/ValidSingleJsonObjectProvider.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/teams/TeamsApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/teams/TeamsResponsesJson.kt

----
----
The parts of the `/teams` api that were already mapped, still were not modularized in the new api client. Closes #129 
Implemented a TeamApi that contains the methods we already had
Added `TeamsApiTest` to our test suit
----
----

feat(teams): split teams API from legacy client to modular client

---

android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/login/LoginRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/failure/AuthenticationFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationResult.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUsingEmailUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/Either.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/SuspendableEitherScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/functional/EitherTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/functional/SuspendableEitherScopeTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/util/EitherAssertions.kt

----
----
For splicit success/failure return values and easy mapping of results, the something like `Either` can be employed, at least internally in the `logic` module.
It can assist us to tie the different pieces / data sources together in a strongly typed way.
Brought up the `Either` class from Android Reloaded, with a small tweak: `isLeft` and `isRight` are not functions and benefit from the kotlin contracts.
Included
----
----

feat: add Either classes for internal usage in `logic` module

---

android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt
buildSrc/src/main/java/Dependencies.kt
cryptography/build.gradle.kts
cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt
cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt
cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/CRUDEngine.module_@wireapp_store-engine.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/Cryptobox.module_@wireapp_cryptobox.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/CryptoboxCRUDStore.module_@wireapp_cryptobox.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/CryptoboxSession.module_@wireapp_cryptobox.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/Decoder.module_@wireapp_cbor.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/Encoder.module_@wireapp_cbor.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/IdentityKey.module_@wireapp_proteus.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/IdentityKeyPair.module_@wireapp_proteus.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/KeyPair.module_@wireapp_proteus.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/MemoryEngine.module_@wireapp_store-engine.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/PreKey.module_@wireapp_proteus.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/PreKeyBundle.module_@wireapp_proteus.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/PreKeyStore.module_@wireapp_proteus.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/PublicKey.module_@wireapp_proteus.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/externals/SecretKey.module_@wireapp_proteus.kt
cryptography/src/jsTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt
cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt
gradle.properties

----
----
We want validate the KMP when targeting JS to assure us that it will also be possible to integrate the library on the web.
- Configure JS target in the cryptography module
- Implement the ProteusClient for JS using the existing [@wireapp/cryptobox](https://www.npmjs.com/search?q=%40wireapp%2Fcryptobox) implementation 
The common ProteusClient tests pass when running against the JS target.
- For simplicity is the JS ProteusClient using the in-memory engine which doesn't support any persistence.
- I've annotated many of ProteusClient methods with `suspend` since the JS cryptobox based on promises.
----
----
----
1. E.g. …

feat: add js implementation of the ProteusClient

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/asset/AssetApiImp.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/asset/AssetApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/asset/AssetDownloadResponseJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/asset/AssetUploadResponseJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/message/MessageApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/prekey/PrekeyApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/teams/TeamsApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/ClientApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/LoginApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/logout/LogoutApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/self/SelfApiTest.kt

----
----
The asset upload api feature was still missing a batch of tests. Also rewrote the `ApiTest` class to make a difference between authenticated an unauthenticated Http clients.

chore: add tests for the upload asset api

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/event/EventInfoStorage.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/kmm_settings/KaliumPreferences.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/event/EventInfoStorageTest.kt

----
----
Even though we already have a global preferences/storage to store the multiple sessions, we also need one storage PER session. 
For example, when dealing with processing of events, we need to store info about the latest event that was processed.
Expanded on @MohamadJaara's work for settings/preferences and created one instance of `KaliumSettings` per `UserScope`.
Based on it, created an `EventInfoStorage` that can hold an ID of the latest processed event.
Added tests for the new `EventInfoStorage`.
----
----

feat: Add session-scoped storage for event processing (AR-915)

---

android/build.gradle.kts
android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/wire/kalium/KaliumApplication.kt
android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt
buildSrc/src/main/java/Dependencies.kt
logic/build.gradle.kts
logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/AuthenticatedDataSourceSet.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthSession.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SlowSyncWorker.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/UserSessionWorker.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt

----
----
Certain operations like performing the slow sync / quick sync / sending messages needs to be continue running in the background after the user has closed the Wire application.
Performing a long running operation on Android can be achieved by using the `WorkManager` to schedule a work item which gets executed independently from activity which scheduled it. 
On iOS you request for the application to continue running in the background by [creating a background task](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio). A background task doesn't necessarily need to run in a separate thread. 
On the web "application" doesn't get put in the background so this is not an issue here. 
---
The …

feat: support for performing long running tasks 

---

android/build.gradle.kts
android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/wire/kalium/KaliumApplication.kt
android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt
buildSrc/src/main/java/Dependencies.kt
logic/build.gradle.kts
logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/AuthenticatedDataSourceSet.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MemberMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthSession.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetConversationsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/SyncConversationsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SlowSyncWorker.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/UserSessionWorker.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt

----
----
We only want to fetch resources like conversations and users only once after login and store them in a local database, subsequent updates are received over the event stream. 
- Update ConverationRespository to fetch conversations from the database instead of doing network requests.
- Introduce SyncManager which starts and keep track of which resources have been fetched. The `GetConversationsUseCase` queries the sync manager to not attempt to fetch the conversation list until the conversation resource has been fetched.
Not testing yet.
- The slow sync is currently repeated on every launch, we would need to start persisting the last fetched even ID in order to  determine if can skip the slow sync.
- The sync is …

feat: slow sync

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryImplTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestClient.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/ClientRegistrationStorageImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/client/ClientRegistrationStorageTest.kt

----
----
We need the ClientId for a lot of operations, and after successfully calling `registerClient`, we don't store its value anywhere.
* Created key/value `ClientRegistrationStorage` for persist the client id.
* Perform storage after registering in `RegisterClientUseCase`
Full coverage for all the layers changed: 
* `ClientRegistrationStorage`
* `ClientRepository`
* `RegisterClientUseCase` (WIP)
----
----

feat: persist client id after registration

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt

----
----
App crashes when initializing UserSessionScope
Session is null when accessed in the `encryptedSettingsHolder` getter.
Make `userPreferencesSettings` lazy
n/a
----
----
----

fix: avoid null pointer exception by making userPreferencesSettings lazy

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
persistence/src/androidAndroidTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/Database.kt

----
----
We don't the consumer of CoreLib to provide password upon launch.
Generate and store a password for the database in the encrypted user preferences.
Base tests class have been updated.
----
----
----

feat: generate and store the DB password in the user preferences

---

cryptography/build.gradle.kts
cryptography/consumer-proguard-rules.pro
network/build.gradle.kts
network/consumer-proguard-rules.pro
persistence/build.gradle.kts
persistence/consumer-proguard-rules.pro

----
the login is falling and the app is showing an Unkown error
R8 is deleting the auto generated serialization classes
It was a joint effort with @vitorhugods 
configuring ProGuard to keep kotlinx.serialization generated classes
N/A
at the moment we have no logging mechanism in kalium which made debugging not an easy task
I suggest using [Kermit by Touchlab](https://github.com/touchlab/Kermit)
----
----
----

fix: login is falling when minify is enabled

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCaseTest.kt

----
----
[AR-979]
Add DeleteClientUseCase to call the related API to delete a client.
Tested Params passing and Generic Failure.
----
----
----
[feat: SelfClientsUseCase]: https://github.com/wireapp/kalium/pull/211
[AR-979]: https://wearezeta.atlassian.net/browse/AR-979

feat: add delete client usecase (AR-979)

---

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt

----
----
When encoding PreKeys on Android to Base64, a `\n` is being added at the end of the string. Backend does not accept prekeys with this format.
Use of `DEFAULT` instead of `NO_WRAP`
`NO_WRAP` 😃 
Not yet in place.
----
----

fix: remove line breaks from PreKeys Base64 encoding/decoding on Android

---

logic/build.gradle.kts
logic/consumer-proguard-rules.pro

…serSessionWorker`s constructors
----
----
Android apps consuming Kalium are crashing on production when starting sync.
Proguard is removing the constructor of classes extending `UserSessionWorker`, as it is only invoked using Reflection.
Add a consumer proguard file to `logic` that keeps the constructor of such classes.
Using Android Reloaded:
* It no longer crashes due to method not being found.
* By inspecting the built `.apk` file, I can see the constructor in question.
----
----

fix: prevent proguard from minifying UserSessionWorker constructor

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/AuthenticatedDataSourceSet.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt

prev. DB was inited in UseCase, because of it we had different DB instances for each request.
Move DB init into CoreLogic, so it will be invited once and passed to necessary places (UserScope, etc.)

feat: Move DB initializations into CoreLogic to have a Singleton

---

logic/consumer-proguard-rules.pro
network/consumer-proguard-rules.pro

----
----
Android devices are crashing on release builds
Proguard is minifying Protobuf classes
Add consumer rule to prevent consumer apps from doing this when building a release artifact.
Tested manually on Android-Reloaded by building a minified `.apk`
----
----

fix(android): prevent minification of protobuf models

---

network/src/commonMain/kotlin/com/wire/kalium/network/HttpClientProvider.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/NetworkUtils.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/ClientApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/LoginApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/logout/LogoutApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/self/SelfApiTest.kt

----
----
BE send 401 -> app crash 
on 401 unauthorized the BE sends error response with `content-type: text/html` and the ktor client does not speak html, so when trying to parse the body it throw `NoTransformationFoundException`
ez just don't parse it 
manually
----
----

fix: app crashing on 401 response [AR-1135]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/LoginApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/NetworkResponse.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/LoginApiTest.kt

----
----
kalium not being able to extract the refresh token from headers
`httpResponse.headers.toMap()` is not case sensitive and will convert the keys to lowercase
get cookie by string key "set-cookie" instead of `HttpHeaders.SetCookie`
----
----
----

fix: login failing

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/login/LoginRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/remote/ClientRemoteRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/failure/AuthenticationFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/failure/ClientFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/test_util/TestNetworkException.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/NetworkErrorLabel.kt

----
----
When entering wrong password while logging in or deleting client, Generic server error is displayed instead of InvalidCredentials.
Updated UseCases to check failure types properly.
UseCase tests updated.
----
----
----

fix: login, delete and register client UseCase failures [AR-1207] [AR-1215]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfigRemoteRepository.kt

----
----
ServerConfigRemoteDataSource not using wrapApiRequest
wrapApiRequest
----
----
----

fix: ServerConfigRemoteDataSource not using wrapApiRequest

---

.github/workflows/generate-dokka.yml

----
----
CD of Dokka docs is failing: https://github.com/wireapp/kalium/runs/5560210086?check_suite_focus=true#step:5:62
It is failing because our Carthage plugin is trying to run Carthage on a Linux machine.
Short term: run on Mac.
Long term: investigate if we can update the Carthage plugin to behave a nicer on non-Mac machines.
🤷🏼 
----
----

ci: generate Dokka docs on Mac runners

---

network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt
network/src/commonMain/kotlin/com/wire/kalium/network/LoginNetworkContainer.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/auth/AccessTokenApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/model/AccessTokenDTO.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/LoginApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/register/RegisterApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/NetworkErrorLabel.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/CustomErrors.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/AccessTokenDTOJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/LoginApiTest.kt

----
----
1. when using ```
cookie(coockie_name, cookie_value)
``` ktor will encode the value and by default it's `URI` encoded, e.g., a cookie with the value `my_cookie.u=some_text` will become `my_cookie.u%3Dsome_text`.
2. when calling `AccessTokenAPI.getToken()` after registration (http client with no host URL) ktor will default to localhost.
1. replace  
```kotlin
cookie(coockie_name, cookie_value)
```
with  
```kotlin
header(HttpHeaders.Cookie, "$cookie_name=$cookie_value")
```
2. calling AccessTokenApi with authenticated http client only and adding 
```kotlin
private suspend fun getToken(refreshToken: String, apiBaseUrl: String): NetworkResponse<AccessTokenDTO> = wrapKaliumResponse {
httpClient.post {
url {
host = apiBaseUrl
pathSegments = …
```

fix: fetching access token from a cookie

---

network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt
network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt

----
----
while attempting to refresh the token, we are running into this [issue](https://youtrack.jetbrains.com/issue/KTOR-2806)
missing WWW-Authenticate header on 401 responses
JVM/Android only: intercept response → is 401 → add header ("WWW-Authenticate", "Bearer")
----
----

fix: part-1 refresh session: token refresh header workaround

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfigRemoteRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/login/LoginRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/remote/ClientRemoteRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/remote/PreKeyRemoteDataSource.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/PublicUserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/register/RegisterAccountRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/local/SessionLocalRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/CoreLogic.kt

----
----
Excessively many mappers are created inside `UserSessionScope`, `AuthenticationScope` and `CoreLogic` and some are actually duplicated 
```kotlin 
object MapperProvider {
fun idMapper(): IdMapper = IdMapperImpl()
.....
}
```
----
----

feat: constructor injection MapperProvider

---

android/build.gradle.kts
protobuf-codegen/build.gradle.kts
protobuf/build.gradle.kts

----
----
protobuf version 4.0.0 rc doesn't support mac m1 chip
Downgraded version to 3.19.4
----

fix: downgrade from 4.0.0 rc to 3.19.4 as it doesn't support mac m1

---

.github/workflows/gradle-mobile-tests.yml

----
----
CI is using Setup Java for caching Gradle, instead of the official [gradle-build-action](https://github.com/gradle/gradle-build-action).
The latter is more optimized and has more gradle-specific features if we ever need them.
Replace setup-java's cache with official Gradle caching.
;D 
----
----

ci: use Gradle setup caching instead of Java Setup

---

network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt
network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/message/MessageApiImp.kt
network/src/commonMain/kotlin/com/wire/kalium/network/serialization/ByteArrayConverter.kt

----
----
We are sending our messages as protobuf and the server requires the content type to be set to `application/x-protobuf`. Ktor however doesn't respect overriding the content-type on a request and will always send binary data as `application/octet-stream`.
We hacked around this on the Android/JVM by installing a http interceptor which re-writes the content type. This has some drawbacks: 
1. It only fixes the problem on Android,
2. The moment we need to send another binary content type the hack doesn't work anymore.
And that moment is now because I need to send binary data with content type `message/mls` when I send MLS messages.
Install the `ContentNegotiation` plugin which can be used to serialise/deserialise requests based on the …

fix: remove content-type hack

---

LICENSE

----
----
The LICENSE file in the project root contained merge conflict markers, which appear to have been accidentally committed into `develop` instead of being removed when the merge conflict was resolved.
This commit removes the merge conflict markers.
----
----
----

fix: remove merge conflict artefacts in licence file.

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/util/DateTimeUtil.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedId.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/Call.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GetOngoingCallsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt

----
----
With now having a GlobalCallManager providing each session with its instance, we are now able to expose ongoing calls from AVS to all the way to the UI.
This is Part 2 of the epic, tests will come in a later PR.
https://user-images.githubusercontent.com/5890660/160573622-02a40532-947e-4e6c-9a17-95ccc2eb3bfd.mov

chore: expose list of ongoing calls

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt

----
----
weird kotlin compile error 
```
e: /Users/mohamad.jaara/Desktop/work/wire-android-reloaded/kalium/logic/src
/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt: (70, 36): 
Type mismatch: inferred type is Either<Any, Unit> but Either<CoreFailure, Unit> was expected
```
I think it's related to kotlin contract but can't verify
```kotlin
@OptIn(ExperimentalContracts::class)
fun <L, R> Either<L, R>.isRight(): Boolean {
contract {
returns(true) implies (this@isRight is Right<R>)
returns(false) implies (this@isRight is Left<L>)
}
return this is Right<R>
}
```
the error message usually disappears after `clean project`, but I'm just tired of it
using 'coFold` instead of kotlin contract 
----
1. …

fix: weird Type mismatch error

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
persistence/build.gradle.kts

----
----
Develop is not buildable:
``` 
> Could not find sqlite:3.24:.
6 actionable tasks: 6 executed
Required by:
project :persistence
```
We were using a Snapshot version of SQLDelight 2.0.0, that was updated and broke some stuff.
[SQLDelight 2.0.0-alpha01](https://github.com/cashapp/sqldelight/releases/tag/2.0.0-alpha01) has just been released.
This PR bumps SQLDelight to `2.0.0-alpha01` and accomodates the required dialect definition change in order to keep the project building.
N/A
----
----

chore: bump SQLDelight version to 2.0.0-alpha01

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/ValidateUserHandleUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/SetUserHandleUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/ValidateUserHandleUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SetUserHandleUseCaseTest.kt

----
----
Right now ValidateUserHandleUseCase returns boolean which determines whether the specific handle is valid, but in order to execute the "shake" animation when the user enters invalid character and not allow the invalid ones to be added to the text field, we need to also get the handle string with invalid chars filtered out.
Update ValidateUserHandleUseCase to return ValidateUserHandleResult which contains both boolean and string with invalid chars filtered out.
Added tests to ValidateUserHandleUseCaseTest and updated others that use this usecase.
----
---- …

feat: update ValidateUserHandleUseCase to return also handleWithoutInvalidChars

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/ValidateUserHandleUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/SetUserHandleUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/ValidateUserHandleUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SetUserHandleUseCaseTest.kt

----
----
ValidateUserHandleUseCase returning the wrong error state when the handle is short/long and has invalid char
1. when invalid char && short/long -> invalid char.
2. ValidateUserHandleResult will always return a handle (to have single source of truth for the handle in the consumer app).
New test case added to test  invalid char && short/long -> invalid char.
----
----

fix: ValidateUserHandleUseCase returns wrong error state

---

cryptography/build.gradle.kts

----
----
Failure to build CLI target:
`:cli:test: Could not resolve androidx.security:security-crypto-ktx:1.1.0-alpha03.`
We're wrongly including an Android library as a JVM dependency in `:cryptography`.
Remove it. It was not being used inside `cryptography/jvmMain`.
N/A
----
----

chore: remove android lib dependency from JVM source set

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/util/DateTimeUtil.kt
protobuf-codegen/build.gradle.kts

----
----
Currently, on M1 Macbooks @MohammedMokresh and I had some issues when the module `protobuf-codegen` was building. As @saleniuk suggested and using the example from https://github.com/streem/pbandk/blob/master/examples/gradle-and-jvm/build.gradle.kts we are now skipping the `compileJava` and `CompileKotlin` tasks, since are not required for code generation purposes
----
----
----

fix: workaround code gen compiling issues

---

logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationResponse.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/CreateConversationRequest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/model/ConversationAccessRole.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationResponseJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/CreateConversationRequestJson.kt

----
----
In order to create MLS group we need support for the  the `protocol` and `group_id` fields.
- Add support for `protocol` field which controls if we are creating a proteus or a MLS group.
- Add support for `group_id` which holds a MLS specific identifier for conversations.
- Replace the usage of deprecated `access_role` with the `access_role_v2`
Unit tests
----
----
----

feat: extend API for creating groups to handle MLS conversations

---

cli/src/main/kotlin/com/wire/kalium/cli/ConversationsApplication.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfig.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfigRemoteRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/session/SessionMapperTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/HttpClientProvider.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/configuration/ServerConfigApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/NotificationApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/session/SessionManager.kt
network/src/commonMain/kotlin/com/wire/kalium/network/tools/ServerConfigDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/notification/NotificationApiTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/model/PersistenceSession.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/client/SessionStorageTest.kt

----
----
ServerConfig class has multiple confusing names in each module 
logic -> ServerConfig
network -> ServerConfigDTO
persistence -> ServerConfigEntitiy
----
----

chore: rename ServerConfig

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt

----
----
We need a way to observe details of a whole list of conversations.
Add `ObserveConversationListDetailsUseCase` that will get the list of conversations, and for each conversation, will observe its details, returning back an observable list of details.
```kotlin
conversationScope.observeConversationListDetails().collect{ listOfConversationDetails ->
// :D
}
```
----
----

feat(conversation): Observe list of conversation details (AR-1177, AR-881)

---

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/utils/CryptoUtils.kt
cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/utils/CryptoUtils.kt
cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/utils/CryptoUtils.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/utils/CryptoUtils.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/Asset.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendImageMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendImageUseCaseTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/asset/AssetDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/asset/AssetDAOImpl.kt

----
----
On the previously merged PR #327 , there was a latent issue on the way of calculating the SHA256 digestion of the encrypted data. It was transforming it to hex value and then transforming it to byte array. This PR fixes this.
The field `status.uploaded` returned by the backend upon asset upload seems to be sometimes null, so added a nullability check for that as well to avoid undesired crashes.
A following PR will come wiring the app logic with the use case so that the image can be directly uploaded as a private asset from the app.
----
----
---- …

fix: issues with image asset encryption flow [AR-1307]

---

.gitignore
protobuf-codegen/build.gradle.kts
protobuf/build.gradle.kts

----
----
There was a "unresolved references" issue with classes generated from proto. It wasn't breaking the build but making it difficult to use them in code.
It probably was because the same path that was supposed to be the source for `protobuf` module was also the "generated source root" for `protobuf-codegen` and probably Android Studio doesn't like that.
Fortunately there is a parameter `generatedFilesBaseDir` that can be used to determine the directory where the generated files are placed. It had to be outside of the `build` directory, because it looks like the pbandk searches for such directory in `build` and marks it as a "generated source root" for the module so separate `generated` folder is created, which is ignored by git, and …

fix: unresolved references when importing classes generated from proto

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MemberMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationMembersUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationMembersUseCaseTest.kt

----
----
Consuming apps need to observe the list of conversation members in order to dislpay it.
Add a new UseCase that will get the members of a conversation and merge the flows of each user into a single list of detailed users.
```kotlin
conversationScope.observeConversationMembers(convId)
```
----
----

feat(conversation): observe conversation members (AR-1178)

---

persistence/src/jvmMain/kotlin/com/wire/kalium/PackagePathProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmm_settings/EncryptedSettingsHolder.kt

----
----
Finding and deleting the data stored in `KaliumPreferences` when running the JVM target is really hard annoying.
Use `userNodeForPackage(EncryptedSettingsHolder::class.java)` instead of `userRoot()` which on macOS at least save the preferences in `~/Library/Preferences/com.wire.kalium.plist` instead of some obscure java plist file. 
CLI app still works.
----
----
----

fix: store jvm preferences in a more discoverable place

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationStatus.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationStatusMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationMutedStatusUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationStatusMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationMutedStatusUseCaseTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/MemberUpdateRequest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/MemberUpdateRequestJson.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt

----
----
- Part 1: #376  
- JIRA Ticket: https://wearezeta.atlassian.net/browse/AR-1264
- More info at: https://wearezeta.atlassian.net/wiki/spaces/PROD/pages/1705328/Notifications
In this PR, we are adding the capabilities to change the muting status of a conversation, this muting can be:
`ALL_ALLOWED` - User is informed about the conversations every time eg incoming calls, video conferencing, mentions & replies, Etc.
`ONLY_MENTIONS_ALLOWED`- User is Informed about the conversions if he/she is mentioned in the conversions or in replies
`ALL_MUTED` - User is never informed about the conversations
On a layer detail, we are adding:
- The DAO implementation for changing a conversation muting status
- The Repository mapping call to persist locally …

feat: muting conversation options - pt.2 local (AR-1264)

---

network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/connection/ConnectionApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/connection/ConnectionResponse.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/Database.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
persistence/src/commonMain/sqldelight/com/wire/kalium/persistence/db/Users.sq
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/UserStubs.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/Database.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/Database.kt

----
----
[AR-1333 - Fetch and store connection status during Sync](https://wearezeta.atlassian.net/browse/AR-1333)
Currently there was no status about the connection between the self user and another user (even if it were from the same team).
This PR starts with the Database and Api layers will later be implemented in the logic module in another PR.
PS: Tests will fail and some classes will be missing some new parameters, the "fix" or rather the correct implementation will be in the next PR, this PR is only to hold database and api layers.
PS.2: We are aware that `ConnectionState` and its way of mapping around is duplicated, we will soon handle this issue with something more `global` for model classes and some enums or classes that we are …

chore: add database and network layers for user connection status

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/SendCallingMessage.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendImageMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MLSMessageCreator.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendImageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MLSMessageCreatorTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreatorTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestMessage.kt

----
----
Add support for sending messages in MLS conversations.
Implements: [Use case: sending a message (MLS)](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/556564601/Use+case+sending+a+message+MLS)
Will soon be testable via CLI
- Backend is not completely ready yet.
----
----
----

feat(mls): send mls message

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/EventContentDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationResponseJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/notification/NotificationApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/notification/NotificationEventsResponseJson.kt

----
----
Conversations created after the slow sync is completed never appear.
We don't handle the `conversation.create` event.
Persist conversation when receiving an `conversation.create` event.
1. Login with User A and wait or slow sync to complete
2. On the web app, create a new conversation with User A
->  New conversation should appear in the conversation list.
----
----
----

feat(conversation): handle new converation events

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ListenToEventsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/ListenToEventsUseCaseTest.kt

----
----
@borichellow noticed that we were receiving some events twice. First in real-time and then when doing sync.
Easy to reproduce:
1. Receive an event through the Websocket
2. Close the app
3. Open the app
4. Event will be received again through the notification API
I remembered a crucial flaw when doing the receiving of events, that right now the "last processed ID" is only updated when receiving events through the API.
So *all* the events received through the Websocket are not being considered as processed, making the app request for them again when opening the app.
Change the current implementation, so:
- Remove the updating of the last ID from the repository, as it has two sources (REST and Websocket);
- Centralise this logic by making …

fix: events received through websocket being re-processed durying sync

---

calling/src/androidMain/kotlin/com/wire/kalium/calling/Calling.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/RejectCallUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/RejectCallUseCaseTest.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt

----
----
No useCase for rejecting call
Create a useCase to allow the use to reject a call
Unit test 
----
----
----

feat: add useCase for rejecting call [AR-1253]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sso/SSOUtil.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOInitiateLoginUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOInitiateLoginUseCaseTest.kt

----
----
SSOInitiateLoginUseCase is not generating the success/error redirects
add a secondary constructor to `SSORedirects` that will generate the redirects from `SSOUtil`
----
----

feat: generate SSO success/error in SSOInitiateLoginUseCase

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/SSOLoginApi.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/SSOLoginApiTest.kt

----
----
Without encoding, when using redirects like `wire://` we get 404 response.
That's because we don't encode the parameters.
Encode the parameters.
Execute the `initiate` request by using `SSOInitiateLoginUseCase` or directly from `SSOLoginApi`.
----
----

fix: encode SSO initiate request

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfig.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/Asset.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/AssetContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendImageMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendImageUseCaseTest.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt

----
----
So far we only could upload image assets and display them on the chat. With this PR, we will also be able to upload any other file types as generic file assets via the `SendAssetMessageUseCase`
----
----
----

feat: display asset messages on conversation [AR-1150]

---

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt
cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt

----
----
Sending the handshake message for creating a group conversation results in 404 "no-conversation" error by the BE.
Group IDs returned by the BE are base64 encoded and CoreCrypto expects the decode bytes but we were passing the raw string.
Decode group IDs inside the MLSClient before given them to CoreCrypto.
```
> cli login create-group
```
----
----
----

fix: decode group ID before passing it to CoreCrypto

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MLSMessageCreator.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/EventContentDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/notification/NotificationEventsResponseJson.kt

----
----
Handle decrypt incoming MLS messages by decrypting and processing the message protobuf.
This implements: [Use case: receive message (MLS)](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/557154491/Use+case+receive+message+MLS)
Login as User B so this it has an MLS client
```
> cli login
```
Login as User A and create a group with user B and send a message
```
> cli login create-group listen-group
```
Login as User B and receive the message
```
> cli login listen-group
```
- Testing is broken due to some bugs in MLS client.
----
----
---- …

feat(mls): handle incoming mls messages

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationStatusMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SlowSyncWorker.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationStatusMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationResponse.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/MemberUpdateDTO.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/MutedStatusSerializer.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationResponseJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/MemberUpdateRequestJson.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt

----
----
Additional PR that allows the mapping for the muting status in a conversation, when fetching/syncing.
- Epic: #405 
- JIRA Ticket: https://wearezeta.atlassian.net/browse/AR-1446
- More info at: https://wearezeta.atlassian.net/wiki/spaces/PROD/pages/1705328/Notifications
In this PR, we are adding the missing mapping from the conversation details muted status, so we can get it and display it on Android Reloaded
Since the field creation on the Conversation table was already done in a previous PR #405 Here we are only mapping/persisting when the sync is performed
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most …

feat: muting conversation status mapping for fetching (AR-1446)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCaseTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/client/ClientRequest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/RegisterClientRequestJson.kt

----
----
In kalium the password is mandatory to register client, but it's not in swagger
password is now optional
----
----

feat: support client register with optional password

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCase.kt

----
Currently there was no real use of ongoing calls and thus renaming it to be correctly used as IncomingCalls
Renamed the usecase to `IncomingCallsUseCase`

chore: Rename OngoingCallsUseCase to IncomingCallsUseCase

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetOngoingCallsUseCase.kt

----
----
We need a useCase for getting the active call.
Create a new usecase.
This call is considered active when it's established with another client.
----
----
----

feat: add usecase for getting ongoingCall

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationDetailsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseTest.kt

----
----
Currently only 1to1 conversations have the legal hold status, but according to the documentation:
> A conversation is under legal hold if any participant is under legal hold. 
so also group conversations should have such indicator. 
Added legal hold status also to group conversation details.
----
----

fix: add legal hold status also to group conversation details

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepositoryTest.kt

----
----
delete server config called with title instead of id
`config.title` -> `config.id`
i did add a unit test to ensure it's called with the right value
----
----

fix: delete server config called with title instead of id

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/core_failure/WrapApiRequestTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCaseTest.kt

----
----
We currently don't identify when an API request fails because we're unable to reach the server.
Ktor will throw `IOException` when we can't reach the server due to any reason.
Handle `IOException` independently from generic `Exception`, mapping it to the current `NoNetworkConnection` failure.
----
----

chore: identify lack of connection failures (AR-1312)

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendingSchedulerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendingScheduler.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendingSchedulerImpl.kt

----
----
Part 1 of the epic. Once a sending of messages fails due to lack of connection, we need to be able to schedule a retry in the future.
1. Define a `MessageSendingScheduler` that should be implemented on a platform-basis.
2. Call this `MessageSendingScheduler` from the `MessageSender` if a `NoNetworkAvailable` causes a failure.
I'll add tests to the next PR.
----
----

feat(messages): retry sending after reconnecting - PART-1: Schedule when failing

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt

----
----
- the search query from the DAO returned the contacts that also had the status as not accepted 
- extended the user dao method to query by additional ConnectionState argument 
----
----
----

feat: add filtering to the search result by only the accepted connection status

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/SendCallingMessage.kt

----
----
As we are now parsing the message date for diff when updating pending messages, when a message of type Calling was being passed, the date was in wrong format.
Add correct creation of calling message type with correct ISO.

fix: Add correct ISO message date for parsing

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ScheduledMessageWorker.kt

----
----
- Scheduler was not being invoked as it was expecting a `ServerMiscomunication` failure instead of `NoNetworkConnection`
- `MissingMethodException` when initializing the Worker.
The generic Worker constructor via reflection was being called instead.
Check the class of the worker being initialized and pass the correct arguments for the new `ScheduledMessageWorker`
Also: add some logs to make it easier to understand in the future.
On Reloaded, with these changes:
- Turn off internet connection
- Send a Message
- Close the app
- Turn on the internet connection
----
---- …

feat(messages): retry sending after reconnecting (PART-3): fix worker initialization

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/MessageDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserConversationDAOIntegrationTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/ConversationStubs.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/MessageStubs.kt

----
----
For AR-1312, I tried one implementation with `WorkManager` and scheduling one worker per message.
However, enqueueing one worker per message may be troublesome in case one fails. All subsequent tries fail too.
In this PR, expose a way to resolve pending messages for a user.
This will enable changing the implementation to enqueue just ONE worker for all pending messages.
This worker will:
- Fetch all pending messages
- Call `MessageSender` for each one of them.
----
----

chore: create a way to get unsent messages (AR-1312)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/id/IdMapperTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/client/ClientRequest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/client/ClientResponse.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/SimpleClientResponseJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/SimpleClientResponseTest.kt

----
----
When getting list of clients from users, we were expecting the `class` to be always present. Leading to crashes.
But the API doesn't always incldue that data.
When nothing comes up, replace with "unknown".
We currently' don't use this field for anything. So just putting in a String is fine.
Once we start using it, we should probably replace it with an enum or similar.
----
----

fix(network): handle unknown device class type when getting clients of users

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncPendingEventsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/SyncPendingEventsUseCaseTest.kt

Added SyncPendingEventsUseCase
It's needed for 1-time syncing of all the pending events, when the app receives FCM.

feat: Added SyncPendingEventsUseCase

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt

----
----
https://wearezeta.atlassian.net/browse/AR-1483
This work it's related to the creation of a connection of a user, "Send a connection request" in detail this PR takes care of the repo layer, namely: Calling the Network layer and persisting locally the response.
You could see prev. PR implemented here -> #468 
----
----
----

feat: send connection repository work - part 2 (AR-1483)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt

----
----
There were changes in the proto messages, the delete message stopped working and another issue was for the HideMessage the qualifiedConversationId is null, and the app was crashing.
Updated delete message functions and removed filtering messages based on the conversationId, now it's on relying on the messageId.
Delete messages for yourself from other devices should not crash the AR app.
Delete messages for everyone from other users should apply to the message in the AR app.
----
----
----

fix(delete-message): fix user verifier for self-deleted(hide) messages

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/SendCallingMessage.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendImageMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/PendingMessagesSenderWorker.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendImageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt

----
----
The names of the public functions inside `MessageSender` were a bit too close to each-other.
Tried to make their usage a bit more clear by changing the names and parameters needed in order to call them.
N/A
----
----

refactor: simplify, add docs and rename functions in `MessageSender`

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt

----
----
Currently, we are exposing the `ConversationEntity.Type` to clients, with this change we created an inner Type that lives on logic module therefore can be accessed by clients, or can be used for unit testing conversations on AR.
PS: Given the existing `ConversationDetails` type, it seems more difficult to just map it from the enum `ConversationEntity.Type` from DB. If you found a way to easily map it, let's talk :D
We are not exposing anymore a type from persistence module
Creates an equivalent enum on logic module side.
----
----
----

chore: dont expose dao type to clients (proposal)

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SyncRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SyncState.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/SyncRepositoryTest.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/CoreLogic.kt

----
----
Currently, the `SyncManager` is the one holding the SyncState, which makes it so far too many UseCases and other entities in the domain layer depend on it, even for read operations.
We can have circular dependencies:
* `Sync` may depend on `Calling` (for processing calling messages)
* `Calling` depends on `MessageSender` (for sending calling messages)
* `MessageSender` depends on `Sync` (to wait for sync to be completed before sending messages)
Move the logic of reading the `SyncState` to a repository, so we reduce the amount of circular dependencies.
----
---- …

refactor: hold the sync state in a repository (AR-1438)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/publicuser/SearchKnownUsersUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchKnownUserUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt

----
----
Currently while searching for the known users with a query starting with '@' we don't get results, even when searching valid handles.
- Add a new query to `Users.sq` to search based on user handle only.
- Add a check on the `SearchKnownUserUseCase`, which verifies if we should search only by handle or keep the normal search.
----
----

feat: search only by handle on search query starting with @ [AR-1558]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt

----
----
After logging with my production account on a fresh device, I got some weird crashes when trying to apply a hard cast on the `status` field of an Asset message. So I added this
----
----
----

fix: added guard against hard casting error

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/CurrentSessionFlowUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/CurrentSessionUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/SessionScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/session/CurrentSessionFlowUseCaseTest.kt
persistence/build.gradle.kts
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/SessionStorage.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/client/SessionStorageTest.kt

----
----
Currently, we only have a use case that returns a single value of the current session, and we have no way to observe changes to the current session. This caused the need to implement a check every interval of the current session, but it's not a proper way of doing that.
Implemented `currentSessionFlow()` using `MutableSharedFlow` to observe current session changes which can be used by invoking `CurrentSessionFlowUseCase`.
----

feat: add CurrentSessionFlowUseCase

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/AnswerCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/MuteCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/RejectCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/StartCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UnMuteCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/AnswerCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/EndCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/RejectCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/StartCallUseCaseTest.kt

----
----
We currently initiate the `CallManager` in a "lazy" way, but it is still initialized too soon.
Even before any calling message is processed or any call-related usecase is used, the `CallManager` and underlying AVS libs are initialized.
- We pass the instance of `CallManager` to `ConversationEventReceiver`.
- So, whenever a sync is going on, independently of the kind of message received, a `CallManager` is already created.
Make it `Lazy<CallManager>`.
The `ConversationEventReceiver` will only call it when/if needed.
Same for other use cases.
If no call goes on, we don't need to initialize this guy.
This also helps with some circular dependencies, as `SyncManager`, `EventReceiver`, `CallManager` and `MessageSender` are cyclic. I'm still …

refactor: make CallManager dependency lazier

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/user/connection/ConnectionApi.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/connection/ConnectionApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/connection/ConnectionRequestsJson.kt

----
----
https://wearezeta.atlassian.net/browse/AR-1503
Creates the API call for accepting a connection request (in fact, updating a connection status).
----
----
----

feat(accept-conn): calling api to update connection status - part 1 (AR-1503)

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetAllCallsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/GetAllCallsUseCaseTest.kt

----
----
`callsFlow()` is not being triggered when a call value of that flow is changed 
This is because we are creating a new MutableStateFlow for `callsFlow()`. Nothing will be fired because we are always passing the same value
I used the backup value of calls and map it to return the list of calls
with unit test
----
----
----

fix: allCalls flow is not emitting data after being updated

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt

Crash when failing to get details of the other user in a 1:1 conversation caused by pending or ignored/blocked connection requests
----
----
When fetching details of a conversation, the other user can be null or not found, leading to crashes.
Pending or ignored connection requests received during sync can create conversations without the other member.
Ignore these conversations when fetching details.
This fixes the persistent issue at least, no need to clear data to get it working.
This is not a full fix.
We also need to stop processing these connection requests (or process them depending on the status), during sync.
----
----
1. E.g. …

fix: Wolfgang bug

---

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt

…with them
----
----
Some messages are not being received.
We're not properly saving the crypto session after encrypting and decrypting messages.
Do it.
Due to the nature of the double ratchet algorythim with "gear slipping" implemented by Cryptobox/Proteus, it may take a few dozens of messages until the sessions lose sync enough to start doing failing.
I couldn't reliably create a test for this. But I'll give it another shot soon.
----
----

fix: missing messages (AR-1553) (AR-1541) (AR-1475)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfigRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepositoryTest.kt
persistence/src/commonMain/db_global/com/wire/kalium/persistence/ServerConfiguration.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao_kalium_db/ServerConfigurationDAO.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao_kalium_db/ServerConfigurationDAOTest.kt

----
----
Currently, when we try to store server config that's already stored, we receive `DataNotFound` error.
Insert query is in fact `INSERT OR IGNORE` and there are some `UNIQUE` fields, so when trying to insert the same config it's ignored, but new ID for this duplicated config is generated anyway and returned, so then to finally return this config, it tries to get it using newly generated ID and gets error because there is no such config stored.
First check if such config is already stored (comparing `title`, `apiBaseUrl`, `webSocketBaseUrl` and `domain`) and if so, then just update API versioning data (`commonApiVersion` and `federation`) because we may have more recent data for such config and pass this config's ID. If there is no such …

fix: inserting the same config

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetAllCallsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetOngoingCallsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetConversationDetailsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetConversationsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationDetailsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationMembersUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/GetSelfTeamUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/GetSelfUserUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/SetUserHandleUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ListenToEventsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncPendingEventsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/GetAllCallsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationDetailsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationMembersUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SetUserHandleUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/SyncManagerTest.kt

----
----
Sync is blocking in a lot of UseCases right now.
Things like getting list of conversations wait until all the events are processed to return results; sending of message waits for sync even BEFORE inserting into the DB, which freezes the send button while offline.
- Rename `performSyncIfWaitingOrFailed` to `startSyncIfIdle` and make it public so other UseCases can use it.
- Create a `waitUntilSlowSyncCompletion` so UseCases can at least hold until basic data is available. Useful for `GetSelfUser` for example.
- Rename `waitForSyncToComplete` to `waitUntilLive` as it better describes what it does (Sync doesn't "end", it stays alive, listening for new events until cancelled)
- Replace utilization of `waitForSyncToComplete` with one of …

feat: unblock sync

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ObserveSyncStateUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/ObserveSyncStateUseCaseTest.kt

----
----
Consumer apps have no way to display sync/online/offline status to users.
The only functionalities regarding Sync currently exposed are through `SyncManager` and some other `SyncPendingEventsUseCase` and `ListenToEventsUseCase`.
Create a `ObserveSyncStateUseCase`.
----
----

feat: add use case to observe sync state

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSFTRequest.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/Either.kt

----
----
`NullPointerException` during Runtime when returning null in `fold` nullables. The compiler doesn't complain about this:
```kotlin
val either: Either<Foo> = bar()
val result = either.fold({
println("Left case")
null
}, {
println("Right case")
it
})
```
The definition of `fold` accepts lambdas that return null. It accepts nullable `T` types.
Explicitly declare `T: Any` instead of the implicit `T: Any?` when no supertype is specified.
Compiler does it!
Can't write tests for this... as it doesn't compile anymore :) 
Type-safety FTW.
----
----

refactor: change fold so it doesn't accept nullable lambdas

---

buildSrc/src/main/java/Dependencies.kt

----
----
If you have bluetooth enabled and you are on Android 12 or newer, the app may crash for you
-  on launch
-  or when you start or answer a call
Starting from Android and later a runtime permission is required to use bluetooth. And since AVS lib is accessing bluetooth feature at the time we initialize it, this crash the app
We already did an improvement on our side by making AVS initialize lazely when we start or answer a call.
On AVS side, Dusan moved the BT initialization after call is entered
On Android 12 or later, try to make calls with BT turned on
----
----
---- …

fix:  app crash when bluetooth is turned on(AR-1461)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt

fix: protocontent mapper is not mapping GenericMessage.Content.Edited

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/call/CallApiImpl.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/call/CallApiTest.kt

----
----
Due to Ktor serialization on the data string we were sending to connect to a SFT server, the characters were being escaped: `{\"foo\":\"bar\"}`.
Properly parse the data string to a json so Ktor doesn't serialize/escape its content and thus successfully connecting to the SFT server.

fix: parse SFT connection data string to json

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt

----
----
Mute options are not respected
Only get conversations where the mute status is not `ALL_MUTED`
----
----

feat: respect muting options per conversation

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveMemberDetailsByIdsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveMemberDetailsByIdsUseCaseTest.kt

----
----
Currently we observe conversation members that are currently in the conversation so when trying to display a message from a user that's already removed from group, we get `NoSuchElementException`.
Implement new use case that allows us to observe member details by passing list of user ids that we want to observe.
----
----
----

feat: add use case to observe member details by id list [AR-1809]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/GetUserInfoUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/GetUserInfoUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/GetUserInfoUseCaseTestArrangement.kt

----
----
- we were not mapping the team name when getting the user details 
- map the team name by getting it locally if exists if not get it form remote.
----
----
---- …

fix: map the team name when getting the other user details

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnClientsRequest.kt

----
----
In clients handler, the json of clients  that we pass to AVS is encoded with an incorrect format 
Wrong passed JSON:
```
[ { userid: "value", clientid: "" } ]
```
Correct format:
```
{ clients: [ { userid: "value", clientid: "" } ] }
```
Fix that =)
Nothing visible to test
----
----

fix(conference-call): passing a wrong json format to AVS

---

.github/workflows/gradle-jvm-tests.yml
build.gradle.kts
codecov.yml

----
----
Our Codecov reports have missing files
Under investigation
Work in Progress:
1. Archive report for debugging
2. Next steps?
----
----

ci: Archive Kover report for debugging

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepositoryTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/keypackage/KeyPackageApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/keypackage/KeyPackageApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/keypackage/KeyPackageDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/keypackage/KeyPackageApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/keypackage/KeyPackageJson.kt

----
----
Fix the KeyPackagesAPI call
The return dto was not correct, added a new one.
Considered as Integer! but was a json model and the value in it.
Added a proper DTO.
----
----
----

fix(keypackages-api): mls keypackages count api call

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfig.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/server/ServerConfigTest.kt

----
----
when introducing changes to `ServerConfig` data class it can break some links in the app e.g. pricing, TOS and passwordRest
move the creation of those urls to kalium so it's more consistent and add unit tests
----
----
----

chore: consistent wire links

---

detekt/detekt.yml
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallClient.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallParticipants.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallMapperTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/SessionStorage.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/TokenStorage.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/kmm_settings/KaliumPreferencesTest.kt

----
----
We are not checking `EnforceSerializableFields` on all modules. Which can lead to breaking changes in the future being missed.
Enable them everywhere in Kalium.
`./gradlew detekt`
----
----

ci: enable `EnforceSerializableFields` on all modules

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt

----
----
While on background, no messages are received after a call message.
AVS requires Flow and Media managers to be initialized in order to process calling messages. And it never finishes initializing.
Start the managers eagerly.
Manually tested 👍🏻
1. Minimize an Android app and throw it away, killing it.
2. Call the account which is logged-in in the device
3. Send text messages to the same account
4. Open the app
5. You should see all messages and calls
----
----

fix: sync hanging when receiving calling messages on the background

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCaseTest.kt

----
----
When deleting messages, we can't display errors.
`DeleteMessageUseCase` waits for sync to be complete / until live. If Sync fails - because of lack of internet connection for example - then the UseCase invocation will be hanging indeterminately.
Don't wait for sync. The decision to sync or not can be delegated to the `MessageSender`, which doesn't care about it for non-pending messages.
`MessageSender` doesn't wait for sync for deleting messages. Also, it blocks indefinitely while waiting for sync when sending pending messages. I'm thinking about adding a timeout for it inside `MessageSender`, and schedule the sending for the future it the timeout is hit.
----
----
1. …

chore: dont wait for sync on delete message (AR-1271)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiverTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/test_util/TimeUtils.kt

----
----
After being added to conversations or after creating conversations, they are staying on the very bottom of the list.
The field `lastModifiedDate` that comes from the server is a LIE. The server doesn't store this information and this field shouldn't be used.
Update the field ourselves so we can sort the conversations.
* Create a group conversation
* As User A, create a group and add account B
* As User B, the new group should appear on the top of the conversation list
----
----

feat: put new conversations on top (AR-1673)

---

buildSrc/src/main/java/Dependencies.kt
network/build.gradle.kts
network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/api/message/EnvelopeProtoMapperImpl.kt
network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/api/message/OtrClientEntryMapper.kt
network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/api/message/OtrClientIdMapper.kt
network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/api/message/OtrUserIdMapper.kt
protobuf/build.gradle.kts

----
----
In `network`, we are still using some Java-based Protobuf to serialize the message envelope.
Replace those with PBandK.
N/A
The implementation is still inside `commonJvmAndroid`, because `OtrUserIdMapper` uses UUID, which is JVM/Android specific. In the future we still need to replace it with a multi-platform approach.
----
----

chore: replace old protobuf with PBandK

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/ObserveConnectionListUseCase.kt

----
----
Can't see cached connection requests and conversations when calling `ObserveConnectionListUseCase`.
`ObserveConnectionListUseCaseImpl` waits until app is live to start returning results, even if we already have them locally.
Just trigger sync instead of waiting for the app to become online.
- Build reloaded with this change on Kalium.
- Open main/conversations screen
----
----

feat: don't wait for sync when getting connection requests

---

logger/src/commonMain/kotlin/com/wire/kalium/logger/KaliumLogger.kt

----
----
Currently, the logs are writing into a `CommonLogger` writer, that means writing the output to `System.out`.
With this change, we are now taking advantage of Kermit `platformLogWriter()`  that returns the platform specific logger, ie: Logcat for Android, and will send to the correct `LogLevel` by the platform.
Before:
After:
----
----
----

chore: logs to use the platform specific log writer 

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/ObserveOngoingCallsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/ObserveOngoingCallsUseCaseTest.kt

----
----
In order to observe ongoing calls that is happening to be able to show on a particular conversation screen, we need a usecase to listen to the ongoing calls
Create ObserveOngoingCallsUseCase

chore: add observe ongoing calls usecase

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt

----
----
As seen in [OTR-Proto](https://github.com/wireapp/generic-message-proto#external):
> [External] message content is used if original message results in large payload, that would not be accepted by backend. Regular messages are encrypted multiple times (per recipient) and in case of multiple participants even quite small message can generate huge payload. In that case we want to encrypt original message with symmetric encryption and only send a key to all participants.
In this PR, I'm addressing one part of the step: making the `ProtoContentMapper` accept `ExternalMessageInstructions` and return the encoded ByteArray.
----
----
1. E.g. …

chore: map external messages to protobuf (AR-1760) [External Messages Part 1]

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/pagination/PaginationRequest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/connection/ConnectionApi.kt

----
----
Border cases, right now we had some code and logic for calling paginated endpoints, but we were not setting this correctly on the request body, so we were stuck in a loop trying to get always more pages. 
This fixes the issue, creating a request class that can be used in paginated endpoints, right now: Conversations and Connections.
Thanks to @vitorhugods for the detailed eagle eye 🦅 
----
----
----

fix: params setup for pagination support in api

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MemberMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MemberMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationEvent.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationResponse.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/EventContentDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/ServiceReferenceDTOJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationResponseJson.kt

----
----
`conversation_role` is not parsed in the network layer
1. refactor the `ConversationMember` to one sealed class that contains information about both self and other members.
2. in swagger the field `conversation_role` is optional but according to Akshay: "Hmm, the field is optional when sending it to the server. The server will always send the field.(The server assumes admin when the field is missing, I don't have the context behind this decision)" therefore i opted to make it a required field in kalium.
_Briefly describe how this change was tested and if applicable the …

feat(network): add conversation role to network layer [AR-1041]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt

----
----
IncomingCall flow returns the same value many times after accepting a call.
This causes some issues on the clients like displaying the same incoming call screen multiple times.
After accepting a call, the Participants callback will occur causing some changes on the `callsFlow`(since we are updating the participants list there). The old and the new values of the incoming call is not the same, so the new value will be emitted in the flow
Filter also by participants, incoming calls should not have an empty list of participants
On the Android app, receive a 1:1 call and accept it
You should not see incoming call screen twice
----
----
----
1. …

fix(calling): fix incoming call flow

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt

----
----
A failure when decoding external messages.
Still unknown, under investigation.
For now, add more logs.
N/A
----
----

chore: add more logs to handling of external messages (AR-1978)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCase.kt

----
----
On Android app, the incoming call screen is not appearing when we have an incoming call
It's a regression of this PR : [fix(calling): fix incoming call flow](https://github.com/wireapp/kalium/pull/645)
Using `distinctUntilChanged` to ensure that we are not emitting  the same incoming call many times
We need to check by id only because for group calls we can have already a list of participants that is not empty
Receive 1:1  and group calls
----
----
----

fix: incoming call screen sometimes not appearing for group calls

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestUser.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiverTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt

----
----
Some users aren't fetched by the app during the slow sync, because for instance they are from a different team, so they are displayed on system messages as "Deleted User".
Fetch unknown user data when handling system messages.
Add someone from other team to the group conversation and look at system messages from the perspective of other account, who isn't connected with that user.
----
----
----

fix: unknown users in system messages [AR-1909] [AR-1872]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationResponse.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/CreateConversationRequest.kt

----
----
After testing with big old accounts, we found out that:
- The server can't handle the load of 1000 ids to fetch conversations ids (413 error)
- `messageTimer` field for older messages, doesn't fit in a `Int` 🙃 
The requests to fetch conversations details, are now made in batch, taking in advantage the pagination from lists-ids endpoint. Now instead of collecting all-ids, we fetch it and persisted right away.
----
----
----

fix: edge cases old big accounts

---

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCaseTest.kt

----
----
- Add a use case for refilling the key packages if are 50% below the desired count.
- Add CLI command for refilling key packages
https://wearezeta.atlassian.net/browse/CL-10
Change the amount key packages we initially upload to something like 10.
run:
`> cli login refill-key-packages`
And you should observe that we initially upload 10 key packages followed by 90 when we check if we need to refill them.
As discussed the refilling could be triggered in a sync step. This will be done in separate PR.
----
----
----

feat: add use case for refilling key packages

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutReason.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/logout/LogoutRepositoryTest.kt

----
----
One of the criterias to stop sync automatically is when the user logs out.
Currently there are no ways to receive this event.
- Add a `observeLogout(): Flow<LogoutReason>` function to `LogoutRepository`.
- Add a `onLogout(reason: LogoutReason)` to `LogoutRepository`.
The idea is that `onLogout` should be called by entities (like the UseCases) with a reason. This event can be observed and handled by the SyncManager later.
----
----

chore: make logout observable (AR-1924)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationResponse.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/CreateConversationRequest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/model/ConversationAccessData.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/model/ConversationAccessDTO.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/model/ConversationAccessRoleDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationResponseJson.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/CreateConversationRequestJson.kt

----
----
missing access and access role info in the ConversationResponse.kt
just forgot to add it in the previous PR
1. rename `ConversationAccess` to `ConversationAccessDTO`
2. rename `ConversationAccessRole` to `ConversationAccessRoleDTO`
3. add access and accessRole to `ConversationResponse`
----
----
----

refactor: rename access model and add access intof to conversation response

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserConversationDAOIntegrationTest.kt

----
----
- the Query was uncorrect the previous one was. :
```
getUsersNotPartOfTheConversation:
SELECT * FROM User AS user
WHERE NOT EXISTS (SELECT user FROM Member AS member WHERE member.conversation == :converastion_id)
AND connection_status = "ACCEPTED";
```
which in fact always returned a empty list because if the converastion_id is valid every user from User returns true for WHERE NOT EXISTS as there must be a member having this conversadtion_id  which in turn was neglated and returned a empty list 
add additional check on the user id of the member 
Added regression tests
_Briefly describe how this change …

fix: users not in conversation SQL query 

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestUser.kt

----
----
User's email was not passed to the `UserEntity` in `UserMapper`, instead it was always null.
Pass on the email to the `UserEntity`.
----

fix: email not passed to UserEntity

---

Makefile
README.md

----
- [x conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
----
The make target for libsodium includes the command `make install` which can usually only executed by root successfully because it copies header files into /usr/lib/ directories.
Additionally the libsodium binary output will be copied into the user's system too but is missing in the `native/libs` directory.
Do not run `make install` but copy the artifact into `native/libs` on the `copy-all-libs` target

chore: copy libsodium artifact into native libs directory too

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/call/CallApiImpl.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/call/CallApiTest.kt

----
----
[v0] Before: `https://prod-nginz-https.wire.com/calls/config/v2`
[v1] Now: `https://prod-nginz-https.wire.com/v1/calls/config/v2`
Call API was calling config request from API v0 and not from v1.
Random issues in calling.
Remove initial backslash so it follows correctly to v1.

chore: adjust call api url to v1 and not v0

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApiImpl.kt

----
----
app crash when updating conversation options when the app is offline
missing try catch for IOException
----
----

fix: app crash when updating conversation options when the app is offline

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt

----
----
logout use case stuck at updating the logout status channel
the channel is not observed anywhere 
----
----

fix: logout use case stuck at updating the logout status channel

---

Makefile

----
----
Brew-installed rust behaves weird and brew is a dependency not mentioned anywhere.
Use the rustup toolchain installer which is the usual way how to install rust on other systems
Only `curl` but AFAIK curl comes with xcode command line binaries.

chore: install rust via rustup instead of brew

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/NotificationApiImpl.kt

----
----
Take the following code for example:
```kt
val collectingJob = launch {
notificationApi.listenToLiveEvents(clientId).collect {
// Handle events
}
}
// After a while, we cancel the collection, or the whole Scope it was launched in.
collectingjob.cancel()
```
When calling it, a WebSocket connection will be activated, events will be emitted, and after cancelling, **the connection won't be dropped**.
This sucks even more because the Backend won't send push notifications whilst the client has an active WebSocket connection.
Ktor's function `webSocketSession()` returns a `WebSocketSession` that is its own `CoroutineScope`.
The scope of the flow collector isn't the same as the `WebSocketSession`. So this means that when cancelling the flow …

fix: disconnect websocket on live events flow cancellation [AR-1924]

---

buildSrc/src/main/kotlin/Dependencies.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmm_settings/EncryptedSettingsHolder.kt

----
----
encryption keys created by `KeyStore` are not using strongbox when available 
update android crypto library and use `.setRequestStrongBoxBacked(true)` when creating a encryption key
----
----
----

feat: request strong box keystore for EncryptedSharedPreferences

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Calls.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAOImpl.kt

----
----
[AR-2079](https://wearezeta.atlassian.net/browse/AR-2079) and [AR-2026](https://wearezeta.atlassian.net/browse/AR-2026)
We were receiving multiple incoming calls when using the app, recurring calls or even ended calls kept on re-appearing after some time.
When rejecting/declining the incoming call, we would get the conversationID wrongly (combining `conversationId` and `id` would never match, as it was getting each from different calls).
Adjust the SQL query to get the correct call for conversation to update its status.

fix: multiple incoming call

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SyncRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/KeyPackageManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ObserveSyncStateUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SlowSyncWorker.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/SyncRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/SyncManagerTest.kt

----
----
We need to call `SyncManager` everywhere in the code.
- Start using the newly added mechanisms, like `SyncCriteriaProvider` to start Sync automatically.
- Disable `startSyncIfIdle` and deprecate similar functions in `SyncManager` so they can be removed in a future PR.
Also, tested manually on Reloaded using these changes.
----
----

feat: start sync automagically (AR-1924)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/UserSearchApiWrapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/publicuser/search/SearchUsersUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/UserSearchApiWrapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchKnownUserUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchUserUseCaseTest.kt

----
----
public search result was including the self user
filter out the self user from the public user search api results
----
----
----

fix: remove self user from public self user search

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/SelfClientsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationsAndConnectionsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/SelfClientsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationsAndConnectionsUseCaseTest.kt

----
----
Lists of devices after login and conversations after fresh install look like they are arranged randomly.
Sort list of devices by reverse chronological order and conversations by reverse chronological, and if that's enough or there is no "updated time" then by alphabetical order.
Install fresh version to see the conversation list order, have too many registered devices when logging in to see devices list order.
----
----
----

fix: order of devices and conversation list [AR-2009] [AR-2070]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetAvatarAssetUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt

----
----
1- app downloading user profile picture at the start of each sync.
2- other user's profile picture is downloaded too frequent
missing local lookup for pictures before downloading the images from remote
not downloading the user profile pic on sync
_Briefly describe how this change was tested and if applicable the exact steps taken to verify t
----
----
----

fix: downloading self profile picture in sync

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/ObserveConnectionListUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationDetailsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationsAndConnectionsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationDetailsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseTest.kt

----
----
Conversation list updates were being done too frequently, especially when first launching the app and because of that the whole list was being rearranged every time.
When fixing one issue with 1-1 conversations with deleted user, we created this one, because until now empty item was emitted at the beginning for each conversation and because of that every actual update with proper data (for every conversation independently) was emitting the whole list again.
Don't emit empty item, instead handle storage failure and pass it through the flow, add `distinctUntilChanged` not to emit the same values multiple times.
- https://github.com/wireapp/wire-android-reloaded/pull/808 …

fix: too frequent conversation list updates

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationMemberRoleUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationMemberRoleUseCaseTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/model/ConversationMemberRoleDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationApiTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt

----
----
We need to be able to change the member's role in the group as an admin.
Implemented the use case, relevant functions in the API and DAO repositories and new DB query.
----
----
----

feat: add update group role use case [AR-1603]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestMessage.kt

----
----
Handle to delete failed messages in delete message usecase.
When a message was failed and unsent, the delete wouldn't work because it was trying to delete a message that wasn't exist on the server side!
When the status was added it wasn't handled in the delete usecase.
Handle the failed messages in the usecase.
None!
Try to delete failed message, it should be deleted! [either by delete for me, or delete for everyone!]
Try to delete failed message, it should be deleted! [either by delete for me, or delete for everyone!]
----
----
----
1. …

feat(delete-message): Delete Failed Message (AR-2017)

---

.github/workflows/gradle-android-tests.yml
.github/workflows/gradle-ios-tests.yml
.github/workflows/gradle-jvm-tests.yml

----
----
Tests currently take a ton of time to run, and when multiple pushes are sent in a row, this creates a big queue of jobs to run on Github Actions.
For example, if someone sends three pushes in a short interval, which is a possible scenario (a couple of review suggestions + merge from develop, for example), all tests will run 3 times.
Android and iOS tests run on Mac machines, which are very limited for us. Which can cause looooong waits until all jobs are through.
We can manually abort all jobs, but this is error-prone.
Automatically abort jobs running in a PR when a new push is made.
For now, only long-lasting jobs are affected (JVM/JS, Android and iOS tests), so code-style (which runs on Linux anyway) can be seen.
Add a concurrency …

ci: abort current jobs when updating PR or develop branch

---

logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCaseTest.kt

----
----
Updated deleteMessageUseCase with Arrangement Pattern
To update and align current codebase with our agreements.
_Attachments like images, videos, etc. (drag and drop in the …

test: refactor DeleteMessageUseCaseTest with Arrangement pattern

---

buildSrc/src/main/kotlin/Dependencies.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt

----
----
When receiving calling messages in the background, the app stays stuck and doesn’t process any new messages, not showing any notifications.
This seems to be the case where AVS is initialized, we fetch calling configs from the server but after feeding them to AVS, it never calls `ReadyHandler`, so initialization never completes.
Whilst this was an issue in the past (where FlowManager and MediaManager were not yet initialised), we're not sure yet what could've changed to make this behaviour resurface, and AVS doesn't provide any kind of logging to help.
I’ve been in touch with @z-dule to help understanding AVS a bit better and what could be the cause of it. So it makes the job to find the culprit easier.
@z-dule released AVS 8.2.4, which …

fix: stuck processing calling messages in the background (AR-2133)

---

logger/src/commonMain/kotlin/com/wire/kalium/logger/KaliumLogger.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/Either.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCaseTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/asset/AssetApiImpl.kt

----
----
When message contains asset, then after deleting it delete also asset externally
- after deleting message asset was still stored externally
Before marking message as removed 
- fetch message locally
- check if contains asset
- if yes remove asset remotely
----
----
----
1. …

feat: remove asset remotely (AR-2034)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt

----
----
AR dosent compile
`MLSKeyPackageCountUseCase` was removed since from the ClientScope since it was thought to be unused.
Revert the change.
----
----
----

fix: restore MLSKeyPackageCountUseCase

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiverTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/EventContentDTO.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt

----
----
Given that, we are not handling the current events for when a user deletes a conversation. We are adding this event handler that will allow us to react and delete all contents related to a conversation (ie: messages, assets)
Note: Tests are coming in upcoming commits.
----
----
----

feat: deleted conversations events (AR-2040)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncStatus.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepositoryTest.kt

----
----
SlowSync happens every time
We don't handle all incremental sync events. So we need to perform SlowSync every so often.
Even though we still can't stay without performing SlowSync for long, we can build the base for the future and allow further progress with Sync retrying mechanisms in a realistic way.
In this PR: 
- Add a way to store SlowSync status
Currently in memory only, so SlowSync will happen again once the client is re-launched.
----
----

chore: add slow sync state and completion storage

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedIdMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/id/QualifiedIdMapperTest.kt

----
----
QualifiedIdMapper doesn't handle properly empty string parameter.
No `return` for the `if` that should handle it.
Changed to `return when...` and all cases handled in this single place.
Added extension function for easier use.
----

fix: QualifiedIdMapper crashes

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/contact/search/UserSearchApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/message/MessageApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/teams/TeamsApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/user/connection/ConnectionApi.kt

----
----
some remote requests not including API version
e.g.  ```https://staging-nginz-https.zinfra.io/list-connections```
it should be  ```https://staging-nginz-https.zinfra.io/v1/list-connections```
the default request plugin allows ignoring any default path if the request path have `/` at the beginning, for example the following HTTP client have `https://base.url/` as the base host and `v1` as base path
```kotlin
val client = HttpClient {
defaultRequest {
url("https://base.url/v1/")*
headers.appendIfNameMissing(HttpHeaders.ContentType, ContentType.Application.Json)
}
}
```
when doing a request with `file` as the path, the request URL is precisely what we want `https://base.url/v1/file`
```kotlin
client.get("file")
// <- requests …
```

fix: some remote requests not including api version

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedIdMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/id/QualifiedIdMapperTest.kt

----
----
When searching, after typing only "@" the app crashes, after typing "@" with anything else (for instance "@text", "something went wrong" info appears instead of search results.
QualifiedIdMapper finds the "@" sign, but when splitting the text, components are filtered out because they are empty, so the list of components is empty and it throws an error when trying to get `component.first()`.
QualifiedId is mapped wrongly for "@text" searches, because it sets "text" as both value and domain (`components.first()` and `components.last()` are the same).
Check if the list of components is empty and then return empty QualifiedId.
Differentiate the situation when we have one "@" and text before and after that ("text@text") or not ("@text", …

fix: Search with @ crashes the app (QualifierIdMapper crash) [AR-2151]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/ValidateEmailUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/ValidateEmailUseCaseTest.kt

----
----
incorrect email validation when the email contains a capital letter
convert the email to lower case before running the regex
----
----
----

fix: incorrect email validation when the email contains a capital letter

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/IncrementalSyncStatus.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/KeyPackageManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ObserveSyncStateUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/full/SlowSyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/full/SlowSyncWorker.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventSource.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorker.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/IncrementalSyncRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/KeyPackageManagerTests.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventGathererTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorkerTest.kt

----
----
The `State` of IncrementalSync is being managed in two places.
`EventGatherer` changes the state of `IncrementalSync`, when the only responsible should be `IncrementalSyncManager`.
Make it so the `EventGatherer` emits what's the source (Pending/Live).
`IncrementalSyncWorker` forwards this, and `IncrementalSyncManager` can collect the current source, changing the state as needed.
> **Note**: With all the pieces in their due places, this should be the last `refactor` PR before actually starting to add the Retry mechanism and connectivity monitoring to better.
----
---- …

refactor: better de-couple incremental sync layers

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt

----
----
Kalium is failing when refreshing tokens.
The following exception is thrown
```
java.lang.ClassCastException: com.wire.kalium.logic.feature.auth.AuthSession cannot be cast to com.wire.kalium.logic.feature.auth.AuthSession$Session$Valid
```
When performing this cast below:
```kt
// TODO: make the function return null when the update fails and delete the type casting
sessionMapper.toSessionDTO(it as AuthSession.Session.Valid)
```
Unpack the `session` before casting. So it can be cast correctly: `it?.session as AuthSession.Session.Valid`
----
----

fix: failure when updating session tokens

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncStatus.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ObserveSyncStateUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncExceptionHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/full/SlowSyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/SyncExceptionHandlerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/full/SlowSyncManagerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/test_util/FlowUtils.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/util/FlowUtils.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/NotificationApi.kt

----
----
Clients drop connection and never recover from it.
Add a retry mechanism to Slow and Incremental syncs.
The retry mechanism is quite simple at the moment:
- A real exception (not cancellation) is thrown
- Wait 10 seconds
- Try again
> **Note**: In the future we can optimise this. Retrying less frequently and observing connectivity changes (like mobile phones moving from Wi-Fi to Mobile Data, for example).
> However, on Android, for example, the WebSocket can be dropped when the app is put into the background or when the screen locks.
> So this delay-retry covers more ground and is more reliable for an initial implementation.
Opening the Reloaded app with these changes:
- Open a conversation
- Receive messages
- Turn Wi-Fi off and on …

chore: add sync retry mechanism

---

network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt
network/src/commonMain/kotlin/com/wire/kalium/network/session/SessionManager.kt
network/src/commonTest/kotlin/com/wire/kalium/network/session/SessionManagerTest.kt

----
----
Ktor requires the server to send a `WWW-Authenticate` header with `Bearer` value so it will refresh the tokens.
Wire servers don't return this, so we manually add this Header in order to get Ktor to refresh the token.
We have this implemented directly in our `OkHttp` creation, but this means that only JVM and Android were covered with this.
Since Ktor 2.0.0, it's possible to overwrite header values, as seen in [this PR](https://github.com/ktorio/ktor/pull/2522/files#diff-5acc2ecf72dfc4fd8710d98c274fada09eee9859cd1adb3936bf4396c982a0e6).
This means all platforms can be covered with this Header fix.
----
----
1. E.g. …

chore: add www-authenticate header for all platforms

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/NotificationApiImpl.kt

----
----
When the token expires and we attempt to call `listenToLiveEvents.collect()`, we get `java.net.ProtocolException: Expected HTTP 101 response but was '401 Unauthorized'`
OkHttp, which runs underneath, expects a protocol upgrade to WebSocket and doesn't handle the errors normally as other Http requests. So the exception leaks through Ktor.
Make another (normal) HTTP call before requesting the token. Because when the token is expired in normal HTTP calls, we handle it properly.
It's dirty 💩. But does the trick.
> **Note**: I'm currently investigating to see how feasible would be to properly handle the response. But given it's a WebSocket call, it's not expected (in code) to handle the response as a HTTP header.
----
----
1. …

fix: make sure token is refreshed before connecting websocket

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetRecentMessagesUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendKnockUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendKnockUserCaseTest.kt

----
----
With @vitorhugods we discovered that my first sent message after login did not arrive because it was send before the sync after the login did not finish.
To prevent this we now wait for the slow sync on certain use cases.
----
----
----

fix: wait for slow sync before certain use cases

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/logout/LogoutRepositoryTest.kt

----
----
When SlowSync fails due to whatever reason, it doesn't try again.
We observe LogoutReason to see if we can perform SlowSync or not. If the User has logged out or has a pending logout, we don't perform SlowSync
LogoutReason is being stored in a Channel and we are calling `consumeAsFlow()` which means that if the collection throws an exception, the original channel is closed.
Replace `consumeAsFlow()` with `receiveAsFlow()`, which doesn't affect the upstream channel.
Drop your internet connection right after opening Reloaded.
----
----

fix: Slow Sync not recovering from failure

---

logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationPagingResponse.kt

----
----
In Federated environments (multiple backends) we need to ignore conversations that are not being able to fetched when some backends are down.
Add correct mapping of failed and not found conversations, this returns a list of qualified ids, since we don't know any other info.
----
----
----

fix: mapping correctly failure and conversations not found (AR-1819)

---

buildSrc/src/main/kotlin/Dependencies.kt
cryptography/build.gradle.kts

----
----
Unlike the rest of the project, kotlinx-serialization plugin is using Kotlin 1.5.31, instead of 1.7.10.
We're using the version of the embedded Kotlin runtime that Gradle runs, instead of the specified 1.7.10 that we want.
Set a hard-coded version of 1.7.10 for kotlinx-serialization
N/A
----
----

chore: upgrade kotlinx serialization plugin

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveUserInfoUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/EitherFlow.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/ObserveUserInfoUseCaseTest.kt

`ObserveUserInfoUseCase` that allows to observe UserInfo changes and fetch it from API if there is no such one in DB
No such UseCase
It wasn't created 
Create it

feat: ObserveUserInfoUseCase

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCaseTest.kt

----
----
I forgot to add the slow sync before the send asset use case in my PR https://github.com/wireapp/kalium/pull/785
Add slow sync in asset send use case
Unit tests are updated in this PR
----
----
----

fix: do a slow sync before sending assets

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/configuration/ClientConfig.kt

----
----
When getting the `deviceName` on Android, there's a crash:
```
java.lang.SecurityException: Settings key: <bluetooth_name> is only readable to apps with targetSdkVersion lower than or equal to: 31
at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3081)
at android.provider.Settings$Secure.getStringForUser(Settings.java:6164)
at android.provider.Settings$Secure.getString(Settings.java:6120)
at vg.a.d(ClientRemoteRepository.kt:11)
at ug.e.d(Unknown Source:2)
at zh.i.a(RegisterClientUseCase.kt:16)
at com.wire.android.ui.authentication.devices.register.RegisterDeviceViewModel.z(RegisterDeviceViewModel.kt:10)
at od.g.l(RegisterDeviceViewModel.kt:8)
```
As it says, apps targeting SDK 32 or above can't get the …

fix(android): crash when getting device name

---

logic/src/jvmMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/PackagePathProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmm_settings/EncryptedSettingsHolder.kt
persistence/src/jvmTest/kotlin/com/wire/kalium/persistence/EncryptedSettingsHolderTest.kt

----
----
The `rootPath` parameter given to CoreLogic is not fully respected when running kalium on JVM. This means that deleting the `~/.kalium` directory does not delete all persistent state from former sessions.
In the JVM implementation of EncryptedSettingsHolder a third-party libary is used which saves app settings to a different location depending of the OS. On macOS this is a plist file in ~/Library/ and on Windows this is saved in the registry.
`JvmPreferencesSettings` is used in `EncryptedSettingsHolder` 
Additionally to `JvmPreferencesSettings` the library also provides `JvmPropertiesSettings` which saves the settings into a properties file instead. The loading and storing needs additional implementation though. This PR adds …

fix: save settings in rootPath on JVM instead of os-specific location

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt

----
----
The logs are flooded with `Failure getting other 1:1 user for, CancellationException bla blabla yadda yadda yadda`
We log Cancellation Exceptions
Don't.
CancellationExceptions can be ignored.
N/A
----
----

chore(logging): ignore CancellationException when getting member details

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/PublicUserMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserModel.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/SyncContactsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/UserSearchApiWrapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetAllContactsNotInTheConversationUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchKnownUserUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchUserDirectoryUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchUserUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestUser.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/NetworkErrorLabel.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/UserStubs.kt

----
----
In case we are not able to get info for federated users, we need to still be able to log in or interact with the app.
To handle users fetching, we are doing the following with this PR:
- Split the fetch of users details on sync process, ie: for same backend as self user, we fetch a list `/list-users` for other backends, fetch one by one `/user/domain/id` and assume `Success`.
- Add the mapping when users are deleted, so we can know if the user is not deleted and doesn't have a name, we can map "unavailable user" label.
**Note:**
IMHO: The ideal case, would be that this endpoint on the backend side, returns the same strategy as with conversations, namely. A list of: found, failed, not-found users. Without having to add all this logic on …

feat: federation resilient users mapping (AR-2097)

---

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt

----
----
Support connecting the CLI to any server by accepting a server config URL for the environment option:
login --environment https://nginz-https.anta.wire.link/deeplink.json
----
----
----

feat(cli): support passing a server config URL for environment option CL-61

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/test_util/TestNetworkException.kt

----
----
passwords with less than 6 chars resulting to server error
the server has a different response for this case
map the server response for short passwords to invalid credentials 
----
----
----

fix: passwords with less than 6 chars resulting to server error

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/SyncManagerTest.kt

----
----
For some UseCases, like creating a group conversation or starting a call, we must be `Live`.
However currently there's only one way to wait until Sync does something, which is `waitUntilLive`.
If the client is offline, these UseCases will be hanging forever without any feedback.
Create a new "wait until" function, that can return either success or failure.
This function will:
- Wait if Sync is in progress
- Return failure if Sync is Failed or Pending
- Return success if Sync is Live
The idea is to start using this, instead of `waitUntilLive` for UseCases that require the user to be Live.
----
---- …

chore: add a way to wait until sync fails or completes (AR-1947)

---

calling/src/androidMain/kotlin/com/wire/kalium/calling/callbacks/NetworkQualityChangedHandler.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnNetworkQualityChanged.kt

----
----
OnNetworkQualityChanged was throwing a NullPointerException
`userId` was being received as `null` and it was stated as `not null`.
Make `userId` nullable :)

fix: make OnNetworkQualityChanged userId nullable

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/StartCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/StartCallUseCaseTest.kt

----
----
When starting a call, the `StartCallUseCase` hangs when Sync is not `LIVE`
`callManager.startCall()` will trigger a `MessageSend` which will wait indeterminately until `Sync` is done.
Use the new `waitUntilLiveOrFailure` so we fail if Sync fails too.
----
----

feat(calling): handle sync failure when starting a call (AR-2145)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/UpdateKeyingMaterialThresholdProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/UpdateKeyingMaterialsThresholdProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/UpdateKeyingMaterialsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/UpdateKeyingMaterialsUseCaseTests.kt

----
----
Make updateKeyingMaterialsThreshold lower for debug builds to make it easier to test.
The reals threshold is 90 days! and that makes it hard to test by the QA, but by this change it would be 1 minute for debug builds.
Help the QA to test MLS Conversations behaviours.
Lower the value for debug builds.
Release with AR PR.
Create an MLS conversation, then go to the conversation details, remember the keying material update value, close the app and open it after one minute. after the sync check the group details again the keying materials update value should be changed.
---- …

feat(mls-conversation): lower update keying materials threshold for debug builds (AR-2163)

---

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCaseTest.kt

----
----
Currently, the `CreateGroupConversationUseCase` will hang indeterminately until Sync is performed.
Like in #814, use the new `waitUntilLiveOrFailure` function.
Also, instead of `Either`, which is not iOS-friendly, use a custom `Result` class for it.
> **Note**: This is a breaking change, so a PR in Reloaded is needed to handle this, which I'll be soon working on.
----
----

feat(conversation): handle sync failure when creating group conversation (AR-2146)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/DeleteTeamConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/TeamScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/team/DeleteTeamConversationUseCaseTest.kt

----
----
Fix to manally delete the conversation locally when is removed, this was originated because the new endpoints for deletion are not triggering any events.
----
----
----

fix: delete conversation locally after remote deletion

---

cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/MLSClient.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ProposalTimer.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PendingProposalScheduler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/Flow.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/PendingProposalSchedulerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt

----
----
Commit pending proposals as described in https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/601522340/Use+Case+Committing+pending+proposals+MLS
Summary:
When we receive a MLS proposal, indicated by a non null `commitDelay` when decrypting a incoming MLS message. We schedule a timer on the conversation to run at message-timestamp + commit-delay. The `PendingProposalScheduler` is observing if timers expire or have expired in the past when app is `Live` and it stops observing whenever the connection drops.
When a timer expire we try commit any pending proposals and clear the timer. If we fail commit the pending proposal we don't clear the timer and we'll do another attempt the next time the app goes Live.
Needs BE support to be …

feat(mls): commit pending proposals

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestMessage.kt

----
----
- Refactor MessageSenderTest to use arrangement pattern.
- Retry sending mls application message on stale message error after the incremental sync finishes.
Review individual commits to review fix in isolation.
----
----
----

fix(mls): retry sending mls application message on stale message error

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnConfigRequest.kt

----
----
When handling the client being offline when initiating the call, I noticed that if the call is hanged up while having no internet connection, the app was crashing. After debugging some code, it boiled down to the `OnConfigRequest` class, that was hitting a `NotImplementedError`. I patched it temporarily, but a more elaborated solution would be added in the near future.
A subsequent PR in AR project will be raised containing this fix.
Tests will need to be added to the `OnConfigRequest` class on a separate PR
----
----
----

feat: fix crash when hanging up and no connection

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSelfAvailabilityStatusUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt

----
----
Sometimes when Sync fails, the `UpdateSelfAvailabilityStatusUseCase` keeps hanging for ever.
We're waiting for Sync to be completed, which may take a long time in case it fails.
We don't need to wait for sync as we don't broadcast the availability status yet, we can just ignore the failure in this case and update locally only.
In the future, we can handle this more gracefully, by:
- Using `waitUntilLiveOrFailure`, which may return an error, AND/OR
- Scheduling the broadcast to be sent once Sync is Live.
Removed code, no need for new tests.
----
---- …

fix: update self availability hanging when sync fails (AR-2147)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/MLSClientProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt

… slow sync
----
----
Slow sync fails with a `KeyStoreException: database is locked` when joining existing MLS conversations.
Joining existing MLS conversations is executed in parallel each having its own MlsClient instance so that multiple connections to the underlaying SQLite database is created which is not supported and fails.
Use one shared MlsClient, CoreCrypto has internal locks which makes this safe.
----
----
----

fix(mls): database locked error when joining mls conversations

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSFTRequest.kt

…ast data
----
----
[AR-2179 - Group Calls stuck in white screen](https://wearezeta.atlassian.net/browse/AR-2179)
When joining group call, the user would get stuck in white screen.
Due to receiving a data Pointer in SFT Callback, when really working with it inside the scope, it would get toasted because the Pointer data would no more exist correctly then having an error when trying to connect to SFT servers.
Move logic of data Pointer to outside of calling scope when handling it.
- Uninstall App
- Install App (needs to be a fresh install as it was always happening on first call)
- Login
- Receive Call and accept it
- User should not be stuck in white screen anymore.

fix: group calls white screen

---

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/utils/AESUtils.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/FakeKaliumFileSystem.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/asset/AssetApiImpl.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/asset/AssetApiTest.kt

----
----
Currently, the app is crashing by out of memory exception, when we are dealing with big files, ie: > 60 MB
This happens because we were handling `ByteArray` (download and decryption) being an expensive DS for the device to handle.
Change the approach to read the `ByteArray` by chunks and write to a temp file.
On the decryption part, being JVM code, we can handle `InputStream`s =)
----
----
----

fix: refactor assets download to avoid OOM exception (AR-2125)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/featureConfigs/FeatureConfigResponse.kt

----
----
Make MLS data config in FeatureConfig API nullable and set a default value as disabled if it is null.
If the mls configurations is not set for a team the backend will not send the data for that key at all!
Break the sync.
Make mls data config nullable.
Fix the connection issue on federated environments without mls config.
----
----

fix(feature-config): handle missing mls configuration

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfig.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfigRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/session/SessionMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/util/stubs/ServerConfigStubs.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/configuration/ServerConfigApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/tools/ServerConfigDTO.kt
persistence/src/commonMain/db_global/com/wire/kalium/persistence/ServerConfiguration.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao_kalium_db/ServerConfigurationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/model/AuthSessionEntity.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao_kalium_db/ServerConfigurationDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/ServerConfigStubs.kt

----
----
there is no way to tell if a stored server config is built into the app or was stored with a deep link
add isOnPremesis to `ServerConfig` data class and set it to true when retrieving the server config value from a deep link
----
----
----

feat: add isOnPremises to ServerConfig

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/RemoveMemberFromConversationUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/RemoveMemberFromConversationUseCaseTest.kt

----
----
Message is only showed when user leaves conversation, but not where we are removing other user from conversation
Disable checking if selfUser left conversation

fix: show message after removing conversation member (AR-2038)

---

cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PendingProposalScheduler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt

----
----
When receiving a pending proposal we schedule a timer to commit it, but the timer never fires.
Timer was scheduled for a non-existent group id: "event.conversationId".
Use the  actual group id of the conversation.
Could have been avoided with stricter typing. Will introduce a `GroupId` type in a separate refactoring PR. 
----
----
----

fix(mls): commit pending proposals

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventGathererTest.kt

----
----
@tmspzz today has lost a few messages while using Reloaded.
Looking through the logs, it seems that the message should have come when fetching pending events.
Repeating the API request, the event was indeed there, however it was never processed.
In the logs around the request that should contain the message, the following can be found:
```
08-29 10:22:58.905 V featureId:event_receiver: REQUEST https://prod-nginz-https.wire.com/v1/notifications?size=100&client=redacted&since=79c948d2-2773-11ed-8001-62124d5bb85d 
failed with exception: nl.b: Socket timeout has expired [url=https://prod-nginz-https.wire.com/v1/notifications?size=100&client=629565824ec0c0d5&since=79c948d2-2773-11ed-8001-62124d5bb85d, socket_timeout=unknown] ms
08-29 …
```

fix: skipping events when failing to fetch pending events (AR-2302)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfig.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/server/ServerConfigTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/util/stubs/ServerConfigStubs.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/configuration/ServerConfigApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/NotificationApiImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/tools/ServerConfigDTO.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/WireDefaultRequest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/TestUtil.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/SSOLoginApiTest.kt

----
----
app showing server error when login
app not able to fetch server metadata from local DB
fixed it
----
----
----

fix: app not able to retrieve server meta data from local

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ProposalTimer.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ProtocolInfoMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedId.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PendingProposalScheduler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ProtocolInfoMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/UpdateKeyingMaterialsUseCaseTests.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt

----
----
Represent group IDs with explicit a GroupID type instead of a String in the logic module. 
Having this type would have prevented this bug: https://github.com/wireapp/kalium/pull/844
----
----
----

refactor: introduce a GroupID type in the logic module

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetSecurityClassificationTypeUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetSecurityClassificationTypeUseCaseTest.kt

----
----
Rename UseCase and type to indicate better the purpose of the security classification level of a conversation.
----
----
----

feat: refactor, naming security classification type

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMention.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/message/MessageTextEditHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/MessageTextEditHandlerTest.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt

----
----
To make unread message badges work well with different types of muting conversations, we need to have the option to observe not only unread messages count, but also unread mentions count. The problem is that we only use very simplified way of checking if the message contains mentions (checking if the text of the message contains the username or handle) which works for notifications but in order to count messages containing mentions it's better to create a desired db query rather than take all messages and check their contents one by one.
Created new table to store message mentions which are taken from the proto of `Text` message type. Implemented a query to count unread messages with mentions and added as a field in `Conversation`. …

feat: unread mentions count [AR-2278]

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfigRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/FederatedIdMapperImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/id/FederatedIdMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/util/stubs/ServerConfigStubs.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt

----
----
Now the feature flag and id mapper for calling is scoped into the global shared preferences.
This mapper and configuration should be scoped per user, so we can support multiple accounts correctly
----
----
----

fix: federation mapper usersession aware (AR-2311)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/EndCallUseCaseTest.kt

----
----
When you end a call and you camera is on at that time, next time you join the call you will join with camera on
We need to set camera state to false when ending the call
1. In a group call turn on your camera and then end the call
2. join the same call again, you should join with camera off
----
----
----

fix: join a call with video enabled by default

---

kotlin-js-store/yarn.lock
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/remote/ClientRemoteRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/GetOtherUserClientsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/PersistOtherUserClientsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendFailureHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/prekey/MessageSendFailureHandlerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/GetOtherUserClientsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/PersistOtherUsersClientsUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt

----
----
storing user client from MessageSendFailureHandler crashes the app
in kalium there are 2 places where a user clients are stored locally 
1. MessageSendFailureHandler
2. PersistOtherUserClientsUseCase
the only difference is in case of 1 we don't get the client type, but we do have it in case 2
Therefore, we had one function to handle both cases
```kotlin
override suspend fun saveNewClients(userId: UserId, clients: List<ClientId>, deviceType: List<DeviceType>?): Either<CoreFailure, Unit> =
userMapper.toUserIdPersistence(userId).let { userEntity ->
clients.map { ClientEntity(userEntity, it.value, deviceType?.get(clients.indexOf(it))?.name) }.let { clientEntityList ->
wrapStorageRequest { clientDAO.insertClients(clientEntityList) }
}
}
``` …

fix: storing user client from MessageSendFailureHandler crashes the app

---

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt
cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/MLSClient.kt
cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt
cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt

----
----
If we receive a `mls-client-mismatch` error when establishing an MLS group we fail the operation even though we can recover. 
We receive a `mls-client-mismatch` if we didn't include all the clients of a user when adding or removing a group member. Not including all the clients is a race condition, which we can recover from by re-trying the add operation.
Change MLSClient API so that we don't add any members when creating the MLS group locally.  That way we can retry the second step where we add the members to the group by wrapping the the operation in a `retryOnCommitFailure`.
----
----
----
1. E.g. …

fix: improve error handling on MLS commits - part 2 AR-2286

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnActiveSpeakers.kt

----
----
For investigation purposes, we are commenting the part of handling  active speakers in a call
----
----
----

chore(calling): disable active speaker for testing

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseImpl.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseTest.kt

----
----
Since we are allowing users to display conversations that they don't belong to anymore for history reasons, we need to add a flag variable indicating this.
----
----
----

fix: add isSelfUserMember to `Conversation` and `ConversationDetails.Group` objects [AR-1552]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/DeleteSessionUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/GetSessionsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/session/DeleteSessionUseCaseTest.kt

----
----
some times consumer clients need to do something after the logout before the session can be deleted e.g. navigation to a different screen
Separate the logout invocation form the release user session scope from memory, and create `DeleteSessionUsecase` to handle the delete and the release of in memory user session
----
----
----

refactor: Separate the logout invocation form the release user session scope from memory

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

This required Gradle Wrapper 7.3.3+, so Gradle Wrapper is now 7.5.1
----
----
When building the Android app, we get lots of warnings:
```
We recommend using a newer Android Gradle plugin to use compileSdk = 32
This Android Gradle plugin (7.0.4) was tested up to compileSdk = 31
This warning can be suppressed by adding
android.suppressUnsupportedCompileSdk=32
to this project's gradle.properties
The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 32
```
Upgrade Android Gradle Plugin
This also requires a newer Gradle Wrapper version, which was updated too
N/A
----
----
1. …

chore: upgrade android build tools to 7.2.2

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetMessageByIdUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt

----
----
The new GetMessageByIdUseCase is not visible by consumers of Kalium
I forgot in #885 🤦🏼‍♂️ 
Expose it in `MessageScope`
N/A
----
----

feat: expose GetMessageByIdUseCase (AR-1882)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt

----
----
Currently, when we are getting the conversation delete event, can be already handled in background, or during the sync process, so whenever when we are trying to delete this conversation the flow was not terminating creating an infinite wait state.
Provide a query, repo level, that allow us to get a Nullable conversation and with that, handle it in the correct way in the `ConversationEventReceiver`
The STR are in the current ticket https://wearezeta.atlassian.net/browse/AR-2298
----
----
----

fix: add correct handling for conversation delete (AR-2298)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/NeedsToRegisterClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/NeedsToRegisterClientUseCaseTest.kt

----
----
NeedsToRegisterClientUseCase returning true when account is invalid
check the account status before deciding if a client need to be registred or not
----
----
----

fix: NeedsToRegisterClientUseCase returning true when account is invalid

---

persistence/src/androidMain/kotlin/com/wire/kalium/persistence/dao/message/KaliumPager.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/dao/message/MessageExtensions.kt

----
----
There's a crash when updating items on paginated message list on Android
Re-using the same `PagingSource` in the `pagingSourceFactory` when creating the `Pager`
Create a new one on demand.
N/A
Not really testable without adding UI tests to Kalium's persistence module. Sounds like hell to be honest.
----
----

fix: crash on paginating messages (AR-1882)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/asset/AssetApiImpl.kt
network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/asset/AssetApiTest.kt

----
----
Sometimes when the user wants to send an image, he gets a network error.
When the token is refreshed, the repeated initial request gets 500, because the `Source` with file data is already closed.
Change `fileContentStream` to be a lambda.
Try to send an image message after leaving the app for some time.
----
----

fix: network error when uploading an image [AR-2349]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationEvent.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/EventContentDTO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt

----
----
There was an unhandled event for updating member role changes. 
Handle WebSocket event and update member role in local DB
Update member role in conversation and check if it updates in other device conversation details screen
_Attachments like  images, videos, etc. (drag and drop in the text box)_
https://user-images.githubusercontent.com/13151239/190134167-89083665-d0c0-40da-8b8d-cbfd57c9adc1.mov
----
----
----
1. E.g. …

feat: handle conversation member change event (AR-2337)

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnClientsRequest.kt

----
----
- In a conference call, if you join from different client you will not see your other tile in the grid.
- Audio not working if you join an ongoing call started from different client.
That's because we were not sending current user clients to AVS
Remove the filter that do that
----
----
----
1. …

fix(calling): show all clients of current user in the call (AR-2412)

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnClientsRequest.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MemberMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt

----
----
Not able to join an ongoing call and we only see current user tile
Fetching users and their clients from local storage. 
After a fresh instal the db and does not contains user and client ids of different conversation, so when we try to join the call we pass to AVS an empty list of participants
Revert code to retrieve users from backend
After a fresh install, try to join an ongoing call
----
----
---- …

fix(calling): can't join ongoing call (AR-2432)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/remote/ClientRemoteRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAO.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt

----
----
App crash due to  No enum constant client.DeviceType  exception
create a mapper for device type to map the values from the entity to the Device type 
open a random user profiles and check that it should not crash 
----
----
----

fix: app crash when open profile [AR-2450]

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
persistence/src/androidAndroidTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/cache/LRUCache.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/cache/LRUCacheTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserConversationDAOIntegrationTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/iosX64Test/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/jsTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/jvmTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt

----
----
Reloaded is querying a lot of User Details in a sequence, which contributes with DB connections deadlocking when multiple operations are being performed.
A simple LRU Cache to store the flows of `UserEntity` in the DAO.
This way:
- We have a single instance of `Flow<UserEntity>` for each UserId, as long as the cache isn't full.
- When the query is invalidated, we make sure that **only one** request to the DB will be made to fetch the updated details even if we have multiple observers for the same User.
As visible in `UserDAOImpl`, this `LRUCache` can be easily used for other entities if we want, like `Conversation` and `Team` for example.
I've done a benchmark comparing before and after adding this in-memory LRU cache.
I've ran the …

fix: slow performance when fetching user IDs repeatedly (AR-2435)

---

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt

----
----
Small improvement on insert messages side, as per benchmark the numbers with this PR will looks like:
```
Insert messages: WITH multiple transactions (currently 5 nested)
1 try
Took 50.928667ms to insert 100 text messages <==
Took 355.546333ms to query 100 messages
2 try
Took 52.569333ms to insert 100 text messages  <==
Took 433.300708ms to query 100 messages
=========
Insert messages: WITH ONE wrapping transaction
1 try
Took 36.601542ms to insert 100 text messages  <==
Took 428.650584ms to query 100 messages
2 try
Took 35.809708ms to insert 100 text messages  <==
Took 429.112333ms to query 100 messages
3 try
Took 37.497417ms to insert 100 text messages  <==
Took 430.110375ms to query 100 messages
```
Now we are using only one …

chore: enhancement on not using unnecessary nested transactions

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/GetUserInfoUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveUserInfoUseCase.kt

----
----
Team owner profile doesn't show the team name
we were checking for the member only from the user type when we try to get the team details
add extra condition to get the team details for the team owner as well while fetching the user profile info
open team owner profile, so now you should see their team name
----
----
----

fix: team owner name not visible [AR-2424]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedIdMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/id/QualifiedIdMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ClearConversationContentUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/GetFeatureConfigsStatusUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/MetadataDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/MetadataDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/client/ClientRegistrationStorageTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/MetadataDAOTest.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt

----
----
We query the DB too often for simple stuff like UserID, ClientID, and also for TimeStamp keys.
- To most, lack of caching. We should keep these values in memory, especially considering that they hardly change.
- For UserId, it's something static that does NOT change after the creation of `UserSessionScope`, so this should be injected into entities that need it.
- Deprecate `UserRepository.getSelfUserId`, so we start injecting `selfUserId`.
Had to make `getSelfUserId` suspendable to use the cache. This also required some changes in the code that was calling it.
- Cache the Metadata using the same approach used in #915.
N/A
Caching is already covered in tests.
----
----
1. …

fix: improve performance of fetching metadata from the database

---

calling/src/androidMain/kotlin/com/wire/kalium/calling/callbacks/NetworkQualityChangedHandler.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnNetworkQualityChanged.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Calls.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAOImpl.kt

----
----
Not able to start a call.
`selectLastCallCreationTimeConversationId` was getting last creation time from currently started call and not last closed call.
Add filter to get last closed call and not only last call.
- Open App
- Select a Conversation
- Start a call (everything should work as normal)

fix: start call regression

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionRepository.kt

----
----
sometimes reading a null value from the DB is not an error e.g. 
for users with email and password if ssoId is null -> wrapStoragRequest -> Either.Left(dataNotFound )
add wrapStorageNullableRequest to support such cases
----
----
----
1. …

fix: sometimes null is not an error

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/IncrementalSyncStatus.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCaseTest.kt

----
----
Call Notifications on Reloaded are stuck.
Not sure yet. Still investigating.
One possible blocking point can be in `GetIncomingCallsUseCase`:
For each `call` in the list, we call `conversationRepository.observeById`.
However, `observeById` has a `filterNotNull` operator which means that if we pass a conversation that doesn't exist, it will stay there blocked for ever.
Add logs.
Clear up the code a bit and replace `observeById` with `detailsById` which doesn't hang in case the conversation doesn't exist. This _probably_ doesn't fix anything, but at least clears up a bit.
N/A
----
----
1. E.g. `feat(conversation-list): Sort conversations …

chore: cleanup and improve logs related to notifications being stuck on reloaded (AR-2437)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/user/ClientEventsData.kt

----
----
Now we are crashing the app when receiving a user update event, this will handle basic infrastructure code to not crash sync and from this built the proper handling
Not finish the sync process when you receive a user update event
----
----
----

fix: basic handling to not break sync on user update event

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt

----
----
when we press log out in the app if we were getting messages at that same time , the app crash due to web socket didn't close 
delay the logout till the websocket closes 
----
----
----

fix: app crash when logout while getting messages [AR-1840]

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt

----
----
when we logout and login again without closing tha app , if we try to make the call the app will crash
the call manager was keeping the reference of the user id even after clear the user session provider
(we might need to update the call manager to be client related here )
clear the user from the call manager holder whenever we logout
login , logout , login again without close the app , try to make  a call 
----
----
----

fix: app crash when call after login

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventGathererTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt

----
----
After fetching pending events, and the `ConnectionPolicy` is `DISCONNECT_AFTER_PENDING_EVENTS`, `SyncState` stays on `LIVE`.
This is unintuitive and is a problem on Reloaded, because Reloaded does:
```kotlin
upgradePolicy()
waitUntilLive()
downgradePolicy()
```
However, takes a few CPU cycles until `IncrementalSyncManager` collects the change in `ConnectionPolicy`, and during this short time the `IncrementalSyncStatus` is still `LIVE`.
Which means that `waitUntilLive` returns immediatelly.
Reloaded would need to put an arbitrary delay between `upgradePolicy()` and `waitUntilLive()` in order to properly wait until Sync finishes.
Make sure that **every time** that incremental sync stops, the state goes back to `Pending`.
This way, when …

fix: update IncrementalSyncState state to pending after executing while policy allows (AR-2437)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCaseTest.kt

----
----
We still try to join any existing MLS conversation during slow sync when MLS is disabled.
Skip slow sync step if MLS is disabled.
----
----
----

fix: skip re-join MLS conversations during slow sync if MLS is disabled

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchUserUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Connections.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/util/MapperUtil.kt

----
----
Due to the DB performance issues, we found some places where we were querying the database nested in other queries.
- Injected the selfUserId instead of querying it every time
- Injected the teamId instead of querying it every time
When we fetch the connection, we need the other user info as well; we were fetching those data by querying the user info by the userId that exists in the connection; replace it with a join query, and now we return the userInfo with the connection data directly from the database.
- Queries nested in other queries in the DAO layer instead of joins on the db level
- Queries nested in other queries in the DAO layer instead of injecting the cached values like the selfUserId
_Briefly describe …

feat(connections): refactor db connections and more (AR-2510)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt

----
----
Clients are crashing when creating a `UserSessionScope`
```
E  FATAL EXCEPTION: main
Process: com.wire.android.dev.debug, PID: 17435
java.lang.NullPointerException: Attempt to invoke virtual method 'com.wire.kalium.persistence.dao.UserDAO com.wire.kalium.persistence.db.UserDatabaseProvider.getUserDAO()' on a null object reference
at com.wire.kalium.logic.feature.UserSessionScopeCommon.getUserRepository(UserSessionScope.kt:276)
at com.wire.kalium.logic.feature.UserSessionScopeCommon.getConversationRepository(UserSessionScope.kt:256)
at com.wire.kalium.logic.feature.UserSessionScopeCommon.<init>(UserSessionScope.kt:207)
at com.wire.kalium.logic.feature.UserSessionScope.<init>(UserSessionScope.kt:29)
at …
```

fix: crash when starting up UserSessionScope

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt

----
----
Exposed the connection lastUpdateTime in the conversationsList view
In the view we were considering the lastUpdate date time only for conversation, now we expose that field from the connection if the conversation type is a connection-pending.
The ordre of the connections in the conversations was not correct.
By exposing the connectionDate in the query, the order now is fixed.
_Attachments like images, …

fix(conversation): order of sent connections in convo list (AR-2543)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt

----
----
Inserting the conversation when we want to persist a connection request[received or sent]
Following the changes we did for the conversation list, now we're relying on a select that it's a result of a join of Conversation and Connection tables, when we send a connection or receive one, we only insert the related data into the Connection table. In the end the conversation list view wasn't concluding the connections data because there wasn't any conversation to survive the join!
Change of structure.
Insert the conversation object alongside of the persisting the connection request [either sent or received]
- for sent connections, we fetch the conversation details by id from the server and the persist it!
-for received connections, there is …

fix(connection): show sent/received connections in conversation list (AR-2541)

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq

----
----
Added ignore case to the conversation list sql query.
It was sorting UpperCase first the lowerCase names.
SQL ordery by considers cases.
Added `COLLATE NOCASE` to the query.
----
----
---- …

fix(conversation): sort alphabetically ignore case (AR-2557)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionStatusMapper.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt

----
----
After accepting the connection, we need to update the conversation type to one-on-one!
Conversation/Connection after accepting it by the second user was still as Connection-pending.
Missing logic.
Updated the conversation type in related places.
----
----
----
1. …

fix(conversation): show conv after accept connection (AR-2553)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt

----
----
There were some problems not being able to display asset messages that were sent from AR. The main issue was that in AR we were just sending one full message containing all the asset metadata as well as the encryption keys. However, Web/Mac clients, were sending 2 messages, one with the preview data and empty decryption keys, and another one with the decryption keys but empty metadata. Now we will be supporting both ways of sending/receiving asset messages.
_Attachments like images, videos, etc. (drag and drop in the …

fix: asset issues [AR-2552]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MLSMessageCreator.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MLSMessageCreatorTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt

----
----
We would attempt do operations like adding a user to an MLS group without first committing any pending proposals.
Always commit any pending proposals before:
- Sending an application message
- Adding a user
- Removing a suer
----
----
----

fix(mls): commit pending proposal before sending an MLS message AR-2568

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt

----
----
The API used to add members to a conversation is using an old deprecated non federated endpoint which has been removed in V2.
Use the proper federated endpoint
----
----
----

fix: addMember uses deprecated non-federated API AR-2573

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfigRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepositoryTest.kt

----
----
fetching server config does not handle version unsupported error
handle version not supported errors and add unit tests
----
----
----

fix: fetching server config does not handle version unsupported error

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCase.kt

----
----
With the refactors made to being able to manage Image Previews sent from other clients, we broke the progress bar indicator, this brings back the indicator (at least for generic assets).
Also was added a correct handling for errors while downloading.
Note: This is an intermedius step, we are going to refactor this use case after the release.
https://user-images.githubusercontent.com/5806454/193938510-34945f11-bcd3-4c0c-9fc4-9337f3614341.mov
----
----
----

fix: progress bar indicator for downloading generic assets

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt

----
----
When running the discard commit & retry strategy when re-trying a failed commit we didn't wait until we've received all incoming events before re-trying.
Wait for all incoming events to finish syncing before re-trying.
----
----
----

fix: wait until live in discardCommitAndRetry strategy AR-2586

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq

----
----
When a user added to an mls conversation and fresh login on a client, the group for that client is in pending-welcome message state, that group is not usable! after seconds, the pending welcome message will be resolved by others and the group will be set as Established and would be usable!
So as an MVP solution before making a nice UI-flow for such a group, we filter out the group that are not established in the conversations list.
Filter invalid groups from the conversations list.
Waiting for pending welcome-message to be committed by others.
MVP Solution: filter them out till the state updates to Established
Ultimate solution: show the group but also in a state that the user can't send/receive messages and show e.g. the reason. …

fix(mls): only show established conversations in the conversation list (AR-2030)

---

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCaseTest.kt

----
----
No system message is inserted when adding a user to a conversation.
Not implemented in the `AddMemberToConversationUseCase`
Add the missing implementation and align adding a member with removing a member.
----
----
----

fix: missing system message when an adding member to a conversation AR-2572

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq

----
----
ALl proteus conversations are hidden
Incorrect SQL query
Fix SQL query to handle both the proteus and mls conversations
----
----
----

fix: broken query for filtering non established MLS conversations

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/authenticated/AssetApiV2.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v2/AssetApiV2Test.kt

----
----
Asset upload on staging backend broke with 502 error.
The current code uploaded assets to `staging-nginz-https.zinfra.io/v2/ass****/v3` but the API on staging backend recently changed to `staging-nginz-https.zinfra.io/v2/ass****`
Using correct path for v2 api.
Testing was done through kalium-testservice. Uploading assets works again after using the fix.
----
----
----

fix: adjust asset upload to change in backend v2 api

---

logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepositoryTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/BackendMetaDataUtil.kt
network/src/commonTest/kotlin/com/wire/kalium/api/common/BackendMetaDataUtilTest.kt

----
----
Our app currently has SupportedApiVersions = [0, 1, 2] and BE announces [0, 1] as supported and [2] as supported in development. This means that 2 is currently in development and can get breaking changes at any time. We ship production builds  with `developmentApiEnabled = false` so they will only use version [0, 1].
Now backend releases version 2 and introduces version 3 as the new development version.
Our previously shipped production builds will now switch to use version 2 since that's highest common version but there's no guarantee that the version 2 implementation which shipped in the previous production builds is compatible with the now released version 2 since backend is allowed to break API at any time until it's released.
💣 💣 …

fix: avoid using unfinished API implementations AR-2592

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepositoryTest.kt

----
----
If you try to create a group with a user who don't have any MLS clients the operation would be reported as successful but the user was not actually added to the user MLS group.
The request for claiming key packages return an empty list in this case, which was silently ignored because the result is merged into single list of key packages for many users.
Fail the `claimKeyPackages` operation if a user doesn't have any key packages available.
We should also persist users after the MLS add operation has successfully finished. This will be handled in different PR though.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by …

fix: fail when trying to add a user without key packages to a group AR-2596

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageTarget.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ClearConversationContentUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt

----
----
[AR-2571 - Targeted messages not implemented](https://wearezeta.atlassian.net/browse/AR-2571)
This is only `PART 1`, another part will follow where this changes are properly used.
We were always send OTR messages to all recipients in a conversation.
There was no parameter for receiving target recipients.
Add target recipients as parameter.

chore: sendMessage with recipients parameter

---

calling/src/androidMain/kotlin/com/wire/kalium/calling/callbacks/SendHandler.kt
logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/CallManagerTest.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/AvsCallBackError.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnHttpRequest.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSendOTR.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/mapper/CallMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/mapper/ParticipantMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeCommon.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/ParticipantMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestCall.kt

----
----
[AR-2571 - Targeted messages not implemented](https://wearezeta.atlassian.net/browse/AR-2571)
This is Part 2 final which contains the logic that parses the target recipients received from AVS to be send as a target message.
We were always send OTR messages to all recipients in a conversation.
There was no parameter for receiving target recipients.
Receive target recipients, parse it and send as parameter to `sendMessage`.
Can only be merged after:

chore: calling target messages logic

---

protobuf/build.gradle.kts

----
----
The IDE can't resolve the generated Protobuf code.
We use a module called `protobuf-codegen` which is JVM only to generate the Protobuf files because the [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) doesn't support multiplatform.
Then, we add these generated files as a sourceset to the `protobuf` module, which is Multiplatform.
The problem is that protobuf-gradle-plugin [adds the generated sources](https://github.com/google/protobuf-gradle-plugin/blob/8dbac6395d23828cee5e298da61ab6c268987a9c/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L277) to the `protobuf-codegen` module too, and the IDE can't handle the fact that the same files are being used by multiple modules at the same time and …

fix: resolution of generated protobuf code

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationEvent.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/NotificationApiV0.kt

----
----
After going for incremental sync, we lost the handling of update muting state. 
Adds handling for `conversation.member-update` that also covers muting status of a conversation.
----
----
----

feat: handling conversation muting event for incremental sync

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/conversation/ConversationApiV0Test.kt

----
----
Calling add member results in 404 endpoint not found when running API v1
Remove domain from path.
----
----
----

fix: add member API endpoint doesn't include the domain on V0 and V1

---

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt
cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt
cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/exceptions/ProteusException.kt
cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt
cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt
cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt
cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/ProteusClientProvider.kt

----
----
After closing and reopening the app, some actions like sending message result in `MissingClientRegistration`.
ProteusClient isn't retrieved from the local files after reopening the app.
Split `open` method into two: `openOrCreate` and `openOrError`. First one creates Proteus local files by opening the box even when not existing, the second one checks if files already exist and only then opens the box, otherwise returns failure.
Install the app, login, close the app, reopen again and try to send a message.
----

fix: MissingClientRegistration after reopening the app

---

logic/build.gradle.kts
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/reaction/ReactionRepositoryTest.kt
persistence-test/build.gradle.kts
persistence-test/src/androidMain/AndroidManifest.xml
persistence-test/src/androidMain/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt
persistence-test/src/commonMain/kotlin/com/wire/kalium/persistence/TestGlobalDatabase.kt
persistence-test/src/commonMain/kotlin/com/wire/kalium/persistence/TestUserDatabase.kt
persistence-test/src/iosX64Main/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt
persistence-test/src/jsMain/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt
persistence-test/src/jvmMain/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/util/FileNameUtil.kt

----
----
We are always mocking the Database.
For some complex high-level tests it's way easier (and faithful to actual prod code) to use a real Database.
For example, if we want to test a scenario where we receive a Sync event, like new message, and then call a UseCase to get messages from a conversation.
Mocking all the different mechanisms would be a huge pain.
Create a `persistence-test` module, which can be used by consumers of `persistence`.
This module contains simple `TestUserDatabase` and `TestGlobalDatabase` classes that can be used to grab DAOs and use actual DAOs instead of mocks.
In this example (added in this PR to the `logic` module), we test the `ReactionRepository` using an actual Dao:
```kt
class ReactionRepositoryTest { …
```

test: add tools to create databases for testing

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/asset/AssetApiV0Test.kt

----
----
Some users reported some crashes when opening certain conversations. After reading the logs, it seems that there are some issues regarding actions on the `KaliumFileSystem` when downloading assets. So since I can't reproduce these crashes, nor deduct what may be causing them, I added a preventive mechanism with a `try/catch` clause to at least prevent the app from crashing.
----
----
----

fix: crash with random failed asset downloads

---

logic/src/commonTest/kotlin/com/wire/kalium/logic/test_util/TestKaliumDispatcher.kt
persistence-test/src/androidMain/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt
persistence-test/src/iosX64Main/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt
persistence-test/src/jvmMain/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt
persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt

----
----
Using the new `TestUserDatabase` is waaay slower than using mocks.
For example, taking the changes from #1057, `SlowSyncRepository` is using an actual database instead of in-memory implementation.
With those changes, the `SlowSyncRepositoryTest` suite went went from 170~220ms to around 4.5 seconds.
With those changes, and this change to use in-memory database for testing, the test suite went down to 350~420ms on my machine.
Switching the file database to an in-memory version
Disk operations are slow.
Use in-memory database for testing.
N/A
----
---- …

test: use in-memory database for testing

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt

----
----
`NullPointerException` when initializing `UserSessionScopeCommon`.
- `platformUserStorageProperties` is not initialized yet, it will be initialized by the child class.
- `UserSessionScopeCommon` is abstract and it's easy to oversee the mistake of relying on abstract fields, leading to `NullPointerException`.
In order to prevent this from happening in the future:
- Rename `UserSessionScopeCommon` to `UserSessionScope` and make it a final class.
- Remove the platform-specific `UserSessionScope` by transforming them into a function. Platform-specific parameters now must be passed via the constructor of `UserSessionScope`, so it's up to each platform to figure out how to create the needed properties.
Manually tested on JVM and Android. …

refactor: make UserSessionScope class final

---

logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/ObserveIsConferenceCallingEnabledUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/GetFeatureConfigsStatusUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/config/UserConfigStorageTest.kt

----
----
[AR-2535 - Calls restriction on non paying members](https://wearezeta.atlassian.net/browse/AR-2535)
This is the PR for tests only.
Users that aren't in a paying team were able to start a conference/group call.
We weren't checking for this feature flag.
Correctly listen and verify the feature flag value when starting a conference/group call.
This is the PR with tests
It is not possible to test it yet, tests will be possible when Kalium side is merged and will be used in AR.

feat: restricted conference calling part2

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt

----
----
We're performing SlowSync every time Kalium launches
We didn't handle all necessary events when receiving them through the REST API or Websockets. We still don't, but we are handling the necessary ones for Kalium to work properly at the moment.
Perform it once a week.
Why once a week?
Cause it's a time long enough that may expose important events we could be ignoring, and not too short that would prevent us from seeing the benefits of this change.
Inside `SlowSyncManager`, when the time comes to perform it, we check the last time it was performed. If it the time since the last slow sync is longer than a treshold (7 days), we perform it again.
Sync! And try to Sync again :)
----
----
1. …

feat: perform SlowSync only once a week (AR-2597)

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/authenticated/ConversationApiV2.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/conversation/ConversationApiV0Test.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v2/ConversationApiV2Test.kt
network/src/commonTest/kotlin/com/wire/kalium/model/EventContentDTOJson.kt

----
----
Add member response parsing fails when using API v2
Response parsing changed but was only updated in API v0
Apply changes to v2
----
----
----

fix: add member not working against API v2

---

.gitattributes
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq

----
----
GitHub doesn't add syntax highlighting for `.sq` and `.sqm` files.
Add `.gitattributes` instructions to add `SQL` syntax to these files.
* Check the diffs below, and/or
* Browse a `.sq` or `.sqm` file on this branch and compare it with browsing it on `develop`
----
----

chore: enable SQL syntax highlighting on GitHub for sq and sqm files

---

.github/workflows/gradle-android-tests.yml
.github/workflows/gradle-ios-tests.yml
.github/workflows/gradle-jvm-tests.yml
README.md
build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt

This reverts commit 0006ec624d1e269301f24d0374e0935f59235af1.
----
----
Revert https://github.com/wireapp/kalium/pull/1088 until I have a solution for local CI and AR
----
----
----

chore: Revert "chore: fetch core-crypto from github packages (#1088)"

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreator.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt

sending mentions was not possible
- `SendTextMessageUseCase` was not accepting Mentions as a parameter 
- `ProtoContentMapper` was not mapping mentions correctly for sending messages
- add mentions as a parameter into `SendTextMessageUseCase`
- fix mapping in `ProtoContentMapper`

fix: Make SendTextUseCase accept mentions

---

network/src/commonMain/kotlin/com/wire/kalium/network/KaliumKtorCustomLogging.kt

----
----
Network Réponse logs span across multiple lines making it hard to correlate response status to endpoint for automated analysis
Group several attributes in 1 line
----

chore: group network respose logs to one line

---

logger/src/commonMain/kotlin/com/wire/kalium/logger/Extensions.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserModel.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt
network/src/commonMain/kotlin/com/wire/kalium/network/KaliumKtorCustomLogging.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/SerializationUtils.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt

----
----
Logging is a bit all over the place. This is an attempt to try and standardise a few representations. When fed to the appropriate tools, not only the logs are searchable but the log lines containing json can be used to perform more complex queries.
Change the `toString()` representation of some objects to actually be JSON, without the object itself declaring it can be serialised to JSON
1. have a way to create `JsonElement` from any `Map<String, Any>`
2. for every object create a `Map<String, Any>`
3. produce string `"${map.toJsonElement()}"`
4. ...
5. Profit
```
2022-11-04 12:16:07.914 7133-12629/com.wire.android.dev.debug V/DataDogLogger: Message received: { "message" : {"type":"calling","id":"90d6673***","conversationId":"870d00d***@ …
```

chore: improve logging by serializing to impromtu json

---

.github/workflows/gradle-android-tests.yml
.github/workflows/gradle-ios-tests.yml
.github/workflows/gradle-jvm-tests.yml
README.md
build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt

----
----
Fetch core-crypto from Github Packages by replacing the `wire-maven` repository.
❗ GitHub Packages currently requires authentication so I added a new section to the  README on how configure Github Packages credentials. 
----
----
----

chore: fetch core-crypto from Github Packages

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationMutedStatusUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationMutedStatusUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandlerTest.kt

----
----
1. after conversation delete endpoint is called, the app is calling updates mute status as well.
2. update conversation mute status end point is called multiple times in row.
1. is out of the scope of this PR
2. when receiving an update mute status event from BE the app is updating the mute status remotely and locally which trigger another conversation mute status update event. 
_Attachments like images, …

fix: update conversation mute status end point is called multiple times in row

---

network/src/commonMain/kotlin/com/wire/kalium/network/NetworkClient.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/networkContainer/AuthenticatedNetworkContainerV0.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/authenticated/networkContainer/AuthenticatedNetworkContainerV2.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/authenticated/networkContainer/AuthenticatedNetworkContainerV3.kt
network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/AuthenticatedNetworkContainer.kt
network/src/commonMain/kotlin/com/wire/kalium/network/session/SessionManager.kt
network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/common/SessionManagerTest.kt

----
----
Code path for refreshing access token is hardcoded to use Api V0.
Inject `accessTokenApi` with the negotiate api version.
----
----
----

fix: access API was hardcoded to v0 when refreshing access token

---

testservice/Jenkinsfile
testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt

----
----
Fix to be able to get latest core-crypto library from restricted maven repository which was introduced with https://github.com/wireapp/kalium/commit/ab723db942d4c899c3d52378841aa3347b6d2888
Additional adjustment to an API change in the ServerConfig object (proxy variable without default value)
----
----
----

fix: Use personal github token to be able to download core-crypto

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/RenameConversationUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/RenameConversationUseCaseTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationRenameRequest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/conversation/ConversationApiV0Test.kt

----
----
Kalium side logic, to update/rename a conversation, this includes:
- Usecase to operate
- Creation of system message triggered by action
- API calls to update endpoint
Enables renaming usecase for usage of reloaded app flow.
----
----
----

feat: rename group conversations flow (AR-1112)

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/NetworkClient.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/LogoutApiV0.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/networkContainer/AuthenticatedNetworkContainerV0.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/authenticated/networkContainer/AuthenticatedNetworkContainerV2.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/authenticated/networkContainer/AuthenticatedNetworkContainerV3.kt
network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/AuthenticatedNetworkContainer.kt
network/src/commonMain/kotlin/com/wire/kalium/network/session/SessionManager.kt
network/src/commonTest/kotlin/com/wire/kalium/api/TestSessionManagerV0.kt
network/src/commonTest/kotlin/com/wire/kalium/api/common/SessionManagerTest.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/user/logout/LogoutApiV0Test.kt

----
----
the access token has a lifetime of 15 min but it was noticed that in some cases the refresh is executed more often that it need to.
each user has 2 HTTP clients at a time and each have its own AuthTokens cache. 
when one of the HTTP clients update the token, the second one is still had the old token cached, which lead to the token being updated twice in a row,
move the caching of tokens to the `SessionManager`
----
----
----

fix: app refreshing auth tokens more that it needs to

---

testservice/Jenkinsfile
testservice/README.md
testservice/build.gradle.kts
testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt

----
----
1. The testservice did not upload prekeys after a certain change [AR-2675](https://wearezeta.atlassian.net/browse/AR-2675)
2. The testservice could not be started up via fat jar anymore
1. flag developmentApiEnabled in kaliumConfig is now set to true
2. Gradle Shadow Plugin is used to create a better fat jar than before
----
----
----

fix: enable development api on testservice and fix fat jar creation [AR-2675]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MigratedMessage.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PersistMigratedMessagesUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ProteusMessageUnpacker.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/PersistMigratedMessagesUseCaseTest.kt

----
----
Migration of messages logic on Kalium side:
- Creation of UseCase to persist migrated messages
- Reusage of existing `ApplicationMessageHandler` to allow proper parsing and transformation of ProtoMessages
Enables the migration of messages.
* WIP
----
----
----

feat: migration of messages (AR-2626)

---

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/MetadataDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/MetadataDAOTest.kt

----
----
We receive multiple 404 responses for the `/push/tokens` requests when we have multiple accounts logged in.
Because of the way our metadata storage is created - it's a key-value DB and to observe changes, we have `valueByKeyFlow` method which transforms `Query` into a `Flow`. The problem is that every update/insert into this table, makes the `Query` dirty and results in re-emission of the same item even if it's another row that has been changed. I was able to make an infinite loop by just adding a random, not related key-value to metadata table after each `/push/tokens` request to prove it. 
Add `distinctUntilChanged` to `valueByKeyFlow` to prevent emitting the same item if another row has been changed.
Have multiple accounts logged …

fix: multiple /push/tokens requests [AR-2691]

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/model/ConversationAccessInfoDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/api/base/authenticated/notification/AccessUpdateTest.kt
network/src/commonTest/kotlin/com/wire/kalium/model/EventContentDTOJson.kt

----
----
The `access_role_v2` will be renamed to `access_role` in a future version of the backend so during a transition period we will need to support both cases.
For more details see: https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/672006169/API+changes+v2+v3?focusedCommentId=684916909#comment-684916909
----
----
---- …

chore(api-v3): support changed conversation.access-update event AR-2743

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt

----
----
1. It's not possible to establish an MLS group, because if you don't add another client there's no commit created which can  be sent do the backend. That is if your client is the only members of a newly created group there's no need to commit this because the self client is a member from the beginning.
2. The other self clients were not added when establishing an MLS group.
1. If creating an empty MLS group update the key material afterwards and send that commit to the backend.
2. Include the self user when adding clients to a newly created group.
----
----
---- …

fix: not possible to establish MLS group with only self client AR-2748

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ImportClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ImportClientUseCaseTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/ClientRegistrationStorageImpl.kt

----
----
`PersistRegisteredClientUseCase` was deleted and it was use for Scala app migration
Introduce ImportClientUseCase which replaces the previously deleted `PersistRegisteredClientUseCase`.
----
----
----

fix: introduce ImportClientUseCase for importing an existing client

---

logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryExtensionsTest.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryExtensions.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/message/GetPaginatedFlowOfMessagesByConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt

----
----
When fetching a list of messages, we're only returning the `standalone` messages: The ones that can be visible.
However, I forgot to make it clear when doing #1171 
Specify the `Standalone` subtype.
> **Note**: What about renaming `Standalone` to `Displayable` or something like that?
> Any name suggestion is welcome.
Compiler does it ;) 
----
----

refactor: narrow down the subtype of Messages when querying locally

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Connections.sq
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConnectionDaoTest.kt

----
----
To reset the notification flag for conversations and connections, we can perform the update 1 single query.
It was implemented with nested loops instead of single query.
Performance!
Replaced with single query.
----
----
----
1. E.g. …

fix(notifications): set connections and conversations notif flag in single query (AR-2771)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/receipt/ReceiptRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/message/ReceiptMessageHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/receipt/ReceiptRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/ObserveMessageReceiptsUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/stub/ReceiptRepositoryStub.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandlerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ReceiptMessageHandlerTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/receipt/ReceiptDAO.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/receipt/ReceiptDAOTest.kt

----
----
We're not receiving read/delivery receipts.
Implement it.
Although the model was already there and we were able to read from storage, there was no protobuf parsing and insertion into the DB.
----
----

feat: receive receipts (AR-2678)

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Receipts.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/receipt/ReceiptDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/receipt/ReceiptDAOTest.kt

----
----
Crash when inserting some read receipts.
Other clients may send read receipts of messages unknown to us, as maybe they were batching and sending all at once, including messages that existed before we logged in on this new device.
`INSERT OR IGNORE` serves for checking when `PRIMARY KEY` or `UNIQUE` constraints fail, **it does not** ignore `FOREIGN KEY` constraints, which is this case.
A bit of a complicated insert with `WHERE EXISTS`.
Send messages from device A in a conversation.
Login with device B.
Read the messages from another account.
Device B should receive receipts from older messages unknown to it
----
----
1. E.g. …

fix: crash when inserting receipts of unknown messages

---

persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt

----
----
Some flaky tests were introduced recently and they're making a lot of PR checks fail.
Usage of `launch(UnconfinedTestDispatcher)` without waiting for the job to end, causing `UncompletedCoroutinesError`
Remove unnecessary `UnconfinedTestDispatcher`, add `join` to wait completion.
> **Note**: We should be able to upgrade `turbine` soon as we upgrade Kotlin, removing the need to use the `launch` completely.
----
----

test: fix flaky tests using UnconfinedTestDispatcher

---

logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/CallManagerTest.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/MLSClientProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/NeedsToRegisterClientUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ClearConversationContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendKnockUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/NeedsToRegisterClientUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ClearConversationContentUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendKnockUserCaseTest.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt

----
----
We use clientRepository to get the current clientId
Use clientProvider to get cached value
----
----
----

refactor: use clientIdProvider to get cached value

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/NotificationApiV0.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/authenticated/NotificationApiV3.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/notification/NotificationApiV0Test.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v3/notification/NotificationApiV3Test.kt

----
----
On API V0~V2, we get a Serialization Error when receiving a 404 on `/notifications`
V3 changed the response, so there aren't events anymore.
We addressed it by removing the failure override, that would retrieve the events even in case of failure.
The problem is that it was done for ALL versions.
And we end up trying to read `ErrorResponse` from a 404 in V0~V2.
Create a hardcoded 404 overwrite for Notifications on V0~V2.
On V3, don't override, just perform the request normally and handle the `ErrorResponse` if it comes.
----
----

fix: handle 404 notification errors in all API versions

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt

----
----
Existing MLS conversations doesn't show after login
Group state is not updated after re-joining them
Set group state to established after joining via external commit
----
----
----

fix: update group state after joining via external commit AR-2506

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq

----
----
Added filtering for our own messages in unread event's which also will remove `blink effect` when we will send message from another client
----
----
---- …

fix: filter own messages as unread [AR-2842]

---

.github/workflows/generate-dokka.yml
build.gradle.kts
buildSrc/src/main/kotlin/com/wire/kalium/plugins/CommonDokkaConfig.kt

----
----
1. Dokka is failing to generate
2. When running `./gradlew :module:dokkaHtml` to test out a single module, it doesn't include samples and the other settings present when running through `./gradlew dokkaHtmlMultiModule`.
1. I broke it in https://github.com/wireapp/kalium/pull/1243
2. `dokkaHtmlMultiModule` will invoke `DokkaTaskPartial` for the modules, when running `dokkaHtml` on a specific module, only a `DokkaTask` will be called, and these two types are are not directly related by inheritance.
1. Revert back to let Dokka solve the default output, and configure the publishing action to correctly solve it
2. Instead of configuring `DokkaTaskPartial`, configure all `AbstractDokkaLeafTask`, which both types of Dokka tasks inherit from. …

docs: tiny docs generation fix

---

gradle/libs.versions.toml

----
----
Trying to run Reloaded with libsodium bindings 0.8.7 causes a failure:
```
15:12:49.497  E  FATAL EXCEPTION: main
Process: com.wire.android.internal.debug, PID: 11628
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~NrqjSvO5heT_q7r5OLpPcw==/com.wire.android.internal.debug-_okmA3v6m3Ks0qZU6KQG3Q==/base.apk!/lib/x86/libavs.so"...
at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
at java.lang.System.loadLibrary(System.java:1664)
at com.waz.avs.AVSystem.load(AVSystem.java:29)
at com.waz.call.FlowManager.<clinit>(FlowManager.java:66)
at com.wire.kalium.logic.feature.call.FlowManagerServiceImpl.<init>(FlowManagerService …
```

chore: upgrade libsodium bindings to 0.8.6

---

buildSrc/src/main/kotlin/OnlyAffectedTestTask.kt
buildSrc/src/main/kotlin/ProjectExtensions.kt

----
----
The prev. PR #1262  tried to address the fact to detect changes on settings file, but there was an error, since the kotlin dsl processor was not working as expected, always returned error code.
Now this fixes and simplify the scripts command execution, also fixed a typo on `libs.versions.toml` file ref
----
----
----

fix: only run affected tests fix and simplify shell exec functions

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq

----
----
When a user is in busy mode, only mentions and replies must be notified!
Added another case that isn't necessary. 
Exclude OneOnOne conversations from the logic.
----
----
----

fix(notification): ignore OneOnOne conversations in busy mode

---

buildSrc/src/main/kotlin/ProjectExtensions.kt

----
----
Data read from `local.properties` may contain sensitive data, this data should not end in stdout.
Remove `$localValue` from the logging and only log if the property contained data.
The CI should still continue to work, but the log does no longer show the values of `github.package.*`
----
----
----

fix: do not print out potentially sensitive data

---

testservice/build.gradle.kts

----
----
The needed version of our dependency **dropwizard-swagger** for kalium-testservice is currently not downloadable because https://jitpack.io/com/github/smoketurner/dropwizard-swagger/72e8441e4a/dropwizard-swagger-72e8441e4a.pom produces an error.
We have to use jitpack in order to get a specific commit (72e8441e4a) because our security team asked for it. Unfortunately the project was a bit unmaintained and did not make a release with this commit yet. I asked in their bug tracker to make a release and they are on it.
In the meantime we downgrade to an older version available from mvn public repos.
----
----
----
1. E.g. …

fix: downgrade to older official release version b/c jitpack.io is unreachable

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MarkMessagesAsNotifiedUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MarkMessagesAsNotifiedUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageLatestTest.kt

----
----
When receiving messages with little interval between them, not all messages trigger a notification.
When we display a notification for a conversation, we call `markMessagesAsNotified(conversationId, DateTimeUtil.currentIsoDateTimeString())`.
What if the `currentIsoDate` is off by a few seconds in the future compared to the backend's clock? The messages that come from the server within this timespan in the next seconds will NOT trigger a notification.
Don't allow passing some arbitrary datetime, use the datetime of the last received message instead.
I've tried the following experiments:
If you advance the device's clock on purpose, so it is 1min in "the future" compared to the server's time. After a notification is received, you should …

fix: messages randomly not triggering notifications (AR-2867)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/message/MessageTextEditHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestMessage.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/MessageTextEditHandlerTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Reactions.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageTextEditTest.kt

----
----
1. When a message is edited, we should clear the current reactions it has. At the moment we’re not clearing it.
2. When a message with reactions is edited, further edits and reactions will not be handled. 
1. Was not implemented before.
2. The Reactions table will cause a Foreign Key Constraint Failure when we attempt to update the ID of a message during and `UPDATE`, and it was a silent error because we don't have this whole operation inside a transaction.
- Move the whole edit a text message to a single DB transaction
This had the bonus that we were exposing 3 DB operations just to edit a single text message, and these operations were not being used elsewhere (update ID and mark as edited). So these functions are now removed.
- Make …

fix: clear reactions when receiving message edits (AR-2881) (AR-2849)

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt

----
----
Asset content fields were not being updating properly, so they were treated as a normal message insert and hence being ignored. 
----

fix: Update all assets fields when updating

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq

----
----
Filter out selfMessages from notifications query.
There is an edge case that the self message appear on the notifications.
SelfMesssages must not be in the notifications.
Filter the isSelfMessages in the query.
Send a message somewhere you must not see your message in the notifications.
----
----
----

fix(notification): filter self message from notifications

---

persistence/src/commonMain/db_user/migrations/23.sqm
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/BaseMessageTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageTextEditTest.kt

----
----
When there are read/delivery receipts attached to a message, edits won't work.
Foreign Key constraint violation when we update the ID of the message.
Add `ON UPDATE CASCADE` to make sure the receipts continue pointing to the new message.
This is the expected behaviour according to [the docs](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/150933773/Use+case+Receive+and+store+read+receipts#Deleting).
----
----

fix: update receipts when editing a text message

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt

----
----
When edited message id was updated there was no update for quoted message id.
----
----
----

fix: update quoted message id after edit [AR-2844]

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq

----
----
Fixed filtering last message to show previous one when latest was deleted
----
----
----

fix: update last message after last message was deleted [AR-2833]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandlerTest.kt

----
----
Fixing add/leave member system message for MLS conversations.
After add/leave member happens and the system message shows in the MLS conversation, the next actions will not have the system message. This PR will fix that and it shows the system message for member changes always.
The system message for member-changes doesn't have event-id [or message id], the first message was surviving the insert into db because it's not against the primary key rules in the db. But the second message and after that, since they don't have the event-id as well, start to seeing duplicate messages error in the db [ the first one had no id as well!]
The system message for member change doesn't have event-id [ message id ] for proteus we were generating it …

fix(mls): show member join/leave system message [AR-2877]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/publicuser/search/SearchKnownUsersUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchKnownUserUseCaseTest.kt

----
----
- When user types a search query starting with '@' we search for the prefix into the handle table, but since we do not add it to the able we find no results.
Remove the prefix before passing it to search
----
----
----
1. E.g. …

fix: remove @ prefix from the search query when looking for known contacts

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/MuteCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UnMuteCallUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/MuteCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/UnMuteCallUseCaseTest.kt

----
----
Microphone is not set to muted when joining an ongoing group call.
The issue is not reproducible and it's rarely happening. My theory is the cached value is not available when joining the call leading the app to skip the muting action
Get value from database to check if there is an active call instead of cache
----
----
----
1. …

fix: join group call un-muted by default (AR-2870)

---

logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCallTest.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt

----
----
- Missed call notification displayed when we accept a call on a different client.
- Called system message displayed during a call
We were checking if the call is closed and is not answered in the current device
Now we are checking missed calls for 1:1 calls using a value returned in OnCloseCall callback
For group calls we still check if the call got answered or not since AVS did report missed calls for group calls
- Start a call from desktop to AR and different client
- Answer that call from the other client
- On AR you should not see missed call notification or "someone called" as a system message …

fix: missed calls notifications (AR-2825)

---

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationResponse.kt

Error while parsing the response for CreatingConversation Request.
`ConversationResponseV3` model had the wrong `SerialName` in 1 field 
fix that `SerialName`

fix: Conversation api response in v3 api

---

.github/workflows/codestyle.yml
.github/workflows/generate-dokka.yml
.github/workflows/gradle-android-tests.yml
.github/workflows/gradle-ios-tests.yml
.github/workflows/gradle-jvm-tests.yml
buildSrc/src/main/kotlin/OnlyAffectedTestTask.kt
gradle.properties

By upgrading the JDK version to 17, enabling the parallel GC and caching dependencies between builds.
----
----
Our CI is sloooooow.
- We do _not_ cache gradle dependencies between builds for all workflows.
- We're using JDK 11
- We're not using parallel garbage collector
The [setup-java](https://github.com/actions/setup-java#caching-packages-dependencies) action is able to cache dependencies between builds. And the cache is smart enough to consider the hash of all important gradle files, so if the hash changes, the cache won't be used.
We can easily enable it by adding `cache: 'gradle'` to all missing workflows.
We had issues in the past and disabled the cache, mostly because this smart hashing thing wasn't in place and we were using transient …

ci: speed up CI builds

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/server/StoreServerConfigUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/server/StoreServerConfigUseCaseTest.kt

----
----
app stuck at loading screen after migration
when reading the server config in staging from the old it can happen that the app adds "/await" to the end of the link path
clean the server config links when migrating
----
----
----
1. E.g. …

fix: app stuck at loading screen after migration

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt

----
----
asset messages content can be overwritten by id
after investigation, this has no impact on send/receive asset messages.
so i reverted the changes and ignored the insert when the message id matches
----
----
----
1. E.g. …

fix: asset messages content can be overwritten by id

---

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/AuthTokenStorage.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/client/AuthTokenStorageTest.kt

----
----
AuthTokenStorage is not covered by unit tests 
add unit tests and fix any issues found, the same tests are added to dev in https://github.com/wireapp/kalium/pull/1268
----
----
----

test: add unit tests to AuthTokenStorage

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/RestoreBackupUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/RestoreBackupUseCaseTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseImporter.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/RestoreBackupTest.kt

----
----
When we create a backup while being in a call, log out, clear data, log in and restore it, while the call is still ongoing, we end up alone in a call which can’t be hanged up, just continues forever.
When we clear data and log in again, the app has to register a new client so calls intended for a previous client won't work anymore.
Check if the backup we want to restore is from another client, if so then do not restore calls table because all calls there are not meant for the client that we currently try to do it on.
- https://github.com/wireapp/kalium/pull/1302
STR:
- be in an active call
- create a backup while being in the call without password
- logout of the app, clear data
- login again
- restore the backup
- …

fix(rc): ghost calls after restoring backup from other client [AR-2893]

---

calling/build.gradle.kts

----
----
- Current version does not support MLS
- Black frame issue on video calls (AR-2582)
Upgrade AVS to 9.0.2
- Make a video call 
- Put the app on background
- Return into forground from recent apps
--> You should see others video and not a black frame.
AVS 9.0.2 is not yet available on Maven-central due to some issues on CI/CD and that could take some time.
I just included the aar directly, and temporary until we have it ready on Maven Central, so we have the time to test before releasing.
----
----
----

chore: bump AVS version to 9.0.2

---

avs/build.gradle.kts
calling/build.gradle.kts

----
----
After upgrading AVS to 9.0.2 in #1308 using an aar file, instead of fetching it from Maven-Central(still not available there due some CI issues), our Android CI failed to run with this error
Still investigating ..
To unblock everyone, I am reverting it to use old version from Maven central
----
----
----
1. …

chore: revert compiling AVS from local aar

---

avs/build.gradle.kts
calling/build.gradle.kts

----
----
THIS A TEMPORARY SOLUTION UNTIL WE HAVE AN AVAILABLE VERSION ON MAVEN-CENTRAL
After [bumping AVS version to 9.0.2](https://github.com/wireapp/kalium/pull/1308) by adding the aar locally, our CI failed to build the android app :
```
Direct local .aar file dependencies are not supported when building an AAR. 
The resulting AAR would be broken because the classes and Android resources from any local .aar 
file dependencies would not be packaged in the resulting AAR. Previous versions of the Android 
Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The 
following direct local .aar file dependencies of the :library_module project caused this error: 
______.aar
```
We reverted in [chore: revert compiling …

chore: add AVS lib in a separate module (develop)

---

avs/build.gradle.kts
calling/build.gradle.kts

----
----
THIS A TEMPORARY SOLUTION UNTIL WE HAVE AN AVAILABLE VERSION ON MAVEN-CENTRAL
After [bumping AVS version to 9.0.2](https://github.com/wireapp/kalium/pull/1308) by adding the aar locally, our CI failed to build the android app :
```
Direct local .aar file dependencies are not supported when building an AAR. 
The resulting AAR would be broken because the classes and Android resources from any local .aar 
file dependencies would not be packaged in the resulting AAR. Previous versions of the Android 
Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The 
following direct local .aar file dependencies of the :library_module project caused this error: 
______.aar
```
We reverted in [chore: revert compiling …

chore: add AVS lib in a separate module

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateDisplayNameUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/UpdateDisplayNameUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt

----
----
Creates and enables a use case to update the self user, `"display name" eg. John Doe`.
Reuse the API implementation that we have for updating the user's avatar, but on the repo layer, we better separate for granularity.
WIP.
Later will be provided the AR counterpart, so you can test changing the user display name if you like to do so.
----
----
----

feat: change user display name (AR-1068)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq

----
----
One ques if you have lot of unread and not notified messages experience slowness and ANR in the app.
When we querying the not notified messages for the user, there is no size limit how many messages should be fetched.
Final and best Solution[not implemented here - blocked by sqldelight]
We can use window functions in sql to filter the messages based on conversations id in the query; but at the moment sqldelight has an issue with `OVER` and `PARTITION` keywords
See: https://github.com/cashapp/sqldelight/issues/2799
Solution in this PR:
Filtering the messages after fetching them from the db in the Repo.
----
----
----
1. E.g. …

fix(notification): limit notifications to 10 messages when fetching messages from repo

---

build.gradle.kts
gradle/libs.versions.toml

----
----
When attempting to write `darwin` code from a Windows or Linux machine, there's absolutely no IDE support.
The IDE says that "Kotlin is not configured" for such files, and says there're Unresolved References in every platform-specific code.
As Kotlin won't really build `darwin` on Linux and Windows machines, it doesn't bother downloading the platorm-specific dependencies.
Rely on [CompleteKotlin](https://github.com/LouisCAD/CompleteKotlin).
It pretty much downloads all platform-specific `klibs` that we might require.
Some interesting notes:
Nope. The plugin checks [the CI environment variable](https://github.com/LouisCAD/CompleteKotlin/blob/af2a6f6e01bf27acbaf5b7f4e234dfd0948c640e/plugin/src/main/kotlin/com/louiscad/complete_kotlin/Comp …

chore: add ide support for cross-platform development

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq

----
----
One ques if you have lot of unread and not notified messages experience slowness and ANR in the app.
When we querying the not notified messages for the user, there is no size limit how many messages should be fetched.
Final and best Solution[not implemented here - blocked by sqldelight]
We can use window functions in sql to filter the messages based on conversations id in the query; but at the moment sqldelight has an issue with `OVER` and `PARTITION` keywords
See: https://github.com/cashapp/sqldelight/issues/2799
Solution in this PR:
Filtering the messages after fetching them from the db in the Repo.
----
----
----
1. E.g. …

fix(notification): limit notifications to 10 messages when fetching messages from repo [DEV] 

---

detekt/baseline.xml
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/adapter/BotServiceAdapter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/adapter/ContentTypeAdapter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/adapter/ConversationAdapter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/adapter/LogoutReasonAdapter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/adapter/MemberRoleAdapter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/adapter/QualifiedIDAdapter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/TableMapper.kt
persistence/src/darwinMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt

----
----
Adapters are mixed up with DAOs in the Project view.
Move to their own dedicated package. Also, make them `internal` as it's not useful to make them `public`
Not Applicable
----
----

refactor: move column adapters to a dedicated package

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/AddSystemMessageToAllConversationsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandlerTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt

----
----
After the 404 error in sync, since the would happen if the user stays offline for long time, there is a chance of missing messages and losing history!
We need to inform the user about that by inserting a local system message for all conversations that indicates the history lost probability. 
----
----
----

feat(sync): insert history-lost systemMessage after 404 sync recovery (AR-2897)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MigratedMessage.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PersistMigratedMessagesUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/PersistMigratedMessagesUseCaseTest.kt

----
----
When we migration from the old scala app and have some assets from web to migrate, they are shown as empty in the new android app.
Sometimes there are two events with the same message id received: first with the metadata (name, size, etc.), second with remote data (key, etc.). Scala app stores the metadata in another table but replaces the whole proto in the Messages table, so when we migrate and take only the proto, we miss these data.
Take name and size from Assets table and include it in the migration message data.
Install scala app, send some assets and update to the AR.
----
----
---- …

fix: migrate asset names and sizes [AR-2939]

---

logic/src/commonJvmAndroid/kotlin/com.wire.kalium.logic/util/BackupUtils.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/BackupConstants.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/RestoreBackupUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/VerifyBackupUseCase.kt

----
----
Adds additional checks to back up importer feature, so we avoid certain undesired behavior like writing on directories we are not supposed to do so.
- Check and enforce only allowed file extensions
- When unzipping, check for patters that would lead to a write-in other directory level
----
----
----

fix(rc): path enhancement checks for import backup feature (AR-2976)

---

network/src/commonMain/kotlin/com/wire/kalium/network/KaliumHttpLogger.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt

----
----
We are logging on request the plain headers
Exposing undesired data to logs
Now logs looks like this on request:
```
REQUEST: {"method":"GET","endpoint":"prod-nginz-ssl.wire.com/awa***?client=eae***","headers":{"Content-Type":"application/json","Accept-Encoding":"gzip,identity","Authorization":"***","Accept":"application/json,message/mls,application/x-protobuf","Accept-Charset":"UTF-8","Upgrade":"websocket","Connection":"upgrade","Sec-WebSocket-Key":"***","Sec-WebSocket-Version":"***"}}
```
Apply obfuscation on request headers using our ["not-allowed" list](https://www.vice.com/en/article/v7dd3d/we-need-to-stop-saying-blacklist-and-whitelist)  =)
We should not see plain elements logged in REQUEST block, like Authorization, Cookie, etc. …

fix: cleaning logs from request headers (AR-2977)

---

logic/src/commonJvmAndroid/kotlin/com.wire.kalium.logic/util/BackupUtils.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/BackupConstants.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/RestoreBackupUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/VerifyBackupUseCase.kt

----
----
Adds additional checks to back up importer feature, so we avoid certain undesired behavior like writing on directories we are not supposed to do so.
- Check and enforce only allowed file extensions
- When unzipping, check for patterns that would lead to a write-in other directory level
NOTE: Pending adding unit tests
----
----
----

fix(dev): path enhancement checks for import backup feature (AR-2976)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt

----
----
We're emitting non-empty notifications unnecessarily.
Clients need to manually check if there's any notification.
Relodaded, for instance, is "marking as notified" without checking if there actually are notifications, causing an infinite loop of notification stream.
As it's a pain in the ass to write tests on Reloaded's `WireNotificationManager`, and as there are no purposes in emitting empty notifications, we might as well not do it from Kalium.
----
----

fix: emit only non empty notifications (RC)

---

network/src/commonMain/kotlin/com/wire/kalium/network/KaliumHttpLogger.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt

This reverts commit 30142ba41e208df6480e7e1ce751d88d107a6d91.
As part of the refactor of logging, this was also covered there, so I'm reverting this back

fix: Revert "fix: cleaning logs from request headers (AR-2977) (#1369)"

---

util/src/androidMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/commonMain/kotlin/com.wire.kalium.util/DateTimeUtil.kt
util/src/commonTest/kotlin/com/wire/kalium/util/DateTimeUtilBenchmark.kt
util/src/commonTest/kotlin/com/wire/kalium/util/DateTimeUtilTest.kt
util/src/jvmMain/kotlin/com/wire/kalium/util/PlatformDateTimeUtil.kt

----
----
Converting Instant to ISO 8601 string is not performant on Android at the moment.
Whilst I can't exactly pinpoint to the exact cause, I didn't observe the same under-performance on JVM. Maybe the way Android implemented this API is different from regular JVMs.
Replace the date/time format with a default `DateFormatterBuilder` with a `appendInstant(int fractionalDigits)`, passing `3` to make sure it always adds 3 digits to the milliseconds.
See the benchmark below.
Moved `DateUtilsTest` stuff to `utils` package.
I've added a benchmark for the future.
Running this benchmark, that transforms _one million_ random instants into ISO date time string:
- 9.215483600s
- 8.698548s
- 8.898969300s
- 8.793911400s
- 9.084778500s
- 855.682ms
- …

fix(android): improve performance of instant to ISO string

---

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt

----
----
Getting the conversation unread count and second line are super slow once the DB grows in size.
We need to further investigate the queries and see what's up.
For now, disable these features until we progressively re-enable them with simplified but performant solutions.
N/A Actually had to ignore some.
----
----

chore: disable slow features (RC)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCase.kt

----
----
Sending read receipt confirmation for messages are very slow.
Probably due to current performance issues and `STORAGE_ERROR` issue, although with upcoming improvements this issue won't be happening.
Disable for now until we find solutions.

fix: disable read receipts

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt

----
----
Port from the PR to `develop`:
- #1371 
----
----

fix: emit only non empty notifications (#1371)

---

android/src/main/AndroidManifest.xml
cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt
gradle/libs.versions.toml
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/SqliteCallback.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseImporter.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOBenchmarkTest.kt
persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt

----
----
Reloaded spends too much time locking/unlocking the Datbase.
In an app as complex as Reloaded, it's expected that we perform multiple read and write operations during long periods of time, especially when processing events.
However, the current SQLCipher build we're using is not great when it comes to optimise locks and unlocks, as explained [here](https://www.zetetic.net/blog/2022/05/11/sqlcipher-android-refresh/).
- Use the new SQLCipher "refresh"
- Enable [WAL Journal Mode](https://www.sqlite.org/wal.html) for the database.
- Pass `journal_mode=wal` to JVM's SQLite Driver.
> **Warning**: Small breaking change on Android. Some internal library has `allowBackup:true` and `supportsRtl:true` on their manifest, so we need to add …

chore: enable sqlite wal journaling (RC)

---

.github/workflows/codestyle.yml
.github/workflows/gradle-android-tests.yml
.github/workflows/gradle-ios-tests.yml
.github/workflows/gradle-jvm-tests.yml

----
----
Test run wether or not there are problems in with code style picked up by Detekt. This is wasteful since the we'll need to run the test again once Detekt succeeds. Runners are occupied for nothing. 
Change the test jobs to depends on the successful run of Detekt.
----

ci: run jobs only if detekt succeeds

---

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt

----
----
I've noticed some notifications showing up again after I dismiss them.
1. The `ConversationDAO` function `updateAllConversationsNotificationDate` is calling the `updateAllUnNotifiedConversationsNotificationsDate`; The DAO function doesn't do what it claims to do.
2. This function only updates if the modification date of the function is newer than the notification date.
3. We consider the `conversation.creationDate` as the value to update the modification date of a converstion. However, this is a value our local device clock can alter, so there's the possibility we mark as notified and our own client modifies the conversation to a `modifiedDate` that is smaller than the `notifiedDate`.
Make sure that …

fix: repeating notification (RC) (AR-2978)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageUnreadCounterTest.kt

----
----
The Unread Event counter was disabled due to performance issues in the PR:
- #1377 
Enable a simple counter that does not fetch ALL unread messages, but just the simplified count.
----
----

feat: enable simplified message counter (RC)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/GetProteusFingerprintUseCase.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/TestserviceApplication.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ClientResources.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/models/FingerprintResponse.kt

----
----
This PR implements a new endpoint (`/instance/{instanceid}/fingerprint`) on kalium testservice which returns the fingerprint of a device if it is using proteus encryption. This way the end to end tests of QA can check if the fingerprint shown in the UI actually match the fingerprint of the device. 
Tested by running the tests which used the same behavior with ETS.
----
----
----

feat: get fingerprint of client devices on testservice (SQPIT-1591)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/CreateBackupUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/CreateBackupUseCaseTest.kt
persistence/src/androidAndroidTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseExporter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseImporter.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/DatabaseImporterTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/UserDatabaseDataGenerator.kt
persistence/src/darwinTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/jsTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
persistence/src/jvmTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt

* fix: no more unreads on backup imports
* Added comment
* Update comment
* Added extra test on BackupRestoreTest class
* detekt
* WHERE true
* removed exclude unnecessary tables
* styling
* Encrypted db for tests too
* replace IIF with CASE WHEN
* Added missing END clauses
* Fixed tests with comments
* dump WAL content to main DB before migration
* fix test
Co-authored-by: Mojtaba Chenani <chenani@outlook.com>
Co-authored-by: Mohamad Jaara <mohamad.jaara@wire.com>
----
----
_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or …

fix: no more unreads on backup imports issue [AR-2983] (#1376)

---

persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/support/SqliteCallback.kt
persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/support/SupportOpenHelperFactory.kt

----
----
When performing a DB migration, the DB will _always_ be recreated when using the new SQLCipher.
The `minimumSupportedVersion` is being always set to the new DB version, so the DB is being recreated as "it's not supported".
- https://github.com/sqlcipher/sqlcipher-android/issues/11
I've opened [a PR on SQLCipher's repo](https://github.com/sqlcipher/sqlcipher-android/pull/12). But in the meanwhile, it's faster to do it ourselves here until a newer version is deployed.
Not sure if applicable, as the dependency is the one that needs fixing.
SQLCipher doesn't seem to have automated tests to assert that, so I did manual testing
Write a DB migration, like `26.sqm` with some simple `SELECT 'hello'`, start the app.
Current behaviour:
The DB …

fix: db being recreated when upgrading (RC)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt

----
----
Application was spammed by notifications during sync
When user was offline for a long time he will receive a lot of notification pop-ups during sync. 
Show notifications after sync complete or an error occurred
----
----
----
1. E.g. …

fix: notification pop-ups during sync [AR-2990]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt

…e handler
----
----
Wrap getNotificationsMessages query with WrapStorage.
----
----
----

chore(messages): wrap getNotificationsMessages query with wrapStorage

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt

----
----
When user tries to logout with clearing all data, application sometimes crashes. 
The reason about it was that updating firebase token flag in past was moved from SharedPreferences to SqlDelight DB. When user do the hard logout we don't need to clear token flag, because db is already cleared.
After opening app user has empty conversation list and he can't do nothing before clearing app data.
Update firebase token flag only when we do not do hard logout.
1. Logout with clearing data when you are receiving messages
2. Logs should not contain any errors for MetadataDAO queries

fix: clear firebase token only on soft logout [AR-3012]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt

* chore(messages): wrap getNotificationsMessages query with wrap storage handler
----
----
Wrap getNotificationsMessages query with WrapStorage.
----
----
----

chore(messages): wrap getNotificationsMessages query with wrapStorage [DEV]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/MLSClientProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClearClientDataUseCase.kt

----
----
Logout is performed on main thread :
- when clearing Proteus files
- when getting MLS client
Switch dispatcher to use IO
----
----
----

fix: Logout is running on main thread

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/util/CommonUtils.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/util/CommonUtilsTest.kt

----
----
Copy of already approved one for `develop`: https://github.com/wireapp/kalium/pull/1410
We don't have any unified way of building names, especially when we need to create unique name containing a copy counter (`filename (2).jpg)`) if the file already exists and then split such names into parts: core name, copy counter and extension. We take all parts after the first dot as extension, but most authors actually define extension in a way that doesn't allow more than one in the same file name. 
- add `buildFileName` method that can generate unified file names
- add `splitFileExtension` and `splitFileExtensionAndCopyCounter` to split the given file name into two (core name with optional copy counter and extension) or three (core name, copy …

fix(rc): file extensions, splitting and building file names and duplicates [AR-2985] [AR-2984]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAOImpl.kt

----
----
[AR-3029 - App Crashing when receiving OnClose call from AVS when there is no call in db](https://wearezeta.atlassian.net/browse/AR-3029)
From a fresh install build that doesn't have any (or at least the expected Call) saved in the database, when receiving a `OnCloseCall` signal from AVS it would trigger to save a `MissedCall` system message, but it requires a `CallerId` which it doesn't have and thus its crashing.
- Update DB to return `executeAsOneOrNull`, in case it returns null the `MissedCall` system message won't be saved as the user did not have any info about that call anyway.
- In case it returns a correct `CallerId` (from a Call that exists in DB) it will persist the message as normal.
- Fresh install
- Receive a …

fix: OnClose call crashing

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAOImpl.kt

----
----
[AR-3029 - App Crashing when receiving OnClose call from AVS when there is no call in db](https://wearezeta.atlassian.net/browse/AR-3029)
From a fresh install build that doesn't have any (or at least the expected Call) saved in the database, when receiving a `OnCloseCall` signal from AVS it would trigger to save a `MissedCall` system message, but it requires a `CallerId` which it doesn't have and thus its crashing.
- Update DB to return `executeAsOneOrNull`, in case it returns null the `MissedCall` system message won't be saved as the user did not have any info about that call anyway.
- In case it returns a correct `CallerId` (from a Call that exists in DB) it will persist the message as normal.
- Fresh install
- Receive a …

fix: (DEV) OnClose call crashing

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MarkMessagesAsNotifiedUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MarkMessagesAsNotifiedUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Notification.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageNotificationsTest.kt

Some notifications repeat sometimes
in getting notification DB query we were using the wrong date for filtering (`last_modified_date` while should be `last_notified_date`). This causes wrong behaviour when the same notification was propagated again. 
Fix the query and add tests to cover that case.
+ removed some deprecated code.

fix: [RC] Notification issues (AR-3016)

---

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ClientResources.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt

----
----
Unfortunately the testservice broke after PR #1428 
Kotlin changes the function signature when functions are marked suspend. The injection framework in Dropwizard was not able to find the functions for the endpoints anymore when it was started (compilation worked) and threw an error.
Removed `suspend` from endpoint functions and used runBlocking blocks to be able to use the kalium library. The good part about this was that i could remove the runBlocking blocks from inside the scopes.
----
----
----

fix: Broken injection source in testservice after functions marked suspend

---

testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt

----
----
The /getMessages endpoint is used in tests that delete messages. The test failed because they deleted the wrong messages.
The order of messages on the endpoint was different in ETS
Our goal is to reach feature parity of testservice and ETS. So the testservice will also deliver messages on /getMessages endpoint in order of newest first to oldest.
----
----
----

fix: Reverse message order in testservice like in ETS (SQPIT-1605)

---

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ClientResources.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt
testservice/src/main/kotlin/com/wire/kalium/testservice/models/AvailabilityRequest.kt

----
----
This PR implements the endpoint /availability for testservice. Unfortunately the broadcast functionality is not implemented in kalium itself so this endpoint will not have any effect yet. But once it is implemented it should directly work.
----
----
----

feat: testservice can change availability status (SQPIT-1609)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncCriteriaProvider.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/logout/LogoutRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt

https://wearezeta.atlassian.net/browse/AR-2989
----
----
Update logout state in LogoutRepository to not receive previous logout state after re-login
Fixed crash after hard logout
After receiving `Removed Client` event user cannot sync after logging again.
After hard logout there was a crash
User cannot use app after login again.
For hard logout don't clear metadata because db was already cleared
For device removal reset logout state to be able login again in the same app session

fix: logout state after removed device [AR-2989]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClearClientDataUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/logout/LogoutRepositoryTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Metadata.sq
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/ClientRegistrationStorageImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/MetadataDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/MetadataDAOImpl.kt

----
----
sync fails with 404 after removing client
some metadata values are not cleared
clear client related metadata values
----
----
----

fix: metadata table is not cleared when client get deleted

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/logout/LogoutRepositoryTest.kt

----
----
HradLogout -> login again -> user will be surprised with a popup that the client has been removed
sync still holds a reference to the old DB  object,  including its cache
fix the cause
----
----
---- …

fix: client removed after hard logout

---

calling/src/commonJvmAndroid/kotlin/com.wire.kalium.calling/callbacks/SendHandler.kt
logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/CallManagerTest.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnHttpRequest.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSendOTR.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/darwinMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/scenario/OnHttpRequestTest.kt
logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/scenario/OnSendOTRTest.kt
protobuf-codegen/src/main/proto/messages.proto

----
----
AVS sometimes targets only your own self clients when sending calling messages like `REJECT` which tells your other devices that you've rejected a call and should stop ringing.
This is not possible with MLS so instead we add support routing calling messages via the self conversation to reach your self clients.
- Update `Calling` protobuf message to include a "target" conversation.
- Route calling messages via self conversation when AVS sets `onlyToMyClients` to `true`.
- Handle receiving a calling message received in the self conversation.
Test code has some code duplication, would need to refactor OnHttpRequest …

feat(calling): support routing calling messages via self conversation AR-2761

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreator.kt

----
----
4 meter tall log walls being added every time a message is encrypted, especially for big groups.
I added this log message for debugging purposes and data validation while developing the External Messages feature and it slipped through.
Remove it!
N/A
----
----

chore: remove message size estimation logging

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageUnpacker.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageUnpackerTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/EventContentDTO.kt
network/src/commonTest/kotlin/com/wire/kalium/model/NotificationEventsResponseJson.kt

----
----
Support receiving MLS messages in a sub-conversation.
`messageFromMLSMessage()` was duplicated in `MLSConversationRepository.kt` and `MLSMessageUnpacker.kt`. It now only lives in `MLSMessageUnpacker.kt`.
----
----
----

feat: support receiving MLS messages in a sub-conversation

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt

----
----
logout is canceled when triggered from sync aka client deleted
start logout from the app global scope so it is not canceled
----
----
----

refactor: start logout from an app global scope

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/MarkFileSharingChangeAsNotifiedUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/config/UserConfigStorageTest.kt

----
----
Receiving a file sharing status update event, the dialog is keep repeating
only the UI state is updated when dismissing the dialog and the local flag is still true for is changed which means the next app launch will display the dialog again
update the the state locally
----
----
----
1. …

fix: [DEV] file sharing changed dialog keep repeating (#1464)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/notification/LocalNotification.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/notification/LocalNotificationMessageMapper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
persistence/src/commonMain/db_user/com/wire/kalium/persistence/Notification.sq
persistence/src/commonMain/db_user/migrations/26.sqm
persistence/src/commonMain/db_user/migrations/27.sqm
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt

----
----
Querying from MessagePreview can be slow
1. reduce complexity by add a new column is_quoting_self by to the MessageTextContent
2. get notification its query instead of using MessagePreview.
----
----
----
1. E.g. `feat(conversation-list): …

fix: [DEV] optimise notification query [#1432]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationOptions.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/AcceptConnectionRequestUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/message/LastReadContentHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/CreateGroupConversationUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandlerTest.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageNotificationsTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageUnreadCounterTest.kt

----
----
leftovers form refactoring iso date string to Instant
----
----
----
1. …

refactor: remove redundant date mapping

---

cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/exceptions/ProteusException.kt
cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/DeleteAssetUseCaseImpl.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/NotificationApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/NotificationApiV0.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/NetworkUtils.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/notification/NotificationApiV0Test.kt
network/src/commonTest/kotlin/com/wire/kalium/model/NotificationEventsResponseJson.kt

----
----
When lastNotification response fails in listenToLiveEvents then user can not receive any websocket events 
User will not receive any notifications until he will kill the app
Check if lastNotification fails and propagate error instead of start listening to websocket when token might by expired.
----
----
---- …

fix: return failure when web socket failed to connect [AR-3073]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt

----
----
[AR-3136 - App crashing in Conversation Mapper](https://wearezeta.atlassian.net/browse/AR-3136)
When a connection request was accepted from another client, current client did not create a Member, thus not having the not-created member in the conversation.
When receiving a notification and clicking it, when opening the Conversation Screen we would try to get info from an user that was not a Member in our DB, thus failing and crashing the app.
Add User from accepted connection request in another client to current Member table.
== TO REPRODUCE THE CRASH IN AN EARLIER BUILD ==
**Devices**: 2x AR (device1 and device2) | 1x Web
**Note**: Both AR is logged in with same user
**Flow**:
- AR(device1) sits on Conversation List or whatever (just …

fix: (RC) conversation mapper crash (AR-3136)

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/sync/WorkSchedulerImpl.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/sync/WrapperWorker.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendingScheduler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/DoesValidSessionExistUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/session/DoesValidSessionExistUseCaseTest.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/sync/WorkSchedulerImpl.kt

----
----
There is an `IllegalStateException` crash at random moments that happens multiple times for some users.
The app tries to fetch the server config for the session that doesn't exist anymore.
It's happens when `PendingMessageSenderWorker` is scheduled because the user tried to send a message and it failed for some reason. If the user logs out before this worker is executed successfully, then every time the app will try to create and run it, there will be this crash, and there's no way of stopping it because if there's a crash, the worker is rescheduled again and it tries to create it again after some time.
Cancel scheduled worker when logging out and if it's still being created, check if the session for which this worker was started still …

fix(rc): crash loop when trying to create PendingMessageSenderWorker [AR-3041]

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserverImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserver.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserverImpl.kt

----
----
We receive `android.net.ConnectivityManager$TooManyRequestsException`, because `registerDefaultNetworkCallback` has a limit of 100 registered callbacks per app and for some reason our app exceeds that limit.
The app doesn't call `unregisterNetworkCallback`. 
I checked multiple scenarios to find possible explanations and the issue probably is that `callbackFlow` which is suggested way of registering such callbacks, doesn't work well when used with `.first()` or `withTimeout { }`. Basically it won't unregister if the flow closes before the execution comes to the `awaitClose` line, so the flow doesn't even know that it has something to unregister.
Here are two examples:
In this case it didn't unregister because timeout happened and flow …

fix(rc): ConnectivityManager$TooManyRequestsException [AR-3134]

---

.github/workflows/gradle-android-tests.yml
network/src/commonMain/kotlin/com/wire/kalium/network/BackendMetaDataUtil.kt

----
----
Builds are stalling waiting for the emulator to boot
ADV cache step seems to be the culprit 🤷‍♂️
Remove the ADV cache steps
----
----

ci: re-enable buildjet

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ProteusMessageUnpacker.kt

----
----
Decryption error logs from Cryptobox and CoreCrypto have different formatting.
We are logging the stack trace of the underlaying cause which is implementation specific.
Log the name of the ProteusException.Code which is a mapping of the underlaying error into a common error.
----
----
----

chore: log error code instead of stacktrace on proteus errors

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/SendMessagePartialFailureMapper.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/SendMessagePartialFailureMapperTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/RecipientDeliveryFailureMapperTest.kt

----
----
This is the second part of the work for handling the sent message response with a partial success adding the code coverage for the changes made on part 1, See: #1525 
Added some small refactors to simplify and tests better the mappers
Previous related work (already merged)
#1493 
#1466 
----
----
----

feat: federation msg failed to send handling - part 2: test coverage (AR-3015) 

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt

----
----
We insert false positive decryption errors
Backend currently forwards the sender own messages and we cause an error when an attempt is made to decrypt them.
Don't insert decryption system messages until we have way to ignore our own messages and/or backends stops forwarding them.
----
----
----

fix: don't insert system message on MLS decryption errors AR-3092

---

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt
cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt
cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMappers.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreator.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreatorTest.kt

----
----
When we use CoreCrypto proteus we can improve encryption performance by using the batch  API. For the case when we are not using CoreCrypto we provide a polyfill for the batch API.
The performance gain is mostly about avoiding passing the FFI boundary for every single message we encrypt.
----
----
----

feat: improve encryption performance by using batch API

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/BackupConstants.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/CreateBackupUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/RestoreBackupUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/CreateBackupUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/RestoreBackupUseCaseTest.kt
util/src/androidMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/commonMain/kotlin/com.wire.kalium.util/DateTimeUtil.kt
util/src/darwinMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/jsMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/jvmMain/kotlin/com/wire/kalium/util/PlatformDateTimeUtil.kt

----
----
Backup created zip files have a not so specific file name so we want to give it a more descriptive one, with the user handle and the creation timestamp.
In order to achieve that, we had to add an extra kmp method on the `PlatformDateTimeUtil` class formatting the current timestamp with only seconds precision, as the previous one was using milliseconds precision.
----
----
----

fix: add more descriptive backup name [AR-2260]

---

cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/exceptions/ProteusException.kt

----
----
Proteus error code 205 was mapped twice
Map `102` to SESSION_NOT_FOUND
----
----
----

fix: error code 205 was mapped twice

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetOtherUserSecurityClassificationLabelUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveSecurityClassificationLabelUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOtherUserSecurityClassificationLabelUseCaseTest.kt

----
----
We need to implement security classification banner for other user profile screen.
Creates a use case that returns the security classification label for a given user id.
----
----
----

feat: other user id classified security banner use case (AR-2702)

---

util/src/androidMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/commonMain/kotlin/com.wire.kalium.util/DateTimeUtil.kt
util/src/commonTest/kotlin/com/wire/kalium/util/DateTimeUtilTest.kt

----
----
There's an error on Android 7 seen on the Play Store about parsing Instant.
Couldn't reproduce on any Android 7 device so it's probably related to some specific devices or weird date time values.
One thing noticed is that the formatter used on older Androids was using a format with `XXX` at the end instead of just `Z`, which means that it could append the timezone values at the end of the date time string (e.g. "2023-03-01T01:02:03.456+01:00"). The problem is that kotlin `Instant.parse` can handle time zones in some forms, like "+01:00" or "+01" but `XXX` also allows to use "+0100". 
Use format with `Z` as we use ISO 8601 date times with UTC time and don't allow different timezones.
----
----
----
1. …

fix(rc): datetime parsing error [AR-3189]

---

util/src/androidMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/commonMain/kotlin/com.wire.kalium.util/DateTimeUtil.kt
util/src/commonTest/kotlin/com/wire/kalium/util/DateTimeUtilTest.kt
util/src/darwinMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/jsMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt
util/src/jvmMain/kotlin/com/wire/kalium/util/PlatformDateTimeUtil.kt

----
----
There's an error on Android 7 seen on the Play Store about parsing Instant.
Couldn't reproduce on any Android 7 device so it's probably related to some specific devices or weird date time values.
One thing noticed is that the formatter used on older Androids was using a format with `XXX` at the end instead of just `Z`, which means that it could append the timezone values at the end of the date time string (e.g. "2023-03-01T01:02:03.456+01:00"). The problem is that kotlin `Instant.parse` can handle time zones in some forms, like "+01:00" or "+01" but `XXX` also allows to use "+0100". 
Use format with `Z` as we use ISO 8601 date times with UTC time and don't allow different timezones.
By the way, I have also unified other functions and …

fix(dev): datetime parsing error [AR-3189]

---

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/CommitBundleEventReceiver.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedId.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserModel.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ObserveMessageReceiptsUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendConfirmationUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ReceiptModeUpdateEventHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/RenamedConversationEventHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt
network/src/commonMain/kotlin/com/wire/kalium/network/KaliumHttpLogger.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/EventContentDTO.kt
network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt
util/build.gradle.kts
util/src/commonMain/kotlin/com.wire.kalium.util/serialization/SerializationUtils.kt

----
----
`toString()` is abused to sometimes be an actual string representation, and sometimes to be a more complex representation for logging. Before disaster strikes and one is used in place of another, we should avoid confusion.
leave `toString()` alone and use `toLogString()` when logging
----
----

chore: improve logging

---

cli/src/jvmMain/kotlin/com/wire/kalium/cli/commands/ConsoleCommand.kt
cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/StartCallUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/StartCallUseCaseTest.kt
logic/src/darwinMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt

----
----
We need to provide the `convType` in several places now so it's much easier if we would do that look up internally and safer. It doesn't make sense to attempt to make a `conferenceMls` call in a proteus conversation.
----
----
----

refactor: look up avs convType interally

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/AssetContent.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/asset/AssetMessageHandler.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandlerTest.kt
logic/src/jvmTest/kotlin/com/wire/kalium/logic/sync/receiver/asset/AssetMessageHandlerTest.kt

----
----
We recently introduced some bug when refactoring the way we handle asset messages. This caused other AR clients not to display generic asset messages sent from an AR client.
Change the implementation of `shouldBeDisplayed()` to not rule out assets that have no metadata information.
Send a generic asset message from different clients, Android and/or web, and check that they are displayed correctly in AR. 
Unit tests will be coming soon too.
----
----
----

fix: fixed bug not showing correctly generic assets on other clients [AR-3187]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/test_util/TestNetworkException.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unauthenticated/LoginApi.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/unauthenticated/LoginApiV0.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt
network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/NetworkErrorLabel.kt

----
----
`login` endpoint now returns two new error messages, as seen in the [tech spec](https://wearezeta.atlassian.net/wiki/spaces/SER/pages/557580675/Tech+spec+BSI+-+1.8+Improve+User+Authentication#Additional-failure-responses):
* `403 code-authentication-required`
* `403 code-authentication-failed`
Handle these failures, making sure they're reflected on the UseCase, so the UI can figure out what to do.
I kept the `InvalidCredentials` class, but add children to it so the UI can figure out what to do.
Most of this PR changes are refactoring the `LoginUseCaseTest` so it now has a `Arrangement` to simplify stuff. Otherwise this PR wouldn't be so big.
----
----
1. …

feat: handle 2fa failures on login (AR-3088)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/util/ExponentialDurationHelper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt

----
----
Right now, after every failed incremental sync attempt, the exponential value that's used to retry is increased, but it's not reset after a success, so after some failures it can unnecessarily delay the sync for longer that it should.
Reset the value after a successful incremental sync.

fix(rc): reset exponential value after successful incremental sync

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/util/ExponentialDurationHelper.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt

----
----
Right now, after every failed incremental sync attempt, the exponential value that's used to retry is increased, but it's not reset after a success, so after some failures it can unnecessarily delay the sync for longer that it should.
Reset the value after a successful incremental sync.

fix(dev): reset exponential value after successful incremental sync

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/verification/SecondFactorVerificationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/verification/VerifiableAction.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/verification/RequestSecondFactorVerificationCodeUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/auth/verification/SecondFactorVerificationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/verification/RequestSecondFactorVerificationCodeUseCaseTest.kt

----
----
When failing to login or register client due to lack of 2FA code, we need to be able to request a new code to be sent via email
Add a simple Repository/UseCase pair to expose this API call to the clients.
----
----

feat: request second factor authentication code (AR-3088)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/IdProviders.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/BackupScope.kt

Move backup-specific stuff to its own scope, making the current one @Deprecated. Also, remove some message-sending instances
----
----
`UserSessionScope` is bloated with stuff. We need to start reducing and scoping things to make it more maintainable.
It's so long and confusing, in fact, that it's hard to use.
It has become a jack-of-all-trades, and a place where UseCases without groups go to meet other random misfits.
`userScope.restoreBackup` and `userScope.observeSyncState` can be in the same instance, for example.
It's also error prone, as seen in this PR, there's unused code in there that went unnoticed.
- Remove the unused code
- Move Backup-related UseCases to a `BackupScope`.
- Move the `IdProviders` to their own file.
This currently …

refactor: clean up UserSessionScope

---

logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCallTest.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnActiveSpeakers.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnAnsweredCall.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnEstablishedCall.kt
logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallMetadataProfile.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/MuteCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/RejectCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UnMuteCallUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UpdateVideoStateUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/EndCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/MuteCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/RejectCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/UnMuteCallUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/UpdateVideoStateUseCaseTest.kt

----
----
We are inconsistently passing conversationId:s as string and sometimes as `ConverationId`, which forces us to map back and forth everywhere.
- Map to `ConversationId` immediately after receiving a conversation ID string from AVS.
- Always use `ConversationId`
----
----
----

refactor: clean up conversation ID mapping for calls

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationAccessRoleUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationAccessUseCaseTest.kt

----
----
When creating or editing guest access, accessRole and access aren't always correct
- Refactor the code to have default values for accessRole and access
- Extract logic into 2 functions `accessRoleFor` and `accessFor`
- Don't hardcode Wire's logic into the SDK, let the caller decide
----
----
----

fix: create group guest link AR-3188

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt

----
----
Support joining MLS conversations via link/code.
See https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/30474648/Use+case+Join+a+conversation+with+a+guest+room+link+cloud#Step-4%3A-Join-MLS-group
----
----
----

feat: join MLS conversations via link/code

---

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/verification/SecondFactorVerificationRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/SessionManagerExt.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/auth/verification/FakeSecondFactorVerificationRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/auth/verification/SecondFactorVerificationRepositoryTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCaseTest.kt
logic/src/darwinMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/darwinMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt

----
----
When logging in, the user might need to input a 2FA code, and this 2FA code should be re-used when registering the client.
Add a in-memory storage of 2FA code using emails as keys.
The storage is unique per authentication scope, meaning that Kalium will hold a storage per backend.
When successfully logging in: persist the 2FA code in the storage.
When registering the client, check for existing 2FA code if there's no input from client.
In case of invalid 2FA code (user mistyped, or 2FA code is too old) clear whatever is in the storage and return the failure so the client can tell the user that a new 2FA code is being sent to their email address.
> **Note**: The more I look into `UserSessionScope`, `AuthenticationScope`, etc. the more I …

feat: automatically reuse 2fa codes when registering client (AR-3088)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt

----
----
Added config flags `wipeOnCookieInvalid` and `wipeOnDeviceRemoval` to control if after logout by reason `DELETED_ACCOUNT`, `REMOVED_CLIENT` or `SESSION_EXPIRED` should wipe all user data
Documentation links:
- https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/157321371/Use+case+delete+local+data+if+the+cookie+is+invalid
- https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/763166985/Use+case+delete+local+data+when+noticing+that+the+account+or+client+get+deleted
_Attachments like images, videos, etc. …

feat: Wipe data when wipe on device removal or cookie invalid [AR-3140]

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/IncrementalSyncRepository.kt
logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ObserveSyncStateUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/IncrementalSyncRepositoryTest.kt

----
----
If `incrementalSyncState` has a slow collector, after it being updated some times, it can cause the emitter suspended indefinitely.
`incrementalSyncState` has a limited buffer size of 64, and once it is full it will suspend the emitters and wait for collectors to catch up.
On Reloaded, there was a bug making this happen very early:
- https://github.com/wireapp/wire-android-reloaded/pull/1544
To make sure small bugs on the client-side cause the whole Sync mechanism to freeze, adopt a different Buffer Overflow policy for this flow: drop the oldest values.
Add documentation describing this behaviour.
----
----
1. E.g. …

fix: protect sync from freezing due to overflown buffer (AR-3167) (AR-3181)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt
network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/unauthenticated/LoginApiV0.kt
network/src/commonTest/kotlin/com/wire/kalium/api/v0/user/login/LoginApiV0Test.kt
network/src/commonTest/kotlin/com/wire/kalium/model/LoginWithEmailRequestJson.kt

----
----
No `verification-code` is actually being added to the serialised request body.
Oversight during the first PR + I really thought we had tests for this serialisation 😅 
Correctly pass the arguments and add tests to make sure it doesn't break.
> **Note**: Also made a small refactoring to the `LoginUseCase` that removes the unnecessary mutability for `isEmail`.
----
----

fix: missing 2fa code on login (AR-3088)

---

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt

----
----
After creating `UserSessionScope` for the first time, there is no information about `SelfUser` and it's easy to make mistakes and assume that user data is known when `observeSelfUser` is available.
This is extremely annoying as `observeSelfUser` has a `filterNotNull()`, which makes Kalium hang forever.
Add an automatic retrieval of self user:
If self user is unknown, fetch it from remote and insert locally.
----
----

chore: automatically fetch self user if null
