wireapp/kalium

.github/workflows/codestyle.yml, .github/workflows/generate-dokka.yml, .github/workflows/gradle-android-tests.yml, .github/workflows/gradle-ios-tests.yml
----
----
CI takes some minutes to run the `Setup JDK` step as it downloads a JDK on every run, and sometimes gets stuck in the process, needing a rebuild.
Use JDK 17 Temurin as it's [bundled with the runners](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java).
Running this PR checks should do the trick.
----
----
=> ci: use JDK 17 Temurin as it's bundled in CI machines

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/login/LoginRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/auth/login/LoginRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unauthenticated/LoginApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/unauthenticated/LoginApiV0.kt
----
----
Users are failing to login using their handles
Kalium sends `verification-code` even when logging in with handles, which is not supported.
Completely on me, as one of the first things I implemented was the serialisation and at that stage I didn't know it was only when logging in using email.
Completely remove the possibility to pass verification code when logging in using handle.
N/A: We removed the possibility to serialize it. It's impossible to pass a value. Won't compile.
----
----
=> fix: do not send 2fa code for login using username (AR-3232)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetOtherUserSecurityClassificationLabelUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveSecurityClassificationLabelUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOtherUserSecurityClassificationLabelUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveSecurityClassificationLabelUseCaseTest.kt
----
----
The logic for classifications labels needed to be adjusted to not trust by default the own domain. 
More context of this on: https://wearezeta.atlassian.net/wiki/spaces/~444846844/pages/770441447/2023-03-15+Playtest+result+classified+conversations+behavior
Adjust the logic to consider the list of trusted domains only for computing the label.
----
----
----
=> chore(rc): adjustment to not trust by default same domain (AR-3215)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryTest.kt
----
----
When removing a device remotely, we were not deleting locally from the storage
Observing to the list of local devices, was not consistent
When successfully removed a device, also delete it locally.
----
----
----
=> fix(dev): remove devices remotely also delete locally (AR-3250)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/type/UserType.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveUserInfoUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
In federated environments data for users is not refreshed
We are not getting updates for names, and in case a backend is down, that info is never refreshed.
When requesting the stored user info —only in case of a federated user— we fetch and store the data. 
This also adds an in-memory cache to avoid excessive requests.
----
----
----
=> fix(rc): federated user data is not refreshed (AR-3249)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/type/UserType.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveUserInfoUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
COPY of https://github.com/wireapp/kalium/pull/1609
In federated environments, data for users is not refreshed
We are not getting updates for names, and in case a backend is down, that info is never refreshed.
When requesting the stored user info —only in case of a federated user— we fetch and store the data. 
This also adds an in-memory cache to avoid excessive requests.
----
----
----
=> fix(dev): federated user data is not refreshed (AR-3249)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/db_user/migrations/32.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
----
----
Quoted messages are ignored if they are not in user db.
Quoted messages are showed as normal text messages.
Pass quoted messages if they contain at least quotedMessageId to show that it's a reply with unknown quoted message
=> fix: pass quoted message id even if it's not in db [AR-3238]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
----
----
In the logs for event handling there is not outcome reported in the json representation
Add "outcome" to the json representation
----
----
=> chore: add outcome to event logging

logic/src/androidMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserverImpl.kt
----
----
`onBlockedStatusChanged` was sending false positive state `NetworkState.ConnectedWithInternet` when user may not have internet connection yet. We should only depend on `onCapabilitiesChanged`
Sometimes after turning on internet user is stuck on connecting
Remove `onBlockedStatusChanged` to only depend on  `onCapabilitiesChanged`
=> fix: stuck on connecting because of onBlockedStatusChanged [AR-3269]

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AddAuthenticatedUserUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/autoVersioningAuth/AutoVersionAuthScopeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/GetSSOLoginSessionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOFinalizeLoginUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOInitiateLoginUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOMetaDataUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOSettingsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/FetchSelfClientsFromRemoteUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ObserveClientDetailsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/publicuser/search/SearchUsersResult.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/server/FetchApiVersionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/server/GetServerConfigUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/server/ObserveServerConfigUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/server/StoreServerConfigUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/SessionResult.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/DeleteTeamConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/webSocketStatus/ObservePersistentWebSocketConnectionStatusUseCase.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt
----
----
The log of some failures are unclear and kinda hard to understand, as they don't provide meaningful info when converted to string.
With things like this showing up:
```
"errorInfo" : "ServerMiscommunication(cause = KaliumException.GenericError@dbf12c)"
```
Especially bad when we have minified code on releases:
```
"errorInfo" : "ServerMiscommunication(cause = co.c$c)"
```
WTF is `co.c$c`, we need the mapping file to figure out.
When converting a regular class to String, and the `toString()` is not overridden, the `[className]@[memoryAddress]` will be used, which doesn't provide enough info.
Again, even worse on minified builds, as the `className` will be replaced with shenanigans.
Convert the generic failure classes into Data classes, …
=> chore: improve generic failure logging

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCase.kt
----
----
[AR-3169 - Read receipts -> It takes some time to send read receipt when we open a conversation](https://wearezeta.atlassian.net/browse/AR-3169)
Sending Read receipts confirmation were being cancelled.
Due to opening and closing a conversation very fast (with unread messages) it would cancel the scope (due to destroying the View and VM) and leading to Job Cancellation exception.
Add usage of User session scope instead of View/VM scope so even if the user closes the conversation screen, the process of read receipts confirmation is properly sent (as the user saw the messages).
- Run this branch on AR
- have a conversation with some unread messages
- open and close the conversation very fast
- job cancellation exceptions should not be …
=> fix: [RC] read receipts cancellation (AR-3169)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCase.kt
----
----
[AR-3169 - Read receipts -> It takes some time to send read receipt when we open a conversation](https://wearezeta.atlassian.net/browse/AR-3169)
Sending Read receipts confirmation were being cancelled.
Due to opening and closing a conversation very fast (with unread messages) it would cancel the scope (due to destroying the View and VM) and leading to Job Cancellation exception.
Add usage of User session scope instead of View/VM scope so even if the user closes the conversation screen, the process of read receipts confirmation is properly sent (as the user saw the messages).
- Run this branch on AR
- have a conversation with some unread messages
- open and close the conversation very fast
- job cancellation exceptions should not be …
=> fix: [DEV] read receipts cancellation (AR-3169)

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unbound/configuration/ServerConfigApi.kt
----
----
custom server deep links for testing are not working because of incorrect content type
accept Text/Plain content type
----
----
----
=> fix: [DEV] accept Text/Plain content type for custom server config

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyListMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/UsersWithoutSessions.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientFingerprintUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SessionEstablisher.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ClientFingerprintUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SessionEstablisherTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/prekey/PreKeyApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/PreKeyApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/PreKeyApiV4.kt, network/src/commonTest/kotlin/com/wire/kalium/api/json/model/DomainToUserIdToClientToPreKeyMapJson.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v4/PrekeyApiV4Test.kt
----
----
Since api v4, `/users/list-prekeys` endpoint will return a different response. This is changed to:
```
{
"failed_to_list": [
{
"domain": "example.com",
"id": "99db9768-04e3-4b5d-9268-831b6a25c4ab"
}
],
"qualified_user_client_prekeys": {
"additionalProp1": {
"000600d0-000b-9c1a-000d-a4130002c221": {
"44901fb0712e588f": {
"id": 1,
"key": "pQABAQECoQBYIOjl7hw0D8YRNq..."
}
}
},
"additionalProp2": {
"000600d0-000b-9c1a-000d-a4130002c221": {
"44901fb0712e588f": {
"id": 1,
"key": "pQABAQECoQBYIOjl7hw0D8YRNq..."
}
}
},
"additionalProp3": {
"000600d0-000b-9c1a-000d-a4130002c221": {
"44901fb0712e588f": {
"id": 1,
"key": "pQABAQECoQBYIOjl7hw0D8YRNq..."
}
}
}
}
}
```
Breaks the retrocompatibility and api versioning we have on the project, since …
=> feat: add support for v4 list-prekeys endpoint new contract

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/userDetails/UserDetailsApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/userDetails/UserProfileDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/UserDetailsApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/UserDetailsApiV4.kt, network/src/commonTest/kotlin/com/wire/kalium/api/json/model/QualifiedIDSamples.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/user/details/UserDetailsApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v4/UserDetailsApiV4Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/ListUsersRequestJson.kt, network/src/commonTest/kotlin/com/wire/kalium/model/ListUsersResponseJson.kt
----
----
Since api v4, `/users/list-users` endpoint will return a different response. This is changed to:
```
{
"failed": [
{
"domain": "example.com",
"id": "99db9768-04e3-4b5d-9268-831b6a25c4ab"
}
],
"found": [
{
"accent_id": 2147483647,
"assets": [
{
"key": "3-1-47de4580-ae51-4650-acbb-d10c028cb0ac",
"size": "preview",
"type": "image"
}
],
"deleted": true,
"email": "string",
"expires_at": "2021-05-12T10:52:02.671Z",
"handle": "string",
"id": "99db9768-04e3-4b5d-9268-831b6a25c4ab",
"legalhold_status": "enabled",
"name": "string",
"picture": [
"string"
],
"qualified_id": {
"domain": "example.com",
"id": "99db9768-04e3-4b5d-9268-831b6a25c4ab"
},
"service": {
"id": "99db9768-04e3-4b5d-9268-831b6a25c4ab",
"provider": …
```
=> feat: add support for v4 list-users endpoint new contract (AR-3322)

network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/commonMain/kotlin/com/wire/kalium/network/NetworkClient.kt
----
----
`SocketTimeoutException` thrown when we try to upload multiple files
```
GenericError(cause=io.ktor.client.network.sockets.SocketTimeoutException: Socket timeout has expired [url=***/v2/assets, socket_timeout=unknown] ms)
04-25 17:05:47.398 31889 10293 I com.wire.internal.debug: 	at com.wire.kalium.network.api.v2.authenticated.AssetApiV2.uploadAsset$suspendImpl(AssetApiV2.kt:106)
04-25 17:05:47.398 31889 10293 I com.wire.internal.debug: 	at com.wire.kalium.network.api.v2.authenticated.AssetApiV2$uploadAsset$1.invokeSuspend(Unknown Source:18)
04-25 17:05:47.398 31889 10293 I com.wire.internal.debug: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-25 17:05:47.398 31889 10293 I …
```
=> fix: increase socket timeout (AR-3344) (develop) 

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/rootDetection/RootDetectorImpl.kt
----
----
When running the RootDetector, the app crashes.
It uses reflection to invoke a private function ([`SystemProperties$get()`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/SystemProperties.java)). 
Our code wants a `get` function that takes in a `List<String>`, and expects a `List<String>` as return type.
The function actually takes in a `String`, not a `List<String>`, and returns a single `String` as well.
Change our code to find the correct method. Also handle `NoSuchMethod` case as a fallback.
Tiny improvement: make the root detections execute lazily. If any results in a detection, the `||` operator will short-circuit and do not invoke the rest.
Using Reloaded on a rooted device and it was …
=> fix: crash during root verification

.github/workflows/generate-changelog.yml
----
----
Usage of workflow templating (e.g. `${{env....}}` could in theory lead to command injection.
Let the variables be handled by the shell environment to receive proper escaping.
Not really testable for this repository.
Needs to be reviewed and next run will show if it still works here, too.
----
----
----
=> ci: escape environment variables in generate-changelog.yml (AR-2928)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/verification/RequestSecondFactorVerificationCodeUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/verification/RequestSecondFactorVerificationCodeUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt
----
----
Users on Reloaded are greeted with generic error when attempting to login frequently using 2FA.
Backend is very harsh and limits to around 1 request per every couple of minutes for each email.
Return a more specific failure in the UseCase. So the UI can better handle it.
----
----
=> fix: improve TooManyRequests failure result on 2FA code request  (AR-3365)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationAccessRoleUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationAccessUseCaseTest.kt
----
----
When removing conversation guest access, revoking guest link should also be triggered
Revoke guest link when it was generated while removing guest access
=> fix: revoke guest link when removing guest access [AR-3282]

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ClientResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/InstanceLifecycle.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/Instance.kt
----
----
- Swagger was not usable because the content-type was not set correctly.
- There was a cycle when we tried to serialize CoreLogic object in instance model
Fixed it
----
=> fix: request content type and fix jackson self-reference cycle

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/userDetails/UserProfileDTO.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v4/UserDetailsApiV4Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/ListUsersResponseJson.kt
----
----
Listing users fails on API V4
The `failed` field is omitted when the are no failures when fetching users, but we expect it to always be there.
Make the `failed` field optional when decoding the response..
----
----
----
=> fix: failed field should be optional when listing users

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt
----
----
When users are on flaky internet connections (_e.g._ mobile data), the 10s min retry is _too_ much and leads to people thinking the app died or something. According to [Nah, 2014](https://www.researchgate.net/publication/220893869_A_Study_on_Tolerable_Waiting_Time_How_Long_Are_Web_Users_Willing_to_Wait): 2 seconds is enough to get users losing patience.
Replace the min retry interval so it is just 1 second.
For example, comparing `minInterval = 1s` and `minInterval = 10s`:
During the first 10 seconds, when the user can lose their patience, being a bit more agressive can be provide a better experience. 
After the first 30 seconds, they behave very similarly.
----
----
1. …
=> chore: reduce sync min retry to 1s

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt
----
----
After adding some feature flags from AR kalium doesn't know to trigger slow sync
Some features can be disabled until app will perform slow sync (max 7 days delay)
Add manual trigger to perform slow sync when there is need.
----
=> fix: trigger slow sync when it is needed after app update [AR-3424]

logic/build.gradle.kts, logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt
----
----
the recent usage of atomic fu in `SessionManagerImpl` had errors
after closer look it is not needed to use atomic ref since the cached session can be accessed only by one thread at a time
----
----
----
=> fix: remove the usage of atomic fu form SessionManager

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
I forgot to pass message timer when inserting conversation 😅 
----
----
----
=> fix: save group message timer on sync

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/service/ServiceRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/service/ObserveAllServicesUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/service/ObserveIsServiceMemberUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/service/SearchServicesByNameUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/service/ServiceRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/service/ObserveIsServiceMemberUseCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Service.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ServiceDAO.kt
----
----
1. search service by name is doing exact name lookup
2. missing unit test for ServiceRepository
----
----
----
=> fix: service search by name is looking only exacg name and add unit test to ServiceRepository

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCaseTest.kt
----
----
file sharing dialog is displayed after a fresh install
the sync was getting its initial value from the IsFileSharingEnabledUseCase which in its part is adding a default value of disabled when no value is stored yet
if file sharing status is missing (fresh install) consider it as not changed
----
----
----
=> fix: file sharing dialog is displayed after first install (AR-3150)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/BreakSessionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/DebugScope.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ClientResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/BreakSessionRequest.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/SendSessionResetRequest.kt
----
----
This PR provides a new function in the debug scope to break a session by creating a new session with a different prekey.
This functionality is tested by automation test C906622 of the QA.
----
----
----
=> feat: testservice can break sessions on purpose (SQPIT-1606)

gradle/libs.versions.toml, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/Asset.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCaseTest.kt, util/build.gradle.kts, util/src/androidMain/kotlin/com.wire.kalium.util/MimeTypeUtil.kt, util/src/appleMain/kotlin/com.wire.kalium.util/MimeTypeUtil.kt, util/src/commonMain/kotlin/com.wire.kalium.util/MimeTypeUtil.kt, util/src/jsMain/kotlin/com.wire.kalium.util/MimeTypeUtil.kt, util/src/jvmMain/kotlin/com/wire/kalium/util/MimeTypeUtil.kt
----
----
Some assets uploaded from iOS or web doesn't have extension in file name.
Sharing those assets by share intent makes them files with unknown type
Get mime type from asset which doesn't have extension and map it to extension suffix to the file 
----
----
----
=> fix: add extension to assets without it [AR-3261, AR-2929, AR-3482]

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/SendEphemeralConfirmationDeliveredRequest.kt
----
----
This PR adds the ability to send timed messages via testservice and also to mark them as delivered and remove them from conversations. The functionality to mark ephemeral messages as read was not used in the automation so it does not need to be implemented.
Additionally it cleans a bit the structure of ConversationResources class.
This was tested through running automatic test cases C318633 and C434930 which deal with ephemeral messaging.
----
----
----
=> feat: testservice can send and receive ephemeral messages (SQPIT-1807)

testservice/build.gradle.kts
----
----
Testservice failed with an exception on startup:
```
Exception in thread "main" java.lang.IllegalStateException: Unable to acquire the logger context
at io.dropwizard.logging.LoggingUtil.getLoggerContext(LoggingUtil.java:46)
at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:51)
at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:40)
at io.dropwizard.Application.bootstrapLogging(Application.java:38)
at io.dropwizard.Application.<init>(Application.java:26)
at com.wire.kalium.testservice.TestserviceApplication.<init>(TestserviceApplication.kt:41)
at com.wire.kalium.testservice.TestserviceApplication$Companion.main(TestserviceApplication.kt:48)
at …
```
=> fix: testservice did not start up anymore because of slf4j dependency

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/mlsmigration/MLSMigrationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/TimestampKeyRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/mlsmigration/MLSMigrationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationManagerTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/featureConfigs/FeatureConfigResponse.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/featureConfig/FeatureConfigApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/FeatureConfigJson.kt
----
----
Implement: [Use case: client periodically check to start migration](https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/760086581/Use+case+client+periodically+check+to+start+migration+Proteus+to+MLS+migration)
Support MLS migration feature config and  a `MLSMigrationManager` which re-fetches the migration configuration and advances the proteus to MLS migration every 24 hours.
----
----
----
=> feat(mls-migration): fetch migration configuration every 24 hours #1

cli/src/commonMain/kotlin/com/wire/kalium/cli/CLIApplication.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/mlsmigration/MLSMigrationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/MLSClientManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationWorker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/MLSClientManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigratorTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/CreateConversationRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/UpdateConversationProtocolRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/UpdateConversationProtocolResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/model/ConversationProtocolDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/EventContentDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/ConversationApiV4.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v4/ConversationApiV4Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/EventContentDTOJson.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
Implements: [Use case: client initialises migration on conversations](https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/760217617/Use+case+client+initialises+migration+on+conversations+Proteus+to+MLS+migration)
When MLS migration is active regularly upgrade "proteus" conversations to "mixed" and establish the associated MLS group.
----
----
----
=> feat(mls-migration): migrate proteus conversations to "mixed" protocol  #2

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/DebugScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/EphemeralMessageDeletionHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/ephemeral/EphemeralMessageDeletionHandlerTest.kt
----
----
self delete timer is started even when the message is not yet sent
start the timer after the message is sent
----
----
----
=> feat: start self delete after the message is sent

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/mapper/CallMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ProtocolInfoMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/RecoverMLSConversationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageUnpacker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ProtocolInfoMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/RecoverMLSConversationsUseCaseTests.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigratorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageUnpackerTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
Support the "mixed" protocol on conversations, which means it's a proteus conversation which also has a mls group. During migration mls clients will be added the mls group until every client has joined, at which the conversation transitions to the mls protocol.
- Support persisting the mixed protocol with associated MLS fields
- Support MLS operations on "mixed" conversations
- Perform proteus & MLS operations when adding, removing users to "mixed" conversations.
Use case: [Maintaining the client list in "mixed" mode](https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/759169316/Use+case+Maintaining+the+client+list+in+mixed+mode+Proteus+to+MLS+migration)
----
----
----
1. …
=> feat(mls-migration): support the mixed protocol #3

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/SubconversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PendingProposalScheduler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/PendingProposalSchedulerTest.kt
----
----
When another participant leaves a MLS conference call he/she isn't immediately removed from the call.
You leave an MLS conference by submitting a leave proposal to the "call" sub-conversation of the conversation where the call is happening. These leave proposals were never committed because we don't store sub-conversation in the database and the proposal timers rely on values being updated in the database.
Use an in memory timer when scheduling proposals from sub-conversations.
----
----
----
=> fix: other participant leaving an MLS conference call WPB-349

persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/GlobalPrefProvider.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/UserPrefBuilder.kt, persistence/src/appleMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/appleMain/kotlin/com/wire/kalium/persistence/kmmSettings/GlobalPrefProvider.kt, persistence/src/appleMain/kotlin/com/wire/kalium/persistence/kmmSettings/UserPrefBuilder.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/jsMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmmSettings/GlobalPrefProvider.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmmSettings/UserPrefBuilder.kt, persistence/src/jvmTest/kotlin/com/wire/kalium/persistence/EncryptedSettingsBuilderTest.kt
----
----
rare crash because of encrypted shared pref creation
Wrapping the build function in an object should resolve any issues with concurrency issues  
----
----
---- …
=> fix: replace @Syncronized annotation with synchronized block and wrap the shared pref builder function in object

.github/workflows/codestyle.yml, .github/workflows/generate-dokka.yml, buildSrc/src/main/kotlin/com/wire/kalium/plugins/CommonDokkaConfig.kt
----
----
Dokka was failing.
Brings dokka back as shown in prev execution, using a build cache, also setting up explicitly the protobuf project.
Manually tested, execution logs on
https://pipelines.actions.githubusercontent.com/serviceHosts/34e009ab-724e-415a-b825-f651abb68c4f/_apis/pipelines/1/runs/56774/signedlogcontent/2?urlExpires=2023-06-05T16%3A07%3A22.3812312Z&urlSigningMethod=HMACV1&urlSignature=%2FxXD6NzZs23Ea3NBCLrtt15VHi5CrTcV35dvlFzrtYI%3D
[2023-06-05T16:00:55.4652656Z-logs.txt](https://github.com/wireapp/kalium/files/11654578/2023-06-05T16.00.55.4652656Z-logs.txt)
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by …
=> chore: another try to run dokka

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientCoreCryptoImpl.kt
----
----
We crash / throw an unexpected exception when opening the core crypto proteus client.
If a CoreCrypto exception is thrown when initialising CoreCrypto attempt to figure out the root cause by calling `coreCrypto.proteusLastErrorCode()`. But the lateinit `coreCrypto` is not yet set and we crash.
Set `coreCrypto` before we call `proteusInit` and avoid calling `coreCrypto.proteusLastErrorCode()` if coreCrypto is not set.
----
----
----
=> fix: crash while initialising CoreCrypto WPB-1923

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt
----
----
Sometimes users on Reloaded are "stuck on connecting"
1. The OS can block the app from connecting to the network when the app isn't visible after a while. And we do not handle the "unblocking" on Kalium's `NetworkStateObserver`.
2. Given the current backoff policy can make it grow to up to 10 minutes while on the background, even if the app is reopened, the retry counter will stay counting.
The first "cause" isn't handled on this PR. As Android's ConnectivityManager calls need some testing to make sure it works well and it would be safer to improve after the next code freeze.
About the second one. It's two-fold:
1. Whenever there's a policy upgrade: reset the backoff timer.
2. Whenever there's a policy upgrade: cancel the timer that is …
=> fix: immediately retry sync on connection policy upgrade

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/EphemeralMessageDeletionHandler.kt
----
----
message delete timer is not starting correctly for outgoing messages 
I was passing the message object that we use to send but it had the sent status not updated (meaning it is still pending) therefore the timer is not starting
if statement to check if the message is sent from the `enqueueSelfDeletion` to `startSelfDeletion`, this solved the issue and the timer is set correctly 
_Attachments like images, …
=> fix: self delete timer not starting after message is sent

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/notification/LocalNotification.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Notification.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageNotificationsTest.kt
----
----
self delete messages content is visible in notifications 
hide content of self delete messages
----
----
----
=> feat: add self delete message type to notifications

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
----
----
when deleting an asset message while being uploaded -> app crash
the asset message send use case is observing the message status to cancel the upload if the message is deleted and after delete the status is null and the mapper crashes (it expects non null values)
change the flow to emit null values when the data is not found
----
---- …
=> fix: crash when deleting a self delete asset message

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt
----
----
QA cannot distinguish between different devices in the automation because the current kalium implementation uses os.name for the devices. See:
In this PR I made the device model value configurable on client registration. If it is not set it will stay os.name.
Might be that this PR breaks android-reloaded? Maybe someone help me with that?
----
----
----
=> feat: Allow testservice to set device model name

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/ProteusClientProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClearClientDataUseCase.kt
----
----
Logging again after your device has been deleted remotely will cause decryption errors
The previous proteus client is re-used when registering the new device on the backend. When any message is encrypted using a pre-existing session, decryption errors generated on the receiving side because it would expect a new session to initiated for this new device.
The proteus client re-used because when `_proteusClient?.clearLocalFiles()` is executed `_proteusClient` is null so the proteus data files are never removed.
- Instantiate a ProteusClient if it doesn't already exist
- Make it safe to call `clearLocalFiles` before opening the proteus client.
----
----
----
1. …
=> fix: re-using previous proteus client after it has been deleted WPB-2289

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/PublicUserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/UserSearchApiWrapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/UserSearchApiWrapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserMapperTest.kt
----
----
1. There's code duplication in the user mapper with several variations of the same mapping.
2. Some mapping function are not used at all
3. The naming is inconsistent 
1. Normalise the mapping functions
2. Delete unused mapping functions
3. Use naming based on actual classes/types
Should we merge PublicUserMapping and UserMapping into one?
----
----
=> refactor: user mapper

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/remote/ClientRemoteRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/NewClientManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/NewClientManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/client/ClientApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/client/ClientDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/EventContentDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/user/ClientEventsData.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ClientApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/model/ClientResponseJson.kt, network/src/commonTest/kotlin/com/wire/kalium/model/NotificationEventsResponseJson.kt
----
----
`NewClientEventData` duplicates `ClientResponse` since they are represented by same underlaying type.
Delete `NewClientEventData` and replace it with `ClientDTO` (renamed from ClientResponse) and we can also remove some repeating mapping code due to this.
----
----
----
=> refactor: replace NewClientEventData with ClientDTO

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/ProteusClientProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClearClientDataUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientFingerprintUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/LeaveSubconversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SessionEstablisher.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ProteusMessageUnpacker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/corefailure/WrapProteusRequestTest.kt
----
----
`wrapCryptoRequest` has a generic name, although it only handles Proteus exceptions.
This can lead to confusion, and misusage of the function.
1. Rename it to `wrapProteusRequest`
2. Replace wrong `wrapCryptoRequest` with `wrapMLSRequest` where needed.
----
----
=> refactor: rename `wrapCryptoRequest` to be proteus specific

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationWorker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrator.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigratorTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
After the migration has started for conversation we should periodically monitor when all members of the groups have announced that they support MLS. When all members support MLS we should make an request to update the protocol to MLS so that future messages are sent via the MLS protocol.
----
----
----
=> feat(mls-migration): update conversation protocol to MLS when every member supports MLS #6

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt
----
----
timer starts for self delete messages even when they fail to send
do not start timer on failure
----
----
----
=> fix: timer start when self delete message failed to send

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandlerTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
----
----
Sometime user gets duplicated event when he changes conversation message timer
They are two the same system messages about conversation message timer change
Check if current message timer is different than timer received from event, if yes then send system message
=> fix: duplicated conversation timer change event [WPB-286]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandlerTest.kt
----
----
Sometime user gets duplicated event when a conversation is created
They are two the same system messages about conversation message started
Check if the conversation received exists, and in that case we don't need to handle it again.
=> fix: duplicated messages conversation creation (WPB-1916)

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSWrongEpochHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSWrongEpochHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/MockativeExt.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageInsertExtension.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
----
----
If there's any race condition on the backend, or the device becomes offline for too long, we might lose some MLS messages, resulting in `WRONG_EPOCH`.
Handle the case, by creating a `MLSWrongEpochHandler`, that will be called when there's a failure to unpack MLS conversations.
This will:
1. Fetch the conversation from the backend
2. Compare the `epoch` and see if it is different from the local version
3. In case of a difference, rejoin the existing MLS conversation to match the epoch
4. In case of a rejoin, insert a MLS warning system message for the affected conversation
----
----
1. E.g. `feat(conversation-list): Sort conversations by …
=> feat(mls): handle wrong epoch error [WPB-1803]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/EphemeralMessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/DebugScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/DeleteEphemeralMessageForSelfUserAsReceiverUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/EphemeralRepositoryTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt
----
----
self deleting messages delete message is sent to all of the conversation members
Send 2 delete messages:
1. for the original message sender if they are still a member.
2. send a message, a delete message to the user self conversation
----
----
----
=> fix(RC): delete message is sent to everyone in the conversation

cli/src/commonMain/kotlin/com/wire/kalium/cli/commands/UpdateSupportedProtocolsCommand.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncStatus.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CheckConversationInviteCodeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationWorker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCaseTest.kt
----
----
Invoke the `UpdateSupportedProtocols` use case during the slow sync and every 24 hours when the migration feature is enabled.
----
----
----
=> feat(mls-migration): update self supported protocols during slow sync #9

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
When fetching failed conversations, the participants with whom I'm not connected with, are showing as "username not available"
This users are not refreshed, because when inserting ids, we assume we have the metadata.
When persisting only id's of users, mark them as incomplete metadata, so we can refetch them later.
**Before**
**After**
----
----
----
=> fix: handle insertion of user with incomplete metadata at query level (WPB-411)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/SyncConversationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationWorker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/SyncConversationsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigratorTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
When the migration configuration has configured an end date (finaliseRegardslessAfter) and this date has arrived we should migrate all team proteus conversation to MLS even though not all members support MLS.
More details: https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/759890302/Use+case+client+checks+if+conversation+migration+can+be+finalised+Proteus+to+MLS+migration
I also generalised the DAO method for fetching conversation ids so that I don't have to create new method for every use case.
----
----
----
=> feat(mls-migration): force migration when migration deadline arrives #10

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/DebugScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/DeleteEphemeralMessageForSelfUserAsReceiverUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ephemeral/DeleteEphemeralMessageForSelfUserAsReceiverUseCaseTest.kt
----
----
endless loop when sending a delete message in a conversation
the backend report that a clients of self user are missing, even so self was NOT included as a message recipient
----
----
---- …
=> fix(RC): include self user id when sending a delete message to a conversion

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/authenticated/ConversationApiV3.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
Remove any references to global team conversations since the feature was dropped and was never released.
=> chore: remove global team conversations

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/SendMessagePartialFailureMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/SendMessagePartialFailureMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/message/SendMLSMessageResponse.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
We need to support partial delivery (some participants offline) while sending a message using the MLS protocol.
More info about the flow, is defined here:
https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/556564601/Use+case+sending+a+message+MLS
Parse new optional response, and handle this list of user ids, as we did with proteus.
----
----
----
=> feat(federation): adding handling of failed to sent message in MLS (WPB-451)

network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/authenticated/ConversationApiV3.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/ConversationApiV4.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v3/ConversationApiV3Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v4/ConversationApiV4Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/conversation/SubconversationDeleteRequestJson.kt, network/src/commonTest/kotlin/com/wire/kalium/model/conversation/SubconversationDetailsResponseJson.kt
The MLS APIs have been moved to V4 so we should also move the implementation to V4.
----
----
----
=> chore: move MLS api implementations from v3 to v4

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandlerTest.kt
----
----
When a new 1:1 MLS conversation was created, the backend would send a regular `conversation.create` event.
Now, it does not.
MLS spec is being updated.
Now, handle the possibility of the conversation not existing during the receiving of a MLS welcome message.
If the conversation doesn't exist: fetch it.
If it exists, or if it doesn't, update the conversation to make it `ESTABLISHED` in any case.
----
----
=> feat(mls): handle mls welcome event according to new spec (WPB-2178)

logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/session/SessionRepositoryTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt, scripts/dev.mk
----
----
We need to enable the websocket by default on devices that doesn't support google play services. ie. col1/3/fdroid builds
When storing the session of the user, persist this config accordingly by configuration given by `KaliumConfig`
We need to raise a PR in reloaded for this.
----
----
----
=> feat(v4.1): handling configuration for websocket enabled by default (WPB-967)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/CommitBundleEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/EventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/TeamEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserPropertiesEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt
----
----
Currently, there's no possibility of gracefuly handling errors during event processing.
For MLS - for example - there are delicate event handling where network requests need to be made and in case of failure or network instability, we should abort sync and retry later again.
Currently when an exception is thrown: Sync will stop.
This is _in parts_ what we want. However, most of our code wraps exceptions and returns as `Either.Left` without throwing exceptions.
Streamline the processing of events, by making handlers return `Either` as well.
In case of failures, the `lastProcessedEventId` shouldn't be updated, and `IncrementalSyncWorker` should throw a `KaliumSyncException`, making Sync stop.
I have _not_ addressed 100% of the event …
=> refactor: handle event processing failure

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt
----
----
self ephemeral messages timer is not starting automatically
after receiving a message, enqueue it for self delete if it is ephemeral and the sender is self
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis …
=> fix(RC): ephemeral messages timer form self user should start automatically

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCaseTest.kt
----
----
This usecase will keep observing the  conversation details that is in active call TO END IT.
The call should be terminated when:
- User leaves that conversation
- User removed from that conversation
- That Conversation got removed
- User Delete his account
----
----
---- …
=> feat(calling): create usecase for ending call on member leave or conversation delete (WPB-2955)

testservice/config.yml
----
----
The testservice configuration does not contain the fields to configure the listening ports.
Making it non-intuitive to figure out where to configure it, when it needs to be changed
Put default configuration into `config.yml` (and restrict admin interface to 127.0.0.1)
Start the testserivce with the updated config file and check, whether it is still accessible.
----
----
----
=> chore(testservice): add default values to testservice config file

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt
----
----
The PR #1765 broke the message timer by removing it from the testservice
https://github.com/wireapp/kalium/commit/02755bb4ae06540e5c3a12b52d9dc8d8881da9c7#diff-02b79a0c7124a72acb5e55b1578470e073aa3e6038a7b75c3d0ac9e0f7e9cdfbL164
Additionally the message timer did not work for files and images.
This PR adds the message timer function back and also adds it to image, file and update text endpoints.
----
----
----
=> fix: testservice self deletion message timer was broken

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistReactionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/PersistReactionUseCaseTest.kt, persistence/src/commonMain/db_user/migrations/47.sqm
----
----
In order to keep compatibility with the old Scala app, we added some quick hacks.
Now that iOS and Web are implementing reactions, we need to align the behaviour of the ❤️ emoji.
| Visual Representation | Unicode Symbols           | Comment                                                                      |
|:---------------------:|:-------------------------:|:----------------------------------------------------------------------------:|
| `❤`                     | Single symbol: \u2764     | Expected by old Android and exchanged between clients during the “Likes” era |
| `❤️`                    | Two symbols: \u2764\uFE0F | Default used by Web, iOS and Android during the “Reactions” era              |
1. Move compatibility layer …
=> refactor: move reaction logic [WPB-826]

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
Incoming connection requests are no longer visible to the user.
Small refactoring introduced this bug recently.
Fix the query that fetches the conversation list. A small bug was introduced during rewriting where instead of checking for non-group, it was limiting only to one-on-one conversations, excluding connection requests.
Added test cases for connection requests to make sure this is cemented in place.
----
----
=> fix: connection requests not appearing [WPB-3033]

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/BaseApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/SelfApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/ConversationApiV4.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/conversation/ConversationApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/user/self/SelfApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v4/ConversationApiV4Test.kt
----
----
Support new API for fetching MLS 1-1 conversation metadata.
----
----
----
=> feat(mls-one2one): support fetching mls 1-1 conversation details

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteConversationNotificationsManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/DeletedConversationEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/DeletedConversationEventHandlerTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/NotificationApiV0.kt
----
----
Same PR as #1872 for RC branch
----
----
----
=> fix: Not receiving messages after deleting conversation (WPB-3040) (RC)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/BreakSessionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/sessionreset/ResetSessionUseCase.kt
----
----
Adding some logs to help QA investigation about some test failures related to reset session.
----
----
----
=> chore: add logs for reset session

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Connections.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConnectionDaoTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
----
----
Add persistence support methods for migrating from proteus to MLS for 1-1 conversations.
- Change the associated conversation for a connection.
- Move message history from one conversation to another.
----
----
----
=> feat(mls-one2one): support migrating to mls 1-1

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendKnockUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfDeletingMessages/ObserveSelfDeletionTimerSettingsForConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfDeletingMessages/SelfDeletionTimer.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendKnockUserCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/selfDeletingMessages/ObserveSelfDeletingMessagesUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/ObserveSelfDeletionTimerSettingsForConversationUseCaseArrangement.kt
----
----
pings are not sent as self deleting
1. set message timer in the knock use case.
2. clean up message duration and remove duplicated code
----
----
---- …
=> feat(RC): send pings as self deleting and messsage duration clenup

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestUser.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandlerTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq, persistence/src/commonMain/db_user/migrations/43.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
When user is leaving conversation, after that he will not receive any events about member leave or join that conversation. So after rejoining conversation he will have wrong conversation member list.
Also slow sync will not remove members who left when user was not a member of conversation, because slow sync only adds members.
Because of potential performance problems I forced slow sync with entire members invalidation just once. In next version we can remove it and always invalidate conversation members when user will rejoin conversation
=> fix: invalidate conversation members [WPB-3047]

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnIncomingCall.kt
----
----
in OnIncomingCall callback, the camera default value is set to `isVideoCall` which can lead to this crash 
https://wearezeta.atlassian.net/browse/WPB-1712
The default value of camera should be false by default for incoming calls.
----
----
----
=> fix: set default value of camera for incoming calls (WPB-1712)

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnIncomingCall.kt
----
----
Same PR as #1880 to be merged into RC branch
----
----
----
=> fix: set default value of camera for incoming calls (WPB-1712)  (RC)

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
We have to manually cherry-pick changes from `release/candidate` into `develop`. Which leads to human error and forgotten commits.
Porting the work @Garzas has done on Reloaded into Kalium:
- https://github.com/wireapp/wire-android-reloaded/pull/1951
Which does:
- Add a new GitHub workflow that will listen for merged PRs into `release/candidate`
- Cherry pick the merge commit
- Push to a new branch with `-cherry-pick` suffix
- Create a new PR with:
- same assignee
- same title
- same body
- `cherry-pick` label
> **Note**: When this PR is merged, it will automatically open a PR on `develop` as well :)
----
----
1. E.g. …
=> ci: automatically cherry-pick changes from `release/candidate`

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCaseTest.kt
----
----
When migration to MLS we are waiting for a user to update all his clients to version which supports MLS. The problem is this might never happen since it's very common to end up with abandon clients which is not longer tied to a physical device and thus it will never become MLS capable.
The solution is to only wait for clients which are actively in use to become MLS capable.
Further reading: 
* https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/791970001/1+1+conversations+with+MLS?focusedCommentId=792657968#Updating-your-supported-protocols
* https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/810450986/Tracking+active+clients+on+the+backend
----
----
----
1. …
=> feat(mls-migration): ignore inactive clients when calculating supported protocols #11

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/SelfDeletionEventLogger.kt
----
----
Logging of self deleting message doesn't log the full message log structure and mixes a few things together.
Log the full message structure according to the existing log mechanisms and improve the auxiliary information.
```
Self-Deletion: {
"message": {
"type": "text",
"id": "7b22797***",
"conversationId": "9b3ebe0***@wir***",
"date": "2023-07-20T13:38:25.386Z",
"senderUserId": "1ba9d96***",
"status": "SENT",
"visibility": "VISIBLE",
"senderClientId": "f487db1***",
"editStatus": {
"value": "NOT_EDITED"
},
"expectsReadConfirmation": "true",
"deliveryStatus": {
"value": "COMPLETE_DELIVERY"
},
"expirationData": {
"expire-after": "10",
"expire-start-time": "null",
"deletion-status": {
"value": "NOT_STARTED"
}
}
},
"deletion-info": { …
```
=> chore: improve logging of self deleting messages

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt
----
----
It should be possible to update `isMLSCapable` from false to true but not the other way around.
----
----
----
=> fix: updating isMLSCapable

.gitignore
----
----
I've created my own personally configured run tasks which gets persisted to `.run` so I think it makes sense to add it to `.gitignore`
----
----
----
=> chore: ignore .run directory

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/MessagePreview.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/LastMessageListTest.kt
----
----
composite messages are not included in the preview
add COMPOSITE to the message type in the getLastMessages query
----
----
---- …
=> fix: composite messages are not included in the getLastMessages query [part-5]

monkeys/src/commonMain/kotlin/com/wire/kalium/monkeys/importer/TestData.kt
----
----
In order to enable extensibility and more use cases we're adding new configuration options for the application.
Right now the application is with most of its parameters hardcoded, not allowing many test scenarios.
This is the first iteration on this. The logic for handling the configuration will come in separate PRs to not have huge code reviews. 
----
----
----
=> feat(monkeys): Add new configuration attributes for the next milestone [WPB-3353]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageCaseTest.kt
----
----
- When the user leaves the scope launching the action to send the message, if the timing is right, the message could gets stucked at any suspend point. 
- Move the execution of the job to UserSessionScope, to send the message as long as the app is "alive".
----
----
----
1. …
=> fix: execute job sending message inside UserSessionScope

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetAvatarAssetUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCase.kt
----
----
When user have multiple accounts of users that are not federating with each other it tries refetch them in loop (400 error code response)
Blinking avatar effect on other accounts screen
Don't refetch asset on any invalid request error
=> fix: do not refetch asset on invalid request response

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/TeamEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/TeamEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
For 1:1 MLS migration, at some point we need to fetch conversations with the other member and see if there is an already-existing MLS 1:1 conversation.
Refactor `selectConversationIdsByUserId` so it becomes `selectConversationsByUserId`.
So instead of returning only the conversation ID, it will return the whole conversation and we can use it.
> **Note**
> Performance-wise, it would be optimal to have a dedicated query that would query and return only IDs, and another dedicated thread that would return full conversations filtering by 1:1 conversation type. However these queries are _not_ used in loops, or used all the time in any way. The performance cost would be lower than maintaining these two queries.
Changed tests to work with this …
=> refactor: allow fetching whole conversations by a member [WPB-2181]

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
Conflicts will be printed in cherry pick PR similar to this: https://github.com/wireapp/this-is-a-test/pull/44
=> chore: print conflicts on cherry-pick

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
I don't know why it stopped working but after updating deprecating functions and adding empty text for conflicts variable it started working
=> fix: cherry-pick automation

cryptography/src/androidInstrumentedTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/appleTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/CheckConversationInviteCodeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinConversationViaCodeUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/CheckConversationInviteCodeUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinConversationViaCodeUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/model/ConversationCodeInfo.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/JoinConversationRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/ConversationApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/NetworkErrorLabel.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/conversation/ConversationApiV0Test.kt
----
----
[WPB-1531]
support password protected guest links, this feature is api v4 only 
----
----
----
[WPB-1531]: …
=> feat: support joining conversation with password protected code [WPB-1531]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UpdateConversationClientsForCurrentCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/UpdateConversationClientsForCurrentCallUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandlerTest.kt
----
----
I am reverting the changes of #1918 as we need to update the conversation call clients on every client removal, not only the current one as #1918 do
I created `UpdateConversationClientsForCurrentCallUseCase` that will be invoked everytime we notice a member removal
----
----
---- …
=> feat: update conversation call clients on member removal (RC-4.2) (WPB-3017)

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfig.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/guestroomlink/CanCreatePasswordProtectedLinksUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/guestroomlink/CanCreatePasswordProtectedLinksUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ServerConfigRepositoryArrangement.kt
----
----
[WPB-1531]
password protected guest links are supported on api v4+
add use case to check the user api version
----
----
----
[WPB-1531]: …
=> feat: add use case to decide if a user can create password protected invite links [WPB-1531]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/EventContentDTO.kt
----
----
Currently, we map multiple different events that we not yet handle as `Event.Unknown`. In logs, there is no way to know which exact type it is.
Add type to unknown event logs. In addition, for some types (like `FieldKeyValue`) also add cause (like "unknown key").
----
----
----
=> chore: add logging details of unknown events

cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/E2EIClientTest.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandlerTest.kt
* fix: duplicated timer change system message
* test improvement
----
----
Wrong local id for conversation message timer change event was passed
=> fix: duplicated timer change system message [WPB-286] (#1935)

cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/E2EIClientTest.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/MLSConnectionMigrator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/MLSOneOnOneConversationResolver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/mls/MLSConnectionMigratorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/mls/MLSOneOnOneConversationResolverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/mls/MLSOneOnOneConversationResolverArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConnectionRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/MessageRepositoryArrangement.kt
----
----
When identifying that a 1:1 conversation could be made through MLS instead of Proteus, we need to perform a migration.
> **Note**
> This does _not_ cover "fake 1:1 conversations" between team members. This is for "true" 1:1 conversations. The team version was already taken care together with group conversations.
Create a `MLSConnectionMigrator`, that is responsible for following the [technical specification](https://wearezeta.atlassian.net/wiki/spaces/PAD/pages/811958286), which says we need to:
This was already implemented in the `GetOrEstablishMLSOneToOneUseCase`, I just renamed it to `MLSOneOnOneConversationResolver`, instead of a _UseCase_ suffix for internal usage.
Built on top of already existing DAO implementation, but now …
=> feat(mls): migrate 1:1 connections from Proteus to MLS [WPB-2258]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SyncState.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/BackupScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/RestoreWebBackupUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/SyncConversationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/SyncSelfUserUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/RestartSlowSyncProcessForRecoveryUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncRecoveryHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/RestoreWebBackupUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/handler/ButtonActionConfirmationHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/handler/DeleteMessageHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/RestartSlowSyncProcessForRecoveryUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorkerTest.kt
----
----
Some parts of slow sync are missing unit test
Cover `RestartSlowSyncProcessForRecoveryUseCase` and `SlowSyncWorker` with test
----
----
----
=> test: cover some missed parts of sync with unit test - PART 1 (WPB-3471)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/prekey/PreKeyApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/prekey/PreKeyDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/PreKeyApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/prekey/PrekeyApiV0Test.kt
----
----
Periodically we need to check if the Proteus prekeys we uploaded when we registered the client are consumed and create and upload new ones as they are consumed.
Currently, we have no implementation of the endpoint to upload them, and we lack some of the repository-level operations.
- Add the missing endpoint to upload prekeys in `PrekeyAPI`
- Expose fetching and uploading operations in the `PreKeyRepository`
This will enable us to create a `PreKeyRefiller` in the next PR. This class will be responsible for figuring out if a new batch of prekeys is needed, and if needed it will create and upload some more.
----
----
1. E.g. …
=> chore: enable fetching and uploading of prekeys [WPB-3552]

build.gradle.kts
----
----
Our coverage reports keep track of "side-projects" within Kalium, which are not actively maintained and parts of Kalium, but rather other projects that are using it.
When we decide to keep some degree of coverage, or that some rules apply to Kalium, these project won't necessarily follow the same rules.
Currently, `koverXmlReport` is triggering `monkeys` tests for example, which are flaky and are getting in the way of development of Kalium itself.
The same could happen to `testservice`.
Also, coverage for `android`, `cli` doesn't really matter as these are not Kalium itself, but samples and auxiliary tools built on top of it.
Disable code coverage for these other modules. Which also disables running of these tests in CI for now.
In the …
=> ci: disable coverage reports for 3rd modules

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/IncrementalSyncRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/MissingMetadataUpdateManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/ObserveSyncStateUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/PendingMessagesSenderWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/SyncManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/TeamEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserPropertiesEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandlerTest.kt
----
----
Follow up PR of #1973 to increase sync unit test
Mainly covering `ObserveSyncStateUseCase` and `ConversationEventReceiver` with unit tests
----
----
----
=> test: cover some missed classes of sync with unit test - PART 2 (WPB-3472)

gradle/libs.versions.toml, monkeys/README.md, monkeys/build.gradle.kts, monkeys/example.json, monkeys/schema.json, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/CreateConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendMessageAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendRequestAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/importer/TestData.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/importer/TestDataImporter.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/importer/UserData.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/ConversationPool.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/MonkeyPool.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendRequestActionTest.kt
----
----
This removes the configuration for setting users and creates the users automatically for the test.
----
=> feat(monkeys): Create users automatically for the test [WPB-3682]

cryptography/src/appleMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/MLSClient.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/DecryptedMessageBundleMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMappers.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinSubconversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageFailureHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageUnpacker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinSubconversationUseCaseTest.kt
----
----
CoreCrypo 1.0.0 introduced a new feature where it will buffer message received after joining a conversation via external commit but before `mergePendingGroupFromExternalCommit` has been called. This scenario will happen if an MLS group has any pending external remove proposals when joining via external commit. The reason is that the backend will immediately re-create the remove proposals because they get invalidated by the external commit.
This PR updates `JoinExistingMLSConversationUseCase` and `JoinSubconversationUseCase` to process any buffered proposals.
1. Create MLS group with user A and B
2. Make user A's client is offline so it can process proposals 
3. Leave the group with user B's client (the group will now have pending …
=> feat: handle buffered events

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, cryptography/src/appleMain/kotlin/com/wire/kalium/cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/appleMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/BreakSessionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/proteus/ProteusPreKeyRefiller.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/proteus/ProteusPreKeyRefillerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/PreKeyRepositoryArrangement.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/PrekeyDAO.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/PrekeyDAOTest.kt
----
----
As prekeys from client X are consumed by other clients when initialising conversations with X, we need to generate more and upload them.
In this PR: create a `ProteusPreKeyRefiller` that is responsible for this.
In a next PR: trigger this Refiller based on Sync status
> **Note**
> I've also renamed and added docs to places that said `lastPreKey`; in order to separate the "last resort" prekey from the "rolling" prekeys and avoid confusion.
----
----
=> chore: create a way to refill Proteus prekeys [WPB-3552]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/proteus/ProteusSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/proteus/ProteusSyncWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/IncrementalSyncRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/PreKeyRepositoryArrangement.kt
----
----
Every so often, we need to refill Proteus prekeys as they are consumed.
Add a `ProteusSyncWorker` that is responsible for triggering `ProteusPreKeyRefiller` when we are Live, with a minimum interval of 1 day.
----
----
=> feat(proteus): periodically refill prekeys when live [WPB-3552]

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/mlsmigration/MLSMigrationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/protocol/OneOnOneProtocolSelectorArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConversationGroupRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConversationRepositoryArrangement.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/featureConfigs/FeatureConfigResponse.kt, network/src/commonTest/kotlin/com/wire/kalium/model/FeatureConfigJson.kt, network/src/commonTest/kotlin/com/wire/kalium/model/NotificationEventsResponseJson.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/config/UserConfigStorageTest.kt
----
----
When initiating a 1-1 conversation with a team member we should select the correct protocol based on the users' supported protocols and do the following
fetch the MLS 1-1 conversation metadata. The underlaying MLS group will be established before sending the first message, this avoids prematurely creating a conversation on the other side. 
create a fake 1-1 conversation (specially configured group conversation)
Storing the default protocol ended up not being necessary for this feature but will be needed later when deciding which protocol use when creating group conversations.
----
----
----
1. E.g. …
=> feat: check supported protocols when creating/fetching team 1-1

logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/FeatureSupportImpl.kt, network/src/commonMain/kotlin/com/wire/kalium/network/BackendMetaDataUtil.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/e2ei/E2EIApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/KeyPackageApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/MLSMessageApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/MLSPublicKeyApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/ConversationApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/E2EIApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/KeyPackageApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/MLSMessageApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/MLSPublicKeyApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/networkContainer/AuthenticatedNetworkContainerV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/ConversationApiV5.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/E2EIApiV5.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/KeyPackageApiV5.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/MLSMessageApiV5.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/MLSPublicKeyApiV5.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v4/ConversationApiV4Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v5/ConversationApiV5Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v5/E2EIApiV5Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v5/KeyPackageApiV5Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v5/MLSMessageApiV5Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v5/MLSPublicKeysApiV5Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/conversation/SubconversationDetailsResponseJson.kt
----
----
This PR is part 2, and contains
- Move MLS related endpoints to v5 development version.
- Enabling v5 development as BE already supports in certain environments https://nginz-https.anta.wire.link/api-version
- https://github.com/wireapp/kalium/pull/2001
----
----
----
=> feat: move mls specific endpoints to v5 and enable dev support pt.2 (WPB-1124)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/publicuser/search/SearchKnownUsersUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/publicuser/search/SearchPublicUsersUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchKnownUserUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchUserUseCaseTest.kt
----
----
If you search on android for `QueenBellaPlume@bella.wire.link` no results are shown
But if you search for `queenbellaplume@bella.wire.link` you have match.
Ignore case, sanitize input, while performing search
----
----
----
=> fix: search does not ignore case while performing search

monkeys/README.md, monkeys/schema.json, monkeys/src/main/kotlin/com/wire/kalium/monkeys/ActionScheduler.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/Action.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/AddUserToConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/CreateConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/DestroyConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/LeaveConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/LoginAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/ReconnectAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendMessageAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendRequestAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/Monkey.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/homeDirectory.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/importer/TestData.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/ConversationPool.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/MonkeyPool.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/AddUserToConversationActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LeaveConversationActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LoginActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendMessageActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendRequestActionTest.kt
----
----
Adds support to run multiple clients within the test. Each test case in the config will use a separate client for the users in the test.
----
=> feat(monkeys): Allow to split clients per test cases [WPB-4332]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/NewGroupConversationSystemMessagesCreator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/RestoreWebBackupUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/PersistMigratedConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/migration/MigrationScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/RestoreWebBackupUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationResponse.kt
----
----
In API v5 the `creator` field has become optional because it's not set for MLS 1-1 conversations. 
The concept for a creator doesn't make sense for 1-1 conversations but for proteus it was assigned to the self user so I decided to do the same for MLS 1-1 conversations until we decide to refactor the persistence layer and make the creator optional there
----
----
----
=> chore: default selfUser when creator field is missing

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
conversations with null name are placed on the top of the conv list
edit the sorting to place null at the end of the list
----
----
----
=> fix: conversations with null name are placed on the top of the conv list

calling/src/commonJvmAndroid/kotlin/com.wire.kalium.calling/Calling.kt, calling/src/commonJvmAndroid/kotlin/com.wire.kalium.calling/callbacks/SelfUserMuteHandler.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnMuteStateForSelfUserChanged.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/scenario/OnMuteStateForSelfUserChangedTest.kt
----
----
Mute self user in a call if he is muted by a call admin from other client.
Needs #2018 to work
----
----
----
=> feat(calling): remote mute for participant (WPB-2953)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/NotificationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/NotificationApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/notification/NotificationApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/NotificationEventsResponseJson.kt
----
----
When a client goes offline for a long period, the backend might have deleted the last processed event and now the client faces a 404 during incremental sync.
In order to recovery from this, we need to fetch the oldest possible event from the backend.
Add `oldestNotification` functionality in the `NotificationApi`. 
Renamed `lastNotification` to `mostRecentNotification` for clearer distinction and understanding of the functionality. 
`oldestNotification` calls the notifications API endpoint without a `since` parameter. This way the backend will return the oldest known event.
----
----
1. E.g. `feat(conversation-list): Sort conversations …
=> chore(notification): add a way to fetch oldest notification [WPB-267]

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventGathererTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/EventRepositoryArrangement.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/notification/NotificationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/NotificationApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/notification/NotificationApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/NotificationEventsResponseJson.kt
----
----
When the server answers a 404 for missing event, we don't clear the `lastProcessedEventId` and stay in a loop trying to fetch the same event for ever.
Updated the logic for handling failures during incremental sync.
Now, in case of a "not found" response when fetching pending events, the system will update the last processed event and restart a full slow sync. 
This ensures that sync procedure is more robust in case of long periods of client inactivity.
A tiny refactor:
- Instead of bubbling up `ServerMiscommunication`, I'm mapping that kind exception on the `EventGatherer` level and translating it to `SyncEventOrClientNotFound` failure. This reduces the amount of places that are actively checking for HTTP status codes in the domain …
=> fix(sync): recover from 404 when fetching pending events [WPB-267]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/RetryFailedMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/RetryFailedMessageUseCaseTest.kt
----
----
Given a `FAILED_REMOTELY`  messages status, are not retriable as of now.
Add support to `FAILED_REMOTELY` to `RetryFailedMessageUseCase` so we can make use of it, and resend messages when they fail and the BE later comes back alive.
----
----
----
=> fix: add failed remotely to supported RetryFailedMessageUseCase (WPB-4457)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConversationRepositoryArrangement.kt
----
----
We need to resolve the active one-on-one conversation after [certain events](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/811958286/Use+case+Migration+of+1+1+conversation+Proteus+to+MLS+migration#Periodically-evaluate-what-protocol-to-use-for-1%3A1-conversation), one these events is after receiving a welcome message for a 1-1 conversation.
----
----
----
=> feat: resolve one-on-one conversations when receiving a welcome message

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/UserRepositoryArrangement.kt
----
----
We need to resolve the active one-on-one conversation after [certain events](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/811958286/Use+case+Migration+of+1+1+conversation+Proteus+to+MLS+migration#Periodically-evaluate-what-protocol-to-use-for-1%3A1-conversation), one these events is after a connection is accepted.
----
----
----
=> feat: resolve one-on-on conversation when the connection is accepted

network/src/commonMain/kotlin/com/wire/kalium/network/BackendMetaDataUtil.kt
----
----
We are approaching finalization of v4 api, meaning when backend mark v4 as supported we can merge this PR.
As default in prod builds, will be used v4 api and for dev builds v5.
We are just reusing and configuring accordingly the api versioning mechanism of Kalium.
The max supported version should be 4, here.
- https://staging-nginz-https.zinfra.io/api-version
- https://nginz-https.anta.wire.link/api-version
----
----
----
=> feat: bump v4 to supported and remove it from development versions (WPB-4352)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventGathererTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/EventRepositoryArrangement.kt
----
----
- When attempting to fetch the oldest possible event from the api, some issue prevents us from moving on. See [WPB-4442](https://wearezeta.atlassian.net/browse/WPB-4442).
- We leave open a time gap between registering client and performing slow-sync until we first fetch the last notification from the backend. Which can lead to some events being lost.
1. Move the responsibility of fetching the last notification from remote outside of the repository, and into slow sync. That now fetches and saves the most recent event IDs after successful workflow if there's no previously processed event ID.
This follows more closely the [general sync documentation](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/15566871/Incremental+synchron …
=> fix(notifications): use last event instead of oldest when recoverying from 404 [WPB-267]

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/ErrorResponse.kt
----
----
Discovered in 06.09, playtest. Currently, the connection request endpoint does not respond with unreachable field, so there could be cases when unreachable could not be determined.
Wrong behavior, as we need this exception to operate on connection request failure, ie: send, ignore, cancel.
Mark the field as optional.
----
----
----
=> fix: offline connection request actions crash when unreachable

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/AcceptConnectionRequestUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/ConnectionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/MLSOneOnOneConversationResolver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneMigrator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneResolver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/connection/AcceptConnectionRequestUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/mls/OneOnOneResolverArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConnectionRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConversationRepositoryArrangement.kt
----
----
We need to resolve the active one-on-one conversation after [certain events](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/811958286/Use+case+Migration+of+1+1+conversation+Proteus+to+MLS+migration#Periodically-evaluate-what-protocol-to-use-for-1%3A1-conversation), one these events is after a connection is accepted.
This is a follow up on https://github.com/wireapp/kalium/pull/2034 since the client which accepts the connection request won't get any event via the web socket, it instead gets the same information in the response of changing the connection status.
----
----
---- …
=> feat: resolve active 1-1 after accepting a connection request

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/di/UserStorageProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/util/CommonUtils.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/ConcurrentMutableMapTest.kt
----
----
app stuck on setting up wire after creation an account
the function inside the unti `computeIfAbsent` is not being called for a tricky reason 
ConcurrentMutableMap inherent from MutableMap and in java HashMaps already have a `computeIfAbsent` and in runtime the one form parent is called ignoring the extension function
this can be confirmed by the app still compiling if I simply delete the extension function we added and kipping everything else as it is
solution: rename it to something else
i also noticed that the calling manager function `getCallManagerForClient` is not thread safe, so I fixed this as well. 
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works …
=> fix: app stuck on setting up wire after account creation

gradle/libs.versions.toml, monkeys/build.gradle.kts, monkeys/example.json, monkeys/src/main/kotlin/com/wire/kalium/monkeys/ActionScheduler.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MetricsCollector.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/Monkey.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/MonkeyConversation.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/ConversationPool.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/MonkeyPool.kt
----
Exposes metrics in prometheus format at runtime on the port 9090. With that, tests can be monitored at runtime about it's state and performance. Now there'll always be a log file for the application and it was split from the kalium log. A custom log file can be specified, otherwise it will be `$CWD/monkeys.log`
----
=> feat(monkeys): Add and expose metrics of the text execution [WPB-4445]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt
----
----
A new edge case was discovered, and we need to handle when adding members from an online backend A and the conversation already has members of an offline backend, then we need to fail and show the system message.
Fail and persist system message in case of unreachable backend informed and not from users in request.
This case was introduced, but valid, when BE started performing NFCG checks on current members.
----
----
----
=> fix: adding participants offline + nfcg new edge case (WPB-4648)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/ProteusClientProvider.kt
----
----
Proteus Cryptobox migration to Proteus CoreCrypto fails (doesn't happen)
The path were we are looking for the cryptobox files are wrong (it includes the CC keystore file)
Remove keystore suffix on path.
----
----
----
=> fix: looking for cryptobox files to migrate at wrong location WPB-4658

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/Asset.kt
----
----
1. atm when we send images the use case will try to resize the image and it will fail and crash when it is an HEIC image
2. HEIC images are not rendered deu to internal coil error 
```
2023-09-13 13:16:27.213 31783-31828 HeifDecoderImpl         com.wire.android.internal.debug      E  getSize: not supported!
2023-09-13 13:16:27.224 31783-31828 HeifDecoderImpl         com.wire.android.internal.debug      E  getSize: not supported!
2023-09-13 13:16:27.225 31783-31828 HeifDecoderImpl         com.wire.android.internal.debug      E  getSize: not supported!
2023-09-13 13:16:27.248 31783-31828 HeifDecoderImpl         com.wire.android.internal.debug      E  getSize: not supported!
2023-09-13 13:16:27.257 31783-31828 HeifDecoderImpl …
```
=> fix: send HEIC images as normal files

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/web/WebMappers.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationAccessUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/migrations/57.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationViewEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/TableMapper.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/DatabaseImporterTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/UserDatabaseDataGenerator.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationMetaDataDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/ConversationStubs.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/TestStubs.kt
----
----
We were retrieving `otr_archived` and `otr_archived_ref` from the API but not persisting in the database.
Add `otr_archived` and `otr_archived_ref` to conversation table when getting from API.
Currently the only way to test is:
- Fresh install/login
- check from App Inspection that you have both fields in the `Conversation` table and if you have any archived conversation, it should be represented as such (1 = true, 0 = false)
=> chore: add archived field to conversations table (WPB-4471)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCaseTest.kt
----
----
While using `ScheduleNewAssetMessageUseCase` to upload assets and the backend has the federator down (technically online but not reachable to/from by other backends) the asset is uploaded but sending the message fails not reflecting this state in the database.
No button to retry is visible, and the asset message shows as pending.
Update the status of the message when we can't send the message with our `MessageSendFailureHandler` component, so can be correctly updated to `FAILED`  accordingly.
----
----
----
=> fix: message status not updated while using the fire and forget asset mechanism (WPB-4519)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ProtocolUpdateEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigratorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ProtocolUpdateEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/SystemMessageInserterArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConversationRepositoryArrangement.kt
----
----
After someone else has migrated a conversation proteus to `mls` messages fail to decrypt. 
When a conversation is migrated to mls this will result in a `conversation.protocol` update event informing everyone that the conversation is now using a different protocol. We were correctly processing this event and updating the protocol field of the conversation but we didn't fetch & persist the group ID which a conversation gets assign when migrates to `mixed` or `mls`.
On processing an incoming message in the migrated conversation we would fail to lookup the groupID which is necessary in order to decrypt the message, instead the whole operation fails and we present it as a decryption error to the user.
Fetch group ID in addition to …
=> fix: fetch  group id on protocol change event WPB-4336

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
----
----
`GlobalCallManager.getCallManagerForClient` is not thread safe, this can cause a case where multiple instances of AVS being created 
use `computeIfAbsent` to fix the issue
----
----
----
=> fix: getCallManagerForClient is not thread safe

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/RenameConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/guestroomlink/GenerateGuestRoomLinkUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneResolver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneResolverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FederationEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/CodeDeletedHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/CodeUpdateHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/mls/OneOnOneResolverArrangement.kt
----
----
Clients will attempt to establish a MLS 1-1 when a connection request is accepted. If more than one client is "online"
when a connection request is accepted this will result in a race to establish the MLS group, which only one client can win. This is wasteful because the clients who loose the race will also consume key packages but they will be discarded when they realise they have lost the race.
1. Distinguish between live events (Websocket) & catchup events (`GET /notifications`)
2. Add a small delay (3s) before attempting to establish the MLS 1-1 upon receiving a live connection accepted event.
----
----
----
1. …
=> feat: avoid race condition when establishing mls 1-1

cryptography/src/appleMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/MLSClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/DecryptedMessageBundleMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMappers.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinSubconversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageFailureHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageUnpacker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinSubconversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageUnpackerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt
----
----
I'm re-opening https://github.com/wireapp/kalium/pull/1958 because it seems to have gotten lost in a rebase.
After reviewing it again I've changed my approach.
1. Handle out order buffered messages when decrypting a message.2
2. Ignore CC's buffered messages when merging commits, because it's much easier and nicer to avoid out order message by enforcing the order of operations in Kalium.
----
----
----
=> feat: handle out of order MLS messages

testservice/Jenkinsfile
----
----
Compiles the testservice with Java 17
=> fix: Compile testservice with Java 17

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/CoreCryptoExceptionMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneResolver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationListDetailsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/mls/MLSOneOnOneConversationResolverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneMigratorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversationDetails.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
----
----
During testing serval issues were identified:
1. Slow sync fails due to non-recoverable errors and is therefore stuck
2. Message migration for 1-1 conversations would sometimes fail with constraint failure on the primary key
3. When establishing 1-1 MLS groups we didn't add other self clients
4. When establishing an MLS group would sometime fail if the MLS group had already been created locally
----
----
----
=> fix: improve stability of MLS 1-1 conversations

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationStatusMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationArchivedStatusUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationMutedStatusUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationStatusMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationArchivedStatusUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandlerTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationEvent.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt
----
----
The `otr_archived` field was recently added on our Conversation DB schema, and also on the api conversation response when handling Conversation objects in general. Therefore the next logical step was to add the needed operations on the data and domain layers in order to manipulate and update this field in isolation.
- Added `isArchiving` and `archivedRef` fields to the `ConversationEvent` model object.
- Added the needed operations on the `ConversationRepository` class to update the archived field both locally and remotely.
- Added `MemberArchivedStatusChanged` event to listen to changes on the conversations via websocket.
- Added `UpdateConversationArchivedStatusUseCase`.
- Tests.
----
1. …
=> feat: add DB + use cases for archived related operations [WPB-4427]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/ProteusClientProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/AnswerCallUseCase.kt
----
----
Some operations are detected to be run on main
Run them om worker thread
----
----
----
=> chore: run some operations on worker thread

buildSrc/src/main/kotlin/Android.kt
----
----
Upgrade target API to 34.
Needed to use compose 1.5.1 [#2248](https://github.com/wireapp/wire-android-reloaded/pull/2248)
----
----
----
=> chore: upgrade to API 34

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt
----
----
The user is "stuck in connecting" after another user was added and removed from the team while he/she was offline.
The app is stuck, because, while being offline, the other user was added and removed from the team we are in, so when we are back online, we receive `team.memberjoin`, `user.update` and only then `team.memberleave`. At the time we handle first one, the user is no longer in the team, so we get `404` when fetching user data and this user is not added to our local db. We ignore errors for team-specific events so it moves to handling the next one, which is `user.update` and again - we can’t handle it because we can’t update the user that’s not in our local db, but this time it results in a sync failure. `lastProcessedEventId` …
=> fix: sync failing when trying to update unknown user [WPB-4805]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/publicuser/search/SearchKnownUsersUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchKnownUserUseCaseTest.kt
----
----
When searching for users, if the domain is present, or in detail "@" present, we were not getting users from DB, considering this user as a not connected (having side effects like send a connection request again) This was caused by considering "@" as part of the search term.
Sanitize correctly the search term, so contacts are retrieved correctly if in DB.
----
----
----
=> fix: search users not filtering correctly users connected when domain present (WPB-4793)

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreLogger.kt
----
----
RC copy of:  https://github.com/wireapp/kalium/pull/2030
Network logs are missing
Network logger activation is missing for CoreLogger.
Add it back.
----
----
----
=> fix: network logging not getting enabled

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt
----
----
Logs are missing when the processing of a new client event happens
Add logs for success and failure
----
=> chore: add logs for new client event

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/notification/LocalNotification.kt
----
----
This PR only adds `LocalNotificationMessage.SelfDeleteKnock` and its mapping needed for AR PR : https://github.com/wireapp/wire-android-reloaded/pull/2269
=> fix: add LocalNotification SelfDeleteKnock (WPB-3175)

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/CoreCryptoExceptionMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageFailureHandler.kt
----
----
When decrypting a message targeting a future epoch CC will buffer the message until the commit arrives. When this happens CC will throw a `BufferedFutureMessage` error which we should ignore.
----
----
----
=> fix: map and ignore BufferedFutureMessage

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/PreKeyApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/prekey/PrekeyApiV0Test.kt
----
----
When uploading new prekeys, we're calling the wrong endpoint.
Fix the path to call the correct endpoint (PUT to `/client/{clientId}`).
This, by itself should not cause breaking issues, but if there's any prekey rollover, it could lead to `INVALID_SIGNATURE` errors.
On a side note, I've added logs to the prekey generation in
- #2092
----
----
=> fix(proteus): call correct endpoint for uploading prekeys

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/prekey/PreKeyRepository.kt
----
----
We don't have information abot prekey generation on Proteus.
Add log entries for generation of prekeys so we can debug what IDs are being generated and we can understand if there's a rollover (old prekeys being overwritten by new ones with the same IDs).
N/A
----
----
=> chore: proteus add log entries when generating prekeys

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/UserRepositoryArrangement.kt
----
----
When a user delete's a client it could be the last active proteus client which gets delete. We should therefore update supported protocol of the self user after deleting a client. And since we might now support MLS we should also resolve the active conversation for all 1-1 connections.
----
----
----
=> feat(mls): update supported protocols on client deletion

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveValidAccountsUseCase.kt
----
----
ObserveValidAccountsUseCase is being invoked on Main thread
Use IO instead
----
----
----
=> fix: DiskReadViolation related ObserveValidAccountsUseCase

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ProteusMessageUnpacker.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
DB query `selectAllConversationDetails` was fetching only `archived` conversations when passing a value of `includeArchived=true`.
This new modification should be able to fetch archived and non archived conversations when `includeArchived` flag is set to `true` now.
We should still add a separate method to fetch only the archived ones on the `ConversationDAO` class.
----
=> fix: fixed wrong query in `ConversationDAO` to fetch all conversations

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/TypingIndicatorRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/TypingIndicatorHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/TypingIndicatorRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/handler/TypingIndicatorHandlerTest.kt
----
----
We need to perform checks in order to clean the typing indicator.
- Skip self user events
- Take in consideration the user configuration about typing indicator to add to the cache
- Also added logs for the event handling.
- Added more tests.
----
----
----
=> feat: typing indicator receiver logs and flag check (WPB-4706)

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/newclient/NewClientDAOImpl.kt
----
----
When inserting and clearing new clients, these ops were being executed w/o specifying on which coroutine context, causing some crashes when being invoked by main thread.
Changing context to the queries context injected in the `NewClientsDAO` class
----
=> fix: clearing new clients was being executed on main thread

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/db_user/migrations/59.sqm
----
----
After upgrading from old version to a version with 1-1 mls support, resolving the active 1-1 conversation will fail.
After upgrading the newly introduced `supported_protocols` field on the self user and other users are null. This makes the 1-1 resolves to think there's no common protocol for your 1-1 contacts. This will hide the 1-1 conversations from the conversation list.
Assign proteus as the default supported protocol on user db migration.
----
----
----
=> fix: assign proteus as default supported protocol during db migration

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/migrations/63.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationViewEntity.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserConversationDAOIntegrationTest.kt
----
----
We're not propagating the new `activeOnOnOneConversationId` field in the `ConversationDetails`
Not yet implemented.
Add a new field to the `ConversationDetails` view, and bubble it up with the rest of the fields all the way to the Mapper.
----
----
=> chore(mls): propagate activeOneOnOneConversation on ConversationDetails [WPB-4705]

network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/SelfApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/SelfApiV5.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v5/SelfApiV5Test.kt
----
----
Supported protocols is only available since API v5
Move it to v5
----
----
----
=> fix: supported protocols is only available since API v5

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/MLSConfigHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCaseTest.kt
----
----
Slow sync fails when MLS is not supported / configured
This was failing at multiple levels:
1. We were attempting to update self supported protocols before we've persisted the protocols which the team supports. This resulted in a `StorageFailure.DataNotFound`
2. There's no guarantee that the team has configured its supported protocols
1. Persist supported protocol before attempting to update supported protocols
2. If MLS is not supported skip updating supported protocols completely.
3. if MLS is supported but supported protocols are not configured also skip updating supported protocols.
----
----
----
1. E.g. `feat(conversation-list): …
=> fix: skip updating supported protocols when mls is not supported

.github/workflows/label-pr.yml
----
----
srvaroa/labeler action fails
Some docker error
Our version is very old, lets update it.
----
----
----
=> chore: bump srvaroa/labeler to v1.6.3

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnConfigRequest.kt
----
----
Some users are stuck in `Waiting for Connection` or `Decrypting Messages` for ever.
If there's any error while we're fetching AVS Config, we don't ever let AVS know, and it will forever keep waiting for the configs.
Let AVS know that there has been an error. AVS will eventually (every 60s) ask us to try again.
> **Note**
> In the future we can make our own retry mechanism for calling config, so it can be more responsive than just "once every 60s".
Tested manually by changing the success code to also simulate an error and check that AVS asks us to try again.
----
---- …
=> fix(events): stuck on processing calling events

README.md, build.gradle.kts
----
----
Remove Github Packages repository since all dependencies are now on maven central.
----
----
----
=> chore: remove github packages repository WPB-5028

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt, tango-tests/src/integrationTest/kotlin/PocIntegrationTest.kt
----
----
Added a new query to fetch the mlsSelfConversationGroupId.
----
----
----
=> feat(conversation-mls): add getMLSSelfConversationGroupId to ConversationDAO

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/keypackage/KeyPackageApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/KeyPackageApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/KeyPackageApiV5.kt
----
----
Add a new api(on V5) to delete a batch key-packages.
----
----
----
=> feat(mls): add delete key-packages api (WPB-1003)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/UpdateAssetMessageDownloadStatusUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UnMuteCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/CleareNewClientsForUser.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/FetchSelfClientsFromRemoteUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/GetOrRegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/IsAllowedToRegisterMLSClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/NeedsToRegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ObserveClientDetailsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterMLSClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetConversationUnreadEventsCountUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/LeaveConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/LeaveSubconversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveArchivedUnreadConversationsCountUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/RemoveMemberFromConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/UpdateKeyingMaterialsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/rootDetection/CheckSystemIntegrityUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfDeletingMessages/PersistNewSelfDeletionTimerUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/DeregisterTokenUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/IsFileSharingEnabledUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/MarkSelfDeletionStatusAsNotifiedUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveFileSharingStatusUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsAndResolveOneOnOnesUseCase.kt
----
----
We have failing tests for use case visibility after introducing `Konsist` in: 
- https://github.com/wireapp/kalium/pull/2133
Use case implementations can be instantiated from the outside world.
Mark them as internal when possible or make their constructor internal to adhere to the rule.
Some tests will still fail, so I need to raise a part 2, or 3 after this.
- https://github.com/wireapp/kalium/pull/2133
Tests for the following checks, should NOT fail.
`useCaseImplementationsShouldBeInternalOrHaveInternalConstructor[jvm] - com.wire.kalium.logic.architecture.UseCaseRulesTest -`
----
----
---- …
=> chore: architectural fitness functions - use case implementation visibility pt1. (ACOL-123)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
Currently when the app needs to fetch multiple users details, it makes a single request with all userIds. When the list contains around 4000 items, the API returns 413 Content Too Large.
Make this request paginated.
----
----
----
=> fix: paginating fetch multiple users request [WPB-4999]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/NewGroupConversationSystemMessagesCreator.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/AcceptConnectionRequestUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/ConnectionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/NewGroupConversationSystemMessagesCreatorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/connection/AcceptConnectionRequestUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/NewGroupConversationSystemMessageCreatorArrangement.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageInsertExtension.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-2266" title="WPB-2266" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-2266</a>  Android Unverified user warning on connection request and in-chat
</td></table>
<br />
----
----
We need to provide a warning to a user on connection request and in-chat to warn them to beware of whom they trust or share sensitive information with on wire.
Not implemented.
- Add a warning for connection requests (sending and receiving) to/from an unverified user.
- Add an initial system message when creating, starting a conversation, so they are aware that there might be unverified users.
----
---- …
=> feat: new conversation started unverified warning system message (WPB-2266) 

logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/network/SessionManagerTest.kt
----
----
Tokens that are result of token-upgrading (_i.e._ associating a client ID with the tokens), are not being used right after they are acquired.
In the previous implementation, the `SessionManagerImpl` was not properly utilizing updated tokens causing session issues.
It was keeping a `session` in memory and using it. So when other entities would modify the `session` directly in storage, it would not be updated.
There was no reason to keep the `session` in memory, as it's something that is rarely used. And as long as the `SessionManager` is atomic in its operations, it won't race with itself.
The code has been updated to not retain the first session instance but fetch a new one each time, hence always using the newest token. Tests have …
=> fix: upgraded tokens not being used

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/adapter/SupportedProtocolSetAdapter.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/adapter/SupportedProtocolSetAdapterTest.kt
----
----
Exception during parsing of `SupportedProtocol`:
```
java.lang.IllegalArgumentException: No enum constant com.wire.kalium.persistence.dao.SupportedProtocolEntity.
```
We're not considering the possibility of empty string `""`
Return `emptySet()` when the string is empty. This means that the client has not set supported protocols for a user yet.
----
----
=> fix: failure to parse lack of supported protocols

cryptography/build.gradle.kts, gradle/libs.versions.toml, persistence/build.gradle.kts, persistence/src/androidInstrumentedTest/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsBuilderTest.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/util/JsonSerializer.kt
----
----
Cherry-pick of #2013
----
----
----
=> fix(cherry-pick): try catch shared pref creation on android 

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt
Now that fetching of users is paginated and errors in this step are properly propagated, we should perform sync again to cover affected users.
----
----
Now that fetching users is being paginated
- #2158 
Users in huge teams (1000+ users) can properly fetch all contacts during slow sync. But #2158 doesn't trigger slow sync again.
Bump the SlowSync Version, so Kalium will trigger it again after updating the app.
Also, move it to be private inside the class, as there's no reason to make it publicly available like it was before.
----
----
=> chore(sync): bump slow sync version (WPB-5057)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/UserDTO.kt
----
----
When user belongs to a huge team (over 2000 members), then all team members are not fetched and stored during the slow sync and because of that, when searching, the app can't filter out the team members from the public search list and doesn't know the connection status of them.
When handling public search results, extract team members from the result and persist them locally as contacts.
----
----
----
=> fix: persist searched team members [WPB-5262]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveE2EIRequiredUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ObserveE2EIRequiredUseCaseTest.kt
E2EI dialog is shown even when the MLS feature is disabled by feature flag.
It was developed when the MLS feature flag was not in the project yet.
in `ObserveE2EIRequiredUseCase` add checking the MLS feature flag.
=> fix(RC): Showing e2ei dialog when feature disabled (WPB-5263)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveE2EIRequiredUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ObserveE2EIRequiredUseCaseTest.kt
E2EI dialog is shown even when the MLS feature is disabled by feature flag.
It was developed when the MLS feature flag was not in the project yet.
in `ObserveE2EIRequiredUseCase` add checking the MLS feature flag.
=> fix: Showing E2EI dialog when feature disabled (WPB-5263)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt
----
----
Currently logout is executed in a new coroutine scoped to the `globalCoroutineScope` so calling logout just creates and executes this coroutine but does not wait until all required logout-related actions are completed. Because of that, it's possible that some other actions that should happen after the logout is completed are actually executed when logout is not yet done and for instance the app can get the info that the session is still valid.
Provide an optional parameter `waitUntilCompletes` - if true, then this suspend fun waits until all required actions are completed.
----
----
---- …
=> chore: add waitUntilCompletes option to LogoutUseCase

logic/src/jvmMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/di/PlatformUserStorageProperties.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/di/PlatformUserStorageProvider.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
----
----
Infinite Monkeys and other short-lived applications using Kalium can get sub-optimal performance when running multiple clients/accounts as Kalium relies on file-based persistence.
The user storage creation process is refactored to support both file-based and in-memory databases. This involves changes in the `PlatformUserStorageProvider`, `CoreLogic`, and `UserSessionScopeProviderImpl` classes. An optional flag is added to the `CoreLogic` constructor to indicate whether to use in-memory storage.
----
----
=> feat(jvm): Add support for in-memory user storage

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
----
----
After fresh login, if user already has some conversations with other team members, when opening other conversation member profile, the app shows “connect” button so the user appears as not connected, but this user is from the same team.
Update also connection status for team members.
According to the documentation for the `upsertTeamMembers` function: 
>This will update all columns, except [UserEntity.userType] 
so it looks like an oversight and it should also update connection status.
----
----
----
=> fix: persisting team members connection state (RC) [WPB-5338]

network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/jvmTest/kotlin/com/wire/kalium/ClientConnectionSpecsTest.kt, network/src/jvmTest/kotlin/com/wire/kalium/HttpClientConnectionSpecsTest.kt
----
----
We need to support a minimum stable version of TLS for the `HttpClient` and being able to test it.
Only default behavior configured as of now.
Configure at the `HttpClient` level the supported versions of TLS that the android client can use.
----
----
----
=> feat: configure supported min TLS versions (WPB-1810)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
Users in big teams or not in teams at all are not receiving profile updates of other users.
Big teams and non-team members do not propagate `user.update` events to all contacts.
This commit removes distinction between federated and non-federated users in UserRepository when getting known users. 
All users are now treated in the same manner when getting them from the database. This implies that their data will be refreshed from the API regardless of the user type.
Adjustments have been made to the UserRepositoryTest to reflect this change in behavior.
----
---- …
=> fix: update all users when getting their data [AR-5057]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandlerTest.kt
----
----
Currently, we're only checking if keypackages are running low every 24h. This could lead to keypackages getting exhausted before the next check.
Also check the count and upload new keypackages if needed on each mls-welcome event.
The result of the refilling action is logged.
----
----
=> feat(mls): refill key package on MLS-welcome events

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
Copy of [fix: persisting team members connection state (RC) [WPB-5338] #2191](https://github.com/wireapp/kalium/pull/2191)
----
----
After fresh login, if user already has some conversations with other team members, when opening other conversation member profile, the app shows “connect” button so the user appears as not connected, but this user is from the same team.
Update also connection status for team members.
----
----
----
[WPB-5338]: https://wearezeta.atlassian.net/browse/WPB-5338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> fix: persisting team members connection state (dev) [WPB-5338]

logic/src/androidInstrumentedTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryExtensionsTest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryExtensions.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/message/GetPaginatedFlowOfMessagesByConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetSearchedConversationMessagePositionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/message/GetSearchedConversationMessagePositionUseCaseTest.kt, persistence/src/androidInstrumentedTest/kotlin/com/wire/kalium/persistence/dao/message/MessageExtensionsTest.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/dao/message/KaliumOffsetQueryPagingSource.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/dao/message/MessageExtensions.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
----
----
There was no way directly from our pager to get the selected searched message position.
This PR aims to add a usecase / repository / DAO to retrieve the message position in DESC order to be used to scroll the user into the right selected message.
There is also the addition of `KaliumOffsetQueryPagingSource` which is an overriden method of `OffsetQueryPagingSource` but with an extra param: `initialOffset` instead of using the given offset provided by :`queryProvider` in order to properly navigate the pager.
AR PR will follow soon.
No way to test this now, only when AR PR will be created.
=> feat: count searched message position (WPB-4986)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/type/UserTypeMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/DomainUserTypeMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserEntityTypeMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/TeamsApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/TeamsApiV0.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt
----
----
The only place where the user type for team members was determined and stored was during the slow sync, but for large teams, members list is ignored, not fully fetched and not stored so we were losing this information. 
Fetch member permissions when searching and fetching users when slow syncing and opening profile so that we always store team members with proper user types.
----
----
----
=> fix(dev): persist proper team members user types [WPB-5343]

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/test_util/TestNetworkException.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/ErrorResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/NetworkErrorLabel.kt
----
----
Cherry-pick from https://github.com/wireapp/kalium/pull/2189
One of client servers returns 
```
ErrorResponse(code=400, message=no federator configured, label=federation-not-enabled, cause=null)
```
probably when user tries to fetch other user data with different domain
Because fetching users is during slow sync, when it returns error the entire slow sync is aborted and user is stuck on connecting
Handle this error and try to fetch again only those users which have the same domain as self user
=> fix: handle federation not enabled [WPB-5237]

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnNetworkQualityChanged.kt
----
----
In NetworkQuality callback userId is logged without being obfuscated
We missed that
Obfuscate it!
----
----
----
=> chore: obfuscate user id in calling logs

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
----
----
generic errors are missing the stack trace when logged 
overwrite the toString fun to include info about the stack trace leading to the generic error
----
----
---- …
=> refactor: add more info to generic core failure logs

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/AuthenticatedNetworkContainer.kt, network/src/commonMain/kotlin/com/wire/kalium/network/utils/CustomErrors.kt
----
----
SessionManager session not found error 
1. shared preferences write into memory first for speed (this can be changed, but there is no need to).
2. if any app crash happens right after login, the session will not be written into disk
3. Kaboom session not found. 
handle missing session by logging out the user in case of session not found
----
----
----
1. …
=> fix: SessionManager missing session error

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/AppLockConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/AppLockConfigHandlerTest.kt
----
----
On Client side, team app lock dialog is displayed when changing timeout from team console.
Wrong logic for setting `isStatusChanged` value
Use last saved value of `isStatusChanged`, if the status is the same as current
----
----
----
1. …
=> fix(applock): team app lock dialog displayed when changing timeout

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandlerTest.kt
----
----
New 1on1 conversations are not visible on conversation list until the user sends any message.
After some recent updates with implementing protocols migration, it's now necessary for the user's `active_one_on_one_conversation_id` field to match the 1on1 conversation id, otherwise it's not added to the list.
Resolving 1on1 conversations that executes protocol migration and results in filling in this field is executed when syncing conversations, creating a new one, accepting connection request or handling new connection, receiving MLS `conversation.mls-welcome` event, but has been missing for Proteus `conversation.create` event.
The conversation was appearing after the user sent a message because then it executes …
=> fix: new 1on1 conversation not visible on list [WPB-5551]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/AppLockConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/AppLockConfigHandlerTest.kt
----
----
cherrypick of #2232
----
----
----
=> fix(applock): team app lock dialog displayed when changing timeout (RC) - cherrypick

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationResponse.kt
----
----
New team 1on1 conversations are still not visible on conversation list.
When handling new conversation event, if a conversation is a team 1on1, the app can receive a false `GROUP` type for such conversation instead of `ONE_TO_ONE`. We handle that case when persisting conversation already but shouldn't use `type` field directly anywhere because of that.
Use mapping function from `ConversationMapper` to get the proper type when handling new conversation event.
user A and B have no conversation
user A and B use Proteus protocol and at least one does not support MLS protocol (so that MLS can't be used for their 1on1 conversation)
**user A and B are in the same team** (this assertion was missing in the previous fix)
user B finds user A, …
=> fix: wrong conversation type when resolving 1on1 after receiving new conversation event [WPB-5551]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/screenshotCensoring/ObserveScreenshotCensoringConfigUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/screeenshotCensoring/ObserveScreenshotCensoringConfigUseCaseTest.kt
----
----
first Screenshot taken in the app is sometimes black
before the sync of feature config is complete, the default value for screen censoring is true so now we switch it to false and it is fixed
----
----
----
1. E.g. …
=> fix: first Screenshot taken in the app is sometimes black

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
to be able to stop maintaining a full list of team members, we need to mark users as deleted when the server response with 404
mark users as deleted when server response with 404
----
----
----
=> feat: mark user as deleted when server response with 404

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/IsAppLockEditableUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/IsAppLockEditableUseCaseTest.kt
----
----
When private users started the app there was no value from `isTeamAppLockEnabled` and was always returning `DataNotFound` thus not enabling the user to toggle `AppLock` in settings
Invert the value provided from the `fold` in the usecase
Testing will be available in AR PR.
=> fix: enable editable app lock toggle (WPB-5610)

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
I was not assigning properly last commit message in automatic cherry-pick
=> fix: typo variable assign in cherry-pick

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/LegalHoldStatusMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncStatus.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/legalhold/FetchLegalHoldForSelfUserFromRemoteUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/TeamScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/legalhold/FetchLegalHoldForSelfUserFromRemoteUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestTeam.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestUser.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorkerTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/TeamsApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/LegalHoldStatusResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/UserDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/TeamsApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/teams/TeamsApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/model/ListUsersResponseJson.kt, tango-tests/src/integrationTest/kotlin/util/ListUsersResponseJson.kt
----
----
When the user has pending legal hold request and logs in on a freshly installed app, the app doesn't receive the legal hold request event.
Make fetching legal hold status to be a step of the slow sync so that the app always knows the proper status of the legal hold.
On a freshly installed app, log in using the account which has a pending legal hold request.
----
----
----
=> feat: fetch legal hold status during the slow sync [WPB-5655]

logic/src/jvmMain/kotlin/com/wire/kalium/logic/di/PlatformUserStorageProvider.kt, persistence-test/src/jvmMain/kotlin/com/wire/kalium/persistence/TestDatabaseManipulation.kt, persistence/src/jsMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/InMemoryDatabaseCache.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt, persistence/src/jvmTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
----
----
When using `inMemoryStorage` for JVM, it's impossible to logout and then login again, as a new instance will be created from scratch, even when using `SELF_SOFT_LOGOUT` LogoutReason.
Introduced the `InMemoryDatabaseCache` to hold a database across logins/logouts without losing the data.
If `nuke` is called, this cache will be cleared too. Which should only happen when there's a hard logout.
Make sure we also clear the cache when running unit tests.
----
----
=> fix(jvm): support logout and login when using in-memory storage

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
…59)"
This reverts commit 66585d1b11d6c7e5d9993e1329d345a60d1e9c71.
----
----
after discussing this feature with int the team it is not required, and the use case is updated 
revert the change
----
----
---- …
=> revert: mark user as deleted when server response with 404 (#2259)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/NotifyConversationIsOpenUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/NotifyConversationIsOpenUseCaseTest.kt
----
----
We should have a fallback / safety net for 1:1 migrations.
Expose a way to notify Kalium that a conversation is being displayed to the user.
This way, Kalium can do some sanity checks.
When calling `NotifyConversationIsOpenUseCase`, Kalium can check if the conversation is 1:1 and if its protocol is up-to-date.
----
----
=> feat(mls): reevaluate protocol on demand [WPB-5049]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/DebugScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendFailureHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/prekey/MessageSendFailureHandlerTest.kt
----
----
error loop when sending a message in an out of sync conversation
update conversation members when we get out of sync error
----
----
----
=> feat: update out of sync conversation info when sending messages fails

logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt
----
----
cert pinning failing for GET:/api-version only
there is a flag to ignore ssl cert in unbound network client for e2ei and that flag should be true only in debug mode and it was not, it should not have effected any users in prod 
----
----
----
=> fix: cert pinning failing for GET:/api-version

network/src/androidMain/kotlin/com/wire/kalium/network/OkhttpClientFactory.kt, network/src/androidMain/kotlin/com/wire/kalium/network/OkhttpClientfactory.kt, network/src/androidUnitTest/kotlin/com/wire/kalium/api/tools/HttpClientConnectionSpecsTest.kt, network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/jvmMain/kotlin/com/wire/kalium/network/OkhttpClientFactory.kt, network/src/jvmMain/kotlin/com/wire/kalium/network/OkhttpClientfactory.kt
----
----
test services are limited on the number of web socket connection that can be created
it was solved temporary by reverting the commit only for the test service branch, but now this is a permanent fix, that refactor the way Okhttp client are created bu using a Singleton in Android and createing a new one each time on jvm
----
----
----
1. …
=> refactor: create a new okhttp client for each user on jvm target

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/E2EIConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/featureConfigs/FeatureConfigResponse.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
in `E2EIConfig` API response we were expecting that field `verificationExpiration` is timestamp of the end of the grace period in nano-seconds. In fact it's amount of seconds that left till the end of grace period (stating from the moment when we receive that info). So needed to update `E2EIConfigHandler`
It wasn't documented well.
Update `E2EIConfigHandler` and tests.
=> fix: E2EI required: grace period in seconds (WPB-5771)

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/legalhold/LegalHoldHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/handler/legalhold/LegalHoldHandlerTest.kt
----
----
When the user isn’t under legal hold, he gets the “no longer under legal hold” dialog message right after logging in.
Status whether the user has been notified about the legal hold change is updated every time legal hold event is handled, so during the slow sync, even if there hasn't been any change to the legal hold status for the user.
Update this flag only when legal hold status changes for the current user.
Login with account that isn't under legal hold and see if the dialog informing about legal hold disabled is shown right after logging in.
----
----
---- …
=> fix: legal hold disabled info is shown right after logging in [W-4870]

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/member/MemberDAO.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/MemberDAOTest.kt
When some other user adds a new client AND conversation with that user was already "proteus-verified", then 3 system messages are added into that conversation: 1. conversation degraded; 2. conversation verified; 3. conversation degraded.
There should be only 1 message "Conversation degraded", as a new client is not verified.
`MessageSendFailureHandlerImpl` which is called in case when sending message is not prepared for some client (for that new client in our case), calls also `ConversationRepository.fetchConversation()` which calls `MemberDAO.updateFullMemberList`. This `updateFullMemberList` removes all the members from the conversation and adds only the members that should be there. 
But at the moment when all the members are removed from the conversation DB-trigger runs and it …
=> fix: Duplicated system message about degraded conversation (WPB-5878)

logic/src/commonMain/kotlin/com/wire/kalium/logic/util/MessageContentEncoder.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/MessageContentEncoderTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageReplyTest.kt, util/src/commonMain/kotlin/com.wire.kalium.util/long/toByteArray.kt
----
----
Location replies not displayed with data.
Hash encoded verification for location messages, not implemented.
Implement according to [docs](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/157221847/Use+case+Generate+the+hash+of+a+quote#Location-message).
----
----
----
=> fix: location replies not displayed (WPB-5951)

persistence/src/commonMain/db_user/com/wire/kalium/persistence/DumpContent.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/ImportContent.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseImporter.kt
----
----
Location messages are not included in backups currently.
Not implemented.
Implement export and import necessary queries.
----
----
----
=> feat: location messages backup (WPB-5826)

cryptography/src/appleMain/kotlin/com/wire/kalium/cryptography/E2EIClientImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/E2EIClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/E2EIClient.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/E2EIClientImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/E2EIClientProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/E2EIRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/EnrollE2EIUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/EnrollE2EICertificateUseCaseTest.kt
----
----
With oAuth refresh token, we can get a new id token without forcing the user to login again on the idp, in this PR all the requirements on kalium are considered.
Needs to be merged with AR
----
----
----
=> feat(e2ei): use refresh token for IDP authorisation (WPB-5880)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/UpdateAssetMessageDownloadStatusUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/IsEligibleToStartCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/GetConversationUnreadEventsCountUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/MembersToMentionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationDetailsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationInteractionAvailabilityUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/SendTypingEventUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/DeleteMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetSearchedConversationMessagePositionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendKnockUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ToggleReactionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfDeletingMessages/ObserveSelfDeletionTimerSettingsForConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfDeletingMessages/PersistNewSelfDeletionTimerUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/GetSelfUserUseCase.kt
----
----
Many operations (use cases) are being executed on the main thread
Blocking clients can lead to ANR, i.e. conversation screen makes use of all the use cases changed in this PR.
Move operations to `io` thread when corresponded.
Current suite should cover and be green.
----
----
----
=> fix: offload from main thread usecase operations used in conversation screen (WPB-5964)

monkeys/src/main/db_monkeys/com/wire/kalium/monkeys/db/ExecutionEvent.sq, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/ReplayApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/Monkey.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/model/EventData.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/MonkeyPool.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/storage/PostgresStorage.kt
----
----
Adds support for storing which client was responsible for executing the event and in replay it will split the events per client.
Also removing the kalium cache folder for the tests. This is helpful if we reuse the same users for further executions.
----
=> feat(monkeys): Add support for multi-clients in the replay mode [WPB-5764]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationInteractionAvailabilityUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationInteractionAvailabilityUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/UserRepositoryArrangement.kt
----
----
During MLS migration, it is possible that some users have only access to MLS or Proteus protocol, and the conversation/other user, is using another protocol.
We need to be able to identify this on the UI-level and show something to the user.
Add a new possible result for `InteractionAvailability`, called `UNSUPPORTED_PROTOCOL`, that indicates this scenario.
----
----
=> feat(mls): handle unsupported protocol for conversation [WPB-5047]

logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/EnrollE2EICertificateUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/PersistMigratedMessagesUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendEditTextMessageUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendKnockUserCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/EitherAssertions.kt
----
----
When asserting either results, `either.shouldSucceed()` and `either.shouldFail()` do not have contracts making easy to consume their wrapped result.
Instead, we need to use `assertTrue(result is Either.Left)` which doesn't provide a good exception message, or `assertIs<Either<R>>(result)` which is verbose AF.
Rely on Kotlin contracts to make the best of both worlds.
Now `shouldSucceed` and `shouldFail` will tell the compiler what it needs to know and we can consume their types without further casting.
I found some usages in the code and replaced them
----
---- …
=> test: improve contracts when asserting either result

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendLocationUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendLocationUseCaseTest.kt
----
----
We didn't have support for sending location messages.
Not implemented.
Implement the sending location messages (supporting self deleting as well) 
PR incoming on Android.
- https://github.com/wireapp/wire-android/pull/2582
----
----
----
=> feat: sending location messages (WPB-1732)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/GetUserE2EIAllCertificatesUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/GetUserE2eiAllCertificateStatusesUseCaseTest.kt
No any UseCase for getting all the E2EI certs for all users client in one "request" (only one-by-one by ClientId, which is not cool).
Would be useful for UserProfile screen, where we display the list of devices and need to show E2EI statuses for each device.
Wasn't implemented
Added `GetUserE2eiCertificatesUseCase` for that, where we can get them by `UserId` and tests for that.
=> feat: UseCase for getting all users E2EI certificates

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationArchivedStatusUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationArchivedStatusUseCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Notification.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageNotificationsTest.kt
----
----
When a conversation is archived before the user logs in on android, he receives notification in this conversation (both for normal and for self deleting messages)
We were not verifying archived status when getting messages for notifications
- Add `Convesation.archived` verification in getting messages for notification
- Remove manual update of muted status when archiving
- have 2 clients available, web A  and android B
- archive any conversation C on client A
- login to the app, client B
- see that the conversation is archived (but does not have a mute icon)
- Go back to conversation list
- receive messages in conversation C
- take a look at the notification center
- Conversation should not be muted and user should not receive …
=> fix: archived conversation notifications before login (WPB-6127)

gradle/wrapper/gradle-wrapper.properties
----
----
Upgrade the Gradle Wrapper to 8.5
- Lets us upgrade the Android Gradle Plugin to newer versions
- Allows us to try out JDK 21, which should speed things up during build time, since [Gradle 8.5](https://docs.gradle.org/8.5/release-notes.html).
- Has better Kotlin DSL support (in fact, Kotlin DSL is the default since Gradle 8.2).
- Decreased memory usage as of [Gradle 8.3](https://docs.gradle.org/8.3/release-notes.html).
- Tons of bug fixes
_It Works On My Machine™_
----
----
=> chore(deps): upgrade Gradle to 8.5

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/FederatedIdMapperImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/search/FederatedSearchParser.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/id/FederatedIdMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/search/FederatedSearchParserTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/SessionRepositoryArrangement.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/daokaliumdb/AccountsDAO.kt
----
----
sessionRepo.isFederated is not main safe
make it main safe
----
----
----
=> fix: insure that isFederated function will never run on the main thread

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
the gh action bot is every where in git blame
preserve Original Author in Cherry-Picked Commits
----
----
----
=> ci: preserve Original Author in Cherry-Picked Commits

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
`NullPointerException ` log is spammed when doing user search even on non MLS enabled enviroments
redundant `!!` in storage request for getting MLSGroupId. It's not needed there as `wrapStorageRequest` already handles the case when the result is `null` and returns `Either.Left(StorageFailure.DataNotFound)`.
remove `!!`
=> fix: MLS log spam with NPE [WPB-6222]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/composite/SendButtonActionConfirmationMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/composite/SendButtonActionConfirmationMessageTest.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/SendButtonActionConfirmationRequest.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/SendButtonActionRequest.kt
----
----
This PR allows kalium to send confirmations for button actions. Button actions are messages that are send after a user clicked on a poll message button. These messages need a confirmation or their show in the UI as not confirmed and not selected. A button action confirmation is send to the initial sender of the button action. Unfortunately we currently do not have this message in the database and therefor cannot get the user id of the button action sender out of the database. Instead we need to rely on the userId that is provided to the use case. The domain of this user will be set to the domain of the conversation for now because the testservice API was implemented before federation.
----
----
----
1. …
=> feat: use case to send button action confirmations (WPB-2633)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MLSMessageCreator.kt
Self-deleting messages in MLS conversations were sent as regular message. 
`MLSMessageCreatorImpl` ignores a message timer, guess it happens cause there were no SelfDeleting messages yet, when the creator was developed. 
update `MLSMessageCreatorImpl` to use message timer.
=> fix: SelfDeleting message in MLS conversation [WPB-5301]

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/ObserveCertificateRevocationForSelfClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/e2ei/MarkNotifyForRevokedCertificateAsNotifiedUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/e2ei/ObserveShouldNotifyForRevokedCertificateUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/e2ei/MarkNotifyForRevokedCertificateAsNotifiedUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/e2ei/ObserveShouldNotifyForRevokedCertificateUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/unread/UserConfigDAO.kt
----
----
Cherry pick from the original PR:
https://github.com/wireapp/kalium/pull/2384
----
----
----
=> feat: Observe self client certificate revocation (WPB-6145) - cherrypick

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FederationEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FederationEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConnectionRepositoryArrangement.kt
----
----
After sending a request and cancelling, the button still shows "cancel request" and clicking again just returns the info that cancelling is not possible, so it stays in this state forever and user cannot send a request.
After cancelling, the connection row in DB is removed but user's field `connection_status` is not updated - it's still `SENT`.
Cancelling a request is the only state change when the user's `connection_status` isn't updated.
Update user's `connection_status` field as well when cancelling a connection request.
Send a connection request and then cancel it.
https://github.com/wireapp/kalium/assets/30429749/e05cb47f-4165-456f-9366-9c6388661e6c
https://github.com/wireapp/kalium/assets/30429749/ee3f1ef2-405b-448e-9336-a2ce21339 …
=> fix: update user connection status after cancelling request

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/E2EIRepository.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/architecture/LayerAccessRulesTest.kt
----
----
Architecture tests are ignored
Circular dependencies, and other code smells, are not being caught.
Renable, and supress (for now) failed tests. 
Tickets are going to be created as tech debt to be solved, at least for develop as a last resort.
----
----
- [] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
=> chore: bring back architecture test after being ignored

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
----
----
When changing user profile avatar it wasn't being reflected in other screens in the app
the query `updateUser` was a transaction returning `SELECT changes()`, thus sqldelight not emitting the update on the table.
Remove transaction and `SELECT changes()` from the query and add `transactionWithResult` on the DAOImpl to properly reflect the changes upwards when needed.
- Use this branch on AR
- Open Profile Screen and change profile avatar
- go back and check that profile avatar change is reflected across other screens
@vitorhugods opened an issue on SQLDelight : https://github.com/cashapp/sqldelight/issues/5001
=> fix: changing profile avatar doesn't reflect update (WPB-5494)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/Asset.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetMimeTypeTest.kt
----
----
When replying to an audio message with format `audio/x-m4a`, as we didn't know about this mimeType we were displaying audio message on reply as a `GENERIC_FILE`
Add `audio/x-m4a` as known audio messages mimeType and add tests to it.
=> fix: icon on reply audio message (WPB-1863)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/GetUpdatedSelfTeamUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/team/GetUpdatedSelfTeamUseCaseTest.kt
----
----
Team changes while fetching was not reflected in DB.
We were not updating the info because of incorrect query call.
Call the existing update team query to reflect the changes from remote into local db.
----
----
=> fix: team event manual sync was not being reflected in db (WPB-5516)

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/ShouldRemoteMuteChecker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/ShouldRemoteMuteCheckerTest.kt
----
----
We need to check if the remote mute event is coming from a conversation admin. If not, then we should not apply the remote mute on the call
----
----
----
=> fix(calling): check user role before applying remote mute

monkeys/README.md, monkeys/docker/Dockerfile, monkeys/docker/docker-compose.yml
----
----
This improves the execution of the monkeys inside docker. Allowing to run the app with external monkeys in a docker network.
----
=> feat(monkeys): Improve docker to allow running external monkeys in it [WPB-6471]

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessingHistory.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessingHistoryTest.kt
----
----
When the device goes offline for an extended amount of time, the list of pending events will grow, which makes the current `PendingEventBuffer` slow when calling `contains`, as it is backed by an `ArrayList`.
Rename `PendingEventBuffer` to `EventProcessingHistory` so it's easier to understand its purpose, as it doesn't quite work as a _buffer_, but rather a "look back into history" thing.
Just replace the list with a `hashSet` for constant-time lookup.
- Add a `lastAddedEvent` for internal usage, in order to keep `clearHistoryIfLastEventEquals` working.
Contains changes of the PR:
- #2459
Although we're mostly expecting to have up to a handful of thousand events in "normal" scenarios. Having 10k or so events isn't that hard in bigger …
=> fix: improve pending events check performance

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/IsE2EIEnabledUseCase.kt
----
----
When E2EI is disabled on the user's team, all the info related to e2ei must be hidden.
Wasn't covered.
----
----
----
=> fix(e2ei): remove E2EI shield and buttons if it's disabled on your team (WPB-6520)

.github/workflows/gradle-android-instrumented-tests.yml, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/Participant.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/ParticipantsOrderByName.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
App could crash when user's name is null. 
It may happens when there is no conversation in common between some call members.
In kalium side if there is no user yet available we just return a null as value and it's up to UI to display a default value in this case.
----
----
---- …
=> fix: crash when answering a call (WPB-6183)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
----
----
In order to be able to use `MembersHavingLegalHoldClientUseCase` in the app, it cannot be private in `UserSessionScope`. Using this use case is more efficient than making a call for each user on a list one by one.
----
----
----
=> feat: make MembersHavingLegalHoldClientUseCase public

network/src/androidMain/kotlin/com/wire/kalium/network/OkhttpClientFactory.kt, network/src/androidUnitTest/kotlin/com/wire/kalium/api/tools/HttpClientConnectionSpecsTest.kt, network/src/appleMain/kotlin/com/wire/kalium/network/defaultHttpEngine.kt, network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/commonMain/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unbound/acme/ACMEApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/UnboundNetworkContainer.kt, network/src/commonTest/kotlin/com/wire/kalium/api/common/ACMEApiTest.kt, network/src/jvmMain/kotlin/com/wire/kalium/network/OkhttpClientFactory.kt, network/src/jvmTest/kotlin/com/wire/kalium/HttpClientConnectionSpecsTest.kt
=> feat: allow http calls when checking Certificate Revocation List (WPB-6493) - cherrypick

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/SyncSelfTeamUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/team/SyncSelfTeamUseCaseTest.kt
----
----
we need to fetch the first 200 team members on android
add configuration to the number of team members fetched during slow sync
----
----
----
=> feat: allow configuration to the number of team members fetched during slow sync

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/GetE2EICertificateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveE2EIRequiredUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ObserveE2EIRequiredUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/GetE2eiCertificateUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
The are 2 issues: 
1. After login and enrolling the E2EI certificate user still see the "Enroll E2EI" dialog 
2. Grace period for enrolling E2EI certificate resets on every app opening. 
1. When user logs in, CC returns an error on getMLSClient, app interprets it as "user doesn't have certificate" and asks user to get it.
2. `E2EIConfigHandler` is called in Syncing and on every sync grace period (which app gets as a period, not exact date) resets
1. 
- update `ObserveE2EIRequiredUseCase` so the error while getting the current client certificate means "Something went wrong, don't show the dialog yet"
- update `MLSConversationRepository.getClientIdentity` to return `null` if client has no certificate (not an error).
2. 
Update `UserConfigStorage.setE2EINotificationTime` -> …
=> fix: release: Do not show EnrollE2EI dialog after login (WPB-6364)

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
E2EI settings data is not cleared on user logout
Wasn't implemented
Implement in
=> fix: release: Remove e2ei settings data on login (WPB-6495)

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/E2EISettings.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/E2EIRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/E2EIConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/e2ei/E2EIRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/featureConfigs/FeatureConfigResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unbound/acme/ACMEApi.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
----
----
it can happen that e2ei endpoint is called with empty URL when it is disabled
small refactor to make sure it cann't be called when it is not enabled
----
----
---- …
=> fix: e2ei endpoint is called even when the feature is disabled

.github/technolinator.yml
Issues
CDXgen was not able to get the correct dependency tree for kalium previously, because it used java21 internally. This config sets the java version to 17 and enables cdxgen to create a dependency tree and push it to dependency track.
How to Test
No need, this change is transparent for devs and only pertains to security tooling and should have no visible effect at all.
=> chore: Add Technolinator config for dependencytrack, setting the correct java version (SEC-598)

monkeys/build.gradle.kts, monkeys/schema.json, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/model/TestData.kt
----
Adds the possibility to skip the warmup (which can be useful when running with preset users) and writes the CC version in the logs
----
=> feat(monkeys): Write CC version in logs and allow to skip warmup [WPB-6784]

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/SendTypingRequest.kt
----
----
The testservice implements a new endpoint /sendTyping which mirrors the old endpoint in ETS. This was successfully tested against the automatic test case C1220500.
=> feat: Testservice can send typing events [WPB-6841]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/TeamsApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/TeamsApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/teams/TeamsApiV0Test.kt
----
----
When a team has more than 200 members the `fetchMembersByTeamId` will start an infinite loop because it doesn't send the paging state back to the backend. This results in the backend always returning the first page and the `hasMore` attribute to true.
The `pagingState` is now sent.
----
=> fix: Team members API not passing paging state and resulting in infinite loop on teams with more than 200 members

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/CertificateRevocationListCheckWorker.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unbound/acme/ACMEApi.kt
----
----
invalid endpoint when checking crl.
```
2024-03-01 13:53:32.225 17773-18238 Network                 com.waz.zclient.dev.debug            V  REQUEST: {"method":"GET","endpoint":"http///acme.elna.wire.link/crl/crl"
```
Corecrypto is returing a valid crl, while for current client are adding the path to the url. 
This leads to get a wrong url format that are returned from CC
Add the `PATH` when getting current client url and not when calling api.
----
----
----
=> fix: incorrect url when checking crl

logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/TeamsApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/TeamsApiV0.kt
----
----
the changes in https://github.com/wireapp/kalium/pull/2573 added 2 issues
1. the added paging state value is present only in API version => 4
2. the. same data class is used or other endpoints and they are not paginated
1. add a default null value for when paging state is missing.
2. split the data class into 2 paginated and not paginated response
_Attachments like images, videos, etc. (drag and drop in the …
=> fix: missing json value pagingState when getting team member by ID

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSelfUserSupportedProtocolsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCaseTest.kt
----
----
missing non mls conversation when app supports MLS but backend does not
keep the folloing in mind
1. kotlin `Collection.all` function will return true if the collection is empty
2. for newly created clients, the lastActive value is return as null from the backend.
3. to check if all of our clients supports MLS we do this
``` kotlin 
val allSelfClientsAreMLSCapable = selfClients.filter { it.isActive }.all { it.isMLSCapable }
```
4. the result of this is allSelfClientsAreMLSCapable = true and the app will update the supported protocols to include MLS 
1. Consider self client as always active
2. To check if a client is active we check the registration date if the last active date is null
_If there are some other pull requests related to …
=> fix: missing non-mls conversation when app supports MLS but backend doesn't

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
----
----
When in MLS call we would still call `wcall_set_clients_for_conv`
`wcall_set_clients_for_conv` should be called only when conversation is `Proteus`
Wrap calling of `wcall_set_clients_for_conv` only when conversation protocol is `Proteus`
- Have 2 accounts with E2EI + MLS enabled
- Have a group with both accounts
- Start a call
- Accept/Join call from another user
- Enable mic/video and everything should be working as expected.
=> fix: No audio/video when in MLS call (WPB-6984)

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/GetE2EICertificateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/E2EIConfigHandler.kt
Re-opening the app re-write E2EI gracePeriod. 
After recent changes `E2EIConfigHandler$handle` is called not only when the E2EI settings changed but in `SyncFeatureConfigsUseCase` too (on every app launch). As far as the gracePeriod is calculated locally in E2EIConfigHandler it was "resetting" gracePeriod on every app launch.
in `E2EIConfigHandler` add checking if the new settings that we are going to set are the same (except gracePeriod end) as already saved one -> do nothing. If it's different -> set it.
=> fix: E2EI enrolling grace period reseting issue RC

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/CheckRevocationListUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/CheckRevocationListUseCaseTest.kt
Crash after login 
Loop dependency in UserSessionScope : 
- `ConversationRepository` needs `CheckRevocationListUseCaseImpl`
- `CheckRevocationListUseCaseImpl` needs `MLSConversationsVerificationStatusesHandler`
- `MLSConversationsVerificationStatusesHandler` needs `ConversationRepository`
remove `MLSConversationsVerificationStatusesHandler` from `CheckRevocationListUseCaseImpl` as it's not really needed. Handler observes changes infinitely in `UserSessionScope`, so no need to run it again in CheckRevocationListUseCaseImpl.
=> fix: Crash by loop dependence

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
----
----
When producing commits inside `MLSConversationRepository` and calling `retryOnCommitFailure`, there's no easy way to get values linked to the produced commit.
For example, in the next PR I want to enable creating MLS groups with _partial_ success, and return the _non-added_ users.
But inside `establishMLSGroup`, I can't keep track of the success the operation had during the retries.
The `retryOnCommitFailure` only supports returning `Unit` on success.
> [!NOTE]
> This PR should have **no behaviour changes at all**, but will allow customisation of some MLS pipelines in the near future. For the tickets: [WPB-3694][WPB-6646][WPB-6643]
Refactor the `retryOnCommitFailure` function (renamed to `produceAndSendCommitWithRetryAndResult`), so it …
=> refactor: allow returning values on commit retry [WPB-3694]

cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/IDs.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/MLSConversationsVerificationStatusesHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
----
----
When getting user identities from core crypto, `handle` field has a different format because it contains also scheme and domain.
Provide another property that returns only the core handle without scheme, `%40` at sign and domain.
Create a new MLS group with all users verified - it should have a badge.
----
----
----
=> fix: handle with scheme and domain from corecrypto [WPB-7084]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationInteractionAvailabilityUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/legalhold/LegalHoldHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationInteractionAvailabilityUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/handler/legalhold/LegalHoldHandlerTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Connections.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConnectionDaoTest.kt
----
----
When other user from 1:1 conversation receives a legal hold request, the app gets `NewConnection` event for that user with status `MISSING_LEGALHOLD_STATUS` - the app is not handling that at all so it's not possible to disable sending messages in that case (it shouldn't be possible if the user doesn't give consent; the conversation's legal hold status should be `DEGRADED` then).
When the app receives these statuses, it creates `ConversationStartedUnverifiedWarning` again so it can be added multiple times.
Provide new status type for interaction availability for the legal hold and return it when the conversation's legal hold is in `ENABLED` or `DEGRADED` state.
Handle legal hold status update if needed when `NewConnection` event is …
=> feat: handle connection status update when legal hold requested [WPB-5937]

cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/IDs.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/WireIdentityHandleTest.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/DecryptedMessageBundleMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/MLSConversationsVerificationStatusesHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
----
----
Right now, after the hotfix https://github.com/wireapp/kalium/pull/2624 the app is able to get the proper handle without scheme or domain (handle format for WireIdentity is `{scheme}%40{username}@{domain}`, example: `wireapp://%40hans.wurst@elna.wire.link`), but it still operates on strings which is error-prone.
Create a dedicated class which defines what this handle consists of and acts as a parser so that we have a single point of failure.
Create a new MLS group with all users verified - it should have a badge.
----
----
----
=> refactor: create a dedicated class for WireIdentity handle [WPB-7084]

monkeys/src/main/kotlin/com/wire/kalium/monkeys/MetricsCollector.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/RemoteMonkey.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/ConversationPool.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/server/routes/Monitoring.kt
----
----
Adding possibility to configure timeouts for the communication between controller and monkeys and make the client retry on errors.
----
=> feat(monkeys): add timeouts and make the client retry requests

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt
----
----
The metadata send with images through kalium testservice was sending width as height and height as width.
Fix the parameter in a single method.
=> fix: Image metadata in kalium testservice was inverted (WPB-7191)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationInteractionAvailabilityUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationInteractionAvailabilityUseCaseTest.kt
----
----
Sending messages is disabled when one of 1:1 conversation members is under legal hold even when both members consent to legal hold.
Interaction is disabled not only when legal hold status for conversation is `DEGRADED` (it means that the app got connection update with `MISSING_LEGALHOLD_CONSENT` status for this other member) but also when the status is `ENABLED`, but it shouldn't be the case, because `ENABLED` legal hold status can happen only when both consent to legal hold so at this point both are allowed to send messages to each other.
Disable interaction only when legal hold status for 1:1 conversation is `DEGRADED`.
Have 1:1 conversation with other team member and enable legal hold for that member.
----
----
----
1. …
=> fix: disable message composer only for degraded legal hold conversation status

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageTextEditTest.kt
----
----
- updating edited message without self mention caused unread self mention
- unread mention badge on conversations
- fix check if mentions contains self user id
mention cases:
Case 1:
1. send a new message with 2 ppl mentioned
2. only the 2 ppl should see the icon
3. edit the message to remove one mention
4. only 1 person should see the icon
Case 2:
1 . send a message without a mention and then edit to add a mention and everyone will see the icon
=> fix: unread self mention [WPB-5786]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/IgnoreConnectionRequestUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/connection/IgnoreConnectionRequestUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConnectionRepositoryArrangement.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/ConnectionApiV4.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Connections.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt
----
When user is trying to ignore the Connection request from the user whose backend is unavailable - Error is displayed.
Igrnoring the ConnectionRequest should be available even in that case.
It was not implemented (quit a tricky case that nobody think about)
Update ConnectionRepository by adding a separate fun for ignoring the connection request. 
In case of `FederatedBackendFailure.FailedDomains` request is still marked as "Ignored" localy.
=> fix: Ignore ConnectionRequest on backend disabled RC [WPB-7087]

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/GetMessageReceiptsRequest.kt
----
----
A new endpoint needs to be implemented for testservice because read receipts are not found inside the output of getRecentMessages. Instead observeMessageReceipts fromObserveMessageReceiptsUseCase in message scope needs to be used once messageId is known.
This PR implements two endpoints. /getMessageReadReceipts for read receipts and /getMessageDeliveryReceipts for delivery receipts
----
----
----
=> feat: testservice can return message receipts [WPB-7414]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/search/SearchUserResult.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/search/SearchByHandleUseCaseTest.kt
In creating new group conversation: while searching the user and trying to select some private acc (that i have already connected with), the selecting check-box doesn't react on clicks.
Searching for the user has 2 sources: local storage (for the users that i'm connected with) and API (for remote users, user from another teams, or private users). 
When kalium gets users from API it's `UserProfileDTO` which needs to be mapped into `OtherUser`, as far as `UserProfileDTO` has no `connectionState` field and `OtherUser` needs it, it's mapped like: "if user is in the same team as me -> he's connected, if not -> not_connected". So even if i'm already connected with some private user he'll be "not_connected". 
Later when these 2 sources (local and remote) are merged: there is a check if some user …
=> fix: SearchUserResult merging local and remote results [WPB-7340]

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/appleMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/session/DeleteSessionUseCaseTest.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/CoreLogic.kt
----
----
When user logs out and login again (without closing the app) and joins or starts(and taps on any of the call options buttons [mute, video, speaker]) a call, the app crashes
Couldn't open already closed database due to the Jobs/Scopes still being held from previous login
Properly cancel Jobs/Scopes from CallManager when doing logout.
**Flow 1:**
- Login
- Start a call and wait for it to be properly established
- End call
- Log out
- Login again
- Start a call and wait for it to be properly established
- Mute/Unmute yourself | turn video on/off | turn speakers on/off
- app should not crash
**Flow 2:**
- Login
- Receive a call and accept it and wait for it to be properly established
- End call
- Log out
- Login again
- Join call through …
=> fix: app crashing when accepting call (WPB-6973)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/RestoreWebBackupUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/RestoreWebBackupUseCaseTest.kt
----
----
There is new version 21 of web backup which adds `initial_protocol` variable not used on Android. Updated supported web backup versions.
=> chore: support v21 web backup

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/notification/LocalNotification.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Notification.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
----
----
when selecting notifications form DB we fetch all available notifications and filter the first 10 in logic 
use window functions to select only 10 notificaions form the DB
----
----
---- …
=> refactor: select only 10 notifications form DB

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationMembersUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveConversationMembersUseCaseTest.kt
Cherry pick from the original PR: 
- #2718
----
----
ANR when trying to get user or device identities.
`ObserveConversationMembersUseCase` was emitting the same items multiple times, especially when navigating in the app, and it was causing the spam of `getUserIdentities` and probably overloading `CoreCrypto`, so `distinctUntilChanged` worked.
Navigate: group conversation -> details -> participants -> user profile -> 1:1 conversation -> back or conversation details
----
----
----
=> fix: ANRs when getting identities [WPB-8753]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
----
----
During a cherry pick we ended up calling `avsSyncStateReporter.execute()` twice from `UserSessionScope`
This caused the Calling Manager to try to get the clientId before it was properly set on `currentClientIdProvider`
Remove duplicate and only execute `avsSyncStateReporter` when clientId is set
=> fix: remove duplicate execution of avsSyncStateReporter

.github/workflows/jira-lint-and-link.yml
<table>
<td>
</td></table>
<br />
----
----
For internal tracking and documentation we need to link JIRA tickets to PRs
Was not implemented in kalium
Add the GH action.
----
----
----
=> chore(docs): jira ticket linking action (WPB-8645)

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationResponse.kt
----
----
Group calling not working when MLS is enabled
```
Caused by: px.c: Field 'cipher_suite' is required for type with serial name 'com.wire.kalium.network.api.base.authenticated.conversation.SubconversationResponse', but it was missing at path: $
```
`cipher_suite` argument in ConversationResponse should be optional 
----
----
----
1. E.g. …
=> fix: Group calling not working when MLS is enabled (WPB-9114)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
Set MLS groupId and correct cipher suite to the migrated conversation.
Due to changes to the ciphersuites we needed to cover rare and edge cases, also one missing part for persisting MLS groupId after receiving protocol updated event.
----
----
----
=> fix(mls): update migrated conversation with correct group id and cipher suites (WPB-9169)

logic/src/androidMain/kotlin/com/wire/kalium/logic/data/asset/KaliumFileSystemImpl.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-7368" title="WPB-7368" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-7368</a>  [Android] Playstore crash - Resample Image and File handling
</td></table>
<br />
----
----
We get multiple crashes when accessing cache files (ENOENT errors) which potentially suggest that the cache is fully cleared and the app cannot find needed directories for the given user in cache to create a temporary file for that user.
Recreate directories when getting a temporary cache file path.
Open the app, clear app cache and try to send or download asset.
----
----
----
1. …
=> fix: recreate cache directories in case cache is cleared [WPB-7368]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9404" title="WPB-9404" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9404</a>  [Android] When creating a group with 2 users, one user under legal hold, group is not created but should
</td></table>
<br />
----
----
Creating group fails with unknown error (dialog with information that something went wrong) when there are users with legal hold enabled and users who has not consent to legal hold.
Fix check if the request is retryable to make a request again with only valid members and add a system message saying that some users could not be added.
Create a group with users under legal …
=> fix: creating a group with users under LH and users who have not consent to LH [WPB-9404]

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/E2EISettings.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/E2EIConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/e2ei/E2EIRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ObserveE2EIRequiredUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterMLSClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/featureConfigs/FeatureConfigResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unbound/acme/ACMEApi.kt, network/src/commonTest/kotlin/com/wire/kalium/model/FeatureConfigJson.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
The web/desktop frontend use a proxy to fetch CRLs from other domains. However Android clients fetch those CRLs directly.
It was implemented like this.
Implement usage of proxy url for fetching CRLs when it's required and available.
=> feat: CRL proxy [WPB-8793]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/legalhold/ListUsersLegalHoldConsent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9404" title="WPB-9404" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9404</a>  [Android] When creating a group with 2 users, one user under legal hold, group is not created but should
</td></table>
<br />
----
----
When creating a group with someone being under legal hold and selecting a member from other team, the app shows "something went wrong" but should create a group just without that specific member.
It probably happens when this other team also have implicit legal hold consent, which means that legal hold for that team has been configured but not enabled - in that case, …
=> fix: exclude users from other teams when missing-legalhold-consent [WPB-9404]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/receipt/ConversationTimeEventWork.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/receipt/ConversationTimeEventWorker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/receipt/ParallelConversationWorkQueue.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/receipt/ParallelConversationWorkQueueTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9216" title="WPB-9216" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9216</a>  [Android] out of memory exception when scrolling a group chat with long unread history
</td></table>
<br />
----
----
The app is _very_ slow to mark messages/conversations as read.
1. We do stuff synchronously: send receipts, update lastReadDate, then send lastRead to other clients.
2. As the user scrolls through unread messages, we call the same `UpdateConversationReadDateUseCase` _multiple_ times in a row. And this use-case is _not_ prepared to only do one thing at a time. If called 30 times, it will …
=> refactor(receipts): Add a queue to perform work per conversation [WPB-9216]

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/CallApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/call/CallApiV0Test.kt
----
----
sft urls are taken as they received and the app tries connecting
parse the url string and hard code the protocol to https
----
----
----
=> fix: parse sft url when connecting

logger/src/commonMain/kotlin/com/wire/kalium/logger/KaliumLogger.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreLogger.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventProcessingPerformanceData.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/BroadcastMessage.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContentLogging.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserPropertiesEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/DeletedConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/RenamedConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/TypingIndicatorHandler.kt, network-util/src/commonMain/kotlin/com/wire/kalium/network/NetworkUtilLogger.kt
----
----
We have no clue what events take more time to process.
Add a structure to represent EventProcessingPerformanceData, which can be used when logging event outcomes.
Add `EventProcessingPerformanceData.TimeTaken` to most processed events (excluding `Unknown`).
Make sure `MessageContent.FromProto` can be translated to a `type` which we can log, to gather metrics between different types of messages.
We can later collect logs, or use Datadog in our private builds to gather all info and see different metrics.
----
----
=> chore: add performance metrics to event processing

logic/src/androidInstrumentedTest/kotlin/com/wire/kalium/logic/feature/call/CallManagerTest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/FlowManagerServiceImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/MediaManagerServiceImpl.kt, logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/FlowManagerServiceImpl.kt, logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/MediaManagerServiceImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/FlowManagerService.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/MediaManagerService.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/FlowManagerServiceImpl.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/MediaManagerServiceImpl.kt
----
----
App Sync is freezing when processing calling messages.
The refactors making FlowManager and MediaManager lazy were really good. They are so lazy that when CallManager wants them, they're not initialized 😅
Ensured the MediaManager and FlowManager services start before the call handle. Implemented these start procedures across all platforms, marking unsupported platforms with warnings.
I wish.
CallManager is far from testable at the moment. We should definitely refactor it.
Tested manually by making sure call manager starts and processes calling messages
----
---- …
=> fix: start related managers before CallManager

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FederationEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserPropertiesEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/DeletedConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ProtocolUpdateEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ReceiptModeUpdateEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/RenamedConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/TypingIndicatorHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/util/EventProcessingLogger.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9788" title="WPB-9788" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-9788</a>  [Android] Add event processing performance logs
</td></table>
<br />
Refactored all event logging code across all event handlers to use a helper logger. This allows concise, consistent event logging.
----
----
Too much code repetition for logging events, especially after I added performance metrics.
Simplify by creating an logger per event, with log functions for success/failure.
This can also take care of logging the time it took between start and end.
Example of the final result:
```kotlin
val …
```
=> refactor: simplify event logging [WPB-9788]

.github/workflows/gradle-ios-tests.yml, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCaseTest.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt
----
----
When sending a new file, assets restrictions are not considered.
check the file restrictions status and return the correct error based on that 
----
----
----
=> fix: asset restriction

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/protocol/OneOnOneProtocolSelector.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/protocol/OneOnOneProtocolSelectorTest.kt
For displaying correct error message in UI we need to split `NoCommonProtocol` error into 
- `SelfNeedToUpdate` means current client is old, doesn't support MLS and needs to update
- `OtherNeedToUpdate` means other user (that we are trying to communicate) has old version, doesn't support MLS and needs to update.
Was not implemented, was not needed
Just do it. 💪 
and update tests
=> fix: Split NoCommonProtocol error

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
Wrong e2ei information for other users after self user is kicked out of the group:
- enable MLS for team on bund-next env
- login with user A, B and C
- create an MLS group with all 3 users
- create a 1:1 between A and C
- enable e2ei for all the users
- generate cert for A and B
- delay generating the cert for C
- remove user C from the group conversation
- now take a look as user C at the 1:1 conversation  with user A > details > devices
Result:
device for user A does not have cert information
To get Identities for each device of user we need to get Id of MLS group this users belongs to. 
To get MLS group kalium finds the conversation that this user belongs to and get MLSGroupId from it. 
The problem comes out when self user is removed from some group-conversation and when kalium is …
=> fix: Wrong E2EI information for other users [WPB-9409]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/confirmation/ConfirmationDeliveryHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/confirmation/ConfirmationDeliveryHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9023" title="WPB-9023" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-9023</a>  [Android] Delivered status of messages not properly propagating
</td></table>
<br />
----
----
There is a crash while removing from the queue of messages that needs delivery confirmations
Not thread safe the removal part
Use the `mutex.withBlock`, to safely remove.
----
----
----
=> fix: crash on delivery confirmation queue cleanup (WPB-9023) 

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrator.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigratorTest.kt
----
----
When Android/Kalium starts the migration flow, we actually creating the MLS Conversation, and due to the agreement that the BE will not set the Correct CS in the Create Conversation Response, we need to ignore that value; in the normal conversation creation this was considered, but not in the migration flow.
* Have a team without MLS enabled
* Login on android and web
* Create a Proteus group and send some messages
* Enable MLS and set the migration to be started
* Log out and log in on Android, the android app must start the migration to MLS
* Web ( without reloading the web-app) and android app must be able to send and receive messages and the group must be established as MLS
----
----
----
1. …
=> fix(mls-migration): set correct CS when Kalium start migration (WPB-9638)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/confirmation/ConfirmationDeliveryHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/confirmation/ConfirmationDeliveryHandlerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9814" title="WPB-9814" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9814</a>  [Android] Stuck on message decryption
</td></table>
<br />
----
----
App is getting stuck while processing some messages
When `ConfirmationDeliveryHandlerImpl$enqueueConfirmationDelivery` is called, it will emit to a collector, that eventually is going to work on pending delivery receipts.
This worker _waits_ until Sync is done.
`ConfirmationDeliveryHandlerImpl$enqueueConfirmationDelivery` emits to a `SharedFlow` that has no buffer and `SUSPEND` strategy (default values).
This means that it will _wait_ …
=> fix: stuck while processing messages [WPB-9814]

logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/video/SetVideoSendStateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/video/UpdateVideoStateUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/video/SetVideoSendStateUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/video/UpdateVideoStateUseCaseTest.kt
cherry pick of 
- https://github.com/wireapp/kalium/pull/2670
----
Moving the logic of updating send state to a separate usecase.
Needed for https://github.com/wireapp/wire-android/pull/3125
----
----
---- …
=> feat: add SetVideoSendStateUseCase (WPB-7114) - cherrypick 4.4

logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/video/SetVideoSendStateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/video/UpdateVideoStateUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/video/SetVideoSendStateUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/video/UpdateVideoStateUseCaseTest.kt
cherry pick of 
- https://github.com/wireapp/kalium/pull/2670
----
Moving the logic of updating send state to a separate usecase.
Needed for -- upcoming pr on reloaded -- 
----
----
----
=> feat: add SetVideoSendStateUseCase (WPB-7114) - cherrypick 4.5

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9878" title="WPB-9878" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9878</a>  [Android] EndCallUseCase doesn't update call when its incoming or outgoing
</td></table>
<br />
----
----
When ending an incoming/outgoing call, `EndCallUseCase` wouldn't update the database with correct call status (`CLOSED`)
We were not verifying these 2 status (INCOMING / outgoing(STARTED)) in EndCallUseCase
Add verification of `INCOMING` and outgoing(`STARTED`) when ending a call
- From AR with this Kalium version:
1. start a call and end the call 
2. receive a call and end the call
on both cases, …
=> fix: end call update status (WPB-9878)

.github/workflows/benchmarks-check.yml, .github/workflows/gradle-android-instrumented-tests.yml, .github/workflows/gradle-android-unit-tests.yml, .github/workflows/gradle-ios-tests.yml, .github/workflows/gradle-jvm-tests.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9914" title="WPB-9914" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-9914</a>  Merge Queues - Use them to their fullest
</td></table>
<br />
----
----
Current concurrency strategy doesn't allow multiple builds in parallel for the merge queue.
What we're currently doing:
```mermaid
%%{ init: { 'gitGraph': { 'mainBranchName': 'develop' }} }%%
gitGraph
commit
branch PR1
commit
commit id: "BUILD PR1" type: HIGHLIGHT
checkout develop
merge PR1
branch PR2
commit
commit id: "BUILD PR2" type: HIGHLIGHT
checkout develop
merge PR2
branch PR3
commit
commit id: "BUILD PR3" type: HIGHLIGHT …
```
=> ci: allow parallel merge queue builds [WPB-9914]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrator.kt
…ls migration
----
----
When the migration started by android, and it needs to be finalised, we must migrate the groups even if there are users don't have keypackages or mls clients!
In this PR during the migration we set establish mls group with allowing partial member adding enabled.
----
----
----
=> fix(mls-migration): allow skipping users without KeyPackages during MLS migration (WPB-9638)

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9920" title="WPB-9920" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9920</a>  [Android] Restrain Sending delivery confirmation to Regular Messages only
</td></table>
<br />
----
----
We were sending delivery confirmation for all types of messages (System, Signaling, etc)
Only send delivery confirmation if message content is of type `Regular`
=> fix: Restrain sending delivery confirmation apart from Regular Messages (WPB-9920)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/mapper/ActiveSpeakerMapper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/ActiveSpeakerMapperTest.kt
(cherry picked from commit 94a64c447637c2bd3fc29c2279faa4d292b40f2d)
----
----
is user speaking mapper causes a flash briefly
the condition to decide if a user is speaking atm is 
activeSpeaker.audioLevel > 0 && activeSpeaker.audioLevelNow > 0
when it should be
activeSpeaker.audioLevel > 0 || activeSpeaker.audioLevelNow > 0
sice the audioLevelNow can be 0 and cause it to plip whenaudioLevel have a decay
----
----
----
1. …
=> fix: is user speaking mapper causes a flash briefly (#2809) [WPB-9684]

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9945" title="WPB-9945" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-9945</a>  [Android] Upload AVS metrics to Datadog
</td></table>
<br />
----
----
Since AVS 9.8 the metrics handler is called with a JSON object containing call metrics suitable for logging.
https://github.com/wireapp/wire-avs/blob/main/docs/api/api_changes_9.8.txt
This PR logs those metrics in DD compatible format so that we can build a calling dashboard from this data.
----
----
----
1. E.g. …
=> feat: log AVS metrics to datadog - WPB-9945

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCaseTest.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt
* fix: asset sending restriction
* add test
* add error messages and detekt
* fist test service
* detekt
* chore: update gradle-ios-tests.yml for runner at that time
---------
Co-authored-by: Yamil Medina <yamilmedina@users.noreply.github.com>
(cherry picked from commit ebcc9f88367c29e75fd582d5b1d06d64d3d9ddb7)
----
----
When sending a new file, assets restrictions are not considered.
check the file restrictions status and return the correct error based on that 
_Attachments like images, videos, etc. (drag and drop in the text …
=> fix: asset restriction [WPB-9947] (#2831)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendConfirmationUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendConfirmationUseCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9216" title="WPB-9216" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9216</a>  [Android] out of memory exception when scrolling a group chat with long unread history
</td></table>
<br />
----
----
Marking messages as read requires performing three actions:
- Getting message IDs / Send receipts to message authors
- Updating Last Read date in the conversation
- Sending new Last Read to other self clients
We can't consistently parallelise these steps, because getting message IDs is currently relying in the `Last Read` information that is stored in the database. What if this is updated …
=> refactor: fetch pending receipt ids within a time window [WPB-9216]

persistence/src/androidInstrumentedTest/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsBuilderTest.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/GlobalPrefProvider.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/UserPrefBuilder.kt, persistence/src/appleMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/appleMain/kotlin/com/wire/kalium/persistence/kmmSettings/GlobalPrefProvider.kt, persistence/src/appleMain/kotlin/com/wire/kalium/persistence/kmmSettings/UserPrefBuilder.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/jsMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmmSettings/GlobalPrefProvider.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmmSettings/UserPrefBuilder.kt, persistence/src/jvmTest/kotlin/com/wire/kalium/persistence/EncryptedSettingsBuilderTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9639" title="WPB-9639" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9639</a>  [Android] Crash on app login -StrongBoxUnavailableException crash in getOrCreateMasterKey
</td></table>
<br />
----
----
On Samsungs Galaxy S24 (regular, plus and ultra) sometimes the app crashes on app login. It occurs for around 40 users, when total install count on S24 is over 6k, so even more strange that it occurs only occasionally. Couldn't reproduce that on real device using Samsung Remote Test Lab.
The cause from stack trace is that the StrongBox is unavailable, but no idea why, maybe some other …
=> fix: strongbox unavailable on galaxy s24 [WPB-9639]

detekt/baseline.xml, logic/src/commonMain/kotlin/com/wire/kalium/logic/cache/SelfConversationIdProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/receipt/ParallelConversationWorkQueue.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/receipt/SendConfirmationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/receipt/SendConfirmationUseCaseImpl.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationReadDateUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/receipt/InstantConversationWorkQueue.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/receipt/ParallelConversationWorkQueueTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/receipt/SendConfirmationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConversationRepositoryArrangement.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9216" title="WPB-9216" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9216</a>  [Android] out of memory exception when scrolling a group chat with long unread history
</td></table>
<br />
----
----
Currently, if the Android app calls to update the conversation read date multiple times, there's nothing that Kalium does to protect from overworking.
Instead of just doing it immediately when called, schedule it to be executed using the new `ParallelConversationWorkQueue`, that allows one work to be executed at a time per conversation.
Add a little debounce to the queue, in case the user …
=> perf: schedule updating conversation read status [WPB-9216]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepositoryTest.kt
When user trying to create a new MLS GroupConversation only with users that has no KeyPackages, then conversation is not created and error is displayed. 
We should allow such a scenario and just create GroupConversation with only 1 (self) user.
Was not implemented (not obvious requirement)
Just do it.
In `KeyPackageDataSource.claimKeyPackages` remove checking if all the users were failed  (and returning `MissingKeyPackages` in that case). 
So `MLSConversationRepository` will take care about returning such an error in case when partial MemberList is not allowed.
=> fix: Allow creating empty MLS GroupConversation [WPB-7099]

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContentLogging.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PersistMigratedMessagesUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/DataTransferEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/handler/DataTransferEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/UserConfigRepositoryArrangement.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/unread/UserConfigDAO.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-8978" title="WPB-8978" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-8978</a>  [Android] Countly analytics ID and user properties
</td></table>
<br />
----
----
There was no common identifier between same user logged in different devices.
Not implemented.
This is only Part 1, which solves:
- Receiving the event for `DataTransfer` with tracking identifier
- Saving this value into user metadata table (saving it from Kalium and on a table because it will later be used in the frontend client, and if in the future Kalium is also used by other platforms, only a small tweak on frontend …
=> feat: add analytics user profile - Part 1 (WPB-8978)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/IncrementalSyncRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sync/SlowSyncRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncRecoveryHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt
<table>
<td>
</td></table>
<br />
----
----
It's hard to Sync logs when there are multiple users in the same CoreLogic instance.
Use `userScopedLogger` from `UserSessionScope` in Sync-related instances.
N/A
----
----
=> chore: use user-scoped logger for sync [WPB-8645] 

testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt
----
----
The issue is that the testservice does not allow new logins of accounts after running for a while. The login timed out and did not directly show an error but was just not logging the user in and seems to wait. The machine showed over 220 established connections to the backend even thought no instance was running.
It looks like the websocket was not closed when instances were destroyed because of using the wrong logout method (which usually triggers closing of the websocket). There is a limit of open websockets either on library side or on system side.
The solution here is to use `logout(reason = LogoutReason.SELF_HARD_LOGOUT, waitUntilCompletes = true)` which triggers a close of the websocket. Not sure if this closing always will …
=> fix: testservice not closing websocket due to wrong logout (WPB-9030)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/GetOrRegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ClientRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/usecase/IsAllowedToRegisterMLSClientUseCaseArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/usecase/RegisterMLSClientUseCase.kt
When the user wants to login with his second account, and cancels generating his certificate and then tries to login again, he’s stuck on setting up wire screen.
When user trying to login to the same acc as already tried, client is already exist. Checking "if E2EI is required" was missed for existed clients.
Add checking if E2EI is required for the case when user login into existed client (`VerifyExistingClientUseCase`). 
And update unit tests.
=> fix: Stuck on Setting up Wire after canceling E2EI during login [WPB-10046]

data/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/ConferenceCallingConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/ConferenceCallingConfigHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, mocks/src/commonMain/kotlin/com/wire/kalium/mocks/responses/FeatureConfigJson.kt, mocks/src/commonMain/kotlin/com/wire/kalium/mocks/responses/FeatureConfigResponseJson.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/featureConfigs/FeatureConfigResponse.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-7153" title="WPB-7153" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-7153</a>  [Android] Add flag for customer specific 1:1 calls in federated environment
</td></table>
<br />
----
----
For some network restrictions in federated environments, some customers need to run 1:1 calls the same as we do for conference calls, using SFT.
For that a new flag added called `useSFTForOneToOneCalls` that we use to know if we should force 1:1 calls to be running on SFTs. 
_Next PR will be to enforce running 1:1 on SFT_
_Briefly describe how this change was tested and if …
=> feat: add useSFTForOneToOneCalls flag (WPB-7153)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/GetOrRegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ClientRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/usecase/IsAllowedToRegisterMLSClientUseCaseArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/usecase/RegisterMLSClientUseCaseArrangement.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10046" title="WPB-10046" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-10046</a>  [Android] When cancelling generating cert with second account, user is stuck on setting up wire screen after second login
</td></table>
<br />
This PR was manually cherry-picked based on the following PR:
- #2883 which was failing during merging release/candidate
Original PR description:
-----
When the user wants to login with his second account, and cancels generating his certificate and then tries to login again, he’s stuck on setting up wire screen.
When user trying to login to the same acc as already tried, client is already exist. Checking …
=> fix: Stuck on Setting up Wire after canceling E2EI during login [WPB-10046] 🍒 🍒

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/analytics/AnalyticsIdentifierManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/analytics/AnalyticsIdentifierManagerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-8978" title="WPB-8978" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-8978</a>  [Android] Countly analytics ID and user properties
</td></table>
<br />
----
----
Packing of DataTransfer message content was not implemented.
Forgot to implement left TODO
- Implement packing of DataTransfer message content
- Add SyncManager to AnalyticsIdentifierManager (specifically to `propagateTrackingIdentifier()`) in order to wait for user current device to be available when propagating identifier message.
Can be tested on this PR : …
=> feat: Add packing and sending DataTransfer message - (WPB-8978)

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/ConferenceCallingConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/handler/ConferenceCallingConfigHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/featureConfigs/FeatureConfigResponse.kt, network/src/commonTest/kotlin/com/wire/kalium/model/FeatureConfigJson.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt
----
----
Cherrypick of https://github.com/wireapp/kalium/pull/2889
----
----
----
=> feat: Add useSFTForOneOneOneCalls -  cherrypick RC4.6 

.github/workflows/benchmarks-check.yml
<table>
<td>
</td></table>
<br />
----
----
Add and use reports storage and visualization for benchmarks using bencher.dev,  since now @wireapp/core-libraries team introduced this for their Core-crypto project
----
----
----
=> ci: add bencher to ci for benchmarks storage (WPB-8645)

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Notification.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageNotificationsTest.kt
----
----
This PR solves a bug introduced by #2874 , assuming that we have always a notification about LH in the conversations
Notifications not being received
LEFT join and assume true (same default value for the table) in case missing.
Added test to cover the case.
----
----
----
=> fix: missing notifications due to LegalHold not Notified (WPB-10351)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/keypackage/KeyPackageApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/KeyPackageApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/KeyPackageApiV5.kt, util/src/commonMain/kotlin/com.wire.kalium.util/int/IntExt.kt, util/src/commonTest/kotlin/com/wire/kalium/util/IntExtTests.kt
----
----
After finding some issues on the backend, now it's mandatory to set the CipherSuite when replacing keypackages after E2EI.
----
----
----
=> fix(e2ei): set ciphersuites when replacing KeyPackages (WPB-10238)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/team/TeamScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/IsSelfATeamMemberUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/IsSelfATeamMemberUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-8978" title="WPB-8978" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-8978</a>  [Android] Countly analytics ID and user properties
</td></table>
<br />
----
----
When first trying to get if self user is a team member, it would return the default(false) value if sync was not done before.
Sync was not done prior to the retrieval of this value.
Add SlowSyncRepository and observe last sync complete before returning a value, so it will now always get the correct value for the user.
- PR for AR will follow
Everything should continue running as is.
=> chore: Improve isSelfATeamMember UseCase (WPB-8978)

.github/workflows/gradle-jvm-tests.yml
<table>
<td>
</td></table>
<br />
----
----
Version 3 was deprecated form codecov (tokenless uploads)
Rate limit hit while trying to upload report
Update action and pass the secret when calling the workflow.
----
----
----
=> ci: missing codecov token (WPB-8645)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/DebugScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/DeleteEphemeralMessageForSelfUserAsSenderUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/asset/AssetRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ephemeral/DeleteEphemeralMessageForSelfUserAsSenderUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/AssetRepositoryArrangement.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9466" title="WPB-9466" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-9466</a>  [Android] locally downloaded assets are not deleted when a message is deleted
</td></table>
<br />
----
----
When deleting an assets message the local file inside the app is not deleted.
Implement removing asset from assets table and asset file downloaded and stored locally when the message containing this asset is removed. For sent self-deleting message, assets are removed when the message is marked as deleted and content is cleared.
Remove some messages with assets and check if assets are still in app …
=> fix: delete assets locally when message is deleted [WPB-9466]

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallHelper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/MLSCallHelperTest.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCallTest.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChangedTest.kt
----
----
- Renamed `MLSCallHelper` to `CallHelper` as it's used also for Proteus.
- Update documentation
----
----
----
=> chore: cleanup MLSCallHelper class (WPB-7153)

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfig.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/analytics/GetCurrentAnalyticsTrackingIdentifierUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/analytics/GetCurrentAnalyticsTrackingIdentifierUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10600" title="WPB-10600" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-10600</a>  [Android] Show countly details in debug settings
</td></table>
<br />
----
----
There was no possible way of getting current analytics tracking identifier directly (only existing way is a observer/flow)
Not implemented
Implement usecase and add tests
AR PR will follow
There is no way to test this PR for now, as it will be used in conjunction with AR
=> feat: Get Current Analytics Tracking Identifier (WPB-10600)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ValidateAssetFileTypeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ValidateAssetMimeTypeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/asset/AssetMessageHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/ValidateAssetFileTypeUseCaseTest.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/sync/receiver/asset/AssetMessageHandlerTest.kt
in `ValidateAssetMimeTypeUseCase` when we calculate if file can be shared or not we were comparing files mimeType to list of allowed Extensions. 
Just was implemented in that way long time ago. 
fix it and compare files extension to  list of allowed Extensions.
=> fix: Check file extension instead of mimeType [WPB-10605]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessorTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-7070" title="WPB-7070" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-7070</a>  [Android] Missing message on flaky internet
</td></table>
<br />
----
----
It's possible to have event processing being cancelled midway through and we would still mark them as processed.
Although unlikely, if we cancel the event processing midway through due to connectivity changing or websocket closing, we may swallow cancellation exceptions in `wrapStorageRequest`, and we do not return success/failure to the EventProcessor itself, as it expects exceptions to be thrown.
The idea is to completely forbid …
=> fix: prevent cancellation midway through event processing [WPB-7070]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10208" title="WPB-10208" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-10208</a>  [Android] Missed call message does not get marked as read if self user called
</td></table>
<br />
----
----
Missed call message does not get marked as read if self user called
We are updating `ConversationReadDate` if the message is coming from selfUser
Exclude missedCall type so `ConversationReadDate` will be updated if the message is coming from self user and not a missed call.
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that …
=> fix: Missed call message does not get marked as read if self user called (WPB-10208)

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallHelper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/MLSCallHelperTest.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCallTest.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChangedTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-7153" title="WPB-7153" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-7153</a>  [Android] Add flag for customer specific 1:1 calls in federated environment
</td></table>
<br />
----
----
Cherrypick of https://github.com/wireapp/kalium/pull/2938
----
----
----
1. …
=> chore: cleanup MLSCallHelper class (WPB-7153) - cherrypick RC

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10208" title="WPB-10208" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-10208</a>  [Android] Missed call message does not get marked as read if self user called
</td></table>
<br />
----
----
cherrypick of https://github.com/wireapp/kalium/pull/2953
----
----
----
1. …
=> fix: Missed call message does not get marked as read if self user called (WPB-10208) - cherrypick

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/MessageTextEditHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/MessageTextEditHandlerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10773" title="WPB-10773" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-10773</a>  [Android] Messages can only be edited once
</td></table>
<br />
----
----
second message edit will fail
wrong if condition 
reverse the if condition and add tests …
=> fix: second message edit will fail [WPB-10773]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCaseTest.kt
----
----
Check if the MLS Client has registered, then skip the registration.
When the user logs out without clearing the data, we were trying to register the exist MLSClient again; that lead to an error!
If the client has registered before and the user log in again to continue on a previously established session no need to register the client again and simply skip the api call.
Have a user with MLS Enabled on their team
1- Log in and log out without clearing the data
2- When you try to log in again with the same use, you should be able to proceed successfully
----
----
---- …
=> fix(mls-client): skip MLSClient registration if registered client is mlsCapable (WPB-10723)

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, cryptography/src/appleMain/kotlin/com/wire/kalium/cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ProteusMessageUnpacker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ProteusMessageUnpackerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10873" title="WPB-10873" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-10873</a>  Version 4.8 does not deliver all attachments in a group chat
</td></table>
<br />
----
----
Some clients reported missing messages. 
We found that it is not that hard to kill the app by swiping it away between decryption and DB insertion.
- CoreCrypto doesn't support transactions yet: every decrypt persist state and if the app dies after decrypting, the message is forever gone.
- CryptoBox does to some degree. It doesn't support rolling back a transaction gracefully. It requires recreating a …
=> fix(proteus): prevent missing messages by using transactions [WPB-10873]

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/asset/AssetMessageHandler.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/sync/receiver/asset/AssetMessageHandlerTest.kt
----
----
images form iOS are blocked when restrictions are applied
1. check if file extention or mime type are valid 
2. if not then and only then. we check if the message have complete meta data
----
----
----
1. E.g. `feat(conversation-list): …
=> fix: images form iOS are blocked when restrictions are applied [WPB-10830]

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
=> revert: "fix(migration): pick one-on-one proteus conversation in alphabetically order for MLS migration (WPB-10259)"

cli/src/commonMain/kotlin/com/wire/kalium/cli/commands/GenerateEventsCommand.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventGenerator.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11075" title="WPB-11075" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-11075</a>  Add debug tool for importing events from an external file
</td></table>
<br />
----
----
1. The sender and receiver IDs shouldn't be qualified on the `conversation.new-otr-message` event.
2. The same ID was set for both sender and receiver
The IOS client discards event because of this.
----
----
----
=> fix: incorrect sender & receiver ID on generated events [WPB-11075]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/mlspublickeys/MLSPublicKeysRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/ApiModelMapper.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v6/authenticated/ConversationApiV6.kt
----
----
Fetch and set removal-keys from the create-conversation response for 1on1 conversations and only APIV6
----
----
----
=> fix(mls): set removal-keys for 1on1 calls from conversation-response (WPB-10743)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/MLSOneOnOneConversationResolver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v6/authenticated/ConversationApiV6.kt
----
----
Fetch and set removal-keys from the get-oneonone-conversation response for 1on1 conversations and only APIV6
----
----
----
=> fix(mls): fetch and set mls-removal keys for 1on1 conversations (WPB-10743)

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/CoreCryptoExceptionMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageFailureHandler.kt
----
----
Some random decryption errors after ending 1:1 on SFT.
A race condition when we try to delete or decrypt a message related to the call and the sub conversation.
Ignore MlsException to not show the decryption
(iOS and web already ignoring it)
----
----
----
=> fix: random decryption errors after ending 1:1 on SFT (WPB-11213)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/CheckCrlRevocationListUseCase.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unbound/acme/ACMEApi.kt, network/src/commonTest/kotlin/com/wire/kalium/api/common/ACMEApiTest.kt
----
----
1. 404 when getting client domain crl
2. app setting the crl protocol to http regardless of what is set ap
1. add only the crl host to the path of the proxy url
2. remove the hard codded protocol 
----
----
----
1. E.g. …
=> fix: 404 when getting client domain crl [WPB-11243]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10700" title="WPB-10700" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-10700</a>  [Android] file not found when sending assets
</td></table>
<br />
`FileNotFoundException` on sending asset message. 
Couldn't reproduce it, or find out the actual reason. 
Wrap it to `try catch` to at least not crash the app.
=> fix: Catch excecption on Asset uploading [WPB-10700]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/DeleteEphemeralMessageForSelfUserAsReceiverUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/EphemeralMessageDeletionHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/SelfDeletionEventLogger.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ephemeral/DeleteEphemeralMessageForSelfUserAsReceiverUseCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-1807" title="WPB-1807" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-1807</a>  Self-deleting: Delete assets from internal storage once the timer runs out
</td></table>
<br />
----
----
Asset file is not removed from the storage once the self-deleting asset message timer runs out.
Wrong order of actions:
- the message is marked as deleted, which means that the content is cleared in db
- attempt to send "deleted" messages
- remove message completely from the db
- try to remove the asset from the db and its file from the storage - at this point, because of the first step, the …
=> fix: delete asset file when removing self-deleting msg [WPB-1807]

.github/workflows/benchmarks-check.yml
<table>
<td>
</td></table>
<br />
----
----
PRs failing with errors for bencher not up to date
Cloud flavor, requires to us to use latest CLI version
Use latest instead of fixed versions.
----
----
----
=> ci: use latest version of bencher as required per cloud flavor (WPB-8645)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneMigrator.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneMigratorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/MessageRepositoryArrangement.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11194" title="WPB-11194" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-11194</a>  [Android] Migration message not shown in 1:1 conversations
</td></table>
<br />
----
----
We don't show any system messages after dowing the migration from Proteus to MLS in 1:1 conversations
Not implemented
Call `insertProtocolChangedSystemMessage` after finishing the migration for 1:1 conversations 
_Specify here any other facts that you think are important …
=> fix: Migration message not shown in 1:1 conversations (WPB-11194)

logic/src/androidMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserverImpl.kt, logic/src/androidUnitTest/kotlin/com/wire/kalium/logic/network/NetworkStateObserverImplTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11200" title="WPB-11200" target="_blank"><img alt="Spike" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10820?size=medium" />WPB-11200</a>  [Android] investigate the posintial of connectivity observer blocking sync
</td></table>
<br />
----
----
There is one case that seems to be not covered by the network state observer being:
`Not connected -> to Unblocked = Connected`
Potentially hanging the state until a new connected state is triggered.
Covering all grounds by adding this case and some logs to help debugging in datadog
For now I'm testing this in an local build, to gather logs and monitor improvements
----
----
----
1. …
=> feat: network observer cover from not connected and blocked to connected (WPB-11200)

gradle/libs.versions.toml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11808" title="WPB-11808" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-11808</a>  [Android] app stalls when fetching a page of conversations from the local DB
</td></table>
<br />
----
----
The app stalls when fetching a page of conversations from the local DB.
Queries used to fetch a page of conversations from the local DB are very complicated, use sql views and many nested left joins resulting in full table scan of messages.
Update sql cipher to newest one (4.6.1) to use newest sqlite version (3.46.1) in our app, in which it looks like they updated and fixed something to better …
=> chore: update sqlcipher [WPB-11808]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/GetIncomingCallsUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10430" title="WPB-10430" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-10430</a>  [Android] When 2 Incoming call notifications at the same time, the app only displays one
</td></table>
<br />
----
----
The use case to return incoming calls was not emitting updated list of incoming calls when another incoming call appeared.
Use case had a `distinctUntilChanged` which was comparing first element on the list and it was not emitting new list if the first element hasn't changed.
Make the use case propagate incoming call list changes when more calls appear.
----
----
----
1. …
=> fix: return all incoming calls [WPB-10430]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/IsAllowedToRegisterMLSClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/PendingProposalScheduler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/FeatureSupportImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/IsAllowedToRegisterMLSClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/PendingProposalSchedulerTest.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/homeDirectory.kt, tango-tests/src/integrationTest/kotlin/PocIntegrationTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10119" title="WPB-10119" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-10119</a>  [Android] Clients should initialize MLS clients according to backend feature flag
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-10119
We now need to check team settings before registering a mls client
Add another check before mls device registration
Make sure registering device only when: feature flag is on, mls keys are present and team settings is enabled
----
----
----
1. E.g. `feat(conversation-list): Sort conversations …
=> feat: Consider team settings when registering mls device #WPB-10119

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/folders/ConversationFolderMappers.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/folders/ConversationFolderRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/folders/ConversationFolderRepositoryTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11639" title="WPB-11639" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-11639</a>  [Android] User Story for Add to favourites/Remove from favourites
</td></table>
<br />
----
----
Slow sync fails when there are no folders on user properties
User is stucked on login
Handle not found error and create favorite folder
=> fix: folders now found [WPB-11639]

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11601" title="WPB-11601" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-11601</a>  [Android] Message stuck on sending
</td></table>
<br />
Adds more logs to debug sending message issues
----
----
----
=> chore: add more logs for sending message debugging #WPB-11601

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/exceptions/ProteusException.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ProteusClientProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ProteusMigrationRecoveryHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/logout/LogoutReason.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ProteusMigrationRecoveryHandlerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncCriteriaProvider.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LogoutUseCaseTest.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/data/client/ProteusClientProviderTest.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/feature/client/ProteusMigrationRecoveryHandlerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-14250" title="WPB-14250" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-14250</a>  [Android] implement fall guards for CC migration
</td></table>
<br />
This PR was automatically cherry-picked based on the following PR:
- #3123
Original PR description:
-----
----
----
When enabling core crypto storage, if there are any Proteus clients, we need to migrate them from **CryptoBox**.
Things usually don't go as planned, so we need to have a recovery plan in place.
There might be some errors while migrating.
Implement a recovery plan for this case:
- Catch possible exceptions from …
=> chore: bulletproofing crypto box to cc migration (WPB-14250) (🍒4.6)

backup/build.gradle.kts, backup/src/commonMain/kotlin/com/wire/backup/data/BackupData.kt, backup/src/commonMain/kotlin/com/wire/backup/dump/MPBackupExporter.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/MPBackupMapper.kt, backup/src/commonTest/kotlin/com/wire/backup/BackupEndToEndTest.kt, backup/src/jsMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/nonJsMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, protobuf-codegen/src/main/proto/backup.proto
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10575" title="WPB-10575" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-10575</a>  Cross Platform Backup: Write common backup / restore library
</td></table>
<br />
----
----
Extend support to other message types, like Assets and Location.
Rely for now on the most certain data. We can fine-tune this with other clients later.
- #3116 
- #3117 
- #3121
----
----
=> feat: support other message types [WPB-10575]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-14747" title="WPB-14747" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-14747</a>  [Android] Sending of messages in EMPTY MLS groups not working with latest 4.10 build
</td></table>
<br />
When user creates empty MLS group (self user is the only member) and has only 1 client. Then sending messages always fails in such a group.
According to logs, send message error: `InvalidRequestError(errorResponse=ErrorResponse(code=400, message=Application messages at epoch 0 are not supported, label=mls-protocol-error, cause=null))`. 
Why `epoch = 0`? 
How it should work: when client creates MLS group `epoch` set 0, after that we suppose …
=> fix: Sending of message in empty MLS group #WPB-14747

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationEntity.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15149" title="WPB-15149" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-15149</a>  App is stuck after MLS migration
</td></table>
<br />
----
----
MLS conversations was not saved if MLS was disabled, causing further message migration fail.
Instead of not saving MLS conversations we save them but with `GroupState.PENDING_JOIN` state to trigger migration when MLS will be enabled
=> fix: persist mls conversation when mls disabled [WPB-15149]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneMigrator.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Reactions.sq, persistence/src/commonMain/db_user/migrations/94.sqm, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/MessageStubs.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15149" title="WPB-15149" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-15149</a>  App is stuck after MLS migration
</td></table>
<br />
----
----
When moving messages from proteus conversation to MLS if some message contained reactions or `RestrictedAsset` then migration failed causing slow sync to break.
Migrate `MessageRestrictedAssetContent` and `Reaction` tables to update on cascade when `Message` is changing `conversation_id`
1. Before enabling mls add reactions to messages on 1on1 conversation
2. Enable MLS for the team
3. Trigger slow sync on both clients in the same 1on1 …
=> fix: messages migration from proteus to mls [WPB-15149]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneMigrator.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/mls/OneOnOneMigratorTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15452" title="WPB-15452" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-15452</a>  [Android] 1:1s end up at the bottom of the list after migration
</td></table>
<br />
----
----
1:1 conversations, after MLS migration, are moved to the bottom of the conversation list, even if the conversation has some messages sent or received in the meantime. 
This is due to the fact that when migrating 1:1, a new conversation with different id is created, so in theory this new one doesn’t have any events thus `lastEventTime` and `last_modified_date` are empty (01.01.1970) - that’s why it’s moved to …
=> fix: 1:1s end up at the bottom of the list after migration [WPB-15452]

backup/src/commonMain/kotlin/com/wire/backup/encryption/EncryptedStream.kt, backup/src/commonMain/kotlin/com/wire/backup/filesystem/InMemoryEntryStorage.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/BackupImportResult.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/commonTest/kotlin/com/wire/backup/envelope/header/FakeHeaderSerializer.kt, backup/src/commonTest/kotlin/com/wire/backup/ingest/MPBackupImporterTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10575" title="WPB-10575" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-10575</a>  Cross Platform Backup: Write common backup / restore library
</td></table>
<br />
----
----
Some possible errors (mainly IO) during unzipping and decryption are not being handled.
Refactored the backup import process to improve error handling by introducing more granular failure types. Added comprehensive test coverage, including tests for edge cases in decryption, parsing, and unzipping.
Other than the current End-To-End test for the happy paths, a new test suite for the failures was introduced. …
=> refactor(backup): enhance error handling and test coverage [WPB-10575]

backup/src/commonMain/kotlin/com/wire/backup/envelope/BackupHeader.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/BackupPeekResult.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/commonTest/kotlin/com/wire/backup/ingest/BackupPeekResultTest.kt, backup/src/commonTest/kotlin/com/wire/backup/ingest/MPBackupImporterTest.kt, backup/src/jsMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/nonJsMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10575" title="WPB-10575" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-10575</a>  Cross Platform Backup: Write common backup / restore library
</td></table>
<br />
----
----
We need a way to peek into a file, to check if the file is using the new backup format or not, and learn more information about, like if it is encrypted or not.
This way the clients can decide which flow to follow, if falling back to older backup logic, asking the user for a password, etc.
Add a function to the backup importer, that will take in data, attempt to parse it and return the relevant header data. …
=> feat(backup): support file peeking [WPB-10575]

backup/src/commonMain/kotlin/com/wire/backup/dump/MPBackupExporter.kt, backup/src/commonMain/kotlin/com/wire/backup/filesystem/BackupPageStorage.kt, backup/src/commonMain/kotlin/com/wire/backup/filesystem/InMemoryBackupPageStorage.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/BackupImportPager.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/commonTest/kotlin/com/wire/backup/BackupEndToEndTest.kt, backup/src/commonTest/kotlin/com/wire/backup/dump/MPBackupExporterTest.kt, backup/src/commonTest/kotlin/com/wire/backup/filesystem/BackupPageStorageTest.kt, backup/src/commonTest/kotlin/com/wire/backup/ingest/BackupImportPagerTest.kt, backup/src/commonTest/kotlin/com/wire/backup/ingest/MPBackupImporterTest.kt, backup/src/jsMain/kotlin/com/wire/backup/dump/MPBackupExporter.kt, backup/src/jsMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/jsTest/kotlin/com/wire/backup/filesystem/EntryStorageTest.kt, backup/src/nonJsMain/kotlin/com/wire/backup/dump/MPBackupExporter.kt, backup/src/nonJsMain/kotlin/com/wire/backup/filesystem/FileBasedBackupPageStorage.kt, backup/src/nonJsMain/kotlin/com/wire/backup/ingest/MPBackupImporter.kt, backup/src/nonJsTest/kotlin/com/wire/backup/filesystem/EntryStorageTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-10575" title="WPB-10575" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-10575</a>  Cross Platform Backup: Write common backup / restore library
</td></table>
<br />
----
----
We can make it easier to clients to consume the data in the same exact order every time.
Otherwise, clients can shoot themselves in the foot if the data being saved into the DB is not properly sorted, by failing to satisfy DB constraints, for example.
Split the pager into smaller pagers. One for each:
- Conversations
- Users
- Messages
These will make sure that the pages are always consumed in order.
---- …
=> feat(backup): paginate different types of content [WPB-10575]

testservice/ansible/roles/kalium-testservice/tasks/main.yml
----
----
Just restarts the testservice every evening at 20:30 on node018
=> feat: Add cron job to restart kalium-testservice every evening

persistence/src/commonMain/db_user/com/wire/kalium/persistence/ConversationFolders.sq
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15890" title="WPB-15890" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-15890</a>  [Android] Sorting of folders list
</td></table>
<br />
----
----
- sorting folders by name
=> fix: sort folders by name [WPB-15890]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/folders/ConversationFolderRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/folders/ConversationFolderRepositoryTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15892" title="WPB-15892" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-15892</a>  [Android] It should not be possible to create empty folders
</td></table>
<br />
----
----
Because backend doesn't clean folders by itself we need to check if they are empty after conversation from folder removal
=> fix: remove folder when conversation list is empty [WPB-15892]

data/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/keypackage/KeyPackageRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/RefillKeyPackageUseCaseTest.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/client/ClientRequest.kt, network-model/src/commonTest/kotlin/com/wire/kalium/network/api/authenticated/client/ClientCapabilityDTOSerializerTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/keypackage/KeyPackageApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/KeyPackageApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v5/authenticated/KeyPackageApiV5.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v5/KeyPackageApiV5Test.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15722" title="WPB-15722" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-15722</a>  [Android] - Adopt API v8 changes in existing endpoints
</td></table>
<br />
----
----
add the following changes 
- `GET /calls/config`. Use `GET /calls/config/v2` instead. (Do not mind the double versioning. This will be cleaned up as soon as we get to it)
- already used
- `POST /password-reset/:key`. Use `POST /password-reset/complete` instead.
- not used
- `POST /onboarding/v3`
- not used
- `PUT /conversations/:cnv`. Use `PUT /conversations/:domain/:conv/name` instead.
- already uesd
- `PUT …
=> feat: adapt api v8 changes [WPB-15722]

data/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/LoginDomainPath.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/DomainRegistrationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/LoginDomainPath.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/GetLoginFlowForDomainUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginRedirectMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginRedirectPath.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/auth/login/DomainRegistrationMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/GetLoginFlowForDomainUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginRedirectMapperTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15520" title="WPB-15520" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-15520</a>  [Android] - Implement error handling for initial screens
</td></table>
<br />
----
----
- Returns Result instead of Either
- Creates specialized errors for proper handling
- Test coverage
----
----
----
=> refactor: return specialized result and error handling for GetLoginFlowForDomainUseCase (WPB-15520)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandlerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16204" title="WPB-16204" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-16204</a>  [Android] First message missing after leaving and being added to MLS group
</td></table>
<br />
----
----
When the user is logged in to two clients, web and android, is added to a conversation, then leaves from web and then is added again then:
- when web client sends first message android client will not receive this message and will show recovery system message
First message after rejoining to conversation is not visible to other client
- wipe mls conversation if Member remove event contains self …
=> fix: wipe conversation after member leave event [WPB-16204]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/connection/ConnectionApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConnectionApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/NetworkErrorLabel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16146" title="WPB-16146" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-16146</a>  [Android]Existing connection resets to pending state after adding user to conversation
</td></table>
<br />
----
----
a broken connection request can never be restored
when updating a connection and getting 403 with `bac_conn_update` then recover by calling the backend to get the updated status of this request
_Briefly describe how this change was tested and if …
=> fix: recover when getting error for updating connection status [WPB-16146]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/folders/ConversationFolderRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/folder/RemoveConversationFromFavoritesUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/folders/ConversationFolderRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/folder/RemoveConversationFromFavoritesUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16164" title="WPB-16164" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-16164</a>  [Android]Removing conversation from favorites does not take effect and causes the filter functionality to behave abruptly
</td></table>
<br />
----
----
- added boolean to not remove favorites folder when favorite folder has empty list after removal
=> fix: do not remove favorites folder [WPB-16164]

logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/util/DummyCallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/AnswerCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/ObserveOngoingAndIncomingCalls.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/AnswerCallUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/ObserveOngoingAndIncomingCallsUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16281" title="WPB-16281" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-16281</a>  [Android]Mic icon shows muted, but participants can hear me
</td></table>
<br />
----
----
1- When enabling video before accepting a call, call does not connect to user 
2- Mic icon shows muted, but participants can hear me
1- There is an additional signalling happening because we are calling set_video_send_state after we answer the call which may confuse the SFT.
2- we recently changed AnsweredCallUSeCase to use incomingCalls flow, but this flow does not include ongoing calls that use can join.
1- …
=> fix: Mic icon shows muted, but participants can hear me (WPB-16281)

data/src/commonMain/kotlin/com/wire/kalium/logic/data/message/AssetContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendTextMessageCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/MessageDetailsView.sq, persistence/src/commonMain/db_user/migrations/99.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15738" title="WPB-15738" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-15738</a>  [Android] Video preview
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-15738
https://wearezeta.atlassian.net/browse/WPB-15736
----
Support for rendering assets preview after downloading / decrypting. To show local preview user needs to download and decrypt the asset file.
- Added `LocalData` field to asset data to have a reference to local file for the asset. This file is used for rendering video / pdf previews.
- Added local data path to the MessageDetailsView to return it with the messages query from the database.
- …
=> feat: support for local assets preview (#WPB-15738)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/PersistSelfUserEmailUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/PersistSelfUserEmailUseCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16573" title="WPB-16573" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-16573</a>  [Android] Invalid information alert received although login is valid
</td></table>
<br />
----
----
When registering device with 2fa, the code is saved from login so that it can be reused, but it uses email as the key.
Currently, the app doesn't know self user's email until initial sync is performed (only then `fetchSelfUser` is executed) so when trying to get email during device registration, it returns null and 2fa code cannot be retrieved resulting in error.
Persist self user email (in User table …
=> fix: persist self email to register device with 2fa [WPB-16573]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/UpgradeCurrentSessionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/token/AccessTokenRefresher.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/network/SessionManagerImpl.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/network/SessionManagerTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/AuthenticatedNetworkContainer.kt, network/src/commonMain/kotlin/com/wire/kalium/network/session/SessionManager.kt, network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/TestSessionManagerV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/common/SessionManagerIntegrationTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16726" title="WPB-16726" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-16726</a>  [Android] Client not being able to send MLS messages, but receive them
</td></table>
<br />
----
----
Some clients have their auth sessions without an associated client ID _somehow_.
We are not sure yet. Might have been a bug we had in the past and it's fixed now. But this was dormant for more than a year until now that MLS is coming out, as MLS requests _require_ an "upgraded" session - _i.e._ an associated client ID.
Send the client ID every time we refresh the auth token. This is a broad safety …
=> fix(MLS): use current client ID when refreshing token [WPB-16726]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/ConversationDetails.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15863" title="WPB-15863" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-15863</a>  [Android] Add channels as an option in the filter menu
</td></table>
<br />
----
----
Channels don't show up when filtering by `Channels`.
Not yet implemented.
Introduced the 'CHANNELS' filter option in ConversationDetails.sq with corresponding test cases in ConversationDAOTest.kt to ensure correct functionality. Removed unused mapping logic in ConversationMapper to streamline the codebase.
----
---- …
=> fix(channels): filtering conversations by channels [WPB-15863]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17115" title="WPB-17115" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-17115</a>  [Android] Second client in a Self MLS conversation stuck on connecting
</td></table>
<br />
----
----
- When a second client (belonging to the same user) attempted to join a self-type MLS conversation, the app would get stuck in a `connecting` state. After a restart, the conversation list was displayed, but the user could not send messages.
- A `409 InvalidRequestError` was thrown due to the second client trying to establish a brand-new self MLS conversation instead of joining the existing one.
- In …
=> fix: mls self conversation join [WPB-17115]

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15730" title="WPB-15730" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-15730</a>  [Android] ANR when opening conversation from notification
</td></table>
<br />
----
----
Some database calls are being invoked on Main thread
Switch context to run on IO
----
----
----
1. …
=> fix: run database operations on IO thread (WPB-15730)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/proteus/ProteusSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/proteus/ProteusSyncWorkerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17160" title="WPB-17160" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-17160</a>  [Android] Excessive frequency of fetching proteus prekeys
</td></table>
<br />
----
----
`ProteusSyncWorker` is being executed hundreds of times per each day instead of once every 24h.
It delays until next interval passes but then it collects incremental sync state flow to run when it's "live", but this flow never ends so it collects indefinitely instead of once and then delay to wait for next interval to pass.
Change `waitUntilLiveAndRefillPreKeysIfNeeded` to wait only for first "live" state and then …
=> fix: ProteusSyncWorker is being executed too often [WPB-17160]

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncExceptionHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManagerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManagerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17145" title="WPB-17145" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-17145</a>  [Android] stuck on sync
</td></table>
<br />
----
----
Some users are stuck on sync. 
Our log lines seem to have spiked.
Battery consumption is higher recently...
Me?
Launching sync retries on a different coroutine scope caused a bug, where multiple retries could be left hanging in this different scope. 
When stopping/starting from the outside (when app goes foreground → background → foreground, for example), sync would restart, but that "retry" attempt would still keep on living.
There is absolutely …
=> fix: prevent multiple sync jobs in parallel [WPB-17145]

backup/build.gradle.kts
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-14598" title="WPB-14598" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-14598</a>  [iOS] Add shared backup library as a dependency
</td></table>
<br />
----
----
In the iOS project the "Wire" prefix is used for all the internal modules/targets.
In order not to have a name collision this PR renames the generated framework with the backup module "KaliumBackup" (project+module).
----
----
----
=> chore(backup): rename backup framework for iOS - WPB-14598

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Calls.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/ConversationDetailsWithEvents.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/ConversationFolders.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/UnreadEvents.sq, persistence/src/commonMain/db_user/migrations/104.sqm
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17782" title="WPB-17782" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-17782</a>  [Android] improve conversation list loading
</td></table>
<br />
----
----
Conversation list feels sluggish on large accounts with older devices.
missing indexes and large views with a lot of joins
us not repeat ourselves 
These snapshots were captured on **macOS** using the stock `sqlite3` CLI (v3.x) against an unen­crypted DB.  
Production runs **SQLCipher 4.x** on iOS / Android devices (encrypted, different page size & flash I/O), so *absolute* numbers will differ — we rely on the **delta** …
=> feat: improve SQL views and indexes for conversation details and unread events [WPB-17782]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/EventRepositoryArrangement.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18144" title="WPB-18144" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-18144</a>  [Android] App not receiving messages (at all!) when in background
</td></table>
<br />
----
----
- Variable for process pending events was not properly passed which caused problems with receiving events and decrypting them.
- updating last processed event should not update last fetched event
- pass variable properly
- split updating processed event and last saved event to separate functions
- trigger slow sync to get users recovered for lost events
=> fix: pending events handling [WPB-18144]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/LiveSourceChangeHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventGathererTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/LiveSourceChangeHandlerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18229" title="WPB-18229" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-18229</a>  [Android] User seeing decrypting messages banner until they receive a message
</td></table>
<br />
----
----
Sync bar needs to be handled with some timing from the processing events and from the moment we open the websocket
Bring back the solution from 
- #3455 
----
----
----
=> fix: syncbar mechanism with local events (WPB-18229)

backup-verification/build.gradle.kts, backup-verification/src/main/kotlin/AppScreen.kt, backup-verification/src/main/kotlin/ComparisonResultScreen.kt, backup-verification/src/main/kotlin/ComparisonScreenState.kt, backup-verification/src/main/kotlin/FileSelectionScreen.kt, backup-verification/src/main/kotlin/Main.kt, backup-verification/src/main/kotlin/com/wire/backup/verification/BackupId.kt, backup-verification/src/main/kotlin/com/wire/backup/verification/BackupVerification.kt, backup-verification/src/main/kotlin/com/wire/backup/verification/DifferentItem.kt, backup-verification/src/main/kotlin/com/wire/backup/verification/EqualItem.kt, backup-verification/src/main/kotlin/com/wire/backup/verification/MessageComparator.kt, backup-verification/src/main/kotlin/com/wire/backup/verification/MissingItem.kt, backup-verification/src/main/kotlin/com/wire/backup/verification/Node.kt, backup/build.gradle.kts, backup/src/commonMain/kotlin/com/wire/backup/data/BackupData.kt, backup/src/commonMain/kotlin/com/wire/backup/data/BackupDateTimeSerializer.kt, backup/src/commonMain/kotlin/com/wire/backup/data/ByteArrayStringSerializer.kt, backup/src/jsMain/kotlin/com/wire/backup/data/BackupDateTime.kt, backup/src/nonJsMain/kotlin/com/wire/backup/data/BackupDateTime.kt, build.gradle.kts, gradle/libs.versions.toml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17821" title="WPB-17821" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-17821</a>  [MPBackup Library] Create a backup file comparison tool
</td></table>
<br />
----
----
We have data being exported differently by each client during backup, and there is no simple way to compare.
Add a backup comparison tool.
Made in Compose/JVM (Desktop).
To run:
`./gradlew :backup-verification:run`
Select two or more `.wbu` files, and have fun!
It works by:
- Importing each backup and collecting the whole data set to a list based on the source (backup file)
- Comparing each data set, splitting …
=> feat(backup): add backup comparison tool [WPB-17821]

cells/src/commonMain/kotlin/com/wire/kalium/cells/data/model/CellNodeDTO.kt, cells/src/commonMain/kotlin/com/wire/kalium/cells/domain/model/CellNode.kt, cells/src/commonMain/kotlin/com/wire/kalium/cells/domain/model/Node.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18466" title="WPB-18466" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-18466</a>  [Android] Show tags in files list
</td></table>
<br />
----
----
Parse the list of tags retrieved from remote
----
----
----
1. …
=> feat(cells): retrieve tags from remote (WPB-18466)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/ReceiptMessageHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ReceiptMessageHandlerTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-8756" title="WPB-8756" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-8756</a>  [Android] Read receipts not generated when responding from notification popup
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-8756
Message status is inconsistent. Changing from read to delivered.
Delivered status receipt from one client overwrites current Read status received from another client. 
Check message status before updating and do not allow changing from Read to Delivered.
=> fix: read receipt race condition (#WPB-8756)

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventGatherer.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorker.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventGathererTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncWorkerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18531" title="WPB-18531" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-18531</a>  [Android] Notification not showing if app process was not running
</td></table>
<br />
----
----
After #3506, we are still emitting `Live` before processing any events, if there are 0 events in the local storage.
Missing edge case, where there are no events in the storage, but we haven't connected through the websocket yet
Quick and dirty solution:
- Rename `receiveEvents()` to `receiveEventsFromRemoteAndInsertIntoLocalStorage()` for clarity
- Make it so the `EventGatherer` waits for a signal from the …
=> fix(sync): consider Live after connecting websocket [WPB-18531]

backup/src/commonMain/kotlin/com/wire/backup/dump/MPBackupExportValidation.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18821" title="WPB-18821" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-18821</a>  [Android] Creating backup not possible if the client has assets without an ID
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-18821
Backup creation failing for some users.
Caused by validation stopping backup when exporting asset with empty id.
Ignore assets with empty ID instead of stopping the backup.
=> fix: invalid asset handling for backup (#WPB-18821)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/UpdateSelfClientCapabilityToConsumableNotificationsUseCase.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18915" title="WPB-18915" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-18915</a>  [Android] Waiting for network banner after updating the app
</td></table>
<br />
----
----
Upgrade of async notifications is happening, since the server ([prod](https://prod-nginz-https.wire.com/api-version)) supports v9 already, triggering registration of the capability, even tho the client still does not perform API migration.
Consider the current API version number in usage to check additionally to the feature flag for upgrade.
----
----
---- …
=> fix: consider current API in usage for upgrade of ack capabilities (WPB-18915)

common/src/commonJvmAndroid/kotlin/com/wire/kalium/common/error/CoreCryptoExceptionMapper.kt, common/src/commonMain/kotlin/com/wire/kalium/common/error/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ResetMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSResetConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageFailureHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/AllowedGlobalOperationsHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ResetMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/notification/EventContentDTO.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/notification/conversation/MlsConversationResetData.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17704" title="WPB-17704" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-17704</a>  [Android] Reset broken MLS conversations
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-17704
- Conversation.MlsReset event
- Handler for new event
=> feat: reset mls conversation event handling (#WPB-17704)

conversation-history/build.gradle.kts, conversation-history/src/commonMain/kotlin/com/wire/kalium/conversation/history/HistoryClient.kt, conversation-history/src/commonMain/kotlin/com/wire/kalium/conversation/history/data/HistoryClientDAO.kt, conversation-history/src/commonMain/kotlin/com/wire/kalium/conversation/history/data/SQLiteHistoryClientDAO.kt, conversation-history/src/commonTest/kotlin/com/wire/kalium/conversation/history/data/SQLiteHistoryClientDAOTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/HistoryClient.sq, persistence/src/commonMain/db_user/migrations/110.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/TableMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18492" title="WPB-18492" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-18492</a>  [Android] Persist all History Clients
</td></table>
<br />
----
----
Add storage for `HistoryClient`.
This PR requires the following PR to be merged before:
- #3536 
The idea here is to add sql-related stuff to the `persistence` module, in order to generate the `*Queries` classes using SQLDelight. However, the `DAO` implementation, mapping to domain models, etc. happen within the new `:conversation-history` module.
=> chore(conversation-history): store history clients [WPB-18492]

common/src/commonJvmAndroid/kotlin/com/wire/kalium/common/error/CoreCryptoExceptionMapper.kt, common/src/commonMain/kotlin/com/wire/kalium/common/error/CoreFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/JoinExistingMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ResetMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSResetConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/MLSMessageFailureHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/AllowedGlobalOperationsHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ResetMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/notification/EventContentDTO.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/notification/conversation/MlsConversationResetData.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17704" title="WPB-17704" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-17704</a>  [Android] Reset broken MLS conversations
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-17704
This PR is related to https://github.com/wireapp/kalium/pull/3529 and resetting broken MLS conversations.
If conversation participant receive MLSReset message with the old version of the app this message is ignored and client will have an old group ID. This will not let the client receive or send messages in this conversation.
App will now try to recover conversation when receiving group ID mismatch error.
=> feat: reset mls event recover [WPB-17704]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/FetchConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19107" title="WPB-19107" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-19107</a>  [Android] Adopt apiVersion 10 breaking changes  - Conversations endpoint
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-19138
Allow calling FetchConversationUseCase from conversation debug screen view model.
=> chore: allow calling fetch conversation from debug screen UI (WPB-19107)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/member/MemberDAO.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18697" title="WPB-18697" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-18697</a>  [Android] Status not sent to other clients
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-18697
User availability status is not sent to other users.
When sending status update via Proteus broadcast message app is using `report_only` strategy to discover missing clients but not preparing correct list of recipient user ids.
1. When preparing a list of all recipients of a broadcast message we need to include all users that have conversation with current user.
2. When setting up broadcast message app must add user ids of all …
=> fix: user availability status [WPB-18697]

data/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, data/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, data/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContentLogging.kt, data/src/commonMain/kotlin/com/wire/kalium/logic/data/message/composite/Button.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/composite/SendButtonMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/MessageCompositeEditHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/handler/MessageCompositeEditHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/MessageRepositoryArrangement.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/content/ButtonContent.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/CompositeMessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19100" title="WPB-19100" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-19100</a>  [Android] Support editing a Composite message
</td></table>
<br />
----
----
To support the work of new apps, there is a new case where apps/bots, can edit composite messages.
Never supported in the app, just a `TODO()`
- Implement the logic to handle the `protobuf` mapping, and add all the persistence handling.
- Clients cannot modify, so it will continue to be unsupported, since clients cannot send composite messages.
[Screen_recording_20250807_105501.webm](https://github.com/user-attachments/asset …
=> feat: support receiving composite message edition (WPB-19100)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/backup/BackupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/CreateMPBackupUseCase.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19611" title="WPB-19611" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-19611</a>  [Android] Backup creation fails with "Something went wrong" error for everyone
</td></table>
<br />
----
----
Failure happening when attempting to create a backup:
```
CoreLogic: Failed to create backup
CoreLogic: java.lang.IllegalStateException: 'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
CoreLogic: Otherwise, a callback/listener may leak in case of external cancellation.
CoreLogic: See callbackFlow API documentation for the details.
CoreLogic: …
```
=> fix(backup): failure when creating backup [WPB-19611]

network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/conversation/ConversationHistory.kt, network-model/src/commonTest/kotlin/com/wire/kalium/network/api/authenticated/conversation/ConversationHistoryDepthSerializerTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/history/ConversationHistoryApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationHistoryApiV0.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-18407" title="WPB-18407" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-18407</a>  [Android] Modify conversation history settings - API
</td></table>
<br />
----
----
Add the API structure for new endpoints and relevant DTOs.
There is still more to come, just splitting the work in smaller PRs.
=> chore(conversation-history): add endpoint stubs [WPB-18407]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/backup/BackupRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/backup/BackupDataSourceTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19611" title="WPB-19611" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-19611</a>  [Android] Backup creation fails with "Something went wrong" error for everyone
</td></table>
<br />
----
----
Actually fix what I couldn't here:
- https://github.com/wireapp/kalium/pull/3589
All we need to do is close the channel/flow once all the pages from the database are consumed, so it doesn't warn us that we might have left a flow/callback open.
Added tests to make sure it is working.
=> fix(backup): failure to export universal backup [WPB-19611]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSResetConversationEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSResetConversationEventHandlerTest.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/notification/conversation/MlsConversationResetData.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19900" title="WPB-19900" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-19900</a>  [Android] Issues with broken conversation after MLS reset
</td></table>
<br />
----
----
after mls reset the group is left broken this can happen sometimes but not always
the code follows exactly what the docs say however we implemented this feature before the backend added the new group id to the event data, and we fetch the conversation info from the server 
m,y theory is when using a limited QA server the event is 
1. sent not in guaranteed order (meaning the MLS welcome event is sent before the …
=> fix: update conversation new group id form the event to avoid race conditions [WPB-19900]

data/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/IsProfileQRCodeEnabledUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/EnableUserProfileQRCodeConfigHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiverTest.kt, mocks/src/commonMain/kotlin/com/wire/kalium/mocks/responses/FeatureConfigJson.kt, mocks/src/commonMain/kotlin/com/wire/kalium/mocks/responses/FeatureConfigResponseJson.kt, network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/featureConfigs/FeatureConfigResponse.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/unread/UserConfigDAO.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-20230" title="WPB-20230" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-20230</a>  [Android] Respond to QR code backend feature flag and turn QR code feature on / off according to flag setting
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-20230
----
1. Feature flag renamed: "disable" -> "enable" to match the flag logic
2. Feature flag logic updated:
- Configuration is missing -> enabled -> show QR code
- Feature enabled (default value on BE) -> show QR code
- Feature disabled -> hide QR code
=> feat: profile qr code feature flag refactor (WPB-20230)
