build.gradle.kts
----
----
See #32 
Wrong dependency declaration
Fix dependency group name
N/A
----
----
----
=> chore: correct JavaX Validation dependency declaration

src/main/java/com/wire/kalium/WireAPI.kt, src/main/java/com/wire/kalium/WireClient.kt, src/main/java/com/wire/kalium/WireClientBase.kt, src/main/java/com/wire/kalium/assets/Asset.kt, src/main/java/com/wire/kalium/assets/AssetBase.kt, src/main/java/com/wire/kalium/assets/AudioAsset.kt, src/main/java/com/wire/kalium/assets/AudioPreview.kt, src/main/java/com/wire/kalium/assets/ButtonActionConfirmation.kt, src/main/java/com/wire/kalium/assets/Calling.kt, src/main/java/com/wire/kalium/assets/DeliveryReceipt.kt, src/main/java/com/wire/kalium/assets/FileAsset.kt, src/main/java/com/wire/kalium/assets/FileAssetPreview.kt, src/main/java/com/wire/kalium/assets/GenericMessageIdentifiable.kt, src/main/java/com/wire/kalium/assets/LinkPreview.kt, src/main/java/com/wire/kalium/assets/MessageDelete.kt, src/main/java/com/wire/kalium/assets/MessageEdit.kt, src/main/java/com/wire/kalium/assets/MessageEphemeral.kt, src/main/java/com/wire/kalium/assets/MessageText.kt, src/main/java/com/wire/kalium/assets/Picture.kt, src/main/java/com/wire/kalium/assets/Ping.kt, src/main/java/com/wire/kalium/assets/Poll.kt, src/main/java/com/wire/kalium/assets/Reaction.kt, src/main/java/com/wire/kalium/assets/VideoAsset.kt, src/main/java/com/wire/kalium/assets/VideoPreview.kt
----
----
For a Kotlin implementation we need to refactor the Assets from Java to Kotlin
Write Assets in Kotlin
N/A
----
----
----
=> refactor: Migrate assets to Kotlin

src/main/java/com/wire/kalium/crypto/CryptoBase.kt
----
----
CryptoBase had few issues remaining from the automatic port
Fixed a few nulls and simplified style here and there
N/A
----
----
----
=> refactor: Migrate CryptoBase to Kotlin

src/main/java/com/wire/kalium/tools/Util.kt
----
----
Util couldn't be used in Kotlin
Fixed errors in nullable types
N/A
----
----
----
=> refactor: Translate Util to Kotlin

src/main/java/com/wire/kalium/tools/Logger.kt
----
----
The logging facility was out of order.
Fix a few null checks and import the correct class
N/A
----
=> refactor: Migrate Logger to Kotlin

src/main/java/com/wire/kalium/MessageHandler.kt
----
----
LinkPrevious are not implemented and thus should be ignored
Comment out code referring to Link Previews
N/A
----
----
=> refactor: Ignore Link Previews

src/main/java/com/wire/kalium/backend/GenericMessageProcessor.kt, src/main/java/com/wire/kalium/models/EditedTextMessage.kt, src/main/java/com/wire/kalium/models/EphemeralTextMessage.kt, src/main/java/com/wire/kalium/models/TextMessage.kt
----
----
GenericMessageProcessor needed a facelift since it wasn't compatible with the rest of the code
Implement a few smart constructor here and there
N/A
----
----
=> refactor: Migrate GenericMessageProcessor to Kotlin

build.gradle.kts, src/main/java/com/wire/kalium/WireAPI.kt, src/main/java/com/wire/kalium/backend/models/Conversation.kt, src/main/java/com/wire/kalium/backend/models/Members.kt, src/main/java/com/wire/kalium/backend/models/User.kt, src/main/java/com/wire/kalium/helium/API.kt, src/main/java/com/wire/kalium/helium/models/Access.kt, src/main/java/com/wire/kalium/helium/models/Connection.kt, src/main/java/com/wire/kalium/helium/models/Cookie.kt, src/main/java/com/wire/kalium/helium/models/Event.kt, src/main/java/com/wire/kalium/helium/models/NewClient.kt, src/main/java/com/wire/kalium/helium/models/NotificationList.kt, src/main/java/com/wire/kalium/models/otr/PreKeys.kt
----
----
the first step to #56 is to get the classes from helium to compile
N/A
still a need a small fix
----
----
----
=> refactor: helium API class rewrite

src/main/java/com/wire/kalium/WireClient.kt, src/main/java/com/wire/kalium/WireClientBase.kt, src/main/java/com/wire/kalium/helium/Application.kt, src/main/java/com/wire/kalium/helium/LoginClient.kt, src/main/java/com/wire/kalium/helium/UserMessageResource.kt, src/main/java/com/wire/kalium/helium/WebSocketApplication.kt, src/main/java/com/wire/kalium/helium/WireClientImp.kt
By splitting this monster class Application we can have App that only sends messages and if we want to also receive them then WebSockApplication
=> Extracted WebSocketApplication.kt from Application.kt

build.gradle.kts, src/main/java/com/wire/kalium/exceptions/KaliumException.kt, src/main/java/com/wire/kalium/helium/API.kt, src/main/java/com/wire/kalium/helium/Application.kt, src/main/java/com/wire/kalium/helium/EventDecoder.kt, src/main/java/com/wire/kalium/helium/LoginClient.kt, src/main/java/com/wire/kalium/helium/SocketReconnectHandler.kt, src/main/java/com/wire/kalium/helium/UserMessageResource.kt, src/main/java/com/wire/kalium/helium/WebSocketApplication.kt, src/main/java/com/wire/kalium/helium/models/Cookie.kt
----
----
See #55 #50 
----
----
----
=> refactor : cleanup helium branch

build.gradle.kts, src/main/java/com/wire/kalium/CliApplication.kt
----
----
#53 #54 
using Clikt library
com.github.ajalt.clikt:clikt:3.2.0
N/A
=> feat: add cli application to send messages from terminal

src/main/java/com/wire/kalium/BaseEventProcessor.kt, src/main/java/com/wire/kalium/backend/models/Access.kt, src/main/java/com/wire/kalium/backend/models/Conversation.kt, src/main/java/com/wire/kalium/helium/Application.kt, src/main/java/com/wire/kalium/helium/LoginClient.kt
=> refactor: fix errors in LoginClient.kt

build.gradle.kts, src/main/java/com/wire/kalium/backend/models/Asset.kt, src/main/java/com/wire/kalium/backend/models/Conversation.kt, src/main/java/com/wire/kalium/backend/models/ErrorMessage.kt, src/main/java/com/wire/kalium/backend/models/Members.kt, src/main/java/com/wire/kalium/backend/models/NewBot.kt, src/main/java/com/wire/kalium/backend/models/Payload.kt, src/main/java/com/wire/kalium/backend/models/Service.kt, src/main/java/com/wire/kalium/backend/models/SystemMessage.kt, src/main/java/com/wire/kalium/backend/models/User.kt, src/main/java/com/wire/kalium/backend/models/Version.kt, src/main/java/com/wire/kalium/tools/UUIDSerializer.kt
----
----
#61 
using ktx serializer
Kotlin plugin.serialization and org.jetbrains.kotlinx:kotlinx-serialization-json
N/A
=> feat: make backend serialize using kotlinx serializer

src/main/java/com/wire/kalium/WireClientBase.kt, src/main/java/com/wire/kalium/helium/API.kt, src/main/java/com/wire/kalium/models/otr/Devices.kt, src/main/java/com/wire/kalium/models/otr/Missing.kt, src/main/java/com/wire/kalium/models/otr/OtrMessage.kt, src/main/java/com/wire/kalium/models/otr/PreKeys.kt, src/test/java/com/wire/kalium/ApplicationSenderTest.kt
Fixed some serialization
PreKeys are still kaputt
Fixed postGenericMessageSending
=> Fixed Serialization and missing devices

src/main/java/com/wire/kalium/CliApplication.kt, src/main/java/com/wire/kalium/helium/API.kt, src/main/java/com/wire/kalium/models/otr/ClientCipher.kt, src/main/java/com/wire/kalium/models/otr/Devices.kt, src/main/java/com/wire/kalium/models/otr/Missing.kt, src/main/java/com/wire/kalium/models/otr/OtrMessage.kt, src/main/java/com/wire/kalium/models/otr/Recipients.kt, src/main/java/com/wire/kalium/tools/KtxSerializer.kt
----
----
#50 #61 
----
----
----
=> fix: fixes serialization errors

.gitignore, Makefile
----
----
It's quite hard to get the right set of dependencies and get started.
Add a Makefile so anyone can get started
Run `make`. Find `libcryptobox-jni.dylib` and `libcryptobox.dylib` in `native/libs`
Only works on macOS
=> chore: Add Makefile

build.gradle.kts, src/main/java/com/wire/kalium/api/KtorHttpClient.kt, src/main/java/com/wire/kalium/api/auth/RemoveCookiesRequest.kt
----
----
#108 
using okhttp Logging intercepter 
com.squareup.okhttp3:logging-interceptor:4.9.0
N/A
----
----
----
=> chor: add logging to the httpClient

src/main/java/com/wire/kalium/LoginClient.kt, src/main/java/com/wire/kalium/api/auth/AuthApi.kt, src/main/java/com/wire/kalium/api/auth/AuthApiImp.kt, src/main/java/com/wire/kalium/api/auth/RemoveCookiesRequest.kt
=> feat: renew access token request

src/main/java/com/wire/kalium/api/notification/EventResponse.kt, src/main/java/com/wire/kalium/api/notification/NotificationApi.kt, src/main/java/com/wire/kalium/api/notification/NotificationApiImpl.kt, src/main/java/com/wire/kalium/api/notification/NotificationResponse.kt, src/main/java/com/wire/kalium/api/user/client/ClientResponse.kt, src/main/java/com/wire/kalium/api/user/client/RegisterClientRequest.kt, src/main/java/com/wire/kalium/models/backend/Location.kt
=> feat: add http requests required to get Notifications

README.md
----
----
Figuring out how to build the native dependencies is a bit intimidating for new comers and for @dkovacevic 
Explain step-by-step what to do
N/A
=> docs(readme): Add build instructions

src/main/java/com/wire/kalium/CliApplication.kt, src/main/java/com/wire/kalium/api/AuthenticationManager.kt, src/main/java/com/wire/kalium/api/KtorHttpClient.kt, src/main/java/com/wire/kalium/api/auth/RenewAccessTokenResponse.kt, src/main/java/com/wire/kalium/api/user/client/ClientApi.kt, src/main/java/com/wire/kalium/api/user/client/ClientApiImp.kt
----
----
#108 
using ktor Auth feature Plugins﻿
=> chore: set up the http client to attach the access token to header

network/src/commonMain/kotlin/com/wire/kalium/network/api/KaliumHttpResult.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/KtorHttpClient.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/asset/AssetApiImp.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/auth/AuthApiImp.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/message/SendMessageRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/EventResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/LoginApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/LoginApiImp.kt
----
----
doing some house cleanup after the split
remove wildcard imports, delete some redundant classes
----
----
=> chore: project clean up

network/src/commonMain/kotlin/com/wire/kalium/network/api/user/client/RegisterClientRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/user/logout/LogoutApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/user/logout/LogoutImp.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/ClientApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/RegisterClientRequestJson.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/client/RegisterClientResponseJson.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/logout/LogoutApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/model/ErrorResponseJson.kt
----
----
#98  
test the request and the fail 
test api request configuration
----
----
=> test: client and logout ap test

buildSrc/src/main/java/Android.kt
----
----
after updating to the latest version of kotlin and android compose which requires the latest android sdk version
using sdk version 31
----
----
=> chore: update the android compile sdk

buildSrc/src/main/java/Dependencies.kt, cli/src/main/kotlin/com/wire/kalium/cli/ConversationsApplication.kt, cli/src/main/kotlin/com/wire/kalium/cli/InMemoryCredentialsLedger.kt, network/build.gradle.kts, network/src/androidMain/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/commonMain/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/commonMain/kotlin/com/wire/kalium/network/NetworkModule.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/CredentialsProvider.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/KtorHttpClient.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/AddParticipantRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationApiImp.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationEvent.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/CreateConversationRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/model/ConversationAccess.kt, network/src/commonMain/kotlin/com/wire/kalium/network/tools/KtxSerializer.kt, network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt, network/src/jvmMain/kotlin/com/wire/kalium/network/HttpEngine.kt
=> feat: add request to create conversations and add users to conversations

.github/workflows/gradle-run-tests.yml, build.gradle.kts
----
----
Currently there are no automatic tests run when creation a PR. This change aim to setup basic automated testing.
Set up a GitHub action to run ./gradlew :network:allTests to cover automatic testing of Kalium's API client
Verify that the action runs correctly
----
----
=> ci: enable github action to run tests

.github/workflows/gradle-run-tests.yml, android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt, buildSrc/src/main/java/Dependencies.kt, cryptography/build.gradle.kts, cryptography/src/androidAndroidTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt, cryptography/src/androidTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt, cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt, cryptography/src/jvmTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt
----
----
- Add tests for the ProteusClient
- Changed the API of the ProteusClient since the existing API wasn't really compatible with the JVM Cryptobox which doesn't expose the concept of sessions.
Closes https://github.com/wireapp/kalium/issues/102
Tests passes
I didn't the add any Android instruments tests because I got stuck and wanted to complete the tests first.
----
=> chore: add tests for the ProteusClient

cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/utils/CryptoUtils.kt
----
----
the project not building because of a missing `calcMd5` function implementation in `JsMain` 
adding `calcMd5` function to JsMain (the actual implementation is still missing)
----
----
=> fix: app not building

buildSrc/src/main/java/Dependencies.kt, legacy/build.gradle.kts
----
----
Kover is not being used and is curently hosted in BinTray, which is unreliable right now.
Removed Kover plugin, as it's not being used yet anyway.
N/A
----
----
=> chore: remove Kover

persistence/build.gradle.kts, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConverationDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/QualifiedIDAdapter.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/commonMain/sqldelight/com/wire/kalium/persistence/db/Converations.sq, persistence/src/commonMain/sqldelight/com/wire/kalium/persistence/db/Members.sq, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConverationDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt, persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/jsMain/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/Database.kt
----
----
Add persistence of conversations and its members
Introduce ConversationDAO
----
----
----
=> feat: ConversationDAO

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/ValidateEmailUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/ValidateEmailUseCaseTest.kt
----
----
AR-1021 AR-1022
----
----
----
=> fix: AR-1021 AR-1022

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/local/SessionLocalRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/SelfClientsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/CurrentSessionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/GetSessionsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/SessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/UpdateCurrentSessionUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/Either.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/SuspendableEitherScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/session/CurrentSessionUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/session/UpdateCurrentSessionUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/EitherAssertions.kt
----
----
providing CurrentSession and updating the session
unit test for UpdateCurrentSessionUseCase and CurrentSessionUseCase
----
----
=> feat: UpdateCurrentSessionUseCase and CurrentSessionUseCase

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/remote/ClientRemoteRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/DeleteClientUseCase.kt
----
----
Errors related to removing clients were not being caught properly.
----
----
----
=> fix: delete client errors

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/androidTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperProvider.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageEnvelope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreator.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageEnvelopeCreatorTest.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/jvmTest/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapperProvider.kt
----
----
We need to encrypt a message for each recipient.
`MessageEnvelopeCreator` takes a message and a list of recipients and is responsible for using whatever encryption mechanism needed in order to output a `MessageEnvelope`
Covered `MessageEnvelopeCreator` with tests.
External messages are not yet supported (when content is too big and we only encrypt once).
----
----
=> chore: create message envelope for sending (AR-972)

android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt, cli/src/main/kotlin/com/wire/kalium/cli/ConversationsApplication.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/GetServerConfigUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfig.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfigRemoteRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfigResult.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/configuration/ServerConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/session/SessionMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/LoginUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/session/CurrentSessionUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/LoginNetworkContainer.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/configuration/ServerConfigApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/configuration/ServerConfigDTO.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/configuration/ServerConfigResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/tools/BackendConfig.kt, network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/notification/NotificationApiTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/model/PersistenceSession.kt
----
----
[AR-1037]
Add api, remoteRepository, repository and useCase for fetch server config.
WIP
Refactor naming of the models
----
----
----
[AR-1037]: https://wearezeta.atlassian.net/browse/AR-1037
=> feat: add fetch server config api and usecase [AR-1037]

build.gradle.kts, dokka/moduledoc.md, gradle/dokka.gradle, network/src/commonMain/kotlin/com/wire/kalium/network/api/teams/TeamsApi.kt
----
----
There is not good way of accessing documentation apart from comments
Add Dokka. 
This will add a number of gradle task, notably:
- `dokkaHtmlMultimodule` use this to generate the documentation in HTML format
- `dokkaClean` to clean the folders and files created by then task above
Find `index.html` at `./build/dokka/htmlMultiModule/index.html`
----
----
=> chore: add dokka

persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/TeamDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/TeamDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/commonMain/sqldelight/com/wire/kalium/persistence/db/Teams.sq, persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/jsMain/kotlin/com/wire/kalium/persistence/db/Database.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/Database.kt
----
----
[AR-1221](https://wearezeta.atlassian.net/browse/AR-1221)
This PR contains only the addition of:
- Team queries
- Team DAO / Team DAO Implementation
- TeamDAO usage in `Database.kt` through the persistence module.
This is only the first PR, more subsequent PRs will appear pointing to the epic.
=> feat: teams database and DAO creation

README.md
----
----
On Apple Silicon users might encounter the error `Unknown host CPU architecture: arm64`
Document how to change the NDK invocation script
----
=> docs: document unknown host CPU architecture: arm64

network/src/commonMain/kotlin/com/wire/kalium/network/api/IDs.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/contact/search/ContactSearchApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/contact/search/ContactSearchApiImpl.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/contact/search/ContactSearchRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/contact/search/ContactSearchResponse.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/contact/search/ContactDTOSearchApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/contact/search/ContactSearchApiTest.kt
----
----
- added support of a network api call to /search/contacts
- via Unit Tests
----
----
----
=> feat: search public contact - add API call to search contacts (part1)

.gitignore, cli/src/main/kotlin/com/wire/kalium/cli/SendReceiveApplication.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/configuration/ClientConfig.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/sync/WorkScheduler.kt
----
----
We need a CLI app for testing & benchmarking purposes
- Add missing implementations for the JVM target
- Create a basic CLI app which can send and receive text messages in an existing conversation
n/a
I plan to extend the functionality in follow up PRs
----
----
----
=> feat: add basic CLI application for sending and receiving messages

android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/team/TeamRepository.kt
----
----
[AR-1220](https://wearezeta.atlassian.net/browse/AR-1220)
Addition of explanation for `hasMore` in `TeamRepository`.
Reverting unwanted change on login credentials in android sample app.
=> fix: team repository hasMore explanation

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/SearchPublicUserUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/SearchPublicUserUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt
----
----
- wrap the public contact repository into the use case
----
----
----
=> feat: search public contact - wrap public contact repository into the use case (part 3)

logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/team/TeamRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserMapperTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/utils/generator/TeamGenerator.kt
----
----
[AR-1220](https://wearezeta.atlassian.net/browse/AR-1220)
Added tests for:
- TeamRepositoryTest
- And added a new test file: `UserMapperTest`, which it is only testing the TeamMember to UserEntity mapping function.
=> test: fetch TeamMembers

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/call/CallApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/call/CallApiImpl.kt
----
----
[AR-1302](https://wearezeta.atlassian.net/browse/AR-1302)
This PR contains Api and Repository for getting the Calls Config.
Other PR's are to come with `UseCase` implementation and usage (currently only in the Android sample app) and tests :)
=> feat: Add call api and call repository to get call config

.github/workflows/gradle-android-tests.yml, .github/workflows/gradle-ios-tests.yml
----
----
Builds are slow
Currently iOS + Android jobs are taking about 20 mins
Run Android and iOS tests in parallel to save some time.
CI running here
----
----
=> ci: run iOS and Android tests in parallel

network/src/commonMain/kotlin/com/wire/kalium/network/api/message/MLSMessageApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/message/MLSMessageApiImpl.kt, network/src/commonTest/kotlin/com/wire/kalium/api/ApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/asset/AssetApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/message/MLSMessageApiTest.kt
----
----
We want to send MLS messages.
Implement the BE API for sending MLS Messages.
Unit tests
The BE API for MLS messages isn't complete yet so it might still change. Spec is here https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/553418860/MLS+implementation+in+wire-server#Message-delivery-service
----
----
----
=> feat: MLS message API

logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/CallManagerTest.kt
----
----
This is the tests for CallManager when receiving a Calling Message
=> test: expose list of calls

network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/SSOLoginApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/user/login/SSOResponse.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/SSOLoginApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/login/SSOResponseJson.kt
----
----
AR-1255 Implement sso endpoints (network)
`SSOLoginApi`
`SSOLoginApiTest` -> run
----
----
=> feat: AR-1355 implement sso endpoints network

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/EventContentDTO.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/notification/NotificationEventsResponseJson.kt
----
----
Add support for decoding MLS welcome events.
User A: Create a MLS group via the CLI with user B.
User B: Open app and view logs.
----
----
----
=> feat: add support for MLS welcome events

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/sso/SSOUtil.kt
----
----
AR-1155
`SSOUtil` with functions to generate both error and success redirect
----
=> feat: [AR-1155] create success and error redirect

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
=> feat: expose get or create one to one conversation use case

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt
Let's not limit ourselves to the first page, shall we?
----
----
- We have crashes when receiving messages from some conversations.
- We are not able to display all conversations.
We are not fetching all conversations!
Fetch them all.
[W.I.P.] I'm finishing this up you're reading this.
----
----
=> fix: fetch all conversations

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
----
----
Establish MLS group when receiving an MLS welcome message.
This implements: [Use case: being added to a conversation (MLS)](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/563053166/Use+case+being+added+to+a+conversation+MLS)
----
----
----
=> feat(mls): handle incoming welcome message

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/EndCallUseCaseTest.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
----
----
No useCase for ending call
Create a useCase to allow the use hang up the call
unit tested
----
----
----
=> feat: add useCase for ending call [AR-1257]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt
----
----
endCall scope incorrect name
fix it
----
----
----
=> fix: endCall scope naming

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/ServerConfig.kt
----
----
Switch default BE to prod
----
----
=> chore: switch default to prod

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
----
----
- Add CLI command for deleting a client.
- Enable chaining of subcommands
- Don't attempt to save a session if it already exists since that doesn't work reliably.
- 
```
./gradlew :cli:run --args="login delete-client"
```
----
----
----
=> feat(cli): add command for deleting clients

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
----
----
not all errors are logged
add logs to `CoreFailure` wrapper functions
----
----
----
=> feat: add error logging to wrappers functions

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt
----
----
The password for registering a new client is optional, in this PR just applied it to the use-case.
password is now optional
----
----
=> feat: add client register optional password to RegisterClientUseCase

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
----
----
We are using unresolved class name in CliApplication
we  missed to update the class name in CliApplication
update it
----
----
----
=> fix: fix ConversationOptions typo

calling/src/androidMain/kotlin/com/wire/kalium/calling/Calling.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/SendCallingMessage.kt
----
----
We were sending messages/notifying the other user via proteus/normal request but not also via AVS.
Call to `wcall_resp` on AVS to notify of any calling change.
=> chore: add avs send http response message

calling/src/androidMain/kotlin/com/wire/kalium/calling/Calling.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/AvsCallBackError.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/call/CallApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/call/CallApiImpl.kt
----
----
We were not handling SFT for calling
Add SFT handling its request and response from and for AVS.
=> chore: add SFT callback

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
----
----
CLIApplication.kt is not compiling
getAllKnownUsers() does not return a flow of conversations anymore
remove .first()
----
----
----
=> fix: CLIApplication.kt not compiling

logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/CallManagerTest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedId.kt
----
----
Moved some internal mapping methods of `QualifiedID` class from the consuming client app, to Kalium. This way we will ensure everyone uses a centralised version of it. Also moved and renamed `asString()`  as `toString()` to avoid using extension function.
Also, mapping method `parseIntoQualifiedID()` now throws an `IllegalStateException` if the string to be mapped is malformed.
----
----
----
=> chore: refactor QualifiedID mapping methods

network/src/commonMain/kotlin/com/wire/kalium/network/api/user/connection/ConnectionApi.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/connection/ConnectionApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/connection/ConnectionResponsesJson.kt
----
----
https://wearezeta.atlassian.net/browse/AR-1482
Creates a connection request, this works it's related to the network module only as described in the ticket
----
----
----
=> feat: create api send connection call - part 1 (AR-1482)

network/src/commonMain/kotlin/com/wire/kalium/network/api/api_version/VersionApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/api_version/VersionInfo.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/api_version/VersionApiTest.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/api_version/VersionInfoDTOJson.kt
----
----
support API versioning AR-1492
this PR add the endpoints to fetch BE api version
----
----
=> feat(network): api version api (AR-1492)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/ConnectionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/SendConnectionRequestUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/connection/SendConnectionRequestUseCaseTest.kt
----
----
https://wearezeta.atlassian.net/browse/AR-1267
This PR adds the usecase code, to consume and expose the operation to AR
- Created `SendConnectionRequestUseCase`
- Exposed for AR using the `ConnectionScope` class
- Added unit tests cases for it
----
----
----
=> feat: send connection request usecase (AR-1267)

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq
----
----
unhandled connection requests -> conversations added to DB with no members -> app go kaboom
this PR is only a suggestion to remove the foreign key constraints in `Members` table, so the app can work fine until we handle connection requests properly 
----
----
---- …
=> fix: temp fix for app crashing because of not handled connection requests

calling/src/androidMain/kotlin/com/wire/kalium/calling/Calling.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnAnsweredCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnConfigRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnEstablishedCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnIncomingCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnMissedCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSFTRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSendOTR.kt
----
----
This PR aims to improve calling logs making it more informative
N/A
----
----
----
=> chore: improve calling logs

logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/GetAllCallsUseCaseTest.kt
----
----
GetAllCallsUseCase not covered by unit test
Added unit test
----
----
----
=> test: cover GetAllCallsUseCase with unit test

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/failure/InvalidMappingFailure.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/CancelConnectionRequestUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/connection/CancelConnectionRequestUseCaseTest.kt
----
----
This PR adds the cancelling use case and checks for correct state transitioning of a connection request.
----
----
----
=> feat(cancel-conn): cancelling a connection request usecase (AR-1527)

calling/src/androidMain/kotlin/com/wire/kalium/calling/Calling.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnNetworkQualityChanged.kt
----
----
Network Quality Changed handler was not implemented for Calling.
Creation of NetworkQualityChanged, its implementation and usage on AVS calls on CallManager.
=> chore: add calling network quality handler

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
fix: update local connections requests on sync
----
----
_Specify here any other facts that you think are important for …
=> chore: handle connection type logic AR-1735

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
----
When trying some to receive or send calls, some would fail due to not having SFT callbacks or Calling config ready.
Due to that and thanks to @vitorhugods , we have added a `Job` to be waited until it is fully finished before continuing what ever it needs to be doing (receiving or sending calls)
=> chore: add job to wait for calling config to be ready to be used

calling/src/androidMain/kotlin/com/wire/kalium/calling/Calling.kt, logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/CallManagerTest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnClientsRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnHttpRequest.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallClient.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/GlobalCallManager.kt
----
----
[AR-1772 - Implement clients handler](https://wearezeta.atlassian.net/browse/AR-1772)
When establishing a group call, we need to know which clients are missing and thus inform AVS about them.
Add implementation of Clients Request Handler (discover all clients in the group call and inform aVS about them).
=> chore: add calling clients handler

.github/workflows/codestyle.yml, .github/workflows/generate-changelog.yml, .github/workflows/generate-dokka.yml, .github/workflows/gradle-android-tests.yml, .github/workflows/gradle-ios-tests.yml, .github/workflows/gradle-jvm-tests.yml, .github/workflows/semantic-commit-lint.yml
----
----
Some GitHub actions have newer versions and can be upgraded
Update:
- cache@v3
- checkout@v3
- setup-java@v3
----
----
=> chore: update github actions

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnClientsRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSendOTR.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedId.kt
----
----
Calling is not working due to not having support for federation yet.
We are removing the domain from the self user Id and the conversation Id in calling only so it works for now, as soon as federation is implemented we will then rework this code to support federation.
So this code is not final.
=> chore: Remove Calling domain before federation

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/MLSKeyPackageCountUseCaseTest.kt
----
----
[AR-1846]
----
[AR-1846]: https://wearezeta.atlassian.net/browse/AR-1846
=> feat(mls-keypackages): add keypackageCountUseCase (AR-1846)

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
=> fix: cascade update on the id of the foreign key on Message Edit receive

.github/workflows/gradle-jvm-tests.yml, cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
----
----
I broke the CLI app on the previous PR #610 
- Remove usage of UseCase that's no longer needed.
- Add a quick step on CI to build the CLI app and identify this sooner.
I guess adding to CI can be considered a test :)
----
----
=> chore: fix cli app

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
----
----
it can be hard to debug the app when the DB is encrypted
using unencrypted DB in debug mode
----
----
=> chore: using unencrypted db in debug mode

buildSrc/src/main/java/Dependencies.kt
----
----
AVS lib not up to date
Update it to 8.1.18
----
----
----
=> chore(calling): update AVS version

buildSrc/src/main/java/Dependencies.kt, network/build.gradle.kts, network/src/commonMain/kotlin/com/wire/kalium/network/AuthenticatedNetworkContainer.kt, network/src/commonMain/kotlin/com/wire/kalium/network/NetworkClient.kt
----
----
Adds support for ktor to compress requests, using `gzip`  (same as scala app) trying to improve a bit http req exchange.
----
----
----
=> feat: add compression support for ktor

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationOptions.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/GetOrCreateOneToOneConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversationDetails.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationAdapter.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/ConversationStubs.kt, persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
----
----
conversation access and access Role are not 
just add it
----
----
=> feat: add access and access role to logic and storage module [AR-1884]

buildSrc/src/main/kotlin/Dependencies.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/MLSClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt, cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt
----
----
- Bump CoreCrypto to 0.2.2
- Expose new methods for:
- Joining an existing conversation from a new client
- Update your key material in a group
----
----
----
=> chore: update core crypto

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnAnsweredCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnClientsRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnConfigRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnEstablishedCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnHttpRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnIncomingCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnMissedCall.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnNetworkQualityChanged.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSFTRequest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnSendOTR.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
----
----
Was a bit hard to understand what was happening in calling.
Add more logs, specially on `callRepository.createCall(..)` so we can better understand what happened if something goes wrong.
=> chore: adjust calling logs

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/BlockUserUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/connection/ConnectionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/connection/BlockUserUseCaseTest.kt
added BlockUserUseCase and tests for it.
=> feat: Add BlockUserUseCase

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MemberMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/IdMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/AvailabilityStatusMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/ConversationEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserClientDAOIntegrationTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt
[Task-2090](https://wearezeta.atlassian.net/browse/AR-2090)
- Added handling Availability status changing from the other users and saving it into DB
=> feat: Receive availability status from the others

buildSrc/src/main/kotlin/Dependencies.kt
----
----
After updating to AVS 8.2, we are facing some crashes when establishing a call
revert to 8.1
Make a call and accept on the other side
----
----
----
=> fix: revert to AVS 8.1.18

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
----
----
the asset file name is missing file extension
just add the extension 
----
----
----
=> fix: append asset extention to the asset file

README.md
include JDK 11 dependency, 
clarify CLI instructions and add caveats
----
----
_Specify here any other facts that you think …
=> chore: Correct README

logger/src/commonMain/kotlin/com/wire/kalium/logger/ObfuscateUtil.kt
----
----
obfuscate log messages affect the performance of the app
comment out the logic in the function till we submit another solution 
----
----
----
=> fix: revert obfuscate logs

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/SendKnockUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/SendKnockUserCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt
----
----
To understand the kalium library better I implemented knock (aka ping) messages with help of @vitorhugods on the persistence layer part.
I tested them manually with my testservice from branch feat/testservice over proteus protocol and added an automatic test although this test is a bit redundant.
AFAIK hot knock was just a louder or longer ping. It was basically removed from all clients a long time ago so we decided to leave it on false for now. 
----
----
----
=> feat: Implementation of knock/ping messages

gradle.properties, gradle/wrapper/gradle-wrapper.properties
----
----
Upgrade Gradle to `7.5.1`
----
----
=> chore: upgrade gradle wrapper to 7.5.1

build.gradle.kts, buildSrc/src/main/kotlin/Android.kt, buildSrc/src/main/kotlin/Dependencies.kt, cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt, cli/src/main/kotlin/com/wire/kalium/cli/RegisterAccountApp.kt, cryptography/build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, kotlin-js-store/yarn.lock, logger/build.gradle.kts, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/stubs/ServerConfigStubs.kt, network/build.gradle.kts, network/src/commonMain/kotlin/com/wire/kalium/network/NetworkClient.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/user/register/RegisterAccountJson.kt, persistence/build.gradle.kts, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/MetadataDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/TeamDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/asset/AssetDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao_kalium_db/ServerConfigurationDAO.kt, protobuf/build.gradle.kts
This reverts commit c1a4804a
----
---- …
=> fix: Revert "chore: update kotlin to 1.7.10 (#779)"

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt
----
----
We need to provide some use cases to the conversation scope
----
----
----
=> fix: update leave group scopes

buildSrc/src/main/kotlin/Dependencies.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt
----
----
Update CoreCrypto Library to 0.3.1 …
=> chore(mls): update core crypto to 0.3.1 (AR-2153)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ProtocolInfoMapper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ProtocolInfoMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestConversation.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/conversation/ConversationResponse.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/conversation/ConversationResponseJson.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt, persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseProvider.kt
…onversations
----
----
Exposed and stored Cipher Suite Tag from the API.
_Specify here any other facts that you think are …
=> feat(mls-conversation): persist and expose cipher suite tag (AR-2157)

cryptography/build.gradle.kts, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/MLSClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt, cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
----
----
- Expose new functionality from CoreCrypto
- Start returning `CommitBundle` class instead of a `Pair<>`
- Call `commitAccepted()` when a commit is accepted by BE
----
----
----
=> refactor: update MLSClient API to reflect changes in CoreCrypto

buildSrc/src/main/kotlin/Dependencies.kt
----
----
Some internal improvements/fixes in AVS library
----
----
----
=> chore: bump avs to 8.2.9

Makefile
----
----
Makefile for crypto libraries (libsodium, cryptobox) does only work on macOS
Adjusted Makefile to run on Linux and macOS:
* Don't use libexec to find java home and instead use JAVA_HOME variable if it is set already
* Fix include for OS specific header file (jni_md.h)
* Use different gcc flags depending on OS
* Use different file endings for libraries depending on OS
* Set bash as default shell to fix issue with `source`
----
----
----
=> feat: Add linux support for make of crypto libraries

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/type/UserTypeMapper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserEntityTypeMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserMapperTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/UserStubs.kt
=> chore: renamed internal user type entity to standard

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq
=> fix: changed default user type from internal to standard

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
----
----
Handle the case if a member leaves an MLS conversation.
Update the flow for removing a member from MLS conversation.
Add a new feature.
Update the repo to handle that case.
----
----
----
=> feat(mls): handle leaving an MLS conversation (AR-1910)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/session/UpdateCurrentSessionUseCase.kt
----
----
UpdateCurrentessionUsease was returning an Either
map Either to a Result sealed class
----
----
----
=> feat: account switching

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/featureConfig/GetFeatureConfigsStatusUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/client/UserConfigStorage.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/client/UserConfigStorageTest.kt
----
----
Fetch and handle feature config `ClassifiedDomains`.
We are using the same mechanism already in place that handle feature flags.
----
----
----
=> feat: persist feature flag of classified domains (AR-2301)

logic/src/androidAndroidTest/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantsVideoStateChangedTest.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantsVideoStateChanged.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/Participant.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/VideoStateChecker.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/mapper/ParticipantMapper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/ActiveSpeakerMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/ParticipantMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/VideoStateCheckerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/ParticipantsOrderTest.kt
----
----
This PR is needed to display others participants screen
----
----
----
=> feat(calling): display screen sharing feed (AR-1234)

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt, network/src/commonMain/kotlin/com/wire/kalium/network/exceptions/KaliumException.kt
----
----
When I log a `CoreFailure.ServerMiscommunication` error it logs something similar to `ServerMiscommunication@123812` which doesn't tell me anything about what actually went wrong.
override `toString()`to include the root cause and specifically the error code, message and label.
----
----
----
=> chore: print meaningful network errors

buildSrc/src/main/kotlin/Dependencies.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/MLSClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/IDs.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/MLSClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/QualifiedIDTest.kt, cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt
----
----
Upgrade core-crypto to 0.4.2
----
----
----
=> chore: upgrade core-crypto to 0.4.2

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt
----
----
This PR handles the error if trying to delete a conversation during sync, that no longer exists (already handled event)
We remove the `onlyRight` call that was blocking forever the sync process waiting for a response.
- Create a group conversation, send some messages, then close the app.
- Go to your desktop/web client account, and delete the conversation
Expected output: we receive the event and when we open the app, no longer we are blocking the sync forever.
----
----
----
=> fix: deleted conversation event blocking sync (AR-2298)

network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/NotificationApiImpl.kt
----
----
When calling 
```kotlin
val notificationApi = notificationApiImplInstance()
val eventHandlingJob = launch {
notificationApi.listenToLiveEvents(clientId)
.collect(::handleLiveEvents)
}
delay(10.seconds)
eventHandlingJob.cancel()
```
The job would be cancelled, however a websocket would still be connected with our backend and receiving events.
Leading to the backend not sending us push notifications, and possible duplicated events (not confirmed).
An issue with Ktor that was fixed on its stable `2.0.0` release. Unfortunately we are unable to upgrade to `2.0.0` as it would require upgrading Kotlin and this breaks the AR project.
- Replace `webSocket` with `webSocketSession`, which has its own scope
- When the flow is aborted, notify the …
=> fix: properly disconnect websocket

buildSrc/src/main/kotlin/Dependencies.kt
----
----
Upgrade to latest AVS version
----
----
----
=> chore: bump AVS version to 8.2.11

buildSrc/src/main/kotlin/Dependencies.kt
----
----
AVS release note: 
- fix for not connecting after reject (SQCALL-537)
----
----
----
=> chore: bump AVS version to 8.2.12

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnCloseCall.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/KaliumWebSocketFactory.kt, network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt
----
----
events and calling showing ids that not obfuscated 
update the tostring functions to hide and obfuscate those info
run the android app and check if the logs if has any sensitive info 
----
----
----
=> chore: obfuscate logs

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Calls.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/asset/AssetDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOImpl.kt
----
----
sql query optimizations for the following tables:
1. Calls
2. Clients
3. Assets
----
----
----
1. …
=> chore: sql query optimizations

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/PublicUserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt
----
----
- Retrieving user info from database is taking too much time
In the old way we were getting all data of user  by making a `select *` query on db . And it took an average of 400ms to finish the full process of retrieving 
Now with just retrieving what we need, specifying the columns that we need only, we see an some improvement. It took about 30-100ms
_Attachments like images, videos, etc. (drag and drop in …
=> fix(calling): participants handling optimization

gradle.properties
----
----
Our CI takes up to 25 mins to run some times.
And while it isn't super annoying right now, we can always try to improve.
Multiple reasons. But we don't execute tasks in parallel.
Try to [execute Gradle tasks in parallel](https://docs.gradle.org/current/userguide/performance.html#parallel_execution).
It did work on my machine :D
Now I wanna see if there's any tangible improvement on GitHub runners.
It should work without failures if multiple tasks don't interact with some shared state/resource at the same time. Such tasks whould be properly configured to depend on each-other, so Gradle doesn't attempt to execute them in parallel.
N/A
----
----
1. …
=> ci: enable parallel gradle execution

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/IncrementalSyncManager.kt
=> chore: added more logs in incremental sync manager

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/RequestVideoStreamsUseCase.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
----
----
Requesting video streams should not be done on every participants change, instead we should only request per screen
I created a use case to be called from app level to request videos of current participants on the screen
----
----
----
1. …
=> feat: create request videos stream use case(AR-2490)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/notification/user/ClientEventsData.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
----
----
Incremental sync support, handling user events.
With this PR we are handling user events, related to when they change personal information, so we act on this, and update the target local user, ie: username, handle, email, avatars.
WIP
You can check out this branch and use it in reloaded, you will see other users info changed automatically.
I´ll open a PR on reloaded for this updated handling
----
----
----
=> feat: incremental sync update user events (AR-2491)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt
----
----
"You wants to connect" is displayed for connections requests with guests
The connection request is persisted and the DB observer triggered BEFORE we fetch user details
Fetch user details, then persist the connection. In case of failure, just persist the connection request and brace.
Receive a connection request from a guest
----
----
=> fix: you wants to connect AR-2370

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt
----
----
Increase the pagination size of getting conversations, since this was already adjusted to support big requests by the backend team.
----
----
----
=> chore: increase paging size to get 500 convos

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/notificationToken/PushTokenUpdater.kt
Added some logs to have some info in logs while registering the Firebase token
=> chore: Added logs in register firebase token

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConnectionApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonTest/kotlin/com/wire/kalium/api/tools/json/api/connection/ConnectionRequestsJson.kt
----
----
SAME AS https://github.com/wireapp/kalium/pull/978 Just changed base without introducing new changes
Increase the paging size that the app talks to the backend, this will speed up the process of sync for big accounts.
----
----
----
=> chore: increase paging convos and connections

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
----
----
Message was not persisted in add user to conversation use case
Update AddMemberToConversationUseCase with persist system message
go to group that you are admin in and add a user 
----
----
----
=> fix: added member system message

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserModel.kt
=> chore: obfuscate connection

logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/KeyingMaterialsManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/keypackage/KeyPackageManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/FeatureSupportImpl.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/KeyingMaterialsManagerTests.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/keypackage/KeyPackageManagerTests.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/jvmMain/kotlin/com/wire/kalium/logic/feature/UserSessionScopeProviderImpl.kt
----
----
Some features are only available when running against given API version so we need expose this fact to the logic module so that it can decide to not perform certain operations / network calls.
----
----
----
=> feat: support different features depending on API version

buildSrc/src/main/kotlin/Dependencies.kt
----
----
Update to CoreCrypto to 0.5.2 which contains a bug fix for external senders.
----
----
----
=> chore: update to CoreCrypto to 0.5.2

buildSrc/src/main/kotlin/Dependencies.kt
----
----
"User called" displayed multiple times during active call
Bump AVS version to 8.2.16
Please test it with clients that are using AVS 8.2.16 or newer
----
----
---- …
=> chore: bump AVS version to 8.2.16 (AR-2498)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/SelfClientsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/Either.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/SelfClientsUseCaseTest.kt
----
----
To show current device on self user devices screen I need to add current client id to SelfClientsUseCase
https://wearezeta.atlassian.net/browse/AR-2215
----
----
----
=> chore: current client (AR-2215)

buildSrc/src/main/kotlin/Dependencies.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/connection/ConnectionStatusMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/AddMemberToConversationUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/ConversationEventReceiverTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
----
----
We want to bring the changes from release to develop
Rebase ✨
----
=> chore: bring changes from release to develop

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/SendAssetMessageUseCaseTest.kt
----
----
Use `CurrentClientIdProvider` and `UserId` in use case
----
----
----
=> chore: cleanup send asset use case

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/authenticated/ConversationApiV2.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/conversation/ConversationApiV0Test.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v2/ConversationApiV2Test.kt
----
----
Add member not working due to API not found due to api versioning 
put the right API version
----
----
----
=> fix: add member not working

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/protobuf/ProtoContentReactionMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/ToggleReactionUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/stub/ReactionRepositoryStub.kt
----
----
Reactions had no test coverage for (de)serializing and the main UseCase.
Cover the most important bits.
----
----
=> test: sending and receiving reactions

cli/src/main/kotlin/com/wire/kalium/cli/CLIApplication.kt
----
----
There's a few global vars used as state for the Console command.
var currentConversation: Conversation? = null
var callsScope: CallsScope? = null
var isMuted: Boolean = false
Move vars into `ConsoleContext` lives in the Console command.
Most changes are due to formatting controlled by detekt.
----
----
----
=> refactor(kcall): move global vars to a class

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
----
----
[AR-2545 - Receiving @mentions](https://wearezeta.atlassian.net/browse/AR-2545)
We weren't selecting and mapping the results from DB View for mentions.
DB View wasn't accounting for mentions
Add mentions in DB View and map its results
Tests will be added in another PR
----
1. https://www.sqlitetutorial.net/sqlite-group_concat/
2. https://www.sqlite.org/lang_corefunc.html
=> feat: Receive mentions

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt
----
----
asset name and web socket key were logged 
obfuscate it from the logs
----
----
----
=> fix: logging [AR-1293]

cryptography/src/androidAndroidTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, cryptography/src/androidTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/ProteusClient.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt, cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/iosX64Test/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/jsTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, cryptography/src/jvmMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, cryptography/src/jvmTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt
----
----
Migrate unencrypted proteus storage to encrypted proteus storage
----
----
----
=> feat: migrate from unencrypted proteus to encrypted proteus

testservice/src/main/kotlin/com/wire/kalium/testservice/models/CustomBackend.kt
----
----
QA members were not able to connect to custom backends.
An exception was thrown when parsing JSON for instance creation that included custom backend setups.
Fix data class to have default values.
----
----
----
=> fix: testservice cannot connect to custom backend SQPIT-1492

.github/workflows/generate-dokka.yml
----
----
Fix missing credentials for dokka docs generator task
No generation of docs in develop workflow.
----
----
----
=> chore: dokka deployer env vars for packages

README.md
----
----
Devs don't have a straight-forward TL;DR way to generate a PAT for reading GitHub packages.
Add a step-based guide to the README, with a link to help creating the PAT easily.
N/A
----
----
=> chore: update GitHub PAT instructions

testservice/README.md, testservice/config.yml, testservice/src/main/kotlin/com/wire/kalium/testservice/TestserviceApplication.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/LogResources.kt
----
----
This PR adds a new endpoint /application.log that just returns the content of the log file for debug purposes.
----
----
----
=> feat: endpoint to get logs from testservice & installation instructions SQPIT-1464

network/src/commonMain/kotlin/com/wire/kalium/network/session/SessionManager.kt
=> chore: add logs to token refresh

network/src/commonMain/kotlin/com/wire/kalium/network/session/SessionManager.kt
=> chore: edit auth tokens refresh tokens

network/src/commonMain/kotlin/com/wire/kalium/network/KaliumKtorCustomLogging.kt
----
----
network logs are missing HTTP method 
just do it
----
----
----
=> chore: add http method network logs

network/src/commonMain/kotlin/com/wire/kalium/network/KaliumKtorCustomLogging.kt
=> fix: MaxLineLength

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt
----
----
The `QuotedMessageDetails` is TOO flat and annoying to manipulate.
Replace multiple fields with a sealed `Content` so it can be read more easily.
----
----
=> refactor: make quoted content hierarchical (AR-2484)

network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt
=> chore: obfuscate access token in logs

.github/workflows/gradle-jvm-tests.yml
----
----
The testservice is now actively used by QA automation tests. If it breaks it will break all tests.
Usually there is not much change that is needed to fix testservice. Sometimes it is just a new config parameter on a method that was added by a developer or something. If the compilation fails in github actions now the developer can easily adjust the method like it is done with cli application too. The github action job runtime will not increase too much because most of the code is already compiled when cli application is compiled. As you can see in this PR it only adds 17 seconds.
----
----
---- …
=> chore: Compile testservice as part of github actions

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt
----
----
`ProtoContentMapper` is too crowded and with deep nesting inside the `when` branches.
Extract the mapping of specific branches to a dedicated function each.
As there are absolutely 0 changes in logic, this wasn't necessary.
----
----
=> refactor: cleanup proto content mapper

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/properties/UserPropertyRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/readReceipts/ObserveReadReceiptsEnabledUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/readReceipts/PersistReadReceiptsStatusConfigUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/properties/UserPropertyRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/ObserveReadReceiptsEnabledUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/PersistReadReceiptsStatusConfigUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestEvent.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessorTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserPropertiesEventReceiverTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/config/UserConfigStorageTest.kt
----
----
Test coverage for PR : #1176 
----
----
----
=> feat: user config read receipts test coverage (AR-2711)

gradle/libs.versions.toml, network/src/commonMain/kotlin/com/wire/kalium/network/NetworkClient.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/config/GlobalAppConfigStorageTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/config/UserConfigStorageTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/kmmSettings/KaliumPreferencesTest.kt, persistence/src/jsMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt
=> chore: update KMM settings to 1.0.0-RC

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
=> fix: flow success data are logged

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq
=> fix: allow to overwrite of asset messages content

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCase.kt
=> fix: provide the asset name to the get message asset use case result

persistence/src/commonMain/db_user/migrations/22.sqm
----
----
Check if the trigger exists before dropping it.
In some edge cases might be an issue.
----
----
----
=> fix(db-migration): check if trigger exist before drop

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/conversation/ConversationApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/model/JoinConversationRequest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/ConversationApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/authenticated/ConversationApiV2.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/conversation/ConversationApiV0Test.kt
----
----
remote API request to join conversation via code
just add it
----
----
----
=> feat: join conversation via invite link

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/util/JsonSerializer.kt
----
----
when adding new nullable values it needs to have a default value of null, otherwise the deserialization fails
disable explicitNulls in persistence json serializer this way the value will be set to null if not present in the json string
----
----
----
1. …
=> chore: disable explicitNulls in persistence json serializer

calling/build.gradle.kts
(cherry picked from commit 8a80f9c838569229b6aa3e1ec5643507aba4bfde)
----
----
Merging same changes of #1308 to RC branch
----
----
----
=> chore: bump AVS version to 9.0.2 (#1308)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetNotificationsUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt
----
----
Just some clean up! Nothing important.
AR PR.
- [] I have added automated test to this contribution
All the notifications must work normally.
----
----
----
=> fix(notification): clean up on notifications and connections dao (AR-2898)

util/src/darwinMain/kotlin/com.wire.kalium.util/FileUtil.kt
----
----
Add missing darwin implementation for FileUtil
----
----
----
=> feat: add missing Darwin implementation for util module

persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/RestoreBackupTest.kt, persistence/src/darwinMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt, persistence/src/darwinMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt, persistence/src/darwinMain/kotlin/com/wire/kalium/persistence/kmmSettings/GlobalPrefProvider.kt, persistence/src/darwinMain/kotlin/com/wire/kalium/persistence/kmmSettings/UserPrefBuilder.kt, persistence/src/darwinTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt, persistence/src/darwinTest/kotlin/com/wire/kalium/persistence/GlobalDBBaseTest.kt
----
----
Add missing Darwin implementation for persistence module
----
----
----
=> feat: add missing Darwin implementation for persistence module

cryptography/build.gradle.kts, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/MLSClientTest.kt, cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt, cryptography/src/darwinMain/kotlin/com/wire/kalium/cryptography/MLSClientImpl.kt, cryptography/src/darwinMain/kotlin/com/wire/kalium/cryptography/ProteusClientCoreCryptoImpl.kt, cryptography/src/darwinMain/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt, cryptography/src/darwinTest/kotlin/com/wire/kalium/cryptography/BaseMLSClientTest.kt, cryptography/src/darwinTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt, gradle/libs.versions.toml
----
----
Add implementations for proteus and MLS clients for the Darwin platform.
- Quite some code duplication going on since core-crypto doesn't doesn't have JS support so I can't just move the implementation to common.
- One test crashes when running on the iOS simulator. See crash report in the comments.
- I haven't moved the android / JVM implementation to use the multiplatform version of core crypto since it's still a bit untested.
----
----
----
=> feat: add missing Darwin implementations for the cryptography module

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/mapper/CallMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/Call.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/RejectCallUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/EndCallUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/RejectCallUseCaseTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/call/CallDAO.kt
----
----
Cherrypicking merged [commit](https://github.com/wireapp/kalium/commit/b88fc4695a1e4e0bc388f6f0dd97a0418b63f27a)  into release branch
Full description of the issue in #1327
----
----
----
=> fix: incoming call keeps showing up even after rejecting it (AR-2934) - RC

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/ProteusClientImpl.kt
----
----
Cherry pick https://github.com/wireapp/kalium/pull/1353
----
----
----
=> chore: cherry pick logging

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MarkMessagesAsNotifiedUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MarkMessagesAsNotifiedUseCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
Un-removable notifications issue fix 
Just a copy of https://github.com/wireapp/kalium/pull/1365 for RC
=> fix: Release candidate: not updating notifications date in conversations

gradle/libs.versions.toml, network/build.gradle.kts, network/src/commonMain/kotlin/com/wire/kalium/network/KaliumHttpLogger.kt, network/src/commonMain/kotlin/com/wire/kalium/network/KaliumKtorCustomLogging.kt, network/src/commonMain/kotlin/com/wire/kalium/network/NetworkClient.kt, network/src/commonMain/kotlin/com/wire/kalium/network/utils/ObfuscateUtil.kt
----
----
[AR-2951 - Mutex causing app crash in KaliumKtorCustomLogging](https://wearezeta.atlassian.net/browse/AR-2951)
Mutex was causing problem when logging.
Ktor changed implementation of logging.
Update our `KaliumKtorCustomLogging` to match newest changes of Ktor logging.
----
----
----
1. …
=> chore: update custom logger

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
* fix: migration fails indefinitely if it fails once
* convert timestamp to instant
----
----
_Specify here any other facts …
=> fix: [RC] migration fails indefinitely if it fails once (#1345) 

util/src/androidMain/kotlin/com.wire.kalium.util/PlatformDateTimeUtil.kt, util/src/commonMain/kotlin/com.wire.kalium.util/DateTimeUtil.kt, util/src/commonTest/kotlin/com/wire/kalium/util/DateTimeUtilBenchmark.kt, util/src/commonTest/kotlin/com/wire/kalium/util/DateTimeUtilTest.kt, util/src/jvmMain/kotlin/com/wire/kalium/util/PlatformDateTimeUtil.kt
----
----
Port of the PR to develop:
- #1373 
----
----
=> fix(android): improve performance of instant to ISO string (#1373)

cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/ProteusClientTest.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/appVersioning/AppVersionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/appVersioning/ObserveIfAppUpdateRequiredUseCase.kt
Copy of [PR](https://github.com/wireapp/kalium/pull/1351)
=> fix: release: Force to update

.github/workflows/gradle-android-tests.yml
----
----
Android test build times are in the oder of 30m
Switch to faster runners
----
----
=> ci: switch android test runner to buildjet

logic/consumer-proguard-rules.pro, persistence/consumer-proguard-rules.pro
----
----
app crash when minify is enabled
Solutions
add proguard rules for sqlCipher
----
----
----
=> fix: missing proguard rules

android/src/main/AndroidManifest.xml, gradle/libs.versions.toml, persistence/consumer-proguard-rules.pro, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/GlobalDatabaseProvider.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/SqliteCallback.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/support/SqliteCallback.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/support/SupportOpenHelperFactory.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOBenchmarkTest.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt
----
----
This PR is a port of the following PRs from `release` to `develop`:
- #1382 
- #1409 
- #1413 
All of these were related to the inclusion of the new SQLCipher and WAL Mode
----
----
=> chore: enable wal journaling mode

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Migration.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/MigrationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt
----
----
messages are unread after migration
Upsert conversion data 
----
----
----
=> fix: messages are unread after migration

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unauthenticated/appVersioning/AppVersioningApi.kt
copy of PR https://github.com/wireapp/kalium/pull/1437 for the `develop`
=> fix: BlackList url into develop

persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseExporter.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseImporter.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt, persistence/src/iosX64Main/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt, persistence/src/jvmMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt
----
----
backup creation error with sqlCipher
needs to pass and empty password when for encrypted databases
----
----
----
=> fix: backup creation error with sqlCipher

.github/workflows/cherry-pick-rc-to-develop.yml
=> feat: test cherry pick

.github/workflows/cherry-pick-rc-to-develop.yml
=> fix: rc cherry pick

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/ClearConversationRequest.kt
----
----
This PR adds a new endpoint /clear to the testservice to clear content of a conversation.
----
----
----
=> feat: testservice can clear conversations (SQPIT-1603)

.github/workflows/gradle-android-tests.yml
=> ci: install JDK 11

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt
----
----
DUPLICATED_MESSAGE errors are handled as normal encryption error
ignore it
----
----
----
=> fix: don't insert decryption errors for duplicate message errors

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/notification/LocalNotification.kt
----
----
Fixed issue with mapping ContentType Knock to LocalNotificationMessage Knock type
----
----
----
=> fix: knock notification type

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandlerTest.kt
=> fix: don't insert decryption errors for duplicate message errors (#1486)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/PersistMigratedConversationUseCase.kt
----
----
PersistMigratedConversationUseCase have a return type of Boolean with no indication about the error type
return meaningful errors
----
----
----
=> refactor: return meaningfull errors when migrating conversations

logic/src/androidMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/androidMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/MLSClientProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/ProteusClientProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/CreateBackupUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/util/SecurityHelper.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/backup/CreateBackupUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/SecurityHelperTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/DumpContent.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/ImportContent.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseExporter.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt
=> fix: [RC] backup fails after the 2nd time (#1498) 

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/SendMessagePartialFailureMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/MessageRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/SendMessagePartialFailureMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestMessage.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/db_user/migrations/29.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/RecipientDeliveryFailureMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/TableMapper.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/message/RecipientDeliveryFailureMapperTest.kt
----
----
This is the epic branch of previous merged PRs:
- #1525 
- #1527 
----
----
----
=> feat: epic - federation, offline backends message sending (AR-3015)

network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unauthenticated/VerificationCodeApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/unauthenticated/VerificationCodeApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/unauthenticated/networkContainer/UnauthenticatedNetworkContainerV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/unauthenticated/VerificationCodeApiV2.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/unauthenticated/networkContainer/UnauthenticatedNetworkContainerV2.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/unauthenticated/VerificationCodeApiV3.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/unauthenticated/networkContainer/UnauthenticatedNetworkContainerV3.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/UnauthenticatedNetworkContainer.kt, network/src/commonTest/kotlin/com/wire/kalium/api/v0/user/VerificationCodeApiV0Test.kt
----
----
For 2FA, we need to call an endpoint to send the verification code to an email.
On this PR, just the network part, implementing the API interface.
----
----
=> feat(network): send verification code endpoint (AR-3088)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/UpdateClientVerificationStatusUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/GetOtherUserClientsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/UpdateClientVerificationStatusUseCaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq, persistence/src/commonMain/db_user/migrations/29.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserClientDAOIntegrationTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt
----
----
client table is missing flag for verified clients
add flag and usecase to update it
----
----
=> feat: store client verification status

cryptography/src/androidMain/kotlin/com/wire/kalium/cryptography/ProteusClientCryptoBoxImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAOImpl.kt
----
----
selectProtocolInfoByQualifiedId is invoked on main thread
Switch to IO context
----
----
----
=> fix: io operations running on main

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/PersistMigratedConversationUseCase.kt
Copy of https://github.com/wireapp/kalium/pull/1522
----
----
PersistMigratedConversationUseCase have a return type of Boolean with no indication about the error type
return meaningful errors
----
----
----
=> refactor(dev): return meaningful errors when migrating conversations

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/id/QualifiedId.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/type/UserTypeMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
there are places where a hard-coded value for domain is used
nuke it
----
----
----
=> fix: [DEV] remove hard coded domain string

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
----
----
When doing a fresh install and login in, the app would get stuck in the set up screen.
When getting self user team id it would get stuck in a loop as it would call the same function it was calling it before thus stuck in the loop.
Use another function to get self user team id
=> fix: stuck in loop when login fresh install

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendFailureHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
----
----
There are no log traces for the message send flow for Beta builds
Trace message send flow with appropriate obfuscation for privacy in Beta builds
----
=> chore: improve message send logging

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/incremental/EventProcessor.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/FeatureConfigEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/TeamEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserPropertiesEventReceiver.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/DeletedConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MLSWelcomeEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberChangeEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/NewConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ReceiptModeUpdateEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/RenamedConversationEventHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/NewMessageEventHandler.kt
----
----
Event handling loops are lacking structured logging
Add "Success" "Failure" "Skipping" logs to all event handlers
----
----
=> chore: add event handling logs

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/client/ClientRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/GetOrRegisterClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/GetOtherUserClientsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ObserveClientDetailsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/SelfClientsUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/VerifyExistingClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestClient.kt
----
----
the client model is missing the isValid flag
add it
----
----
----
=> feat: add is valid to client model

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
----
----
`tempFileSink` and `decodedAssetSink` are leaking 
```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1987)
at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
at java.io.FileOutputStream.finalize(FileOutputStream.java:495)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
at java.lang.Daemons$Daemon.run(Daemons.java:140)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.Throwable: Explicit …
```
=> fix: leaked object, resource was acquired but never released

logic/src/androidMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserverImpl.kt
----
----
RC: https://github.com/wireapp/kalium/pull/1634
=> fix: stuck on connecting because of onBlockedStatusChanged [AR-3269]

logic/src/androidMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserverImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/network/NetworkStateObserver.kt
----
----
More logs for `NetworkStateObserver`
=> chore: logs for network state observer

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/Event.kt
----
----
The type key is missing in the logs for User.NewClient event
Add the type key and value to the logs
----
----
=> chore: improve event logging

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt
----
----
the client name was only consumed by the UI, so i moved it to the app and changed the display name to reflect design
----
----
----
=> chore: remove unused Client name

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/Asset.kt
----
----
We have methods to check the mime type for audio and image file types, but not video.
Add a method to check if the given mime type is of video type.
----
----
----
=> chore(rc): add video mime types

persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
----
----
Same PR as #1639 to be merged into RC branch
----
----
----
=> fix: Message not received when there 2 mentions of self (AR-3302) (RC)

buildSrc/src/main/kotlin/Android.kt
----
----
Making the required OS to use Wire Android 8
----
----
----
=> chore: raise minSdk to Android 8 API 26 (RC)

buildSrc/src/main/kotlin/Android.kt
----
----
Making the required OS to use Wire Android 8
----
----
----
=> chore: raise minSdk to Android 8 (API 26) (develop)

testservice/src/main/kotlin/com/wire/kalium/testservice/managed/InstanceService.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/InstanceRequest.kt
----
----
This PR implements login on backends with 2FA feature enabled. It is implemented the same way as on the old ETS.
=> feat: Support 2FA login on testservice (SQPIT-1744)

.github/workflows/generate-dokka.yml
----
----
Dock goes OOM during execution. 
Let's try another executor and see what happens then.
----
----
=> ci: run dokka on buildjet

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ConversationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationAccessRoleUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationAccessUseCaseTest.kt
----
RC: https://github.com/wireapp/kalium/pull/1686
=> fix: revoke guest link when removing guest access [AR-3282]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveValidAccountsUseCase.kt
After user soft-logout and logging again, he doesn't receive notifications until restarting the app. 
Observing the notifications and creating the channels for it happens in `GlobalObserversManager` which uses `ObserveValidAccountsUseCase`: if there is any user - create channels for him and observe the notifications. To get rid doing it few times we have `.distinctUntilChanged()` there, so the new channels are created only when something changed. 
The problems come when user logout from the last user and `ObserveValidAccountsUseCase` suppose to emit an empty list, but it doesn't.  `combine(List<Flow<Any>>) { it.asList() }` just doesn't emit anything. 
So in `GlobalObserversManager` it looks like this: 
ValidAccounts emitts: 
- `listOf(account_1)` 
[user logged out, but nothing emitted ] …
=> fix: Not receiving notifications after logout login (AN-3374)

cryptography/src/commonJvmAndroid/kotlin/com.wire.kalium.cryptography/E2EIClientImpl.kt, cryptography/src/commonMain/kotlin/com/wire/kalium/cryptography/E2EIClient.kt, cryptography/src/darwinMain/kotlin/com/wire/kalium/cryptography/E2EIClientImpl.kt, cryptography/src/jsMain/kotlin/com/wire/kalium/cryptography/E2EIClientImpl.kt
----
----
Refactor E2EI Client 
----
----
----
=> feat(e2ei): refactor e2eiClient

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/commonMain/kotlin/com/wire/kalium/network/HttpEngine.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/networkContainer/AuthenticatedNetworkContainerV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/AuthenticatedNetworkContainer.kt, network/src/darwinMain/kotlin/com/wire/kalium/network/defaultHttpEngine.kt
----
----
For testings purposes, we need to call some apis with invalid SSL Certs, added an option to bypass all ssl certificates if needed.
----
----
----
=> feat(network): add option to ignore ssl certificates

persistence/src/androidAndroidTest/kotlin/com/wire/kalium/persistence/dao/message/MessageExtensionsTest.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/dao/message/MessageExtensions.kt
----
----
the changes from  https://github.com/wireapp/kalium/pull/1704 caused the message pager to not observe the BD for cahnges
revert some changes and use the function form sql delight to create the paging source
----
----
----
=> fix: pager not updating

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/SyncManager.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/SyncManagerTest.kt
sister of the release PR https://github.com/wireapp/kalium/pull/1681
=> fix: DEV delayed notification

network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/authenticated/SelfApiV0.kt
----
----
Exception when changing email while offline 
wrap the request with `wrapKaliumResponse`
----
----
----
=> fix: crash when changing email while offline

logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/server/ServerConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AddAuthenticatedUserUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/backup/VerifyBackupUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/StartCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/RegisterClientUseCase.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/kmmSettings/EncryptedSettingsHolder.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageDAOImpl.kt
----
----
Some usecases are still running on main thread which can lead to ANR to happen 
Switch them to a worker thread 
----
----
----
=> fix: run operations on worker thread

cli/src/commonMain/kotlin/com/wire/kalium/cli/commands/LoginCommand.kt
----
----
Can't login into certain environments with the CLI
These environments enforces 2FA
Support login with 2fa with the CLI.
----
----
----
=> feat: support 2fa in the cli login command

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/FetchSSOSettingsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOLoginScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/sso/FetchSSOSettingsUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unauthenticated/SSOSettingsResponse.kt
----
----
sso login with email
use case to fetch default sso code
----
----
----
=> feat: default sso code use case

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/JoinExistingMLSConversationUseCase.kt
----
----
A bit hard to eye-scanning / readability of the class.
Improve by reorganizing the functions, sorting it by the invocation order.
N/A
Nitpick. But also an excuse for me to try out [Tasks on IntelliJ](https://www.jetbrains.com/help/idea/managing-tasks-and-context.html#work-with-tasks) to better manage between diffs/branches and be able to switch context more quickly.
----
----
=> style: reorder join MLS conversation use case functions

persistence/src/androidAndroidTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt, persistence/src/androidMain/kotlin/com/wire/kalium/persistence/db/UserDatabase.kt, persistence/src/appleTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/DumpContent.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Messages.sq, persistence/src/commonMain/db_user/migrations/42.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseExporter.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseImporter.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/UserDatabaseBuilder.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/DatabaseExporterTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/NukeDBTest.kt, persistence/src/jsTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt, persistence/src/jvmTest/kotlin/com/wire/kalium/persistence/BaseDatabaseTest.kt
=> fix: [RC] exclude self deleting messages from bckup

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/mlsmigration/MLSMigrationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/mlsmigration/MLSMigrationManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/FeatureConfigMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/mlsmigration/MLSMigrationRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/user/UpdateSupportedProtocolsUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/featureConfigs/FeatureConfigResponse.kt, network/src/commonTest/kotlin/com/wire/kalium/model/FeatureConfigJson.kt
----
----
- Make all `mlsMigration` config fields optional.
- Delete usersThreshold and clientsThreshold fields since they are no longer necessary.
----
----
----
=> fix(mls-migration): migration feature config #8

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/DeleteEphemeralMessageForSelfUserAsReceiverUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/ClearConversationContentHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/DeleteForMeHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/DeleteMessageHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/LastReadContentHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/MessageTextEditHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/ReceiptMessageHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/GetMessageByIdUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/MessageSenderTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/RetryFailedMessageUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/handler/DeleteMessageHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/MessageTextEditHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ReceiptMessageHandlerTest.kt
----
----
message delete for self deleting messages is not handled
handle it correctly and unify it deleting normal messages add unit tests
----
----
----
=> fix(RC): delete message is not handled correctly

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/publicuser/PublicUserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveSecurityClassificationLabelUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/call/CallingParticipantsOrderTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/connection/ConnectionRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/SearchUserRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/publicuser/UserSearchApiWrapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserMapperTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveSecurityClassificationLabelUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/framework/TestUser.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/db_user/migrations/46.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConnectionDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/db/TableMapper.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/backup/UserDatabaseDataGenerator.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/utils/stubs/UserStubs.kt
----
----
We don't have information about temporary users
Temporary users are showed in the same way as guest users
Added variable expires at which shows which user is temporary
=> feat: temporary user [WPB-84]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/EphemeralMessageRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/debug/DebugScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/ephemeral/DeleteEphemeralMessageForSelfUserAsReceiverUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/message/EphemeralRepositoryTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt
* send the delete message to only self and the sender
* send the delete message to only self and the sender
* missing param
* add unit test
* detekt
----
----
_Briefly describe how this change was tested and if applicable the exact steps taken to …
=> fix(DEV): delete message is sent to everyone in the conversation (#1818)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetAvatarAssetUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/ObserveSecurityClassificationLabelUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/GetMessageAssetUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/GetPublicAssetUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/ObserveSecurityClassificationLabelUseCaseTest.kt
----
----
We were not checking conversation domain, only members domain
Label was showing that conversation is classified where conversation domain was not in classified domain list
Check also conversation domain to show proper classification domain label
Also added fix to not refetch assets when backend returns federation error
=> fix: check conversation domain for classification banner [WPB-78]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/ProtoContentMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ApplicationMessageHandler.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
ephemeral messages logs expose ids
obfuscate
----
----
----
=> fix(RC): obfuscate logs in ephemeral messages

logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/session/SessionRepositoryTest.kt
Copy of for dev: 
- https://github.com/wireapp/kalium/pull/1852
=> feat(dev): handling configuration for websocket enabled by default (WPB-967)

logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/session/SessionRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/session/SessionRepositoryTest.kt
Copy for RC of: 
- https://github.com/wireapp/kalium/pull/1852
=> feat(rc): handling configuration for websocket enabled by default (WPB-967)

logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreLogic.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/login/DomainLookupResult.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/auth/login/SSOLoginRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/appVersioning/ObserveIfAppUpdateRequiredUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/AuthenticationScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/DomainLookupUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/autoVersioningAuth/AutoVersionAuthScopeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/FetchSSOSettingsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/auth/sso/SSOLoginScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/auth/login/SSOLoginRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/DomainLookupUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/auth/sso/FetchSSOSettingsUseCaseTest.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unauthenticated/DomainLookupApi.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/base/unauthenticated/SSOSettingsResponse.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/unauthenticated/DomainLookupApiV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v0/unauthenticated/networkContainer/UnauthenticatedNetworkContainerV0.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/unauthenticated/DomainLookupApiV2.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v2/unauthenticated/networkContainer/UnauthenticatedNetworkContainerV2.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/unauthenticated/DomainLookupApiV3.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v3/unauthenticated/networkContainer/UnauthenticatedNetworkContainerV3.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/unauthenticated/DomainLookupApiV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/unauthenticated/networkContainer/UnauthenticatedNetworkContainerV4.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/UnauthenticatedNetworkContainer.kt
----
----
domain lookup use case and SSO with email login
----
----
----
=> feat(RC): SSO with email login

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCaseTest.kt
----
----
Sister PR of #1865 to be merged into RC branch
----
----
----
=> feat(calling): create usecase for ending call on member leave or conversation delete (RC)

persistence/src/commonMain/db_user/com/wire/kalium/persistence/DumpContent.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/ImportContent.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/backup/DatabaseImporter.kt
----
----
backup composite messages 
----
----
----
1. …
=> feat: composit messages backup [part-6]

.github/workflows/gradle-android-tests.yml, .github/workflows/gradle-ios-tests.yml, .github/workflows/gradle-jvm-tests.yml
----
----
Previous PR introduced broken pipelines for tests 
Fix formatting 
----
----
----
=> chore: Fix formatting of upload to DataDog (WPB-3489)

.github/workflows/gradle-android-tests.yml, .github/workflows/gradle-ios-tests.yml, .github/workflows/gradle-jvm-tests.yml
----
----
Workflow files contain typo 
----
----
----
=> chore: fix formatting of dd upload (WPB-3489)

.github/workflows/gradle-android-tests.yml
----
----
invalid script in the android test gh action
----
----
----
1. …
=> ci(GH): fix the issue with invalid script prevent android test action from running

.github/workflows/gradle-android-tests.yml, .github/workflows/gradle-ios-tests.yml, .github/workflows/gradle-jvm-tests.yml
----
----
Previous command was not resolving all possible paths on ubuntu bash compared to local zsh shell
Don't rely on bash resolving and manually pass paths
----
----
----
=> chore: Improve DD JUnit upload command (WPB-3489)

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/ConversationMessageTimerEventHandlerTest.kt
----
----
There is a check `fun check(id: String): Boolean = id.startsWith(LOCAL_ID_PREFIX)` which returning false because I was generating random uuid instead of creating it from LocalId
Pass proper id instead of generating random
=> fix: duplicated timer change system message [WPB-286]

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
Secured case when there are no merge conflicts
=> fix: cp automation v2

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
Cherry picked from RC: https://github.com/wireapp/kalium/pull/1942
=> feat: cherry pick improvements

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UpdateConversationClientsForCurrentCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/UpdateConversationClientsForCurrentCallUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandlerTest.kt
----
----
Sister PR of #1951 targeting tting RC branch 
----
----
----
1. …
=> feat: update conversation call clients on member removal (RC)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/UpdateConversationClientsForCurrentCallUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/EndCallOnConversationChangeUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/UpdateConversationClientsForCurrentCallUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberJoinEventHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/conversation/MemberLeaveEventHandlerTest.kt
----
----
Cherry-pick of #1951
----
----
----
=> feat: update conversation clients on member removal (WPB-3017)

gradle/libs.versions.toml, monkeys/README.md, monkeys/build.gradle.kts, monkeys/example.json, monkeys/schema.json, monkeys/src/main/kotlin/com/wire/kalium/monkeys/ActionScheduler.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/Action.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/AddUserToConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/CreateConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/DestroyConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/LeaveConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/LoginAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/ReconnectAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendMessageAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendRequestAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/Monkey.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/MonkeyConversation.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/importer/TestData.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/ConversationPool.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/MonkeyPool.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/AddUserToConversationActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LeaveConversationActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LoginActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendMessageActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendRequestActionTest.kt
----
----
This implements the base actions in the infinite monkeys to execute stress tests. After this is merged the application should be functional.
Create a configuration file and run `./gradlew :monkeys:run --args"PATH_TO_CONFIG"`
And example config is present in the repo. And a schema definition for the config is also available.
----
----
----
=> feat(monkeys): Implement base actions - WPB-3355

logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/dao/MemberDAOArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConnectionRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ConversationRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/UserRepositoryArrangement.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/usecase/PersistMessageUseCaseArrangement.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/member/MemberDAO.kt
----
----
More arrangement classes needed for federation tests
=> chore: more arrangement classes

gradle/libs.versions.toml, monkeys/README.md, monkeys/build.gradle.kts, monkeys/example.json, monkeys/schema.json, monkeys/src/main/kotlin/com/wire/kalium/monkeys/ActionScheduler.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/MonkeyApplication.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/Action.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/AddUserToConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/CreateConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/DestroyConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/LeaveConversationAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/LoginAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/ReconnectAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendMessageAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/actions/SendRequestAction.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/Monkey.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/MonkeyConversation.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/importer/TestData.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/ConversationPool.kt, monkeys/src/main/kotlin/com/wire/kalium/monkeys/pool/MonkeyPool.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/AddUserToConversationActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LeaveConversationActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LoginActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendMessageActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendRequestActionTest.kt
----
----
This implements the base actions in the infinite monkeys to execute stress tests. After this is merged the application should be functional.
Create a configuration file and run `./gradlew :monkeys:run --args"PATH_TO_CONFIG"`
And example config is present in the repo. And a schema definition for the config is also available.
----
----
----
=> feat(monkeys): Implement base actions - WPB-3355 (#1947)

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/migrations/51.sqm, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
----
----
group conversations with null name are not visible in the conversation screen
this hot fix will make it visible but the name will be deleted account, and this need to be handled in a separated task
----
----
----
1. E.g. …
=> fix: group conversations with null name are not visible in the conversations screen [WPB-3986]

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt
----
----
we need to bump the sync version to try to fix any incorrect group conversations names we have
----
----
---- …
=> chore: bump sync version

logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/UserConfigRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/featureConfig/FeatureConfigModel.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/featureConfig/SyncFeatureConfigsUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncManager.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/config/UserConfigStorage.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/config/UserConfigStorageTest.kt, util/src/commonMain/kotlin/com.wire.kalium.util/time/TimeTypes.kt
----
----
storing app lock team config
----
----
----
=> feat: parse and store app lock feature config

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/conversation/message/ProteusMessageUnpacker.kt
----
- [] contains a reference JIRA issue number like `SQPIT-764`
----
Add more logs to unpacker and crypto error.
----
----
----
=> chore: add logs to crypto error unpacker ProteusFailure

monkeys/README.md, monkeys/docker/Dockerfile, monkeys/docker/docker-compose.yml, monkeys/docker/grafana/dashboards/monkeys.json, monkeys/docker/grafana/provisioning/dashboards/dashboard.yml, monkeys/docker/grafana/provisioning/datasources/datasource.yml, monkeys/docker/grafana/provisioning/plugins/plugin.yml, monkeys/docker/prometheus/prometheus.yml, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LeaveConversationActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/LoginActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendMessageActionTest.kt, monkeys/src/test/kotlin/com/wire/kalium/monkeys/actions/SendRequestActionTest.kt
----
This adds a docker stack to execute the monkeys and monitore it. Prometheus and grafana instances will start alongside the monkeys app and automatically scrape metrics from it.
The tests have been marked as `Ignored` because they are flaky inside docker. Once we figure out the reason we'll add them back to the CI.
----
=> feat(monkeys): Create docker image to facilitate execution of the monkeys application [WPB-4558]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/Message.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageContent.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/PersistMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/MLSConversationsVerificationStatusesHandler.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/MLSConversationsVerificationStatusesHandlerTest.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageEntity.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageInsertExtension.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/message/MessageMapper.kt
When the MLS conversation becomes Verified, app informs user about it by adding SystemMessage
=> feat: SystemMessage about MLS verified conversation

logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt
----
----
Fix for random crash in video state handler. Can be reproduced by start-stopping video several times in kalium-cli.
Seems the videoReceiveStateHandler can be garbage collected, when AVS calls this callback we get a crash.
Adding .keepingStrongReference() to prevent the callback from getting garbage collected fixes the issue.
Can be reproduced by start-stopping video several times in JVM version.
----
----
----
1. …
=> fix: random crash in video state handler

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationArchivedStatusUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/UpdateConversationArchivedStatusUseCaseTest.kt
----
----
Added option to control if we should archive only locally conversation. It's needed when user is no longer a member of conversation and want to archive this conversation
=> feat: archive only locally [WPB-5006]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationRepository.kt
----
----
There is unknown crash in conversationMapper which I assume it's about some required field.
I secured crash and added logger to log error when it occurs to have more information what is causing this.
=> fix: crash conversation mapper [WPB-5199]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/SendMessageFailureMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSendFailureHandler.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/functional/Either.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/prekey/MessageSendFailureHandlerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/util/arrangement/repository/ClientRepositoryArrangement.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Clients.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/client/ClientDAOTest.kt
----
----
when sending a message fails the following should happen
1. [x] for the deleted list we should remove users clients
2. [x] for the deleted list we should refresh user info for users that have no clients left after step 1  
3. [x] for the missing users we should add the clients and update info
my solution is to do the following 
1. delete any deleted clients
2. query and users with 0 clients after the delete 
3. append the list from 3 to the list of missing user ids
4. fetch info for the users ids list from step 3
5. add any missing clients
_Briefly describe how this …
=> refactor: message send error handling

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageSender.kt
----
----
- added retryCount to avoid infinite loop on message sending failures
=> fix: infinite loop on message send failure [WPB-5789]

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiver.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/receiver/UserEventReceiverTest.kt
----
----
The app is "waiting for network" after receiving "connection request cancelled" event.
The sync is stuck because there's an infinite loop when trying to handle this event because when the state is "cancelled" then the app removes the 1-1 conversation with that user, but then it tries to create an initial system message informing about encrypted communication in WIre.
Do not create such system message until the connection state is "accepted" - just like with resolving 1-1 conversation.
Only when "accepted", the conversation is in a normal state and users can exchange messages so the system message shouldn't be added if the state is different.
The app should recover automatically when updated with this fix if the user encountered this …
=> fix: sync is stuck on connection cancelled event [WPB-6004][WPB-5981]

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Members.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/member/MemberDAO.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/MemberDAOTest.kt
RC cherry-pick of https://github.com/wireapp/kalium/pull/2310
=> fix: duplicated System Message about degraded conversation [rc]

testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/models/SendLocationRequest.kt
----
----
Implement location sharing for testservice
----
----
----
=> feat: testservice sending location messages (WPB-2649)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepositoryTest.kt
----
----
When there is no stored CRL list in db, addOrUpdateCRL
We don't handle the case when getCrls using getSerializable() returns null. Which lead to not add new CRLs into DB
Handle null case 
----
----
----
1. E.g. `feat(conversation-list): …
=> fix: add crl url when there is no stored list

.github/workflows/cherry-pick-rc-to-develop.yml
----
----
base64 encoding, adding a new line after 76 char
add -w 0 flag to remove this behaviour
_Attachments like images, videos, etc. (drag and drop in the text box)_ 
----
----
----
=> ci: base64 encoding adding a new line after 76 char

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
----
----
Logging epoch changes to help us investigate
https://wearezeta.atlassian.net/browse/WPB-6250
----
----
----
=> chore(calling): log epoch changes

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/message/MessageMapper.kt
----
----
- fixed mapping sender to self or other user in system messages
=> fix: self sender in system message [WPB-6500]

.github/workflows/gradle-android-instrumented-tests.yml, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnParticipantListChanged.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/Participant.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/ParticipantsOrderByName.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/user/UserRepositoryTest.kt
=> fix: crash when answering a call (WPB-6183) - cherrypick

network/src/commonMain/kotlin/com/wire/kalium/network/BackendMetaDataUtil.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/AuthenticatedNetworkContainer.kt, network/src/commonMain/kotlin/com/wire/kalium/network/networkContainer/UnauthenticatedNetworkContainer.kt, network/src/commonTest/kotlin/com/wire/kalium/api/common/SupportedApiVersionTest.kt, persistence/src/commonMain/db_global/migrations/7.sqm
----
----
client should default back to API v2 if it tries to connect to API v3
1. Default to API v2 implementation when requesting API v3
2. Update the server config table to replace API v3 with API v2
----
----
----
1. E.g. …
=> refactor: drop support for api v3

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepositoryTest.kt
----
----
circular dependency in CertificateRevocationListRepository
revert some changes that did thus issue
----
----
----
=> fix: circular dependency in CertificateRevocationListRepository

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/composite/SendButtonMessageUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/message/composite/SendButtonMessageCaseTest.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/api/v1/ConversationResources.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt
@mchenani accidentially removed changes of both PRs by merging #2403. I readded the changes here.
=> fix: Solved merge conflict that removed PR 2393 and 2377

monkeys/src/main/kotlin/com/wire/kalium/monkeys/homeDirectory.kt
----
----
Code broke in previous commits, because an attribute was removed from the KaliumConfig.
----
=> fix(monkeys): Fix removed attribute

network/src/commonMain/kotlin/com/wire/kalium/network/api/v4/authenticated/ConversationApiV4.kt
----
----
adding members to group does not reflect in on the screen
the adding is done correctly but the app could not handle the response 
----
----
----
=> fix: adding members to group

logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncWorker.kt
=> refactor: ignore 1:1 resolver errors during slow sync

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/CheckCrlRevocationListUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/e2ei/CertificateRevocationListRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/CertificateRevocationListCheckWorkerTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/CheckCrlRevocationListUseCaseTest.kt
----
----
add a use case to check CRL revocation list once
----
----
----
1. …
=> feat: add a use case to check CRL revocation list once

logic/src/appleMain/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/CallManagerImpl.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallManager.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/CallsScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/video/SetVideoSendStateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/video/UpdateVideoStateUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/video/SetVideoSendStateUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/call/usecase/video/UpdateVideoStateUseCaseTest.kt
=> feat: add SetVideoSendStateUseCase (WPB-7114) - cherrypick

cryptography/src/commonTest/kotlin/com/wire/kalium/cryptography/E2EIClientTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/GetOrRegisterClientUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/sync/slow/SlowSyncCriteriaProviderTest.kt
----
----
Fixed all ignored tests from the crunch time.
Fixed the tests and added some new.
----
----
----
=> fix(tests): fixed ingored tests for E2EI (WPB-6286)

persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Notification.sq, persistence/src/commonMain/db_user/migrations/82.sqm
----
----
notification query is missing indexing
add index to conversation table that are needed not only for notifications but also for other stuff
----
----
---- …
=> feat: add indexing for notification queries [WPB-7227]

monkeys/src/main/kotlin/com/wire/kalium/monkeys/conversation/LocalMonkey.kt
----
----
Monkeys is not compiling
New parameter for proxy config not passed down.
Pass the parameter
Run `./gradlew :monkeys:assembleDist` to verify
----
----
----
=> fix: compilation for monkeys

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/call/usecase/RequestVideoStreamsUseCase.kt
----
----
Adding some logs `RequestVideoStreamsUseCase`
----
----
----
=> chore: add some logs to RequestVideoStreamsUseCase

logic/src/commonMain/kotlin/com/wire/kalium/logic/di/MapperProvider.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/E2eiCertificate.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/GetE2EICertificateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/GetMembersE2EICertificateStatusesUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/GetUserE2EIAllCertificatesUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/usecase/GetUserE2EICertificateUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/ObserveE2EIRequiredUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/GetE2eiCertificateUseCaseTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/e2ei/GetMembersE2EICertificateStatusesUseCaseTest.kt
----
----
Exposing userHandle and the MLS Client Thumbprint with E2EI certificate.
Needed in the AR.
----
----
----
=> fix(e2ei): expose thumbprint and userhandle with e2ei cert (WPB-8606)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
----
----
Update CipherSuite in DB  after conversation is established.
----
----
----
=> fix(mls): set correct CipherSuite when establishing new created group

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/e2ei/E2eiCertificate.kt
----
----
Adding serialisation annotation to serialisable classes.
Was missing for android navigation arguments.
----
----
----
=> fix(e2ei): crash on downloading certificates (WPB-9097)

benchmarks/build.gradle.kts, benchmarks/src/commonMain/kotlin/com/wire/kalium/benchmarks/logic/CoreLogicBenchmark.kt, detekt/baseline.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9534" title="WPB-9534" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-9534</a>  Benchmark creation of coreLogic object
</td></table>
<br />
----
----
Adds benchmarks for instantiation of CoreLogic object with or without In-Memory-Storage.
=> feat: Add benchmarks for core logic (WPB-9534)

.github/workflows/jira-lint-and-link.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-9779" title="WPB-9779" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-9779</a>  [Android] configure jira linking action to run on all PRs
</td></table>
<br />
----
----
make JIRA action required
set fail-when-jira-issue-not-found to true and check if the pr author is either dependabot or Android bob and exit with success in that case
_Attachments like images, …
=> ci: configure jira linking action to run on all PRs [WPB-9779]

README.md, cli/src/commonMain/kotlin/com/wire/kalium/cli/CLIApplication.kt
----
----
- Run the CLI with CoreCrypto by default so a user doesn't need to compile and refer to the native libs
- Improve the CLI docs with a more useful example.
----
----
----
=> docs: improve cli documentation - no ticket

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/message/MessageScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/asset/ScheduleNewAssetMessageUseCaseTest.kt, testservice/src/main/kotlin/com/wire/kalium/testservice/managed/ConversationRepository.kt
* fix: asset restriction (#2831)
* fix: asset sending restriction
* add test
* add error messages and detekt
* fist test service
* detekt
* chore: update gradle-ios-tests.yml for runner at that time
---------
Co-authored-by: Yamil Medina <yamilmedina@users.noreply.github.com>
(cherry picked from commit ebcc9f88367c29e75fd582d5b1d06d64d3d9ddb7)
* fix merge issues
* fix unresolved reference
(cherry picked from commit 116f27656cc2d2a47ab35c67d9c371a9ed989299)
----
----
When sending a new file, assets restrictions are not considered.
check the file restrictions status and return the correct error based on that 
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as …
=> fix: asset restriction [WPB-9947] (#2831) (#2856)

network/src/commonMain/kotlin/com/wire/kalium/network/BackendMetaDataUtil.kt
----
----
support api v6
----
----
----
1. …
=> feat: support api v6 [WPB-10265]

gradle.properties
----
----
removing unwanted gradle logs about not supported targets
----
----
----
1. …
=> ci: ignoreDisabledTargets when building with CI that does not support apple targets

build.gradle.kts
----
----
some securaty tests are not running when building the  android app 
add 2 gradle tasks that will run jvm and andriud unit tests and aggregate the results
----
----
----
=> ci: run jvm and android unit tests and aggregating results [WPB-10599]

calling/build.gradle.kts, cryptography/build.gradle.kts
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11427" title="WPB-11427" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />WPB-11427</a>  [Android] drop support for x86
</td></table>
<br />
----
----
disable x86 support
try to run the app on x86 emulator it should not install
----
----
----
1. …
=> feat: disable x86 support [WPB-11427]

gradle/libs.versions.toml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-11808" title="WPB-11808" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-11808</a>  [Android] app stalls when fetching a page of conversations from the local DB
</td></table>
<br />
This reverts commit 96044bc0e47427e263e0348099a17399392b42ea.
----
----
4.6.1 is causing performance issues
revert to 4.5.7
_Specify here any other …
=> revert: "chore: update sqlcipher [WPB-11808] (#3069)"

logic/src/commonMain/kotlin/com/wire/kalium/logic/GlobalKaliumScope.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15520" title="WPB-15520" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-15520</a>  [Android] - Implement error handling for initial screens
</td></table>
<br />
----
----
We need to perform some user input validations for SSO code and email at client level.
In order to validate input for email and SSO code and encouraging reusage, expose SSO code validator use case, to be used at client level.
----
----
---- …
=> feat: new enterprise login validations expose SSO code validator use case (WPB-15520)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepositoryTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16229" title="WPB-16229" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-16229</a>  [Android] joining an MLS conversation via invite link breaks the conversation
</td></table>
<br />
----
----
we should not decrypt messages while processing pending commits 
this can lead to breaking the conversation to everyone
user Mutex to sync those functions
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it …
=> fix: run MLS operation to decrypt and handle pending commits in sync [WPB-16229 ]

cells/src/commonMain/kotlin/com/wire/kalium/cells/CellsScope.kt, cells/src/commonMain/kotlin/com/wire/kalium/cells/domain/usecase/SetWireCellForConversationUseCase.kt, data/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationOptions.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16621" title="WPB-16621" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-16621</a>  [Android] Feature flag for cell feature
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-16621
----
- Update access token and path for working with wire cells on imai environment
- Support for creating conversation with enabled wire cell feature
=> feat: Support for imai environment and feature flag [WPB-16621]

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/analytics/AnalyticsRepository.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/analytics/AnalyticsRepositoryTest.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Users.sq, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/UserDAOImpl.kt, persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/UserDAOTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16121" title="WPB-16121" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-16121</a>  [Android] Implement new user properties
</td></table>
<br />
----
----
when reporting team size self is not counted
----
----
----
1. …
=> fix: count self as team member [WPB-16121 ]

.github/workflows/gradle-ios-tests.yml, backup/build.gradle.kts, buildSrc/src/main/kotlin/OnlyAffectedTestTask.kt, buildSrc/src/main/kotlin/com/wire/kalium/plugins/CommonDarwinConfig.kt, cells/src/appleMain/kotlin/com/wire/kalium/cells/data/CellsAwsClient.apple.kt, gradle/libs.versions.toml, protobuf/build.gradle.kts
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-15386" title="WPB-15386" target="_blank"><img alt="Epic" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10807?size=medium" />WPB-15386</a>  [Android] Implement Cell File Upload
</td></table>
<br />
----
Reverting commit disabling iOS tests
Using new version of cells-sdk library with iOS artifact
=> chore: revert iosx64 [WPB-15386]

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/UpdateKeyingMaterialsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/conversation/keyingmaterials/UpdateKeyingMaterialsUseCaseTests.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17367" title="WPB-17367" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-17367</a>  [Android] unlimited MLS jobs when sync goes live
</td></table>
<br />
----
----
key material update will run again and again if only one conv failed for any reason 
1. rerty later (retyurn error) iff there is no internet error and abort
2. if any other error then try with the rest of the groups and return success so the next retry is in 24h
_Briefly describe how this …
=> fix: only retry key material update with no internet [WPB-17367]

.github/workflows/backup-publish-swift.yml, .github/workflows/backup-publish-web-npm.yml, backup/build.gradle.kts, backup/src/commonMain/kotlin/com/wire/backup/data/BackupData.kt, backup/src/commonMain/kotlin/com/wire/backup/ingest/MPBackupMapper.kt, buildSrc/src/main/kotlin/com/wire/kalium/plugins/LibraryPlugin.kt, buildSrc/src/main/kotlin/com/wire/kalium/plugins/Multiplatform.kt, buildSrc/src/main/kotlin/com/wire/kalium/plugins/commonJsConfig.kt, protobuf/build.gradle.kts
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-16925" title="WPB-16925" target="_blank"><img alt="Epic" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10807?size=medium" />WPB-16925</a>  Backup: Publish Common Library
</td></table>
<br />
----
----
Introduce GitHub workflows to publish JS/TS packages to npm and Swift XCFrameworks to GitHub Releases on `backup/*` tags.
Ensures signed tags, builds required artifacts, and configures environments for both processes.
----
----
=> ci(backup): add workflows for npm and Swift package publishing [WPB-16925]

.github/workflows/gradle-android-instrumented-tests.yml, .github/workflows/gradle-android-unit-tests.yml, .github/workflows/gradle-ios-tests.yml, .github/workflows/gradle-jvm-tests.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17635" title="WPB-17635" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-17635</a>  [Android] updater deprecated github action to publish test results
</td></table>
<br />
----
----
update publish unit test results action to use platform-specific versions
https://github.com/EnricoMi/publish-unit-test-result-action/tree/v2#running-as-a-composite-action
update it according the docs
_Specify here any other facts that you think are important for …
=> chore: update publish unit test results action to use platform-specific versions [WPB-17635]

cells/src/commonMain/kotlin/com/wire/kalium/cells/data/CellsApiImpl.kt, cells/src/commonMain/kotlin/com/wire/kalium/cells/domain/usecase/GetPaginatedNodesUseCase.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-17966" title="WPB-17966" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-17966</a>  [Android] Sort items by type
</td></table>
<br />
----
----
We no longer need to sort items in client, we do get the results sorted: folders first and then files …
=> feat: sort by folder (WPB-17966)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ResetMLSConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/conversation/ResetMLSConversationUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19664" title="WPB-19664" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-19664</a>  [Android] add compile time flag for mls reset
</td></table>
<br />
----
----
add flag to control MLS reset
----
----
----
1. …
=> chore: add compile-time flag for MLS reset feature [WPB-19664]

cells/src/commonMain/kotlin/com/wire/kalium/cells/CellsScope.kt, cells/src/commonMain/kotlin/com/wire/kalium/cells/data/CellConversationDataSource.kt, cells/src/commonMain/kotlin/com/wire/kalium/cells/domain/usecase/IsAtLeastOneCellAvailableUseCase.kt, persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq, persistence/src/commonMain/db_user/migrations/112.sqm, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAO.kt, persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/conversation/ConversationDAOImpl.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19767" title="WPB-19767" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-19767</a>  [Android] Do not request files if no cell available
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-19767
Use case to check if there is at least one conversation with wire cell enabled.
=> feat: check if at least one cell available (WPB-19767)

logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/IsWireCellsEnabledForConversationUseCase.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/UserScope.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/client/IsWireCellsEnabledForConversationUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19789" title="WPB-19789" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-19789</a>  [Android] Support cell attachment uploads via external app sharing
</td></table>
<br />
----
----
This use case will return true if the conversation supports cells feature, and false otherwise.
_Specify here any other facts that you think are …
=> feat: add use case to check if cells enabled for a conversation (WPB-19789)

logic/src/commonMain/kotlin/com/wire/kalium/logic/data/event/EventRepository.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/UpdateSelfClientCapabilityToConsumableNotificationsUseCase.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/data/event/EventRepositoryTest.kt, logic/src/commonTest/kotlin/com/wire/kalium/logic/feature/client/UpdateSelfClientCapabilityToConsumableNotificationsUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-19980" title="WPB-19980" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-19980</a>  [Android] Implement monitoring for health observability of async notifications
</td></table>
<br />
----
----
Some basic monitoring needs to be done for releasing the feature of async notifications
Add some logs to help DD to observe and add some graphs
N/A
----
----
----
=> chore: add more logs for basic monitoring of async notifications (WPB-19980)

data/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/Conversation.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ProtocolInfoMapper.kt, logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ResetMLSConversationUseCase.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-20097" title="WPB-20097" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />WPB-20097</a>  [Android] do not hide conversaitons that are awaiting ongoing MLS welcome message after reset
</td></table>
<br />
----
----
add PENDING_AFTER_RESET to logic module and the needed mappings
use the epoch from the db in case the conversation is not found in CC
_If there …
=> feat: add PENDING_AFTER_RESET state to MLSCapable.GroupState and update related mappings [WPB-20097]

cells/src/commonMain/kotlin/com/wire/kalium/cells/data/CellsApiImpl.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/WPB-20479" title="WPB-20479" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />WPB-20479</a>  [Web][Android] Default ordering for All Files differs between Web & Android (to be rechecked)
</td></table>
<br />
https://wearezeta.atlassian.net/browse/WPB-20479
Align files sorting with web client.
=> chore: adjust file sorting (WPB-20479)
